### ISSUE TITLE
Missing `sgx_quote_5.h` in libsgx-headers 2.23.100.2

### ISSUE THREAD

**Issue by imlk0** [intel/linux-sgx#1024]
It seems that the new `sgx_quote_5.h` header file was not included in libsgx-headers package:
https://github.com/intel/linux-sgx/blob/242644c77764fe46da2f86f352f4fdca349f2926/linux/installer/common/libsgx-headers/BOMs/libsgx-headers.txt#L12-L14

While this header file was included in the intel sgx sdk:
https://github.com/intel/linux-sgx/blob/242644c77764fe46da2f86f352f4fdca349f2926/linux/installer/common/sdk/BOMs/sdk_base.txt#L94-L97

Can be verified by checking this deb package: https://download.01.org/intel-sgx/sgx_repo/ubuntu/pool/main/devel/libsgx-headers/libsgx-headers_2.23.100.2-focal1_amd64.deb

Now, in order to use `sgx_quote_5.h` in [our project](https://github.com/inclavare-containers/librats), we have to install the latest sgx sdk instead of just using libsgx-headers as we used to do in the old sgx_quote_4.h days. I'd like to know if this is the expected state?

**Comment by llly** [comment]
Thanks for reporting it. This is a bug.  Will Fix it in next release.
