### ISSUE TITLE
sgx-gdb attestation issue.

### ISSUE THREAD

**Issue by kaimast** [intel/linux-sgx#104]
I have an application that performs multiple remote attestations in parallel. It works fine with plain gdb or no debugger at all, but for some reason, when running under sgx-gdb only one of the attestations succeed.  The others return SGX_ERROR_INVALID_STATE. 

Any idea how to debug this? What does sgx-gdb change about the attestation process?

**Comment by kaimast** [comment]
It's been almost two months and I still have this problem. Help?

**Comment by ZongminGu** [comment]
May I have your code to reproduce the issue?

**Comment by fqiu1** [comment]
The APIs in sgx_tkey_exchange are not stateless. If you get SGX_ERROR_INVALID_STATE, it means you called these APIs in wrong order. If you're using sgx-gdb, you might step into one of the thread in your enclave, which cause some timing or racing issue.

**Comment by kaimast** [comment]
fqiu1: That seems very unlikely to me. I tested the code extensively without problems when not using GDB.
The sgx-gdb plugin does seems to set some flags in the runtime but it's fairly hard to read. I suspect there is something about the plugin that changes the attestation procedure. I'm not asking for a bugfix but pointers on how to debug this problem. There seems to be no documentation on what that pugin actually does....

My workaround right now is to run the process and then attach gdb after all attestations have been successfully processed.

ZongminGu: I unfortunately cannot share the code at this point. Will hopefully be able to do so soon.

**Comment by andyzyb** [comment]
Very old issue
