### ISSUE TITLE
SGX_LC: SGX launch config supported = false 

### ISSUE THREAD

**Issue by ketulpatel1411** [intel/linux-sgx#1048]
when i run **cpuid -1 | grep -i sgx** in ubuntu 20.04 i am getting output like 
![IMG_20240828_170622031_HDR~2](https://github.com/user-attachments/assets/e2d61ce9-596a-4f9d-8435-696e6e2d780e)
I also ensured that SGX is enable from my bios
I am using intel i7-6700TE processor .
what is problem i am not getting? , can any one please help me , 
thanks in advance

**Comment by jbdelcuv** [comment]
You have a SkyLake processor that supports SGX but neither the CPU nor the firmware support Flexible Launch Configuration (SGX_LC).

**Comment by ketulpatel1411** [comment]
Thank you for the information regarding the lack of Flexible Launch Configuration (SGX_LC) support on the Intel® Core™ i7-6700TE processor.

Given this, can you confirm if it’s still possible to build and develop SGX applications using [Gramine](https://gramine.readthedocs.io/en/stable/) without SGX_LC support? If so, could you suggest the steps or provide guidance on how to proceed with this setup?

Your assistance would be greatly appreciated as I continue with my project.

**Comment by jbdelcuv** [comment]
If I remember correctly, Gramine also depends on the SGX driver that was upstream to the Linux kernel, which requires Flexible Launch.
I'd suggest you check Gramine requirements.

**Comment by ketulpatel1411** [comment]
**Thank you very much for your constant support and replies**. I appreciate the information regarding Gramine's dependency on the SGX driver upstreamed to the Linux kernel and the requirement for Flexible Launch. I'll definitely check Gramine's requirements to ensure everything is in order.
