### ISSUE TITLE
Inconsistent size for uint types

### ISSUE THREAD

**Issue by bl4ck5un** [intel/linux-sgx#105]
So tlibc defines `uint64_t` as `unsigned long long`:

```c
// /opt/intel/sgxsdk/include/tlibc/sys/_types.h:46
typedef unsigned long long  __uint64_t;
```

But in `inttypes.h`, the specifier for `uint64_t` is defined as `lu`
```c
// /opt/intel/sgxsdk/include/tlibc/inttypes.h:181
#ifdef __x86_64__
#define PRIu64          "lu"    /* uint64_t */
#else
```
I think they should be consistent, right? Is this a bug?

**Comment by lzha101** [comment]
Thanks for reporting this bug. The fix will be included in next release.

**Comment by lzha101** [comment]
The bug should be fixed now. @bl4ck5un, could you please verify it and close this issue?
