### ISSUE TITLE
Creating Multi threads in SGX

### ISSUE THREAD

**Issue by adrkh** [intel/linux-sgx#106]
Hi,
I am trying to create multi threads inside an SGX Application. But in sgx_thread.h include file, i don't see any function to create a sgx thread, where as i see some functions declared for sgx_thread_mutex_lock , init etc.

Also developer guide/reference guide doesn't mention any API for creating a sgx thread.
Any pointer on this will be helpful.
rgds
rkh

**Comment by zhaohuidu** [comment]
There could be multiple threads in the applications and each of them could enter into the enclave. Also code inside enclave could ocall to code outside enclave to create another thread and ecall into enclave inside the thread

**Comment by adrkh** [comment]
If i understand correctly :
1. I can use pthread_Create() out side the enclave to create thread and then should do a ecall into enclave for any enclave data handling.
2. I can't create threads inside enclave .

I have additional question:
1. Who will allocate a  TCS for each thread ? Does application developer need to take care of this ? Or Defining numtcs in xml file is enough ?
2. Is it possible to track no of SSA's free and dump the tcs structure per thread or current thread ? 

Thanks in advance
rkh

**Comment by andyzyb** [comment]
@adrkh your understanding is correct.   For your additional questions,  The TCS number is defined in XML file, that is max number of TCS (thread) can be executing inside Enclave at the same time.  There is no public API to track number of free SSA/TCS, and you cannot dump TCS content.

**Comment by adrkh** [comment]
Thanks andyzyb and zhaohuidu for your answers.
1. While going through the sgx multithread trusted library functions(Thread.cpp) , i do see that 4* LOOPS_PER_THREAD in ecall_producer() function. Is there any  significance of multiplication factor 4 in producer function ?
2. in Thread.cpp file, first 4 threads created with increase_counter as function parameter, and then  4 consumer threads and 1 producer thread created . Why we have these initial 4 threads created separately with the increase_counter function ? (https://github.com/01org/linux-sgx/blob/master/SampleCode/SampleEnclave/App/TrustedLibrary/Thread.cpp)

Thanks in Advance
adrkh

**Comment by lzha101** [comment]
1. The Sample Enclave APP creates 4 thread to enter the enclave to call ecall_increase_counter(). 4 is the thread number. 
2. We use the initial 4 threads to show how to use the thread APIs `sgx_thread_mutex_lock` and `sgx_thread_mutex_unlock`.  And the other producer/consumer threads to demo the condition variable usage.
