### ISSUE TITLE
Where is EPID 'issuer' API/source code?

### ISSUE THREAD

**Issue by Rupertredding** [intel/linux-sgx#118]
Don't see any code related to the 'Issuer'. Are those available at least commercially?

**Comment by lzha101** [comment]
The opensource EPID SDK doesn't include 'Issuer'.  From https://01.org/epid-sdk/:

> The SDK supports both member and verifier functions and includes elliptic curve cryptography (ECC) and other math libraries to support its implementation, along with a well-defined math interface layer to allow customization with MCU FW libraries that provide cryptographic HW acceleration, if available.
