### ISSUE TITLE
Unable to Compile SDK: Protocol Buffer Issue

### ISSUE THREAD

**Issue by RodelFMiguel** [intel/linux-sgx#131]
Hi, 

When I try to build the SDK with protoc version 3.0 to 3.2, I get the following issue:

./../../psw/ae/common/proto/messages.pb.cc:1389:10: error: unused parameter ‘deterministic’ [-Werror=unused-parameter] bool deterministic, ::google::protobuf::uint8* target) const {

This is for both release 1.9 and 1.8.  The libraries wouldnt link if the protoc version I use is 3.3.  I had to revert back to 2.6.1 to make it work.  What is causing this issue?

Thanks.

**Comment by geogriff** [comment]
this was a bug fixed in protobuf, upstream: https://github.com/google/protobuf/commit/08b1c718e437041bfe0e6a28611621896e4fe904

**Comment by RodelFMiguel** [comment]
Hi geogriff,  

Yes, I tried getting and building the latest protobuf, however, it is not linking, as mentioned above.  So, there is something new in the latest protobuf that does not seem to be backward compatible which I couldn't pinpoint.

Thanks.

Kind Regards,
Rodel

**Comment by rupc** [comment]
I'm suffering similar issue related to protobuf. When I try to compile SGX 1.9 with [latest protobuf 3.4.0](https://github.com/google/protobuf/releases/tag/v3.4.0), I encountered annoying lengthy error messages like followings
```
...
messages.pb.cc:(.text._ZN4aesm7message42Response_SGXGetExtendedEpidGroupIdResponse27MergePartialFromCodedStreamEPN6google8protobuf2io16CodedInputStreamE+0x11e): undefined reference to `google::protobuf::io::CodedInputStream::ReadVarint32Fallback(unsigned int)'
messages.pb.o: In function `aesm::message::Response_SGXSwitchExtendedEpidGroupResponse::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)':
messages.pb.cc:(.text._ZN4aesm7message43Response_SGXSwitchExtendedEpidGroupResponse27MergePartialFromCodedStreamEPN6google8protobuf2io16CodedInputStreamE+0x86): undefined reference to `google::protobuf::io::CodedInputStream::ReadTagFallback(unsigned int)'
...
messages.pb.o:(.data.rel.ro._ZTVN4aesm7message37Request_ReportAttestationErrorRequestE[_ZTVN4aesm7message37Request_ReportAttestationErrorRequestE]+0xb8): undefined reference to `google::protobuf::Message::SpaceUsedLong() const'
messages.pb.o:(.data.rel.ro._ZTVN4aesm7message28Request_CreateSessionRequestE[_ZTVN4aesm7message28Request_CreateSessionRequestE]+0xb8): undefined reference to `google::protobuf::Message::SpaceUsedLong() const'
messages.pb.o:(.data.rel.ro._ZTVN4aesm7message28Request_InvokeServiceRequestE[_ZTVN4aesm7message28Request_InvokeServiceRequestE]+0xb8): more undefined references to `google::protobuf::Message::SpaceUsedLong() const' follow

```

**Comment by Eleix** [comment]
Also receiving the same errors as seen by OP using protobuf-3.3.0

> ../../../psw/ae/common/proto/messages.pb.cc:938:10: error: unused parameter ‘deterministic’ [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {

**Comment by haitaohuang** [comment]
you can patch pb as @geogriff pointed out, or use workaround like this: https://github.com/haitaohuang/linux-sgx/commit/074dc5487bec32b08bae2b3272876b2afd4acf0d

**Comment by kaimast** [comment]
Ubuntu currently still ships protobuf 3.0 which contains this bug.

If some folks could subscribe to the bug I filed this might change for 18.04:
**https://bugs.launchpad.net/ubuntu/+source/protobuf/+bug/1739977**

**Comment by elichai** [comment]
I have the same Errors. Installing Protobuf 3.6.1 didn't help.
it fails at this command:
`g++ -Wnon-virtual-dtor -std=c++11 -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -UDEBUG -DNDEBUG -ffunction-sections -fdata-sections -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type -Waddress -Wsequence-point -Wformat-security -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow -Wcast-align -Wconversion -Wredundant-decls -DITT_ARCH_IA64 -fpie AECloseSessionRequest.o AEGetQuoteResponse.o AECloseSessionResponse.o AEInitQuoteRequest.o AECreateSessionRequest.o AEInitQuoteResponse.o AECreateSessionResponse.o AEInvokeServiceRequest.o AEExchangeReportRequest.o AEInvokeServiceResponse.o AEExchangeReportResponse.o ProtobufSerializer.o AEGetLaunchTokenRequest.o AEGetPsCapRequest.o AEGetPsCapResponse.o AEGetWhiteListSizeRequest.o AEGetWhiteListSizeResponse.o AEGetWhiteListRequest.o AEGetWhiteListResponse.o AESGXGetExtendedEpidGroupIdRequest.o AESGXGetExtendedEpidGroupIdResponse.o AESGXSwitchExtendedEpidGroupRequest.o AESGXSwitchExtendedEpidGroupResponse.o AEReportAttestationRequest.o AEReportAttestationResponse.o AESGXRegisterRequest.o AESGXRegisterResponse.o SocketTransporter.o AEGetLaunchTokenResponse.o UnixCommunicationSocket.o NonBlockingUnixCommunicationSocket.o AEGetQuoteRequest.o UnixSocketFactory.o NonBlockingUnixSocketFactory.o  consttime_memequal.o AESMLogicWrapper.o CAESMServer.o main.o Thread.o AESMWorkerThread.o AESMQueueManager.o CSelector.o UnixServerSocket.o ./source/oal/aesm_util.o aesm_config.o aesm_http_msg.o source/pse_op/jhi_proxy.o messages.pb.o sqlite3.o libaesm_service_common.a -pthread -L/home/elichai2/Downloads/intel/linux-sgx/build/linux -lurts_internal  -pie -Wl,-z,relro,-z,now,-z,noexecstack -L/home/elichai2/Downloads/intel/linux-sgx/sdk/tlibcrypto -lsgx_tcrypto -lprotobuf -lrt -lcrypto  -lcurl -L/home/elichai2/Downloads/intel/linux-sgx/common/se_wrapper -lwrapper -lrt -L/home/elichai2/Downloads/intel/linux-sgx/external/rdrand/src -lrdrand -L/home/elichai2/Downloads/intel/linux-sgx/external/vtune/linux/sdk/src/ittnotify -littnotify sgx_memset_s.o -o aesm_service -ldl`

With a lot of errors like: `messages.pb.cc:(.text._ZN25protobuf_messages_2eproto12InitDefaultsEv+0x1b8): undefined reference to `google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)'`

The full log: http://paste.ubuntu.com/p/DNd4n5cnFm/

**Comment by andyzyb** [comment]
Currently protocol buffer 3 is not supported.

**Comment by elichai** [comment]
@andyzyb So what protobuf version *is* supported? 
Because before I updated I used Ubuntu's built in version which is 2.6 and I had the same problems.
