### ISSUE TITLE
AES implementation is susceptible to cache attacks

### ISSUE THREAD

**Issue by geogriff** [intel/linux-sgx#139]
The open-source SDK's AES implementation was taken from the Intel Performance Primitives (IPP) library. While the downloadable "precompiled optimized IPP binaries" use the constant-time AES-NI instructions, the open-source implementation is not resistant to cache attacks which SGX enclaves are susceptible to:
1. [getSboxValue](https://github.com/01org/linux-sgx/blob/6f0e20cfd992c073aefe76926d28893c51f52445/external/crypto_px/sources/ippcp/src/pcprij128safeenc2pxca.c#L41), in an effort to stifle cache attacks divulging secret indices into the S-Box, uses a 16-byte stack buffer to store information from the S-Box from each cache line before indexing into the stack buffer to return a value. However, since the 16-byte stack buffer is not necessarily aligned to be contained within a single cache line, memory access to the buffer may leak information about the secret index.
2. In [ExpandRijndaelKey](https://github.com/01org/linux-sgx/blob/6f0e20cfd992c073aefe76926d28893c51f52445/external/crypto_px/sources/ippcp/src/pcprijkeysca.c#L94), key bytes are used as indices to the S-Box and are not obscured in any way against cache attacks.

Please consider providing an AES implementation which uses the constant-time AES-NI, or an implementation hardened against cache attacks; or alternatively, sufficiently warning developers about the AES implementation's vulnerability to cache attacks in the SDK documentation.

**Comment by lzha101** [comment]
Thanks for reporting this. We will consider to include this in documentations.

**Comment by andyzyb** [comment]
The IPP source code is only a reference code and not recommended for product usage as it is stated in README.

Note: This repository includes a subset of the Intel(R) Integrated Performance Primitives (IPP) Cryptography library under external/crypto_px. It is provided as reference implementation for the cryptographic primitives used in SDK and PSW. The primitives are written in pure C and are not optimized for performance.

**Comment by geogriff** [comment]
I've seen that, but the README doesn't actually state as you say that it's not recommended for product usage. I'd suggest that and the reasoning behind it (i.e. may be susceptible to cache-timing attacks) be stated explicitly..

**Comment by andyzyb** [comment]
Old IPP source code removed.
