### ISSUE TITLE
Get current enclave memory usage?

### ISSUE THREAD

**Issue by abcdabcd987** [intel/linux-sgx#157]
I'm wondering if there exists some way to get the current enclave memory usage? Only for debug purpose. Hardware mode and simulation mode are both acceptable.

I think this might be possible because it seems the memory limit in the xml configuration also applies to simulation mode. So I guess the simulation library/runtime has a way to measure the memory usage?

Thanks!

**Comment by haitaohuang** [comment]
Is sgx_emmt what you want?
see documentation in https://download.01.org/intel-sgx/linux-1.9/docs/Intel_SGX_SDK_Developer_Reference_Linux_1.9_Open_Source.pdf

**Comment by abcdabcd987** [comment]
@haitaohuang Thanks. I have read this before. I suppose it can only be used with `sgx-gdb`? My concern is that `sgx-gdb` seems can utilize only single cpu core, thus running program in `sgx-gdb` is extremely slow and painful.

I wonder if there is some other function that can be called at runtime?

**Comment by ZongminGu** [comment]
Do you mean running app in sgx-gdb is slower than running it in gdb?

**Comment by abcdabcd987** [comment]
@ZongminGu Yes. Using sgx-gdb, the cpu usage is at most 100%, i.e. looks like can only utilize single core. But if you look at the result of htop, you can see that every thread is indeed scheduled, and also the program can serve multiple clients in a multithreaded manner as designed. Everything looks ok within sgx-gdb except cpu usage never exceed 100%. 

I wanted to open another issue about this problem at first, and I wrote a simple multithreaded program. Unfortunately, running that in sgx-gdb can utilize my full cpu. Therefore, I cannot give you a simple code that can reproduce the bug.

**Comment by ZongminGu** [comment]
Do you create a lot of enclaves in a loop? sgx-gdb needs to do a lot work when you create a new enclave. Maybe the cpu cycle is used to get new enclaves information.

**Comment by abcdabcd987** [comment]
No. I only have one enclave.

**Comment by ZongminGu** [comment]
Then we do need a case to reproduce this issue.

**Comment by ZongminGu** [comment]
The current SGX does not support dynamic EPC allocation. So If you want to know how many EPC used by the enclave, you can reference the information reported by signing tool.

**Comment by abcdabcd987** [comment]
@ZongminGu Thanks! But the reason why I want to see memory usage inside enclave at run time is that I ran into some SIGILL which is actually running out of enclave memory. I think if there is some APIs telling you the memory usage would be a great tool to help debug. I guess this can be done because even in the simulation mode, the memory limitation is enforced, so I suppose there must be some code inside simulation runtime library that trace memory usage. Maybe this could be an enhancement?

**Comment by ZongminGu** [comment]
If you get SIGILL, then you can use sgx-gdb to debug it. sgx-gdb's behavior is same as gdb.
