### ISSUE TITLE
How to use Sgxsdk to protect the function in a class？

### ISSUE THREAD

**Issue by daichunkai** [intel/linux-sgx#167]
Hello，I want to protect the function in a class，for exampe
```
class test{
public:
	void  test_fun(char *buf,size_t len)
        {
        const char *secret="Hello Enclave!";
	if(len>=0)
	     {
		memcpy(buf,secret,strlen(secret)+1);
	    }
        }

};
```
also when I read the document:Intel_SGX_SDK_Developer_Reference_Linux_1.8_Open_Source,I notice that it suppouted to **Call C++ class methods**,but I can't find good way to protect the class function,Thank you very much!

**Comment by light1021** [comment]
If you just to use this function inside enclave, you can write it in enclave cpp files. Ecall and Ocall interface only support c function now.

**Comment by andyzyb** [comment]
Exactly.  No C++ interface support in ECALL/OCALL, but it can be used inside Enclave.
