### ISSUE TITLE
Remote attestation guarantees

### ISSUE THREAD

**Issue by rsinha** [intel/linux-sgx#170]
During remote attestation, are there any CPU-specific bits (unique to that SGX CPU)?
Specifically, can a remote verifier distinguish between the following two scenarios:
1. two enclaves with the same identity (MRENCLAVE and MRSIGNER) running on the same CPU
2. two enclaves with the same identity (MRENCLAVE and MRSIGNER) running on different CPUs

My hope is to have the verifier identify how many instances of that enclave have been launched.

**Comment by andyzyb** [comment]
Every system is provisioned with unique EPID key, so the message (signed with EPID key) sent to ISV service backend will be different.  But Intel attestation server is doing anonymous attestation and not identifying the system.

**Comment by bodzhang** [comment]
SGX Remote Attestation and EPID primer at https://software.intel.com/en-us/blogs/2016/03/09/intel-sgx-epid-provisioning-and-attestation-services. 

A lot of SGX info available at https://software.intel.com/en-us/sgx/resource-library
