### ISSUE TITLE
sgx_fwrite returns zero on successful write

### ISSUE THREAD

**Issue by RodelFMiguel** [intel/linux-sgx#171]
Hi, 

I am currently trying to use the protected filesystem library but I am having issues regarding sgx_fwrite.

When I do the following sequence:

sgx_fopen("test.txt", "r+");
sgx_fread(...). // read through the end of the file
if(!sgx_frwite(...)) print "Error";

I am getting the correct response from sgx_fwrite.  However whenever I do this:

sgx_fopen("test.txt", "r+");
sgx_fread(...). // read through the the file until some condition
sgx_fseek(...). // go back to some point in the file, e.g. start of the file, or somewhere in the middle
if(!sgx_frwite(...)) print "Error";

The sgx_fwrite here returns an error.  However, further investigation on the file's contents shows that the file was correctly updated.

Kind Regards,
Rodel

**Comment by naishai** [comment]
Hi Rodel,

Can you give us a detailed code that reproduce your bug? with the file size, offsets and sizes you read and write.
I tried to reproduce it but I don't get any errors in my code (with a big existing file):
file = sgx_fopen_auto_key(filename, "r+");
if (file == NULL)
...
result = sgx_fseek(file, 5000, SEEK_SET);
if (result != 0)
...
count = sgx_fread(buffer, 10, 100, file);
if (count != 100)
...
count = sgx_fread(buffer, 100, 10, file);
if (count != 10)
...
result = sgx_fseek(file, 10000, SEEK_CUR);
if (result != 0)
...
count = sgx_fwrite(buffer, 10, 100, file);
if (count != 100)
...
count = sgx_fwrite(buffer, 100, 10, file);
if (count != 10)
...
result = sgx_fseek(file, 15000, SEEK_CUR);
if (result != 0)
...
count = sgx_fread(buffer, 10, 100, file);
if (count != 100)
...
count = sgx_fread(buffer, 100, 10, file);
if (count != 10)
...
result = sgx_fseek(file, 20000, SEEK_SET);
if (result != 0)
...
count = sgx_fwrite(buffer, 10, 100, file);
if (count != 100)
...
count = sgx_fwrite(buffer, 100, 10, file);
if (count != 10)
...
result = sgx_fclose(file);
if (result != 0)
...

Thanks,
Ishai

**Comment by RodelFMiguel** [comment]
Hi Ishai,

Here's the simplified code that I am using.  Basically, I read a structure-sized chunk of data, check the contents of that structure, then overwrite that structure if it hits a condition.  I am hitting an error condition (ERR_FILE_WRITE) everytime, however, when I check the contents of the file later, the data is actually written.  My current "workaround" is not to check the return value.  I have tested this on the v1.9 release.

Thanks.

Kind Regards,
Rodel

---------------------------------------------------------------
    SGX_FILE* fp;
    fp = sgx_fopen_auto_key(file, "r+");
    if (!fp)
        ...

    do {
        read_sz = sgx_fread(entry, sizeof(unsigned char), entry_len, fp);
        if (...) {
	    // move back to the entry_length size when we hit a condition                
	    sgx_fseek(fp, -entry_len, SEEK_CUR);
            if (!sgx_fwrite(entry, sizeof(unsigned char), entry_len, fp));
                 status = ERROR(ERR_FILE_WRITE);
            break;
        }
    } while (read_sz);

    if (sgx_fclose(fp))
        status = ERROR(ERR_FILE_OPEN);
------------------------------------------------------------------

**Comment by naishai** [comment]
Hi,

If the code above is a direct copy from your code, then your bug is simply the ';' at the end of the 'if' statement.
Before I look further into it, please make sure this is not the problem.

Thanks,
Ishai
