### ISSUE TITLE
 SGX SDK installer is x86,not x64

### ISSUE THREAD

**Issue by daichunkai** [intel/linux-sgx#177]
Hello,When I use command
```
make sdk_install_pkg
```
to build the Intel(R) SGX SDK installer,the installer should be x64,but in my computer is x86, 
the install as follows:
![image](https://user-images.githubusercontent.com/17898478/32529748-d977fdf4-c3ff-11e7-9d25-e76a95ce9bc0.png)

and the information of my computer as follows:
![image](https://user-images.githubusercontent.com/17898478/32529518-a823d94a-c3fe-11e7-8660-b95ad8e36dc8.png)

**Comment by yuyuany** [comment]
Can you paste the output of the following command:
                 readelf -h $(SGX_SDK_DIR)/build/linux/sgx_sign

**Comment by daichunkai** [comment]
![image](https://user-images.githubusercontent.com/17898478/32535950-c8bc4a2a-c421-11e7-92f1-a39ba2b223fa.png)

**Comment by daichunkai** [comment]
also I find a question,When my system's language is English,it will build 64bit installer,but other language is x86

**Comment by yuyuany** [comment]
The installer build script simply reads the magic number of sgx_sign to determine it is x86 or x64. The parser may get the wrong number from a different language other than English. You can find the parser from get_arch() in linux/installer/bin/build-installpkg.sh.

**Comment by llly** [comment]
Can you give the result of `file -L /bin/sh` for another language except English?

**Comment by daichunkai** [comment]
@llly In Chinese ,the readout of `file -L /bin/sh`is 
![image](https://user-images.githubusercontent.com/17898478/32536923-0abe8506-c426-11e7-9884-3bcc74cfc62d.png)
@yuyuany  I find  build-installpkg.sh and I will try to change some code to build x64 installer

**Comment by yuyuany** [comment]
Ok, and pull requests are welcome.

**Comment by jat001** [comment]
```
LANGUAGE=en_US readelf -h build/linux/sgx_sign | sed -n '2p'
Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00

LANGUAGE=zh_CN readelf -h build/linux/sgx_sign | sed -n '2p'
Magic：  7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
```

The colon ```：``` is [fullwidth](https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms) in CJK computing. So ```awk '/:/{print $6}'``` does not work. The simplest solution is to remove ```/:/``` on https://github.com/intel/linux-sgx/blob/master/linux/installer/bin/build-installpkg.sh#L60
