### ISSUE TITLE
OpenSSL 1.1.0 Compatibility

### ISSUE THREAD

**Issue by omor1** [intel/linux-sgx#189]
When compiling, I get an error in `sdk/simulation/urtssim/enclave_creator_sim.cpp`
```
error: ‘void ERR_remove_thread_state(void*)’ is deprecated [-Werror=deprecated-declarations]
```

This is because the function is deprecated in OpenSSL 1.1.0.

**Comment by omor1** [comment]
There seem to be other problems associated with OpenSSL 1.1.0 (for instance, `sdk/sign_tool/SignTool/sign_tool.cpp` has accesses to members of structs, which is no longer allowed; they are now opaque, and require using function accessors).

See [the wiki](https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes) for an overview of the API changes and suggested fixes.

**Comment by llly** [comment]
Thanks. We will fix it. You can create a pull request about it if you'd like to contribute to SGX.

**Comment by samscott89** [comment]
Sorry for the noise. I have a WIP patch which works fine on 1.1, but needs some work for < 1.1.

**Comment by samscott89** [comment]
Fixes addressed by #203 instead. Thanks all for the awesome work.

**Comment by lzha101** [comment]
The PR #203 has been merged.

**Comment by omor1** [comment]
Thanks @lzha101 and @samscott89 for getting this merged! Can this be close now—are there any other OpenSSL 1.1.0 compatibility issues?

**Comment by lzha101** [comment]
Sure, please close this if you have no other related comments.
