### ISSUE TITLE
Should add  \$SGX_SDK/lib64 at 186th and 188th line of linux-sgx/linux/installer/bin/install-sgx-sdk.bin.tmpl?

### ISSUE THREAD

**Issue by TaihuLight** [intel/linux-sgx#193]
**error while loading shared libraries: libsgx_urts.so: cannot open shared object file: No such file or directory**
For the error as above when run the code of SampleCode/LocalAttestation, it works well for me on Ubuntu 16.04.2 after add \$SGX_SDK/lib64 at 186th and 188th line of linux-sgx/linux/installer/bin/install-sgx-sdk.bin.tmpl
@Jaak

**Comment by lzha101** [comment]
The libsgx_urts.so in $SGX_SDK/lib64 is only for build.  You need to install the PSW installer and use the libsgx_urts.so from PSW for runtime.

**Comment by TaihuLight** [comment]
BTW.  SGX_INVALID_LICENSE in the graphene/Pal/src/host/Linux-SGX/sgx_framework.c is nor declared, and it leads to error!
