### ISSUE TITLE
Modifying and compiling PSE code inside PSW

### ISSUE THREAD

**Issue by fatimanwar** [intel/linux-sgx#194]
I am trying to modify the Platform Service Enclave (PSE) code inside the Platform Software (PSW) of Linux SDK.

I noticed that the compilation process of intel SGX linux SDK and PSW does not compile the individual source code of architectural enclaves (AE) like pse, le, qe etc. Instead the makefile downloads prebuilt binaries signed by Intel and copy them to the "/opt/intel/psw" path upon installation.

When I tried to compile the code changes using "USE_OPT_LIBS = 0" option, it still did not compile the AEs source code at "psw/ae/..". So I manually changed the makefiles such that that it no longer looks for prebuilt binaries for AEs, instead it compiles the source code of AEs at "psw/ae" path and install the generated binaries to /opt/intel. I only made changes to "psw/ae/pse/pse_op" enclave, compiled and made sure that the generated binary (pse_op.so file) is actually installed. But when I tried to run a very simple API like "sgx_create_pse_session", which makes use of pse_op AE, it failed with the error code (0x4001) which is SGX_ERROR_SERVICE_UNAVAILABLE (aesm didn't respond or the requested service is not supported). I know for sure that the service is supported, so I am assuming that aesm didn't respond to the request. What I am assuming that my generated binary (pse_op.so) was not signed by Intel, hence aesm is rejecting it. Correct me if I am wrong in my analysis. Kindly guide me if it is possible to,

1. change an AE code like pse_op code, and test it? If so, what changes do we have to make so that aesm does not reject it. Can we sign our modified AE code by own key and then make the aesm accept it for development purposes?

2. If we can make changes to code for an AE (pse_op in my  case), and compile it but cannot test it, what is the point of having the code and its makefile in Linux SDK?

I really need this for my development and testing, and looking forward to a response from the community.

**Comment by yuyuany** [comment]
Yes, architectural enclaves (AE) are special type of enclaves. They must be signed by Intel, otherwise, they cannot be loaded. The AE source code is only used for debug purpose, and users can read the code to understand how AE works.

**Comment by andyzyb** [comment]
The PSE is talking to CSME and Intel backend service.  Simply changing the logic of PSE and rebuilding it won't work at present.  It needs to be release signed.  

Currently for a release signing if the signer is not in whitelist of Intel's Launch Enclave, it won't be loaded successfully.

**Comment by bodzhang** [comment]
@fatimanwar, The PSE and certain other AEs related to SGX remote attestation interact with Intel backend, which must verify the identity of the enclaves before issuing credentials to them required to perform their functions. AEs signed by any key different from the original signing key owned by Intel will not be accepted by the Intel  backend. The AE source code and build script is provided for the community to review the function and security of the implementation. You can modify and sign the PSE-op enclave and test it (might require some change to the AESM code, which might have a check on PSE-op's signing key, supposedly to be same as the PSE-Pr signing key) , but the modified PSE-op will not be able to use the secure channel with CSME FW established by the unmodified PSE-pr. Without security communication to the CSME, the root of trust of the Trusted Time service and Monotonic Counter is not present, but the PSE-op code can simulate them if your purpose is to test alternative implementation outside of the Root of Trust portion.
