### ISSUE TITLE
Use BigNumber implementation from IPP

### ISSUE THREAD

**Issue by CiraciNicolo** [intel/linux-sgx#195]
Hi,

for my project, I need a big number (integer) implementation. How can I achieve this using IPP? There is an example somewhere? Or can I link the GNU GMP library and use it inside an enclave?

**Comment by naishai** [comment]
You can use sgx-ssl, an OpenSSL port for SGX.
https://github.com/intel/intel-sgx-ssl

**Comment by CiraciNicolo** [comment]
I'm unable to build the library, I get an error with the script: 

```
make[1]: ingresso nella directory "/home/<user>/intel-sgx-ssl/Linux/sgx/test_app"
make[1]: uscita dalla directory "/home/<user>/intel-sgx-ssl/Linux/sgx/test_app"
make -C ./test_app    -f sgx_t.mk clean;
make[1]: ingresso nella directory "/home/<user>/intel-sgx-ssl/Linux/sgx/test_app"
/bin/sh: 1: [: -ge: unexpected operator
make[1]: uscita dalla directory "/home/<user>/intel-sgx-ssl/Linux/sgx/test_app"
```

**Comment by naishai** [comment]
the test app is built after the actual libraries, so I think you already have what you need,
also, please look in the documentation in the project and make sure you have all the pre-requisites, and if you have any additional problems with it, please open another ticket there

**Comment by CiraciNicolo** [comment]
No, I don't have anything. The folders are empty, no binaries.

**Comment by CiraciNicolo** [comment]
This is the output using 'set -x'. As you can see the script fails and remove the binaries.

```
/bin/sh: 1: [: -ge: unexpected operator
make[1]: Leaving directory '/home/<user>/SGX/intel-sgx-ssl/Linux/sgx/test_app'
+ cd /home/<user>/SGX/intel-sgx-ssl/Linux/sgx/libsgx_tsgxssl
+ rm -f tsgxssl_version.cpp
+ cd /home/<user>/SGX/intel-sgx-ssl/Linux/sgx/libsgx_usgxssl
+ rm -f usgxssl_version.cpp
+ cd /home/<user>/SGX/intel-sgx-ssl/Linux/package
+ rm -rf include/openssl/aes.h include/openssl/asn1.h include/openssl/asn1_mac.h include/openssl/asn1t.h include/openssl/async.h include/openssl/bio.h include/openssl/blowfish.h include/openssl/bn.h include/openssl/buffer.h include/openssl/camellia.h include/openssl/cast.h include/openssl/cmac.h include/openssl/cms.h include/openssl/comp.h include/openssl/conf_api.h include/openssl/conf.h include/openssl/crypto.h include/openssl/ct.h include/openssl/__DECC_INCLUDE_EPILOGUE.H include/openssl/__DECC_INCLUDE_PROLOGUE.H include/openssl/des.h include/openssl/dh.h include/openssl/dsa.h include/openssl/dtls1.h include/openssl/ebcdic.h include/openssl/ecdh.h include/openssl/ecdsa.h include/openssl/ec.h include/openssl/engine.h include/openssl/e_os2.h include/openssl/err.h include/openssl/evp.h include/openssl/hmac.h include/openssl/idea.h include/openssl/kdf.h include/openssl/lhash.h include/openssl/md2.h include/openssl/md4.h include/openssl/md5.h include/openssl/mdc2.h include/openssl/modes.h include/openssl/objects.h include/openssl/obj_mac.h include/openssl/ocsp.h include/openssl/opensslconf.h include/openssl/opensslconf.h.in include/openssl/opensslv.h include/openssl/ossl_typ.h include/openssl/pem2.h include/openssl/pem.h include/openssl/pkcs12.h include/openssl/pkcs7.h include/openssl/rand.h include/openssl/rc2.h include/openssl/rc4.h include/openssl/rc5.h include/openssl/ripemd.h include/openssl/rsa.h include/openssl/safestack.h include/openssl/seed.h include/openssl/sha.h include/openssl/srp.h include/openssl/srtp.h include/openssl/ssl2.h include/openssl/ssl3.h include/openssl/ssl.h include/openssl/stack.h include/openssl/symhacks.h include/openssl/tls1.h include/openssl/ts.h include/openssl/txt_db.h include/openssl/ui.h include/openssl/whrlpool.h include/openssl/x509.h include/openssl/x509v3.h include/openssl/x509_vfy.h
+ rm -rf lib64/release/libsgx_tsgxssl.a lib64/release/libsgx_tsgxssl_crypto.a lib64/release/libsgx_usgxssl.a
+ rm -rf lib64/debug/libsgx_tsgxssl.a lib64/debug/libsgx_tsgxssl_crypto.a lib64/debug/libsgx_usgxssl.a
+ cd /home/<user>/SGX/intel-sgx-ssl/Linux
+ exit 0
```

**Comment by akryeem-INTC** [comment]
Looks like it exit with 0 return code.
Can you check if there is any tar.gz package in the Linux/ directory? (sgxssl*.tar.gz)

**Comment by CiraciNicolo** [comment]
Yep, there is a sgxssl tar

**Comment by akryeem-INTC** [comment]
Good, that tar includes the required libraries.

**Comment by CiraciNicolo** [comment]
Furthermore, it seems that tsetjmp is not available. The pdf state that it ships with SGX SDK

`/usr/bin/ld.bfd.real: cannot find -lsgx_tsetjmp`

**Comment by yuyuany** [comment]
Which version of SGX SDK are you using? tsetjmp is a separate library in Linux 1.9, but it's merge to libsgx_tstdc.a in Linux 2.0.

**Comment by lzha101** [comment]
@CiraciNicolo, besides SGXSSL library, actually the libsgx_tcrypto.a based on optimized IPP library also has the Big Number implementation. If you just want to use Big Number inside enclave, you can choose to use the implementation in that library.  As we don't release the IPP header files in SGX SDK, you need to  include some necessary IPP header files in your enclave project or directly add some necessary function declarations in your enclave code before calling them.  The IPP header files could be found under `external/ippcp_internal/inc`

**Comment by CiraciNicolo** [comment]
Regarding IPP BigNumber, there is a way to convert a BigNumber to a common integer type?

**Comment by lzha101** [comment]
@CiraciNicolo if you choose to use IPP BigNumber in the libsgx_tcrypto, you don't need sgx-ssl.  And you can use ippsRef_BN() to convert a BigNumber to a common integer type. Refer to https://software.intel.com/en-us/ipp-crypto-reference-big-number-arithmetic for more info.

**Comment by jasiek** [comment]
I've had luck using bignum from OpenSSL.

**Comment by jmechalas** [comment]
I have posted an implementation of libgmp that works in an enclave. No source changes were needed (save for commenting out some fprintf statements). Most of the work was in integrating SGX into GMP's build system.

[sgx-gmp](https://github.com/intel/sgx-gmp)
[sgx-gmp-demo](https://github.com/intel/sgx-gmp-demo)
