### ISSUE TITLE
About statically Linking the app

### ISSUE THREAD

**Issue by penhoi** [intel/linux-sgx#196]
Hi, 

I am trying to link the app (the app from SampleCode/SampleEnclave) in a static way.

When i use the flag "App_Link_Flags := $(SGX_COMMON_CFLAGS) -static -L$(SGX_LIBRARY_PATH) -l$(Urts_Library_Name) -lpthread" for linking,  i get a huge number of errors! 

When i use the flag "App_Link_Flags := $(SGX_COMMON_CFLAGS) -static libsgx_urts.a libsgx_uae_service.a libprotobuf.a liburts_internal.a libittnotify.a  -lpthread -ldl"  for linking, it success but the running of app crashes!

So could someone give me some suggestions on fixing it?
Thanks.

**Comment by llly** [comment]
`liburts_internal.a` should not be linked. As it's named it's for internal linking only.

**Comment by penhoi** [comment]
Thanks @llly 

The compling process is OK, but the output binary is wield. 

We know function sgx_create_enclave is contained in libsgx_urts.a, it should also be appeared in the output binary as we apply static linking.
However, the result is as following:

------------------------------------------------------------------------------------------------------
    14 000000007102d010 <.plt.got>:
    15     7102d010:   ff 25 ca 7f 5c 00       jmpq   *0x5c7fca(%rip)        # 715f4fe0 <_DYNAMIC+0x150>
    16     7102d016:   66 90                   xchg   %ax,%ax
    17     7102d018:   ff 25 ca 7f 5c 00       jmpq   *0x5c7fca(%rip)        # 715f4fe8 <_DYNAMIC+0x158>
    18     7102d01e:   66 90                   xchg   %ax,%ax
    19     7102d020:   ff 25 ca 7f 5c 00       jmpq   *0x5c7fca(%rip)        # 715f4ff0 <_DYNAMIC+0x160>
    20     7102d026:   66 90    
 ......
 20994     71042388:   be 01 00 00 00          mov    $0x1,%esi
 20995     7104238d:   48 89 c7                mov    %rax,%rdi
 20996     71042390:   e8 83 ac fe ff          callq  7102d018 <__executable_start+0x2d018> #Is this instruction wiled?
 20997     71042395:   89 45 fc                mov    %eax,-0x4(%rbp)
 20998     71042398:   83 7d fc 00             cmpl   $0x0,-0x4(%rbp)

------------------------------------------------------------------------------------------------------

The source code is  "sgx_create_enclave(eid, ...)", so the expected binary code should be "call sgx_create_enclave". However, it is "callq  7102d018 <__executable_start+0x2d018>", whose target is a dynamically resolved function! So, i think, there are something wrong.

**Comment by haitaohuang** [comment]
Did you build libsgx_urts.a from source? There is no static lib in installed binaries,
Also not sure why you need static link, but libsgx_urts.so under sdk/lib64 is only a shell for dynamic link and  it does not have any implementation code in it. If you want to static link, you need link the binary deployed by psw installer under /usr/lib/. 

Note you'll need update your application whenever urts is updated if you static link. And you'll need make sure urts/uae_service dependencies installed as well

**Comment by gshankaran** [comment]
@penhoi - were you able to get it working with static library. 

@haitaohuang - One question regarding psw. I build an app with simulator (without installing psw) and it works fine. When exactly do we need psw ? Is it needed only when we run on real hardware? Also what libraries should be included in urts.a from psw

**Comment by llly** [comment]
@penhoi 's `-static` is command line means building a static executable instead of normal  dynamic executable. Maybe `-Wl,-Bstatic -lurts -Wl,-Bdynamic` is needed for static linking. 

PSW is needed only when we run on real hardware. This is to say enclave built with trts instead of trts_sim, app built with urts instead of urtssim, SGX driver works.
