### ISSUE TITLE
Kernel SGX driver

### ISSUE THREAD

**Issue by light1021** [intel/linux-sgx#200]
Hi：
I noticed that there are some changes like：
+    if (is_in_kernel_driver())
 +    {
 +        //Should not be called
 +        AESM_LOG_ERROR("InKernel LE loaded");
 +        return AESM_SERVICE_UNAVAILABLE;
 +    }

in asem，is that means SGX Psw now supports both kernel integrated driver (/dev/sgx) and normal sgx driver（/dev/isgx） ？

**Comment by andyzyb** [comment]
Thanks for noticing that. Yes, now the user space software supports both in-kernel driver (which was posted for upstream review) and out of tree driver in https://github.com/intel/linux-sgx

**Comment by light1021** [comment]
Hi: It's great to here that. Can you please tell me where can I find the in-kernel driver ? I have tried the KVM-sgx project before.  Is the in-kernel driver something like driver in that project?
Kind regard
you

**Comment by haitaohuang** [comment]
Hi the upstreaming in-kernel module is still under review so there is no formal release at the moment. It is here: https://github.com/jsakkine-intel/linux-sgx/tree/mainline-v10.  We do only limited testing against particular version ( the current tip in above branch) in that tree to ensure that PSW and SDK user space components are compatible.

**Comment by light1021** [comment]
@haitaohuang Hi， Sorry for my late replay. Thank you very much !
