### ISSUE TITLE
Intel SGX Eclipse Plugin on Linux 

### ISSUE THREAD

**Issue by srjrjjr** [intel/linux-sgx#207]
Dear All, 
The recommended Eclipse Mars 1 version of C/C++ IDE is buggy. It is impossible to even install the Eclipse SGX Plugin( I tried the latest version as well as older versions of the plugin 1.9,2.0,2.1 etc). None of them work on newer Eclipse(Oxygen). Can anyone recommend a newer version of Eclipse IDE with a working version of the plugin please?

Thanks a ton.

Sri.

**Comment by xiangquanliu** [comment]
Hi Sri,
Right now you can only use Mars 1 or Mars 2. In Ubuntu 1604, you need to modify file eclipse.ini to make it work.

Add one parameter "--launcher.GTK_version" to eclipse.ini like bellow.

--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.400.v20160518-1444
**--launcher.GTK_version
2**

We may plan to upgrade the eclipse to latest version. Thanks!

**Comment by gmatesunny** [comment]
Please target visual studio code for Linux in future.

**Comment by andyzyb** [comment]
@gmatesunny We currently don't have plan to support Visual Studio code.  It is a good suggestion, but it seems a big investment and not sure how many Linux developers actually use it.
