### ISSUE TITLE
conflicting declaration with ‘C’ linkage, note: previous declaration with ‘C++’ linkage

### ISSUE THREAD

**Issue by gmatesunny** [intel/linux-sgx#208]
untrusted files:

u_fileutils.h
`int ocall_get_textsize(const char *fname, long *f_size, int is_encrypted);`

u_fileutils.cpp

```
#include "u_fileutils.h"
int ocall_get_textsize(const char *fname, long *f_size, int is_encrypted)
{

	FILE *ifp = NULL;
	if((ifp = fopen(fname, "rb")) == NULL)
	{
		std::cout << "input file not found" << std::endl;
		return -1;
	}

	fseek(ifp, 0, SEEK_END);
	long fsize = ftell(ifp);
	fseek(ifp, 0, SEEK_SET);

	if(is_encrypted == 0)
	{
		*f_size = fsize;
		fclose(ifp);
		return 0;
	}
	*f_size = fsize - (SGX_AESGCM_MAC_SIZE + SGX_AESGCM_IV_SIZE);
	fclose(ifp);
	return 0;
}
```

edl file:

```
    untrusted {
      
	int ocall_get_textsize([in] const char *fname, [out] long *fsize, int is_encrypted); 
};
```

on the compilation I keep getting the error:

```
In file included from /opt/intel/sgxsdk/include/sgx_urts.h:40:0,
                 from untrusted/../includes/u_fileutils.h:10,
                 from untrusted/u_fileutils.cpp:1:
untrusted/analysis_u.h:20:108: error: conflicting declaration of ‘int ocall_get_textsize(const char*, long int*, int)’ with ‘C’ linkage
 int SGX_UBRIDGE(SGX_NOCONVENTION, ocall_get_textsize, (const char* fname, long int* fsize, int is_encrypted));
                                                                                                            ^
/opt/intel/sgxsdk/include/sgx_defs.h:49:55: note: in definition of macro ‘SGX_UBRIDGE’
 # define SGX_UBRIDGE(attr, fname, args...) attr fname args
                                                       ^
In file included from untrusted/u_fileutils.cpp:1:0:
untrusted/../includes/u_fileutils.h:23:5: note: previous declaration with ‘C++’ linkage
 int ocall_get_textsize(const char *fname, long *f_size, int is_encrypted);
```

My makefile flags for untrusted part.
```
ifeq ($(SGX_DEBUG), 1)
        App_C_Flags += -DDEBUG -UNDEBUG -UEDEBUG
else ifeq ($(SGX_PRERELEASE), 1)
        App_C_Flags += -DNDEBUG -DEDEBUG -UDEBUG
else
        App_C_Flags += -DNDEBUG -UEDEBUG -UDEBUG
endif

App_Cpp_Flags := $(App_C_Flags) -std=c++11
```
I have never faced such C linkage kind of error. Could someone please guide me on this, how to resolve it, or what is wrong with my code. I am using default eclipse generated code but I create *.cpp files.

**Comment by andyzyb** [comment]
I guess you may 2 definitions for ocall_get_textsize,  please check if they are the same.  Other may come with extern "C" while the other does not.

**Comment by gmatesunny** [comment]
I suspected I did  wrong declaration in edl file but not sure what and how to correct.

**Comment by hyjiang** [comment]
The OCALL function "ocall_get_textsize" defined in "u_fileutils.h" is used in both your app code (.cpp) and SGX proxy code (.c). 

So I am assume you need to add extern "C" in header file "u_fileutils.h", like this:

'''''''''''''''''''''''''''''''''''
#ifdef __cplusplus
extern "C" {
#endif

int ocall_get_textsize(const char *fname, long *f_size, int is_encrypted);

#ifdef __cplusplus
}
#endif
''''''''''''''''''''''''''''''''''''''

**Comment by gmatesunny** [comment]
Solved, but the other way would be to write another proxy function that calls the actual 

int ocall_get_textsize(const char *fname, long *f_size, int is_encrypted);

[Yes?] Which way is preferred 1. direct use 2. writing a wrapper function?
