### ISSUE TITLE
SGX driver removed if SGX device exists

### ISSUE THREAD

**Issue by jethrogb** [intel/linux-sgx#209]
The following was added to `linksgx.sh` in 2.1, which has the strange consequence of unloading the SGX driver if the SGX device is detected, which of course results in AESMD being unable to load:
```
if [ -e /dev/sgx ]; then
    chmod 666 /dev/sgx &> /dev/null
    /sbin/modprobe -r isgx &> /dev/null
```

**Comment by ZongminGu** [comment]
Please check the /dev/sgx node on your machine. If you need to use isgx node, please remove /dev/sgx. We are only able to support one SGX driver on a machine.
