### ISSUE TITLE
Question: Passing vector of vector to enclave

### ISSUE THREAD

**Issue by gmatesunny** [intel/linux-sgx#213]
I have a vector<vector<string>> a; How could I pass it to the enclave? How I declare edl function. 
A sample function declaration for the app, edl and enclave is much appreciated. 

I am aware of this: https://stackoverflow.com/questions/41901884/c-arguments-to-sgx-enclave-edge-functions.

A sample to pass even a vector of string is ok for me.

**Comment by gmatesunny** [comment]
I came up with this:

App.cpp
const char *convert(const std::string & s)
{
   return s.c_str();
}
	std::vector<const char*>  vc;
	std::transform(members_data.begin(), members_data.end(), std::back_inserter(vc), convert);


edl:
    trusted {
    	   public void ecall_receive_vector([in, size=len] const char **arr, size_t len);
    };

enclave
void ecall_receive_vector(const char *arr[], size_t len)
{
	vector<string> v(arr, arr+len);

	printf("%s\n", v[2].c_str());

}

But enclave does not receive any data, the program compiles perfectly with no error. Could anyone help?

**Comment by light1021** [comment]
Hi :
Maybe you can pass it by using a char buffer and a int array represent size of each string member.

`ecall_receive_vector([in, size=len]  char arr_buffer[], int size_of_memberstring[], size_t len);`

Inside enclave, When you get the content of arr_buffer[], you can use the size in  size_of_memberstring[] to get back the strings.

**Comment by andyzyb** [comment]
Yes, we don't support C++ class passing through the boundary of Enclave in EDL file. You have to change it to some equivalent C struct or array.
