### ISSUE TITLE
remove copywrite obligations from sample code

### ISSUE THREAD

**Issue by dimalinux** [intel/linux-sgx#214]
Can Intel use a separate copyright, without restrictions, on their sample code?

I can understand a restrictive copyright on SDK libraries, but copyrights that create obligations should not be in sample code that Intel would reasonably expect developers to use as a starting point for their own projects.  The barrier to entry for using SGX is already sky-high.  I don't think it's in Intel's interest to make it any higher.  :)

**Comment by haitaohuang** [comment]
We are using standard BSD-3 clause headers which is the same as other parts of this repo. So I would expect no additional hurdle if you are using SDK and PSW from this git. Maybe I missed some of your points,  but what are the restrictions causing additional obligations? Or what do you suggest?

**Comment by haitaohuang** [comment]
We still  prefer to use the same license for all code we created in this project. However, we will consider replacing the existing header with just the copyright statement and the SPDX license identifier which would make it even easier to copy.
