### ISSUE TITLE
Why is `type_info` non-SGX only?

### ISSUE THREAD

**Issue by nhynes** [intel/linux-sgx#218]
In tlibcxx [`type_index`](https://github.com/intel/linux-sgx/blob/0fb9f47e784261369c52c1b49d1484f34409ecaf/sdk/tlibcxx/include/typeindex#L92-L103) has its `hash` method gated for non-SGX use. The underlying issue is that [`type_info`](https://github.com/intel/linux-sgx/blob/0fb9f47e784261369c52c1b49d1484f34409ecaf/sdk/tlibcxx/include/typeinfo#L61-L63) is non-SGX only. This seems to conflict with [the docs](https://download.01.org/intel-sgx/linux-2.1.1/docs/Intel_SGX_Developer_Reference_Linux_2.1.1_Open_Source.pdf) which suggest that `type_index` is fully supported. Is there a reason for this?

**Comment by andyzyb** [comment]
tlibcxx is only targeted to be used with SGX.  What specific usage you are targeting?  I think it is mainly to simply the implementation because C++ name mangling is complicated.

**Comment by nhynes** [comment]
Thanks for the reply! I'm specifically trying to port a [JSON parser](https://github.com/dmlc/dmlc-core/blob/master/include/dmlc/json.h#L533) that can look up a type by name and then construct that type.

I removed the feature gates in the relevant files and found that compilation worked. My worry is that some linking error will occur, which is why I ask _why_ the feature is disabled.

**Comment by xxu36** [comment]
Hi @nhynes 
Most of `type_info`'s functionalities are not disabled inside enclave. We just use the implementation from libcxxrt (sdk/cpprt/linux/typeinfo.cc) from the beginning of the project. Now, to supply a C++11 compliant STL, we ported LLVM's libc++, but for the runtime part, we still stick to libcxxrt at this moment. 

`type_index` is a C++11 feature. The `hash_code` method in this class, according to the source code, replies on `type_info`'s `hash_code` method, which does not exist within libcxxrt‘s implementation. 

So, precisely, the `hash_code` method of type_info class is not implemented in enclave. We can fix it when we upgrade the runtime as a whole. But I do not know when we can do it. Or we can fix it by referencing the `hash_code` method provided by libc++ and put it inside our current implementation.

**Comment by xxu36** [comment]
Hi @nhynes
Most of type_info's functionalities are not disabled inside enclave. We just use the implementation from libcxxrt (sdk/cpprt/linux/typeinfo.cc) from the beginning of the project. Now, to supply a C++11 compliant STL, we ported LLVM's libc++, but for the runtime part, we still stick to libcxxrt at this moment.

type_index is a C++11 feature. The hash_code method in this class, according to the source code, relies on type_info's hash_code method, which does not exist within libcxxrt‘s implementation.

So, precisely, the hash_code method of type_info class is not implemented in enclave. We can fix it when we upgrade the runtime as a whole. But I do not know when we can do it. Or we can fix it by referencing the hash_code method provided by libc++ and put it inside our current implementation.
