### ISSUE TITLE
undefined reference error when calling "sgx_create_pse_session()"

### ISSUE THREAD

**Issue by rupc** [intel/linux-sgx#220]
Hello, I'm using SGX 2.1 in hardware mode. 
I have trouble with generating enclave image:
When I used "sgx_create_pse_session" function in enclave, and compiling with provided Makefile from SampleCode/Cxx11SGXDemo directory (I didn't touch any flags except for adding my own .cpp file to generate object file)
following error message occurs.

```
CXX  <=  Enclave/Enclave.cpp
/home/jyr/work/proj/linux-sgx/linux/installer/bin/sgxsdk/lib64/libsgx_tservice.a(tae_service.o): In function `close_pse_session_within_mutex() [clone .part.0]':
tae_service.cpp:(.text._ZL30close_pse_session_within_mutexv.part.0+0x4c): undefined reference to `close_session_ocall'
/home/jyr/work/proj/linux-sgx/linux/installer/bin/sgxsdk/lib64/libsgx_tservice.a(tae_service.o): In function `create_pse_session_within_mutex() [clone .part.1]':
tae_service.cpp:(.text._ZL31create_pse_session_within_mutexv.part.1+0xcc): undefined reference to `create_session_ocall'
tae_service.cpp:(.text._ZL31create_pse_session_within_mutexv.part.1+0x140): undefined reference to `exchange_report_ocall'
tae_service.cpp:(.text._ZL31create_pse_session_within_mutexv.part.1+0x2d0): undefined reference to `close_session_ocall'
/home/jyr/work/proj/linux-sgx/linux/installer/bin/sgxsdk/lib64/libsgx_tservice.a(tae_service.o): In function `crypt_invoke(_pse_message_t*, unsigned int, _pse_req_hdr_t*, unsigned int, _pse_message_t*, unsigned int, _pse_resp_hdr_t*) [clone .constprop.5]':
tae_service.cpp:(.text._ZL12crypt_invokeP14_pse_message_tjP14_pse_req_hdr_tjS0_jP15_pse_resp_hdr_t.constprop.5+0xb5): undefined reference to `invoke_service_ocall'
collect2: error: ld returned 1 exit status

```

I have right location which points to $(SGX_SDK) and it is well installed.
Other crypto functions such as  sgx_cmac128_*() or sgx_sha256_*(), works well though.
I got successfully generate enclave image when I removed sgx_create_pse_session(). I used this function to make use of monotonic counter functions.
Can I get some help?
Thanks!

**Comment by andyzyb** [comment]
Please check SealedData sample code for using platform service(sgx_create_pse_session), you need to include sgx_tae_service.edl in your enclave EDL file.   See below EDL file for example:

https://github.com/intel/linux-sgx/blob/master/SampleCode/SealedData/DRM_enclave/DRM_enclave.edl

**Comment by light1021** [comment]
Hi:
And you also need to and link flags in your make file.
`-lsgx_tservice`

**Comment by rupc** [comment]
Thanks a lot! After importing "sgx_tae_service.edl", it works fine.
