### ISSUE TITLE
Can the latest release linux SGX SDK prevent SgxPectre ?

### ISSUE THREAD

**Issue by light1021** [intel/linux-sgx#224]
Hi：Recently I read a paper on SGXPectre，which can leak enclave secret.  What I want to know is that can the latest release of linux SGX SDK can prevent this from happening， If not what can we do ？

**Comment by andyzyb** [comment]
Please refer to below SGX whitepaper for latest change of SGX software, and recommendation for user's Enclave code.

https://software.intel.com/sites/default/files/180204_SGX_SDK_Developer_Guidance_v1.0.pdf
