### ISSUE TITLE
[feature request] expose enclave_id to ocall targets

### ISSUE THREAD

**Issue by nhynes** [intel/linux-sgx#226]
It'd be useful for an `ocall` target to automatically receive the `enclave_id` of the calling enclave. For backwards compatibility, this could be configured using the `enclave_config.xml`.

Currently the unergonomic alternative is to pass the `eid` into the enclave, register it as a global, and send it back out.

**Comment by ZongminGu** [comment]
An alternative solution is: Save the enclave_id as a TLS variable before using the ecall. In the ocall, if you need the enclave_id, read the variable.

**Comment by nhynes** [comment]
This is probably a better idea. Thanks!
