### ISSUE TITLE
Strange issue with binary read 

### ISSUE THREAD

**Issue by gmatesunny** [intel/linux-sgx#229]
I have a some((DecisionTree) C++ class in app and enclave. As I know I cannot pass C++ class through enclave, I tried to save the set(initialized) object of the class to the disk in binary format like this at App.
This save to disk actual purpose is to use it later. The idea is train the ML model and pass inside enclave. 
 
```
	FILE * file = fopen("/home/roshan/thesis/server/data/user/alice/dt_model", "wb");
	if (file != NULL) {

		fwrite((char*)&decisionTree, sizeof(DecisionTree), 1, file);
		fclose(file);
		cout << "wrote to file" << endl;
	}
```
Then I read the saved object from disk in binary format like this at App and passed to enclave.
```
    char data[sizeof(DecisionTree)];
    if((file = fopen("/home/roshan/thesis/server/data/user/alice/dt_model", "rb")) != NULL)
    {
    	printf("Read the file and loaded into data");
    	fread(data, (long)sizeof(DecisionTree), 1, file);
    	long fsize = (long)sizeof(DecisionTree);
    	ret = ecall_analysis_server(global_eid, &ecall_return, data, fsize);
}
```

At enclave I do this:
```
int ecall_analysis_server(char *data2, long fsize2)
{
	DecisionTree *decisionTree2 = reinterpret_cast<DecisionTree*>(data2);
	vector<vector<string> > test_data;
	vector<string> tmp = {"<=30","low","no","fair"};
	test_data.push_back(tmp);
	auto x = decisionTree2->guess(test_data[0]);
	print_debug("%s: result of new", x.c_str());
}
```
In Edl I wrote this:
```
    trusted {
    	    public int ecall_analysis_server([in, size=fsize] char* data, long fsize);
}
```
Now the problem is print_debug("%s: result of new", x.c_str()); gives me the wrong result but when I do similar thing at App like this after/before **ret = ecall_analysis_server(global_eid, &ecall_return, data, fsize);** it gives me the correct result. 
At App:
```
    	DecisionTree *decisionTree3 = reinterpret_cast<DecisionTree*>(data);
		vector<vector<string> > test_data;
		vector<string> tmp = {"<=30","low","no","fair"};
		test_data.push_back(tmp);
		cout << decisionTree3->guess(test_data[0]);
```

My Class looks like this:

```
class Table {
public:
    vector<string> attrName;
    vector<vector<string> > data;

    vector<vector<string> > attrValueList;
    void extractAttrValue() {
        attrValueList.resize(attrName.size());
        for(int j=0; j<attrName.size(); j++) {
            map<string, int> value;
            for(int i=0; i<data.size(); i++) {
                value[data[i][j]]=1;
            }

            for(auto iter=value.begin(); iter != value.end(); iter++) {
                attrValueList[j].push_back(iter->first);
            }
        }
    }
};

class Node {
public:
    int criteriaAttrIndex;
    string attrValue;

    int treeIndex;
    bool isLeaf;
    string label;

    vector<int > children;

    Node() {
        isLeaf = false;
    }
};

class DecisionTree {
public:
    int checker;
    Table initialTable;
    vector<Node> tree;
    DecisionTree() = default;


    DecisionTree(Table table) {
        initialTable = table;
        initialTable.extractAttrValue();

        Node root;
        root.treeIndex=0;
        tree.push_back(root);
        run(initialTable, 0);
   }

    string guess(vector<string> row) {
        string label = "";
        int leafNode = dfs(row, 0);
        if(leafNode == -1) {
            return "dfs failed";
        }
        label = tree[leafNode].label;
        return label;
    }

    int dfs(vector<string>& row, int here) {
        if(tree[here].isLeaf) {
            return here;
        }

        int criteriaAttrIndex = tree[here].criteriaAttrIndex;

        for(int i=0;i<tree[here].children.size(); i++) {
            int next = tree[here].children[i];

            if (row[criteriaAttrIndex] == tree[next].attrValue) {
                return dfs(row, next);
            }
        }
        return -1;
    }

    void run(Table table, int nodeIndex) {
        if(isLeafNode(table) == true) {
            tree[nodeIndex].isLeaf = true;
            tree[nodeIndex].label = table.data.back().back();
            return;
        }

        int selectedAttrIndex = getSelectedAttribute(table);

        map<string, vector<int> > attrValueMap;
        for(int i=0;i<table.data.size();i++) {
            attrValueMap[table.data[i][selectedAttrIndex]].push_back(i);
        }

        tree[nodeIndex].criteriaAttrIndex = selectedAttrIndex;

        pair<string, int> majority = getMajorityLabel(table);
        if((double)majority.second/table.data.size() > 0.8) {
            tree[nodeIndex].isLeaf = true;
            tree[nodeIndex].label = majority.first;
            return;
        }

        for(int i=0;i< initialTable.attrValueList[selectedAttrIndex].size(); i++) {
            string attrValue = initialTable.attrValueList[selectedAttrIndex][i];

            Table nextTable;
            vector<int> candi = attrValueMap[attrValue];
            for(int i=0;i<candi.size(); i++) {
                nextTable.data.push_back(table.data[candi[i]]);
            }

            Node nextNode;
            nextNode.attrValue = attrValue;
            nextNode.treeIndex = (int)tree.size();
            tree[nodeIndex].children.push_back(nextNode.treeIndex);
            tree.push_back(nextNode);

            // for empty table
            if(nextTable.data.size()==0) {
                nextNode.isLeaf = true;
                nextNode.label = getMajorityLabel(table).first;
                tree[nextNode.treeIndex] = nextNode;
            } else {
                run(nextTable, nextNode.treeIndex);
            }
        }
    }

    double getEstimatedError(double f, int N) {
        double z = 0.69;
        if(N==0) {
   //         cout << ":: getEstimatedError :: N is zero" << endl;
            abort();
        }
        return (f+z*z/(2*N)+z*sqrt(f/N-f*f/N+z*z/(4*N*N)))/(1+z*z/N);
    }

    pair<string, int> getMajorityLabel(Table table) {
        string majorLabel = "";
        int majorCount = 0;

        map<string, int> labelCount;
        for(int i=0;i< table.data.size(); i++) {
            labelCount[table.data[i].back()]++;

            if(labelCount[table.data[i].back()] > majorCount) {
                majorCount = labelCount[table.data[i].back()];
                majorLabel = table.data[i].back();
            }
        }

        return {majorLabel, majorCount};
    }


    bool isLeafNode(Table table) {
        for(int i=1;i < table.data.size();i++) {
            if(table.data[0].back() != table.data[i].back()) {
                return false;
            }
        }
        return true;
    }

    int getSelectedAttribute(Table table) {
        int maxAttrIndex = -1;
        double maxAttrValue = 0.0;

        // except label
        for(int i=0; i< initialTable.attrName.size()-1; i++) {
            if(maxAttrValue < getGainRatio(table, i)) {
                maxAttrValue = getGainRatio(table, i);
                maxAttrIndex = i;
            }
        }

        return maxAttrIndex;
    }

    double getGainRatio(Table table, int attrIndex) {
        return getGain(table, attrIndex)/getSplitInfoAttrD(table, attrIndex);
    }

    double getInfoD(Table table) {
        double ret = 0.0;

        int itemCount = (int)table.data.size();
        map<string, int> labelCount;

        for(int i=0;i<table.data.size();i++) {
            labelCount[table.data[i].back()]++;
        }

        for(auto iter=labelCount.begin(); iter != labelCount.end(); iter++) {
            double p = (double)iter->second/itemCount;

            ret += -1.0 * p * log(p)/log(2);
        }

        return ret;
    }

    double getInfoAttrD(Table table, int attrIndex) {
        double ret = 0.0;
        int itemCount = (int)table.data.size();

        map<string, vector<int> > attrValueMap;
        for(int i=0;i<table.data.size();i++) {
            attrValueMap[table.data[i][attrIndex]].push_back(i);
        }

        for(auto iter=attrValueMap.begin(); iter != attrValueMap.end(); iter++) {
            Table nextTable;
            for(int i=0;i<iter->second.size(); i++) {
                nextTable.data.push_back(table.data[iter->second[i]]);
            }
            int nextItemCount = (int)nextTable.data.size();

            ret += (double)nextItemCount/itemCount * getInfoD(nextTable);
        }

        return ret;
    }

    double getGain(Table table, int attrIndex) {
        return getInfoD(table)-getInfoAttrD(table, attrIndex);
    }

    double getSplitInfoAttrD(Table table, int attrIndex) {
        double ret = 0.0;

        int itemCount = (int)table.data.size();

        map<string, vector<int> > attrValueMap;
        for(int i=0;i<table.data.size();i++) {
            attrValueMap[table.data[i][attrIndex]].push_back(i);
        }

        for(auto iter=attrValueMap.begin(); iter != attrValueMap.end(); iter++) {
            Table nextTable;
            for(int i=0;i<iter->second.size(); i++) {
                nextTable.data.push_back(table.data[iter->second[i]]);
            }
            int nextItemCount = (int)nextTable.data.size();

            double d = (double)nextItemCount/itemCount;
            ret += -1.0 * d * log(d) / log(2);
        }

        return ret;
    }
};
```

The strange part is when I check the value of DecisionTree::checker either from App or enclave it gives me the same value.

`print_debug("\n\nEnclave: %d\n\n", decisionTree2->checker); `

Could anyone, please enlighten me what is wrong I am doing? I have a fixed 64bit machine running on Ubuntu 16.04, so I do not need to worry about endianness. I think I am missing something conceptually.

**Comment by MWShan** [comment]
You might try using C++ Serialization where a class supports a serialize (or load/store) method to deliberately write its members out to a buffer in a specific format that can then be deserialized back into a new instantiation of the class.

Beware that when passing a "serialized" buffer into an enclave that elements of the buffer could be modified to cause a buffer to overrun.  For example, a size element may be deliberately set very large to cause the deserialization process to read farther than the length of the input buffer.  All input data should be checked (and the checks should be followed by fencing per [https://software.intel.com/en-us/download/intel-software-guard-extensions-sgx-sw-development-guidance-for-potential-bounds-check](url) )

**Comment by gmatesunny** [comment]
Why am I able to reinitialize correctly in the App but wrongly in Enclave?

I think what I did is how the C++ Serialization works without using any 3rd party library.

**Comment by MWShan** [comment]
What you are doing now may successfully copy the primitive member variables of your class; however, it looks like you are really storing the class object (which for some classes could include elements such as vtable pointer), not the full contents of the class.  Class members which consist of pointers will be copied directly instead of copying the data that is pointed to.  

Reconstructing the class object might work if you do it while the original class object still exists.  In this case you might find that the reconstructed class object is sharing member data with the original class.

I would emphasize that you should be careful when passing anything that contains pointers or sizes into the enclave.  All of these must be checked to make sure that they cannot compromise the security of the enclave.  For example, a pointer that is supposed to point to an outside buffer, may instead point to a place inside the enclave - this could cause the enclave to inadvertently reveal secrets.

**Comment by gmatesunny** [comment]
Any suggestion to the solution?

**Comment by MWShan** [comment]
This blog entry by Olivier Coudert  [http://www.ocoudert.com/blog/2011/07/09/a-practical-guide-to-c-serialization/](url) provides some insight into serialization (though deserializing an untrusted data buffer while inside the enclave requires extra security checks).

**Comment by gmatesunny** [comment]
**Update 2:**
I tried something else now:
Common function to App and enclave, taken intel sgx sample code:

```
int32_t checksum_internal(char *buf, size_t count)
{
    register int32_t sum = 0;
    int16_t *ptr = (int16_t *)buf;
    /* Main summing loop */
    while(count > 1) {
        sum = sum + *ptr++;
        count = count - 2;
    }
    /* Add left-over byte, if any */
    if (count > 0)
        sum = sum + *((char *)ptr);
	return ~sum;
}

```

In App:
```
    DecisionTree *decisionTree = new DecisionTree(trainInputReader.getTable());
    decisionTree->checker = 99;
    void *data3 = static_cast<void*>(decisionTree);
    DecisionTree *decisionTree2 = static_cast<DecisionTree*>(data3);
	long fsize = (long)sizeof(*decisionTree);

    int32_t sum = checksum_internal((char *)decisionTree2, fsize);
    printf("\n\nAPP: Checksum(0x%p, %zu) = 0x%x\n", decisionTree2, fsize, (unsigned int)sum);
	vector<vector<string> > test_data;
	vector<string> tmp = {"<=30","low","no","fair"};
	test_data.push_back(tmp);
	cout << decisionTree2->guess(test_data[0]);
    ret = ecall_analysis_server(global_eid, &ecall_return, data3, fsize);
```

It gives the result: 
APP: Checksum(0x0x99ba90, 104) = 0xfffb8f58

In EDL:
`public int ecall_analysis_server([user_check] void* data, long fsize);`

In Enclave:
```
int ecall_analysis_server(void *data2, long fsize2)
{
	DecisionTree *decisionTree6 = new DecisionTree;
	memcpy(decisionTree6, data2, fsize2);
        int32_t sum = checksum_internal((char *)decisionTree6, fsize2);
        print_debug("\n\nChecksum(0x%p, %zu) = 0x%x\n",
    		data2, fsize2, (unsigned int)sum);
	vector<vector<string> > test_data;
	vector<string> tmp = {"<=30","low","no","fair"};
	test_data.push_back(tmp);
	auto x = decisionTree6->guess(test_data[0]);
	return 0;
}
```
It also prints:
Checksum(0x0x99ba90, 104) = 0xfffb8f58

But decisionTree6->guess(test_data[0]); in enclave does not matched with what I got at App.

On debugging I found:
tree[here].children.size() at App is not been set same to tree[here].children.size() at enclave i.e. In app is set to 3 where as in enclave it is set to 0. 

Why even the memcpy() failed to initialize my class object properly inside the enclave. Also, I am using user_check this time and even the checksum value is same.

I have to make it work as it is a matter for my university assignment, else I will flunk. So if some kind soul could help.

**Comment by gmatesunny** [comment]
**update 3:**
Now I changed my structure and tried a fresh but still :(

I have a C++ struct like this:


    typedef vector<string> vs;
    typedef vector<vs> vvs;
    typedef vector<int> vi;
    typedef map<string, int> msi;
    typedef vector<double> vd;
    
    struct node													
    {
    	string splitOn;											
    	string label;											
    	bool isLeaf;											
    	vector<string> childrenValues;							
    	vector<node*> children;									
    };


I wanted to pass this from App to the enclave. Based on what is mentioned here: https://software.intel.com/en-us/forums/intel-software-guard-extensions-intel-sgx/topic/703489

I tried this:

**APP:**

    node *root = new node;											
    root = buildDecisionTree(dataTable, root, *tableInfo);	
    void *data3 = static_cast<void*>(root);
    ecall_my_dtree(global_eid, &ecall_return, data3);

**EDL:**

      public int ecall_my_dtree([user_check] void* data);

**Enclave:**

    int ecall_my_dtree(void *data2)
    node* root2 = static_cast<node*>(data2);

But it seems, the root2 is not able to initialize properly and it points to garbage. 

Any help regarding how I could properly read the data inside the enclave.
PS: Intel SGX enclave does not support any serialization library.

**Comment by llly** [comment]
To copy a class instance from app to enclave, you need a Copy Constructors which is Deep Copy instead of  memcpy() which is Shallow Copy.
