### ISSUE TITLE
Eclipse unable to run binary

### ISSUE THREAD

**Issue by gmatesunny** [intel/linux-sgx#232]
I have created an SGX project in eclipse and it compiles fine but when I try to run from eclipse it fails.

```
sgx_create_enclave returned 0x200f
Error: Can't open enclave file.
```
But it runs correctly from the terminal. My directory where the binary is placed look like this:
```
roshan@bolt:~/thesis/osn_server/sgx/enclave_enclave$ ls 
common             enclave.so  mbedtls_SGX-2.6.0  sgx_t.mk  trusted
enclave.signed.so  Makefile    osn_server         sgx_u.mk  untrusted
```
I know somehow the eclipse is not able to find the enclave.signed.so. Any idea what variable I could set either in eclipse or code to make it run from eclipse. 
I am not concerned about any production issue.

**Comment by gmatesunny** [comment]
Solution: If anyone else faces a similar problem, you need to perform chdir(absolutePath) before enclave initialization. 

    char absolutePath [MAX_PATH];
    char *ptr = NULL;
    ptr = realpath(dirname(argv[0]),absolutePath);
    if( chdir(absolutePath) != 0)
    		abort();

**Comment by xiangquanliu** [comment]
Hi,
The solution above is OK.
I'd like to explain why in eclipse it doesn't work if you doesn't use the above solution. As every executable is ran from the directory of your project by default. So if "enclave.signed.so" is put in the root directory of your project, it should woks fine. Also you may change your working directory and arguments under "Run configurations" - switch to tab "Arguments", uncheck "use default" and set whatever you like.
