### ISSUE TITLE
0x1007 which means SGX_ERROR_ECALL_NOT_ALLOWED 

### ISSUE THREAD

**Issue by gmatesunny** [intel/linux-sgx#233]
I am facing the error:
0x1007 which means SGX_ERROR_ECALL_NOT_ALLOWED
and the reason given here: https://software.intel.com/en-us/node/709252

> ECALL is not allowed at this time. For examples:ECALL is not public.ECALL is blocked by the dynamic entry table. A nested ECALL is not allowed during global initialization.

I have checked my ecall is public. Could someone can explain the reason:
1. ECALL is blocked by the dynamic entry table.
2.  A nested ECALL is not allowed during global initialization.

In my case: The server is running inside SGX(https://github.com/bl4ck5un/mbedtls-SGX/blob/master/example/enclave/ssl_conn_hdlr.cpp) After step 6 and in between step 7. I am calling an ocall, do something with the request payload and then call another different ecall which finally returns to the actual ecall(start of step 7 of ssl_conn_hdlr).

Am I doing nested ecall ? What does it mean by during global initialization.

Update 1:
I got it that I am doing nested ecall. But the document also says it is not allowed **during global initialization**. Any idea how I can over come that ? Should I create another enclave?

**Comment by gmatesunny** [comment]
I solved the issue. A simple approach is to make another thread in the app, all another function in the app and then from this function, you can perform any ecall.

**Comment by andyzyb** [comment]
Good to know if it is resolved.   

For your description, you are doing nested ECALLs - doing ECALL in the OCALL function.

In that case you need to define the ECALLs which are allowed in specific OCALL functions in EDL file.  Please look at developer reference for the detailed EDL syntax.

**Comment by andyzyb** [comment]
Global initialization only happens in Enclave initialization phase (create_enclave). A typical ECALL/OCALL flow will be after that phase.
