### ISSUE TITLE
Failed to generate dumpfile with sgx_sign

### ISSUE THREAD

**Issue by gmatesunny** [intel/linux-sgx#236]
SGX SDK 2.0
Based on page 15 of SDK developer reference, I tried to dump the enclave info to a file but it fails. Could anyone tell me the possible reason?

```
roshan@bolt:~/osn_server/sgx/enclave_enclave$ ls 
common  enclave.signed.so  enclave.so  Makefile  mbedtls_SGX-2.6.0  osn_server  sgx_t.mk  sgx_u.mk  third_party  trusted  untrusted
roshan@bolt:~/osn_server/sgx/enclave_enclave$ sgx_sign dump -enclave enclave.signed.so -dumpfile metadata.txt
Failed to open file "(null)".
Failed to dump metadata info to file "(null)".

roshan@bolt:~/thesis/osn_server/sgx/enclave_enclave$ file enclave.signed.so 
enclave.signed.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=a288f5eb0763be8cef615660b6eb73d27a756ceb, not stripped
roshan@bolt:~/thesis/osn_server/sgx/enclave_enclave$ size enclave.signed.so 
   text	   data	    bss	    dec	    hex	filename
1058928	  25880	  90624	1175432	 11ef88	enclave.signed.so

```
The enclave.signed.so is default generated by the eclipse when I build the project in eclipse.

**Comment by lzha101** [comment]
If you are using SDK 2.0, yes, there is a bug in signing tool. The bug is fixed in SDK 2.1.2 installer. 
You can also build a signing tool by yourself based on the code including fix https://github.com/intel/linux-sgx/commit/7d0a4086ed8842bcb97197032020745520b0e4f5

**Comment by gmatesunny** [comment]
Thanks, I built from a current repository and it worked. Although I have a question, you might answer.

I just wanted to uniquely identify my enclave, what value ( metadata->enclave_css.body.enclave_hash.m or  mrsigner value) and which sgx api could give me one of these value. 

I do not want to use remote attestation.

**Comment by lzha101** [comment]
I think metadata->enclave_css.body.enclave_hash.m is what you want. mrsigner is the hash for the signing key. And you can get the values from the enclave report (by calling `sgx_create_report` API).
