### ISSUE TITLE
SGX service fails to start, cannot run LocalAttestation sample in hardware mode

### ISSUE THREAD

**Issue by desimone** [intel/linux-sgx#238]
Steps to reproduce.

## setup

- Fresh install of Ubuntu 16.04.3
- Install sgx_linux_x64_driver_1bf506e.bin .
- Install sgx_linux_x64_psw_2.1.102.43402.bin .
- Install sgx_linux_x64_sdk_2.1.102.43402.bin .
- Clone linux-sgx repository, cd to `/linux-sgx/SampleCode/LocalAttestation`.
- Confirm that `make SGX_MODE=SIM` && `./app` works successfully. 

## Cannot run LocalAttestation in hardware mode 

`source $HOME/sgxsdk/environment`

Build is ok.

```
~/linux-sgx/SampleCode/LocalAttestation$ make
GEN  =>  LocalAttestationCode/LocalAttestationCode_t.c
CC   <=  LocalAttestationCode/LocalAttestationCode_t.c
CC   <= LocalAttestationCode/EnclaveMessageExchange.cpp
GEN  =>  libLocalAttestation_Trusted.a
CC   <=  Untrusted_LocalAttestation/UntrustedEnclaveMessageExchange.cpp
GEN  =>  libLocalAttestation_unTrusted.a
GEN  =>  Enclave1/Enclave1_t.c
CC   <=  Enclave1/Enclave1_t.c
CXX  <=  Enclave1/Utility_E1.cpp
CXX  <=  Enclave1/Enclave1.cpp
LINK =>  Enclave1.so
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>0x40000</StackMaxSize>
    <HeapMaxSize>0x100000</HeapMaxSize>
    <TCSNum>1</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    <!-- Recommend changing 'DisableDebug' to 1 to make the enclave undebuggable for enclave release -->
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
</EnclaveConfiguration>
tcs_num 1, tcs_max_num 1, tcs_min_pool 1
The required memory is 2260992B.
Succeed.
SIGN =>  libenclave1.so
GEN  =>  Enclave2/Enclave2_t.c
CC   <=  Enclave2/Enclave2_t.c
CXX  <=  Enclave2/Enclave2.cpp
CXX  <=  Enclave2/Utility_E2.cpp
LINK =>  Enclave2.so
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>0x40000</StackMaxSize>
    <HeapMaxSize>0x100000</HeapMaxSize>
    <TCSNum>1</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    <!-- Recommend changing 'DisableDebug' to 1 to make the enclave undebuggable for enclave release -->
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
</EnclaveConfiguration>
tcs_num 1, tcs_max_num 1, tcs_min_pool 1
The required memory is 2256896B.
Succeed.
SIGN =>  libenclave2.so
GEN  =>  Enclave3/Enclave3_t.c
CC   <=  Enclave3/Enclave3_t.c
CXX  <=  Enclave3/Enclave3.cpp
CXX  <=  Enclave3/Utility_E3.cpp
LINK =>  Enclave3.so
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>0x40000</StackMaxSize>
    <HeapMaxSize>0x100000</HeapMaxSize>
    <TCSNum>1</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    <!-- Recommend changing 'DisableDebug' to 1 to make the enclave undebuggable for enclave release -->
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
</EnclaveConfiguration>
tcs_num 1, tcs_max_num 1, tcs_min_pool 1
The required memory is 2260992B.
Succeed.
SIGN =>  libenclave3.so
GEN  =>  Enclave1/Enclave1_u.c
CC   <=  Enclave1/Enclave1_u.c
GEN  =>  Enclave2/Enclave2_u.c
CC   <=  Enclave2/Enclave2_u.c
GEN  =>  Enclave3/Enclave3_u.c
CC   <=  Enclave3/Enclave3_u.c
CXX  <=  App/App.cpp
LINK =>  app
The project has been built in debug hardware mode.
```

Fails to get SGX service.

```bash
Load Enclave Failure
Available Enclaves
Enclave1 - EnclaveID 0
Enclave2 - EnclaveID 0
Enclave3 - EnclaveID 0Enclave1_test_create_session Ecall failed: Error code is 2002

Hit a key....
```

## AESMD service fails.

```bash
    aesm_service[4566]: SGX Service unavailable
    aesm_service[4566]: Fail to start service.
    systemd[1]: aesmd.service: Main process exited, code=exited, status=1/FAILURE
    systemd[1]: aesmd.service: Unit entered failed state.
    systemd[1]: aesmd.service: Failed with result 'exit-code'.
    systemd[1]: aesmd.service: Service hold-off time over, scheduling restart.
    systemd[1]: Stopped Intel(R) Architectural Enclave Service Manager.
    systemd[1]: Starting Intel(R) Architectural Enclave Service Manager...
    systemd[1]: Started Intel(R) Architectural Enclave Service Manager.
    aesm_service[4614]: SGX Service unavailable
    aesm_service[4614]: Fail to start service.
    systemd[1]: aesmd.service: Main process exited, code=exited, status=1/FAILURE
    systemd[1]: aesmd.service: Unit entered failed state.
    systemd[1]: aesmd.service: Failed with result 'exit-code'.
```

## Other potentially helpful details in debugging issue.

output of `lsmod |grep isgx`

```bash
isgx                   77824  0
```

```bash
$ ls /dev/mei0
/dev/mei0
$ ls /dev/isgx
ls: cannot access '/dev/isgx': No such file or directory
```

output of `lscpu` suggest my hardware is [fine](https://ark.intel.com/products/88191/Intel-Core-i5-6600K-Processor-6M-Cache-up-to-3_90-GHz)
```
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 94
...
Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
```

I have confirmed my SGX is supported by my BIOS (and updated) and turned on ("set to software controlled").
![20qf5ne](https://user-images.githubusercontent.com/1544881/38049469-3726595a-327d-11e8-944c-2e9d5870ee3f.png)

**Comment by avchinch** [comment]
Hi desimone,

Set the BIOS SGX option to "Enabled" instead of "Software Controlled" and give it a try again.

**Comment by desimone** [comment]
@avchinch Unfortunately, that's not an option. There is only "Software Controlled" or "Disabled".

[See more](https://dlsvr04.asus.com/pub/ASUS/mb/LGA1151/STRIX_B250F_GAMING/E12497_STRIX_B250F-GAMING_BIOS_UM_web_only_20170706.pdf)

**Comment by andyzyb** [comment]
sgx_enable_device API in libsgx_capable.so is used to enable SGX in software control mode.

**Comment by avchinch** [comment]
Yes, if explicitly setting it to enabled is not an option, you will have to do a bit more work to enable it yourself in software.
Here's a good reference on the subject, which describes use of the library mentioned above:
https://software.intel.com/en-us/articles/properly-detecting-intel-software-guard-extensions-in-your-applications

**Comment by andyzyb** [comment]
May be able to do it on command line.

# cat /sys/firmware/efi/efivars/EPCBIOS-c60aa7f6-e8d6-4956-8ba1-fe26298f5e87

Use the value read from above EFI variable to write a new EFI variable
# echo xxx > /sys/firmware/efi/efivars/EPCSW-d69a279b-58eb-45d1-a148-771bb9eb5251

**Comment by desimone** [comment]
Thank you @andyzyb @avchinch 

The linked document is challenging to follow and I don't even know where'd I start in actual implementation. Incidentally, in multiple places the docs say conflicting things like 

> The Linux version of the PSW does not implement this capability, and as a result this function is not included in the Linux version of the Intel SGX SDK.

Would it be possible to update the `LocalAttestation` (or any other extremely basic example) sample to include how exactly this is done ?

**Comment by desimone** [comment]
@andyzyb No luck.

Is there a reason you are using cat, then echo instead of just doing `cp`?

```bash

$ sudo comm -23 /sys/firmware/efi/efivars/EPCSW-d69a279b-58eb-45d1-a148-771bb9eb5251 /sys/firmware/efi/efivars/EPCSW-d69a279b-58eb-45d1-a148-771bb9eb5251

$ ls -al /sys/firmware/efi/efivars/EPCSW-d69a279b-58eb-45d1-a148-771bb9eb5251
-rw-r--r-- 1 root root 144 Mar 28 22:53 /sys/firmware/efi/efivars/EPCSW-d69a279b-58eb-45d1-a148-771bb9eb5251

$ ls -al /sys/firmware/efi/efivars/EPCSW-d69a279b-58eb-45d1-a148-771bb9eb5251
-rw-r--r-- 1 root root 144 Mar 28 22:53 /sys/firmware/efi/efivars/EPCSW-d69a279b-58eb-45d1-a148-771bb9eb5251

ls /dev/isgx
ls: cannot access '/dev/isgx': No such file or directory
```

**Comment by andyzyb** [comment]
OK, I just looked at the implementation of sgx_cap_enable_device API in libsgx_capable.so, and thought using simple command might work.  But it seems not that easy.

So you'b better to follow the approach of using sgx_cap_enable_device API.   sgx_capable.h and libsgx_capable.so are now part of SGX SDK and you should be able to find them after SDK installation.

A quick link to sgx_capable.h is https://github.com/intel/linux-sgx/blob/master/common/inc/sgx_capable.h

**Comment by desimone** [comment]
Okay. I'm sure this is a naive question but for my particular use case I need to be able to use the `/dev/isgx` interface. I assume that's not possible if I have to invoke it programmatically? 

Would it be possible to one-time bootstrap (especially since it requires `root`) my environment so I can use my machine as if bios was set to `enabled`? 

Hopefully that makes sense.

**Comment by andyzyb** [comment]
Right, you cannot use /dev/isgx interface without invoking it programmatically.

Not sure I understand second part of the question.  Once you use API to enable SGX in "software controlled" mode,  there is no need to do it again and it will remain as enable state.

**Comment by desimone** [comment]
```c++

#include "App.h"
#include "sgx_uae_service.h"
#include "sgx_capable.h"

/* Application entry */
int SGX_CDECL main(int argc, char *argv[])
{
	(void)(argc);
	(void)(argv);

	sgx_device_status_t sgx_device_status;
	sgx_status_t sgx_ret = sgx_cap_enable_device(&sgx_device_status);
	if (sgx_ret != SGX_SUCCESS) {
		printf("Failed to get SGX device status.\n");
		return -1;
	}
	else {
		switch (sgx_device_status) {
			case SGX_ENABLED:
			printf("SGX device is enabled\n");
			return 0;
			case SGX_DISABLED_REBOOT_REQUIRED:
			printf("SGX device has been enabled. Please reboot your machine.\n");
			return -1;
			case SGX_DISABLED_LEGACY_OS:
			printf("SGX device can't be enabled on an OS that doesn't support EFI interface.\n");
			return -1;
			case SGX_DISABLED:
			printf("SGX device not found.\n");
			return -1;
			default:
			printf("Unexpected error.\n");
			return -1;
		}
	}
	return -1;
}
```

```bash
$ sudo ./app
SGX device has been enabled. Please reboot your machine.
```
(reboot)

Still no luck.

```bash
$ lsmod |grep isgx
isgx                   77824  0
$ ls /dev/mei0
/dev/mei0
$ ls /dev/isgx
ls: cannot access '/dev/isgx': No such file or directory
```

```bash
systemd[1]: aesmd.service: Failed with result 'exit-code'.
systemd[1]: aesmd.service: Service hold-off time over, scheduling restart.
systemd[1]: Stopped Intel(R) Architectural Enclave Service Manager.
systemd[1]: Starting Intel(R) Architectural Enclave Service Manager...
systemd[1]: Started Intel(R) Architectural Enclave Service Manager.
aesm_service[2253]: SGX Service unavailable
aesm_service[2253]: Fail to start service.
systemd[1]: aesmd.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: aesmd.service: Unit entered failed state.
systemd[1]: aesmd.service: Failed with result 'exit-code'.
systemd[1]: aesmd.service: Service hold-off time over, scheduling restart.
```

**Comment by andyzyb** [comment]
1. Did you remove the previously copied file:  /sys/firmware/efi/efivars/EPCSW-d69a279b-58eb-45d1-a148-771bb9eb5251 before calling this app?  

2. Did you install the Intel SGX driver?

**Comment by desimone** [comment]
Yep, that was it!  

```bash
$ sudo ./app
SGX device is enabled
```

For future readers, root cannot delete this file you must  first change it's immutable property with `sudo chattr -i /sys/firmware/efi/efivars/EPCSW-d69a279b-58eb-45d1-a148-771bb9eb5251`.


Thank you again for all your help @andyzyb 👍

**Comment by andyzyb** [comment]
Good to know the issue is resolved.

**Comment by Anthony-Mai** [comment]
I run into the same issue but I do not see anything that looks like /sys/firmware/efi/efivars/EPCSW
However I see something related SGX:

/sys/firmware/efi/efivars$ cat SOFTWAREGUARDSTATUS-9cb2e73f-7325-40f4-a484-659bb344c3cd | xxd
00000000: 0600 0000 01

/sys/firmware/efi/efivars$ ls /dev/isgx
ls: cannot access '/dev/isgx': No such file or directory

My processor is Intel Pentium Gold G5400. I looked up the spec, on SGX it says "yes with Intel ME" Why is it not a straight forward "yes"? What is the Intel ME thing that I have to have to get the SGX feature? I do set the BOIS config on SGX as "enabled", not "software controlled"

How can I get SGX working on my machine?

**Comment by rodolfoams** [comment]
@Anthony-Mai Did you install the SGX driver? You should install it prior to executing any SGX application in hardware mode.
https://github.com/intel/linux-sgx-driver

**Comment by Anthony-Mai** [comment]
@rodolfoams Thanks for the help. Yes I did follow the steps of https://github.com/intel/linux-sgx-driver to compile and installed the sgx device driver. I tried everything. Still could not get it work so I gave up.
And then today I want to come back to test again. Magically without doing anything, ls /dev/isgx shows up the device driver. And then I run SampleCode/LocalAttestation/app. Everything works at hardware mode this time. I am thrilled to see it working.

What have I done to make it work? Nothing. What made the difference? I have powered off the machine after frustration and I have turned it back on today. So probably a cold reboot fixed the problem. Or maybe it carried out some needed software update. Anyway I am happy that I get it working now.

**Comment by ZongminGu** [comment]
@Anthony-Mai Do you remember the installation sequence of sgx PSW and sgx driver?

**Comment by h4x3rotab** [comment]
I'm on SGX driver 2.5 and had similar problem. It turned out there are two drivers but only the second one worked for me:

- sgx_linux_x64_driver_2.5.0_2605efa.bin
- sgx_linux_x64_driver_f7dc97c.bin

**Comment by taserghar** [comment]
Hi, Does anyone know the actual reason why this issue occurs?
SGX was running fine. But suddenly PC got restarted and since then SGX is not running in actual hardware mode.

**Comment by Anthony-Mai** [comment]
I came back to exactly the same problem and had to struggle through the same thing to resolve it. To recap:
1. Must follow https://github.com/intel/linux-sgx-driver to compile and install the sgx device driver. Verify that install is successful by this command: ls /dev/isgx
2. Must **reboot** for the driver to become effective.
3. Must source environment depending on where you installed the SDK, before make:
     source ~/sgxsdk/environment
4. Make the sample in HW_RELEASE mode:
    /sgxsdk/SampleCode/LocalAttestation$ make HW_RELEASE=1
5. Run the sample: ./app  And returns a whole bunch of success!

**Comment by Teeina** [comment]
Hi, I met the same problem except that i already had the driver installed and SGX set to 'Enabled' in BIOS. I restart the machine as Anthony mentioned, but no luck for me. Any suggestions?

**Comment by tgamal** [comment]
> ```c++
> #include "App.h"
> #include "sgx_uae_service.h"
> #include "sgx_capable.h"
> 
> /* Application entry */
> int SGX_CDECL main(int argc, char *argv[])
> {
> 	(void)(argc);
> 	(void)(argv);
> 
> 	sgx_device_status_t sgx_device_status;
> 	sgx_status_t sgx_ret = sgx_cap_enable_device(&sgx_device_status);
> 	if (sgx_ret != SGX_SUCCESS) {
> 		printf("Failed to get SGX device status.\n");
> 		return -1;
> 	}
> 	else {
> 		switch (sgx_device_status) {
> 			case SGX_ENABLED:
> 			printf("SGX device is enabled\n");
> 			return 0;
> 			case SGX_DISABLED_REBOOT_REQUIRED:
> 			printf("SGX device has been enabled. Please reboot your machine.\n");
> 			return -1;
> 			case SGX_DISABLED_LEGACY_OS:
> 			printf("SGX device can't be enabled on an OS that doesn't support EFI interface.\n");
> 			return -1;
> 			case SGX_DISABLED:
> 			printf("SGX device not found.\n");
> 			return -1;
> 			default:
> 			printf("Unexpected error.\n");
> 			return -1;
> 		}
> 	}
> 	return -1;
> }
> ```
> 
> ```shell
> $ sudo ./app
> SGX device has been enabled. Please reboot your machine.
> ```
> 
> (reboot)
> 
> Still no luck.
> 
> ```shell
> $ lsmod |grep isgx
> isgx                   77824  0
> $ ls /dev/mei0
> /dev/mei0
> $ ls /dev/isgx
> ls: cannot access '/dev/isgx': No such file or directory
> ```
> 
> ```shell
> systemd[1]: aesmd.service: Failed with result 'exit-code'.
> systemd[1]: aesmd.service: Service hold-off time over, scheduling restart.
> systemd[1]: Stopped Intel(R) Architectural Enclave Service Manager.
> systemd[1]: Starting Intel(R) Architectural Enclave Service Manager...
> systemd[1]: Started Intel(R) Architectural Enclave Service Manager.
> aesm_service[2253]: SGX Service unavailable
> aesm_service[2253]: Fail to start service.
> systemd[1]: aesmd.service: Main process exited, code=exited, status=1/FAILURE
> systemd[1]: aesmd.service: Unit entered failed state.
> systemd[1]: aesmd.service: Failed with result 'exit-code'.
> systemd[1]: aesmd.service: Service hold-off time over, scheduling restart.
> ```
> 
> Any thoughts as to why reboot is not working?

@desimone , I have the same issue with enabling sgx from software .. Could you please let me know where to place the above piece of code ?
