### ISSUE TITLE
make: *** No rule to make target.needed by ...

### ISSUE THREAD

**Issue by lcs100** [intel/linux-sgx#239]
hello.
when I try to run samplecode.the instruction is
`make SGX_MODE=SIM`
the result is 
`No rule to make target '/home/lcs/linux-sgx-master/linux/installer/bin/sgxsdk/bin/x64/sgx_edger8r', needed by 'LocalAttestationCode/LocalAttestationCode_t.c'。`
I cannot find the error

**Comment by andyzyb** [comment]
Have you installed the SGX SDK before building the sample project?

**Comment by lcs100** [comment]
I have worked out this question
because my system language is Chineses.
It should be English
Thank you

**Comment by kaimast** [comment]
Can we close this?

**Comment by codersz** [comment]
hello. My mistakes is "make: *** No rule to make target '/opt/intel/sgxsdk/bin/x64/sgx_edger8r', needed by 'App/Enclave_u.c'.  Stop.",i have installed the SGX SDK, do you have solutions for this question?Thank you

**Comment by yuyuany** [comment]
After you install the SDK, you need to run 'source <sdk-install-path>/environment' to setup environment variables.

**Comment by ZongminGu** [comment]
You need to add the sdk into the path. When you install the SDK, there is a green line to tell you how to do it.

**Comment by codersz** [comment]
yeah,I lost this operation.Thank you very much
