### ISSUE TITLE
How to specify base-address

### ISSUE THREAD

**Issue by penhoi** [intel/linux-sgx#241]
Can I specify the base-address where staring an enclave, and also where loading the enclave-SO?

I have tried the following methods but failed. 
1. I checked the file Enclave.config.xml, found that there is no option for setting the base-address.
2. When I used -Ttext option for compiling the enclave-SO, the app cannot execute correctly. It issues an error message "initialize enclave failed".

Could you help me to fix this problem? Thanks.

**Comment by heartever** [comment]
As far as I know, the base address can be specified by modifying the 1st parameter of [#133 of linux-sgx/psw/urts/linux/enclave_creator_hw.cpp](https://github.com/intel/linux-sgx/blob/0f45cad401e974bee57704f3fb0ff185146bbde2/psw/urts/linux/enclave_creator_hw.cpp#L133)
