### ISSUE TITLE
Problems creating a shared library from enclave project

### ISSUE THREAD

**Issue by jamch21** [intel/linux-sgx#242]
Hi Dear all,

I converted the untrusted part of my enclave project into a shared library so another application will use the functions defined in my untrusted.h
however when I compiled my other function gcc application.o -L. lenclaveproject -o finalprogram i get undefined reference to the functions defined inside the shared library.

the changes I made to the makefile for the untrusted part:

`_libsample.so : $(UNTRUSTED_DIR)/myenclave_u.o $(App_C_Objects)
	@$(CXX) -shared $(UNTRUSTED_DIR)/myenclave_u.o $(UNTRUSTED_DIR)/sample.o $(UNTRUSTED_DIR)/sgx_utils.o -L/opt/intel/sgxsdk/lib64/ -lsgx_urts_sim -lsgx_uae_service_sim  -o $@
	@echo "LINK => $@"_`

**Comment by yuyuany** [comment]
My understanding is you compiled the untrusted part of enclave to a shared library 'libsample.so'. So when you compile the final program, you need to:
            gcc application.o -L. **-lsample** -o finalprogram
