### ISSUE TITLE
Rationale for pseudo-random numbers in simulation mode

### ISSUE THREAD

**Issue by kaimast** [intel/linux-sgx#246]
Hi,

Is there a specific reason why sgx_read_rand returns a pseudo-random number in simulation mode? 
(as document here https://software.intel.com/en-us/node/709094)

In particular it results my application to always generate the same public/private key pair in simulation mode which causes various problems.

Is there any way to force randomness in simulation mode?

Thanks,
Kai

**Comment by ZongminGu** [comment]
I tested it in a simple case:

65 void test()
 66 {
 67     int a = 0;
 68
 69     for (int i=0; i<4; ++i)
 70     {
 71
 72     sgx_status_t status = sgx_read_rand((unsigned char *)&a, sizeof(a));
 73
 74     printf("random:%d\n", a);
 75
 76 }
 77 }

I run it twice. The result is:
./app
random:-1514151190
random:793048459
random:-522582890
random:168439143
Enter a character before exit ...

./app
random:308955192
random:1344177320
random:-218509240
random:1266178082
Enter a character before exit ...

The value changed every time.

**Comment by kaimast** [comment]
We don't use simulation in production but for our automated tests. Hopefully in the future we can test in prerelease mode but it's just not possible with the current virtualization infrastructure. 

So it seems that the seed for randomness is derived from the local time. Is that true? I added a delay in my test suite between starting enclaves and it seems to fix the problem.

**Comment by sergefdrv** [comment]
@kaimast I encountered the same effect. It looks like the random number generation is pre-seeded with current time in seconds. So in all tests, I have to add one second delay between invocations to make sure that it is unlikely to get the same random value... That makes unit-testing awfully slow :slightly_frowning_face:

**Comment by sergefdrv** [comment]
I believe this line is the guilty: https://github.com/intel/linux-sgx/blob/54cae063cd0d21be5fab28c0d4b81b073b5d0914/sdk/simulation/urtssim/enclave_creator_sim.cpp#L232

It would be better to use nanoseconds for the seed value.

**Comment by lzha101** [comment]
In the latest release, we have changed the random generator on simulation mode to use RDRAND if the platform supports RDRAND instruction to reduce the usage of LCG.  
https://github.com/intel/linux-sgx/blob/master/sdk/trts/trts.cpp#L258

And we suggest to use HW mode instead of simulation mode. Simulation mode doesn't support all the SGX features.

**Comment by sergefdrv** [comment]
> In the latest release, we have changed the random generator on simulation mode to use RDRAND if the platform supports RDRAND instruction 

Thanks for pointing that out.

> And we suggest to use HW mode instead of simulation mode. Simulation mode doesn't support all the SGX features.

I agree, but cloud-based CI services wouldn't allow to use SGX in HW mode.
