### ISSUE TITLE
In Ubuntu 16.04, using sgx_cap_enable_device() cannot enable SGX in software controlled mode

### ISSUE THREAD

**Issue by Visualsf** [intel/linux-sgx#255]
In Ubuntu 16.04, when I use sgx_cap_enable_device() to enabel SGX in software controlled mode. This function always return sgx_status == 2(need reboot the system to enable SGX).
But this problem is still exist after I reboot.
I hope someone could help me. Thanks!

**Comment by andyzyb** [comment]
Is SGX actually enabled after you called sgx_cap_enable_device?

**Comment by Visualsf** [comment]
Thanks for your attention. 
Actually SGX is still disabled after I called sgx_cap_enable_device. The return value asks me to reboot.
After I reboot, I build and run the project. The SGX is still disabled. (BIOS is in software controlled mode)

**Comment by andyzyb** [comment]
Can you install the SGX driver, and check its log with dmesg?

**Comment by Visualsf** [comment]
I can install SGX driver successfully and the dmesg log is like
"yaoss@yaoss-System-Product-Name:~$ dmesg | grep sgx
[    2.108165] isgx: loading out-of-tree module taints kernel.
[    2.108199] isgx: module verification failed: signature and/or required key missing - tainting kernel
[    2.108441] intel_sgx: SGX is not enabled
[  281.519450] intel_sgx: SGX is not enabled"
The full procedure I did is as follow:
1.When I run the project , I get the message "
sgx state: 2
token_path: /home/yaoss/enclave.token
Info: Please make sure Intel(R) SGX module is enabled in the BIOS, and install Intel(R) SGX driver afterwards.
Error: Invalid Intel(R) SGX device." 
2. Then I reboot the system and reinstall the driver. The log is as bellow:
"yaoss@yaoss-System-Product-Name:~/下载$ sudo ./sgx_linux_x64_driver_1bf506e.bin Unpacking Intel SGX Driver ... done.
Verifying the integrity of the install package ... done.
Installing Intel SGX Driver ...
/tmp/sgx-driver-qvYz9O ~/下载
install -d /opt/intel/sgxdriver/package
install -d /opt/intel/sgxdriver/scripts
install package/* /opt/intel/sgxdriver/package
install scripts/* /opt/intel/sgxdriver/scripts
~/下载
/opt/intel/sgxdriver/package ~/下载
make -C /lib/modules/4.13.0-38-generic/build SUBDIRS=/opt/intel/sgxdriver/package CFLAGS_MODULE="-DDEBUG -g -O0" modules
make[1]: Entering directory '/usr/src/linux-headers-4.13.0-38-generic'
  CC [M]  /opt/intel/sgxdriver/package/sgx_main.o
  CC [M]  /opt/intel/sgxdriver/package/sgx_page_cache.o
  CC [M]  /opt/intel/sgxdriver/package/sgx_ioctl.o
  CC [M]  /opt/intel/sgxdriver/package/sgx_vma.o
  CC [M]  /opt/intel/sgxdriver/package/sgx_util.o
  CC [M]  /opt/intel/sgxdriver/package/sgx_encl.o
  CC [M]  /opt/intel/sgxdriver/package/sgx_encl2.o
  LD [M]  /opt/intel/sgxdriver/package/isgx.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /opt/intel/sgxdriver/package/isgx.mod.o
  LD [M]  /opt/intel/sgxdriver/package/isgx.ko
make[1]: Leaving directory '/usr/src/linux-headers-4.13.0-38-generic'

uninstall.sh script generated in /opt/intel/sgxdriver

Installation is successful!"
3. Then I build and run the project again. I get same error in console "sgx state: 2
token_path: /home/yaoss/enclave.token
Info: Please make sure Intel(R) SGX module is enabled in the BIOS, and install Intel(R) SGX driver afterwards.
Error: Invalid Intel(R) SGX device."

**Comment by andyzyb** [comment]
It looks the driver loading failed.   Are you running an OS with secure boot enabled?  If so, then you have to sign the SGX driver to make sure it can be loaded.  Refer to the OS help for how to sign the driver.

>>>[ 2.108165] isgx: loading out-of-tree module taints kernel.
>>>[ 2.108199] isgx: module verification failed: signature and/or required key missing - tainting kernel

**Comment by jmechalas** [comment]
I assume you are running sgx_cap_enable_device() as root? If not, it won't work (though you should get an error from it in that case...)

After you run sgx_cap_enable_device(), but before you reboot, there should be a file at /sys/firmware/efi/EPCSW-d69a279b-58eb-45d1-a148-771bb9eb5251. If that file is there, and SGX isn't enabling on the reboot, then the BIOS may not be properly doing the software enable.

**Comment by Visualsf** [comment]
Thanks for your advice.  But in my /sys/firmware only has these dir as below.
yaoss@yaoss-System-Product-Name:~$ cd /sys/firmware/
yaoss@yaoss-System-Product-Name:/sys/firmware$ ls
acpi  dmi  memmap

**Comment by jmechalas** [comment]
@Visualsf The software enable requires access to the EFI variables. Since your system does not have the efi filesystem, that suggests you did your Linux install in legacy boot mode instead of UEFI. The boot mode is typically set in the BIOS. Only a UEFI booted system has access to EFI variables, so you'd need to do a reinstall using UEFI boot.

**Comment by Visualsf** [comment]
@jmechalas @andyzyb thanks for your help.
