### ISSUE TITLE
sgx_fopen was not declared in this scope

### ISSUE THREAD

**Issue by lcs100** [intel/linux-sgx#258]
I use sgx_fopen to read file:
sgx_fopen("1.txt","r");
however it says 
 error: ‘sgx_fopen’ was not declared in this scope
could anyone help me?

**Comment by naishai** [comment]
Did you include the header file? you also need to 'import' the EDL file and to link with the appropriate libraries (trusted and untrusted), please refer to the manual for all the details.

**Comment by lcs100** [comment]
OK I have solved this problem
I want to let the app set a file and the encalve read this file
Could you tell me what should I do?
Thanks

**Comment by naishai** [comment]
You cannot, SGX file APIs are intended for use by the enclave to store/load it's data. The files are encrypted and uses a unique format. They cannot be used to read regular files, only those which were created by the enclave with these APIs.
