### ISSUE TITLE
sgx_sha256_msg hash to base64

### ISSUE THREAD

**Issue by gmatesunny** [intel/linux-sgx#262]
I wanted to also know how I could convert sgx_sha256_msg hash to base64 encoding inside enclave? Anyone aware any base64 library that works inside enclave?

**Comment by zhaohuidu** [comment]
We should not use if(p_hash_1 == p_hash_2) to determine whether the two hash values are same.
memcmp(&p_hash_1, &p_hash_2, sizeof(sgx_sha256_hash_t))==0 could be used to replace the condition.

**Comment by gmatesunny** [comment]
Thanks and I am looking for an anybase64 library that works inside the enclave. I need to convert the result of sgx_sha256_msg and send it over the network.

**Comment by gmatesunny** [comment]
Found it: https://github.com/cloud-security-research/sgx-kms/blob/master/BarbiE/service_provider/Base64.cpp
