### ISSUE TITLE
How to generate random number inside enclave

### ISSUE THREAD

**Issue by gmatesunny** [intel/linux-sgx#263]
I want to generate random readable number inside enclave so I used:

```
	sgx_status_t ret;
	unsigned char alpha[16];
	ret = sgx_read_rand(alpha, 16);
	  if(ret != SGX_SUCCESS)
	  {
		  mbedtls_printf("sgx_read_rand failed %#x", ret);
		  abort();
	  }
	  std::string alphastr( alpha, alpha + sizeof alpha / sizeof alpha[0] );
 	  mbedtls_printf("%s", alphastr.c_str());
```
But this gives me binary string, I wanted to have readable character, How do I get that ?

**Comment by gmatesunny** [comment]
Update 1: I changed it like this:

```
	sgx_status_t ret;
	unsigned char alpha[8];

	ret = sgx_read_rand(alpha, 8);

	  if(ret != SGX_SUCCESS)
	  {
		  mbedtls_printf("sgx_read_rand failed %#x", ret);
		  abort();
	  }

	uint64_t n = abs(std::atoi( (char *) alpha ));
	mbedtls_printf("Salt number: %d", &n);
```
but I wonder the output it prints is some negative number which make me certain that I am doing something wrong. 
Salt number: -1554167224

**Comment by gmatesunny** [comment]
Solution if anyone else is wondering although I still do not know why the above method failed.

char n[12];
sgx_read_rand(reinterpret_cast<unsigned char*>(&n),
	                sizeof(n));
mbedtls_printf("Sealing Salt number: %llu", *(char *)n);

**Comment by andyzyb** [comment]
An integer could be negative or positive.  "%d" means printing it as signed integer (so it could be negative).  "%llu" means printing it as unsigned integer (so it is always positive).
