### ISSUE TITLE
Returning of Remote Attestation Results

### ISSUE THREAD

**Issue by Xepheryy** [intel/linux-sgx#264]
Is it possible to return the remote attestation results of a server that is registered with Intel from IAS to a client that is not registered under IAS?

**Comment by andyzyb** [comment]
The communication between server and client is fully controlled (implemented) by developers.  There is no restriction to return the remote attestation result from server to client.   Client doesn't need to register to IAS.

**Comment by andyzyb** [comment]
Are you running Enclave on client or server?  If it is on client, then the flow would be like:

client Enclave report -> server -> IAS, then generated result is IAS -> server -> client.

**Comment by Xepheryy** [comment]
@andyzyb The enclave would be running on the server. I was wondering if a client can receive the attestation result instead of the server. Hence the initial flow. 

_the supposed client will not have Intel SGX hardware capabilities_

**Comment by andyzyb** [comment]
The attestation result is returned from IAS to the party who communicates to it.   If you want to return it to other client, then you need to implement those logic in your software.

**Comment by Xepheryy** [comment]
@andyzyb Thank you!
