### ISSUE TITLE
How to read a char pointer of unprotected region from enclave

### ISSUE THREAD

**Issue by gmatesunny** [intel/linux-sgx#267]
At App, I have a function like this:
void suu(char *a)
{
string data = "sunny"; //could be anything
a = new char[data.size()+1];
strcpy(a, (char * )data.c_str());
}

I wanted to read the content of data in enclave using OCALL so in EDL I defined.
void suu([out] char *r_abc);

And at the enclave I do this:
char *r_abc;
suu(r_abc);

But I am failed to read the content which is available in unprotected region.

Any idea, How I could read content of data at enclave using ocall ?

**Comment by andyzyb** [comment]
Basically you just need to read the data through the data address.   You should try to pass that address to the ocall function, or declare it as some global variable so ocall function can easily access it.
