### ISSUE TITLE
Sending of attestation report to IAS

### ISSUE THREAD

**Issue by nickyex2** [intel/linux-sgx#268]
When sending the attestation report to IAS, can I still use the ra_network_send_receive() function that is shown in the sample code to communicate with IAS to retrieve the attestation results?

**Comment by jmechalas** [comment]
That function in the sample code is a bare-bones, no-frills TCP send and receive between the client and server with no actual protocol around it. It is literally just writing and reading raw bytes.

To communicate with IAS, you need to be an HTTP/1.1 capable client. See the IAS API document "Interfacing with Developer Services" at software.intel.com/sgx
