### ISSUE TITLE
The vector get function is not protect

### ISSUE THREAD

**Issue by calbeb** [intel/linux-sgx#276]
https://github.com/intel/linux-sgx/blob/0b493e04efe6e24d67ca6dcceb0d1af6f4010868/sdk/tkey_exchange/tkey_exchange.cpp#L100
The vector get function is not protect, while another thread push back value, realloc was trigger. There is a invalid ptr will be use.

**Comment by llly** [comment]
You are right. We will update implementation to address this issue.
