### ISSUE TITLE
Multiple definition of function "sgx_oc_cpuidex" detected

### ISSUE THREAD

**Issue by gmatesunny** [intel/linux-sgx#277]
I needed to include both of the following in edl file

  from "sgx_tstdc.edl" import *;
  from "sgx_tkey_exchange.edl" import *;

But doing so, give me error 
make[1]: Entering directory '/home/roshan/thesis/osn_server/sgx/enclave_enclave'
error: Multiple definition of function "sgx_oc_cpuidex" detected.

How should I resolve it

**Comment by akryeem-INTC** [comment]
In `sgx_tkey_exchange.edl` you have: `from "sgx_tae_service.edl" import *;`
In `sgx_tae_service.edl` you have: `from "sgx_tstdc.edl" import *;`
This mean you already have imported definitions from `sgx_tstdc.edl`. You don't need to include it manually it's already included.
