### ISSUE TITLE
Error: undefined reference to 

### ISSUE THREAD

**Issue by gmatesunny** [intel/linux-sgx#278]
In edl file I wrote this:
enclave {
	  from "sgx_tkey_exchange.edl" import *;	
	  include "sgx_key_exchange.h"
	  include "sgx_trts.h"
    trusted {
   	    
   public sgx_status_t ecall_init_ra(int b_pse, [out] sgx_ra_context_t *p_context);
   public sgx_status_t ecall_close_ra(sgx_ra_context_t context);

}

inside enclave I try this:

#include "my_t.h"
#include "sgx_tkey_exchange.h"
#include "sgx_tcrypto.h"
#include "string.h"

sgx_status_t SGXAPI ecall_close_ra(sgx_ra_context_t context){
   sgx_status_t ret;
  ret = sgx_ra_close(context);
  return ret;
}

But its keep failing to compile with the error undefined reference to `sgx_ra_init'

What is the reason for this undefined reference. How could i resolve it

**Comment by gmatesunny** [comment]
I am using the SIM mode and on ubuntu16.04

**Comment by gmatesunny** [comment]
For anyone new, link this library
-lsgx_tkey_exchange

**Comment by sandeep007734** [comment]
> For anyone new, link this library
> -lsgx_tkey_exchange

This worked. Thanks
