### ISSUE TITLE
How to use threading inside enclave

### ISSUE THREAD

**Issue by gmatesunny** [intel/linux-sgx#280]
Can someone gives a small example of the use of threading inside enclave. 
I have method say my_longfunc() and my_shortfunc() and both are inside enclave. 
I wanted to call my_longfunc() from my_shortfunc()  but do not want to wait for my_longfunc() to finish. my_shortfunc() should return imediately after calling my_longfunc(). 

Any hint, any sample code, anything in this regard is highly appreciated.

**Comment by sergeay** [comment]
You need a worker thread running within the enclave and waiting for a task to be queued.
untrusted code will create a new thread and call this worker thread routine.
the task managing routines need to be implemented by you.

Some pseudo code:

/* Enclave code */
task_struct queue;

void my_short_func()
{
      ......
      /* at this point you invoke my_long_func using your task/queue infrastructure */
       insert_task(&queue, my_long_func, params);
      .......
}

void ecall_worker()
{
      while (true)
      {
            task = get_task(&queue);
            if (!task)
            {
                   wait() / sleep / excute nop;
                   continue;
            }
            execute_task(task);
      }
}

/* untrusted code */
/* create worker thread that gets into enclave and wait for tasks */
pthread_create(ecall_worker_thread);
....
/* enter enclave and at some point call my_short_func() */
ecall_my_short_func();

Hope this helps,
Serge

**Comment by gmatesunny** [comment]
He Serge, 

Are you aware of any sample code where I could see the sgx threading in working? 
Next, beside my_shortfunc and my_longfunc, do I need to write void ecall_worker() method inside enclave ? can you show the calling calling sequence for the entire operation something like 
my_shortfunc(enclave) ----> app(create thread ---->  ecall_worker(enclave)

**Comment by sergeay** [comment]
I am not aware of any relevant sample code that works with sgx sdk.
Also this is not something specific to SGX SDK. I would expect the internet to have many many samples of that type (they need to be adapted to SGX).
Yes you need to implement an ecall_worker inside the enclave and define it in the edl file.
