### ISSUE TITLE
connecting to ias using curl protocol

### ISSUE THREAD

**Issue by nickyex2** [intel/linux-sgx#284]
(instance retrieved
Successfully initialised Curl
retriving ias sigrl now
*   Trying 52.0.160.62...
* Connected to test-as.sgx.trustedservices.intel.com (52.0.160.62) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* Unknown SSL protocol error in connection to test-as.sgx.trustedservices.intel.com:443 
* Closing connection 0
curl_easy_perform() failed: SSL connect error)

this is the error i got when i was trying to communicate with the ias using the curl protocol. Does anyone know how to solve this?

**Comment by nickyex2** [comment]
an update i solve the problem earlier, however now i am faced with a bigger problem

curl --tlsv1.2 --cert cert3072.pem --key key3072.pem https://as.sgx.trustedservices.intel.com:443/sigrl/00000010 -v

*   Trying 54.152.207.9...
* TCP_NODELAY set
* Connected to as.sgx.trustedservices.intel.com (54.152.207.9) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS handshake, CERT verify (15):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to as.sgx.trustedservices.intel.com:443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to as.sgx.trustedservices.intel.com:443

this is the current error i am facing, i am not sure if anyone has gotten this but is there anyone that might know how to solve this?

**Comment by naishai** [comment]
hi,
have you registered your client certificate with IAS?
see the second paragraph here:
https://software.intel.com/en-us/articles/intel-software-guard-extensions-remote-attestation-end-to-end-example
also note that you need to connect to the server you registered to, your first post refers to as-test server while the second to the production server.
ishai

**Comment by nickyex2** [comment]
hi naishai,
i have registered my client certificate with IAS and am using the correct url, however they are still giving me this error.

**Comment by amztc34283** [comment]
When I was using curl to connect with Intel, I usually concatenate the key and the certificate into one pem file and using -E to connect with Intel.
