### ISSUE TITLE
Checksum failure for prebuilt libraries

### ISSUE THREAD

**Issue by dburihabwa** [intel/linux-sgx#287]
Downloading the prebuilt packages using `download_prebuilt.sh` from commit 984c04c696bddaff7fb1621b79760fabcb8c94d7 fails because the expected hash in the script does not match the one comupted by `sha256sum` for file `optimized_libs-2.1.3_with_license.tar`

Expected from the script : 5a40b2b34f9a41f42bc4dd95761168e22eb63948ffce856f540d28a60b32ef93
Hash of the downloaded file: 43f57a1e54b37652d1c336712547ccf4be5d7232bee41140310db7c85e8a5097

**Comment by ericqzou** [comment]
I have this very same issue

**Comment by yuyuany** [comment]
You've got the right checksum. PR #286 was submitted but not merged yet. That's why the checksum failed.  We'll get it done soon. Sorry for the inconvenience.

**Comment by lzha101** [comment]
The PR #286 is merged now.  Sorry for the inconvenience.

**Comment by lzha101** [comment]
Close this as the issue has been resolved.
