### ISSUE TITLE
Launching guess VM with  sgx enable

### ISSUE THREAD

**Issue by jamch21** [intel/linux-sgx#288]
Hi Everybody,

I am trying to launch a VM with SGX enabled to run an application. However, it seems that the app in the VM is not running in SGX hardware mode. I installed the patch (KVM-sgx) and then I run my guess virtual machine from qemu(clone from qemu-sgx repository), using -cpu host -machine epc=32M. according the documentation I could explicitly enable it with -cpu +sgx but whenever I use this flag (+sgx) I get  that the CPU doesnt recognize it. How is the correct way to launch a VM with SGX enable?

Regards

**Comment by sean-jc** [comment]
Does this resolve your issue?

https://github.com/intel/kvm-sgx/issues/4

**Comment by maincui** [comment]
@sean-jc , I need your help to enable SGX on Azure VM for another application, more specifically, [Signal Server](https://github.com/signalapp/Signal-Server). The VM says it supports SGX 1 shown in [another issue I created](https://github.com/intel/linux-sgx/issues/436). But the jhi failed to serve AESMD service. I want to know:
1. which version of SGX bundle should be the right choice for Azure VM? the prebuilt one, this linux-sgx, or the other kvm-sgx?
2. how to make sure SGX is properly installed and configured to support other applications? is that the AESMD is run successfully?

Thank you and kindest regards,
Main C

**Comment by andyzyb** [comment]
I don't think jhi can work inside a guest VM because ME device is not virtualized.

**Comment by maincui** [comment]
@andyzyb , my understanding is JHI is a must for application in Java, and hence I have to deploy it on a bear metal machine with SGX support, right?

**Comment by andyzyb** [comment]
JHI is not for java application. It is used for SGX platform service which is an optional feature.

**Comment by maincui** [comment]
thank you for upgrading my concepts of SGX. So only the driver, SDK and PSW is necessary for support for other applications, among which SDK is mandatory for development and optional for production?

**Comment by andyzyb** [comment]
Yes.

**Comment by maincui** [comment]
Then why the AESMD service cant be run successfully? it needs DAL, which should be part of JHI? I dont know, I just conclude by its name, Dynamic Application Loader (DAL) Host Interface (aka JHI).

I just tried Azure VM without Open Enclave SDK, only installing driver and PSW, without iclsClient and dal/jhi, but the AESMD service reported error ( I dont know whether it is really an error, since after the failure error it also reported whit list successful) Please help me for the possibly final step:

```
main@PigramUbuntu1804NoEnclave:~/work/wind/linux-sgx/linux/installer/deb$ sudo service aesmd status
● aesmd.service - Intel(R) Architectural Enclave Service Manager
   Loaded: loaded (/lib/systemd/system/aesmd.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-09-02 05:52:34 UTC; 4s ago
  Process: 114382 ExecStart=/opt/intel/libsgx-enclave-common/aesm/aesm_service (code=exited, status=0/SUCCESS)
  Process: 114381 ExecStartPre=/bin/chmod 0755 /var/run/aesmd/ (code=exited, status=0/SUCCESS)
  Process: 114380 ExecStartPre=/bin/chown -R aesmd:aesmd /var/run/aesmd/ (code=exited, status=0/SUCCESS)
  Process: 114379 ExecStartPre=/bin/mkdir -p /var/run/aesmd/ (code=exited, status=0/SUCCESS)
  Process: 114364 ExecStartPre=/opt/intel/libsgx-enclave-common/aesm/linksgx.sh (code=exited, status=0/SUCCESS)
 Main PID: 114384 (aesm_service)
    Tasks: 4 (limit: 19164)
   CGroup: /system.slice/aesmd.service
           └─114384 /opt/intel/libsgx-enclave-common/aesm/aesm_service

Sep 02 05:52:34 PigramUbuntu1804NoEnclave jhi[114384]: JHI init at server side failed
Sep 02 05:52:34 PigramUbuntu1804NoEnclave jhi[114384]: JHI init failed. Status: 768
Sep 02 05:52:34 PigramUbuntu1804NoEnclave jhi[114384]: JHI init at server side failed
Sep 02 05:52:34 PigramUbuntu1804NoEnclave jhi[114384]: JHI init failed. Status: 768
Sep 02 05:52:34 PigramUbuntu1804NoEnclave jhi[114384]: JHI init at server side failed
Sep 02 05:52:34 PigramUbuntu1804NoEnclave jhi[114384]: JHI init failed. Status: 768
Sep 02 05:52:34 PigramUbuntu1804NoEnclave aesm_service[114384]: [ADMIN]Platform Services initializing
Sep 02 05:52:34 PigramUbuntu1804NoEnclave aesm_service[114384]: [ADMIN]Platform Services initialization failed due to DAL error
Sep 02 05:52:34 PigramUbuntu1804NoEnclave aesm_service[114384]: The server sock is 0x55aea8c79e60
Sep 02 05:52:34 PigramUbuntu1804NoEnclave aesm_service[114384]: [ADMIN]White list update request successful for Version: 57
main@PigramUbuntu1804NoEnclave:~/work/wind/linux-sgx/linux/installer/deb$ 
```

**Comment by maincui** [comment]
@andyzyb Sorry sorry I just found iclsClient and JHI both require existence of /dev/mei, seems AESMD cant run successfully. Is AESMD service mandatory for running other applications? if not, how I can make sure driver and PSW together can support other applications?

**Comment by andyzyb** [comment]
SGX driver + AESMD service are mandatory for other applications.

**Comment by maincui** [comment]
But AESMD needs DAL/JHI, may it be configured to use other mechanisms, without JHI? if not, does it mean Azure cant support SGX completely? It's weird someone [made it](https://community.signalusers.org/t/guide-deploy-signal-server-v2-xx-cds-sgx/8331/32?u=main_cui)

**Comment by andyzyb** [comment]
DAL/JHI is for SGX platform service which is optional feature.  Without DAL/JHI,  AESMD service can execute successfully and just cannot provide the platform service, like monotonic counter/trusted time.

**Comment by andyzyb** [comment]
From above link you mentioned, I don't see it is related to platform service, so likely it works in Azure environment with installing SGX driver and PSW (including AESMD service).  Azure may use hyper-V to launch the guest OS.

**Comment by maincui** [comment]
@andyzyb , thank you very much for the greatest help. As the log shows what you meant: although the Platform Services initialization failed, the AESMD still listens to the sock and updates the white list. I will go on for other application configuration. Thank you again.

```
Sep 02 05:52:34 PigramUbuntu1804NoEnclave aesm_service[114384]: [ADMIN]Platform Services initializing
Sep 02 05:52:34 PigramUbuntu1804NoEnclave aesm_service[114384]: [ADMIN]Platform Services initialization failed due to DAL error
Sep 02 05:52:34 PigramUbuntu1804NoEnclave aesm_service[114384]: The server sock is 0x55aea8c79e60
Sep 02 05:52:34 PigramUbuntu1804NoEnclave aesm_service[114384]: [ADMIN]White list update request successful for Version: 57
```
