### ISSUE TITLE
Fedora 27

### ISSUE THREAD

**Issue by fredfortier** [intel/linux-sgx#291]
The README file suggests that Fedora 27 is supported. However, it does not appear to be supported by the SGX driver which is a prerequisite. I was able to build the SGX driver, but unable to add to my Fedora kernel. Have others used Fedora successfully? Or is it only supported in simulation mode?

**Comment by andyzyb** [comment]
What is the error you've seen for using the driver on Fedora 27?

**Comment by fredfortier** [comment]
I get an error at the last step (when running `modprobe`). Unfortunately, I haven't documented my tracks very well so I don't have the error message. Are you aware of anyone who successfully installed the driver on Fedora 27? If so, I'll try again and document the process.

**Comment by sergeay** [comment]
do you have a 4.16 kernel or newer? If yes you may have to install the following:
"sudo dnf install elfutils-libelf-devel"
Can you dump the error message here.

**Comment by andyzyb** [comment]
Fedora may install a different version of kernel header, then modprobe will fail with version mismatch.  Please check the kernel header version you build the driver and system kernel version.

**Comment by fredfortier** [comment]
Okay thanks. I will try again while keeping these considerations in mind and better documenting my tracks. Does the kernel version matter? If not, would my odds of success be any different if I try with Fedora 28? I appreciate the help.

**Comment by fredfortier** [comment]
I tried  building the `sgx-linux-driver` again on Fedora 28 with kernel `4.17.6-200.fc28.x86_64`. It seems to have worked smoothly this time. @sergeay answer above might have made the difference.
