### ISSUE TITLE
Error 4001: when running SampleEnclave in HW-debug mode

### ISSUE THREAD

**Issue by bronzeMe** [intel/linux-sgx#292]
(1)OS version,
OS :Ubuntu 14.04 x64 
Kernel:4.4.0-124-generic
CPU info: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
(2) Running SampleEnclave 
Compiling works well , as the following

++----------------------------------------------------++
make
tcs_num 10, tcs_max_num 10, tcs_min_pool 1
[build_secs /home/yun/Downloads/linux-sgx-master/psw/urts/loader.cpp:470] enclave start address = (nil), size = 0x1000000
The required memory is 4198400B.
Succeed.
SIGN =>  enclave.signed.so
The project has been built in debug hardware mode.
++----------------------------------------------------++
**Running the ./app is failed ,**
++----------------------------------------------------++
./app
....
Error code is **0x4001.** Please refer to the "Intel SGX SDK Developer Reference" for more details.
Enter a character before exit ...
++----------------------------------------------------++
![image](https://user-images.githubusercontent.com/11402109/42682559-80de2e94-86bd-11e8-9db5-2ed58379baeb.png)

**Is  "AE service"  the Architectural enclave?**, and how to enable the AE service ?
(3) Intel SGX Driver information
 **$ dmesg|grep sgx**
[    8.485421] isgx: loading out-of-tree module taints kernel.
[    8.485465] isgx: module verification failed: signature and/or required key missing - tainting kernel
[    8.486052**] intel_sgx: Intel SGX Driver v0.10**
[    8.486091] intel_sgx INT0E0C:00: EPC bank 0x70200000-0x75f80000
[    8.487294] intel_sgx: second initialization call skipped
[   22.893753] intel_sgx: [1367:0x00007f43f5600000] EINIT returned 2
[   27.221614] intel_sgx: [1634:0x00007fe285600000] EINIT returned 2
[   27.314543] intel_sgx: [1655:0x00007fc17fc00000] EINIT returned 2
[   27.444122] intel_sgx: [1683:0x00007fbc8dc00000] EINIT returned 2
[   27.515887] intel_sgx: [1694:0x00007f0be1200000] EINIT returned 2
[   27.596131] intel_sgx: [1707:0x00007f1be2c00000] EINIT returned 2
[   27.676923] intel_sgx: [1723:0x00007f492de00000] EINIT returned 2
[   27.757562] intel_sgx: [1770:0x00007f66d0e00000] EINIT returned 2
[   29.858244] intel_sgx: [1985:0x00007fe248c00000] EINIT returned 2
[   30.430718] intel_sgx: [2037:0x00007f953ac00000] EINIT returned 2
[   30.501770] intel_sgx: [2053:0x00007f5297800000] EINIT returned 2

$ lsmod |grep sgx
isgx                   57344  1 
$ ls /dev/isgx 
/dev/isgx
(4) The result of[ SGX-hardware](https://github.com/ayeks/SGX-hardware)
:~/Downloads/SGX-hardware-master$ ./test-sgx
eax: 906ea ebx: 1100800 ecx: 7ffafbff edx: bfebfbff
stepping 10
model 14
family 6
processor type 0
extended model 9
extended family 0
smx: 1

Extended feature bits (EAX=07H, ECX=0H)
eax: 0 ebx: 29c6fbf ecx: 40000000 edx: 9c000000
**sgx available: 1**

CPUID Leaf 12H, Sub-Leaf 0 of Intel SGX Capabilities (EAX=12H,ECX=0)
eax: 1 ebx: 0 ecx: 0 edx: 241f
**sgx 1 supported: 1**
sgx 2 supported: 0
MaxEnclaveSize_Not64: 1f
MaxEnclaveSize_64: 24

CPUID Leaf 12H, Sub-Leaf 1 of Intel SGX Capabilities (EAX=12H,ECX=1)
eax: 36 ebx: 0 ecx: 1f edx: 0

CPUID Leaf 12H, Sub-Leaf 2 of Intel SGX Capabilities (EAX=12H,ECX=2)
eax: 70200001 ebx: 0 ecx: 5d80001 edx: 0

CPUID Leaf 12H, Sub-Leaf 3 of Intel SGX Capabilities (EAX=12H,ECX=3)
eax: 0 ebx: 0 ecx: 0 edx: 0

CPUID Leaf 12H, Sub-Leaf 4 of Intel SGX Capabilities (EAX=12H,ECX=4)
eax: 0 ebx: 0 ecx: 0 edx: 0
(5) The result of sgx_feautre.c

```
#include "sgx_uae_service.h"
#include "sgx_capable.h"
#include<stdio.h>

int SGX_CDECL main(int argc, char *argv[])
{
	(void)(argc);
	(void)(argv);
	unsigned int sgx_support;
	int rv= 0;
	sgx_device_status_t sgx_device_status;
	sgx_status_t sgx_ret = sgx_cap_enable_device(&sgx_device_status);

	if (sgx_ret != SGX_SUCCESS) {
		printf("Failed to get SGX device status.\n");
		return -1;
	}
	else {
		switch (sgx_device_status) {
			case SGX_ENABLED:
			printf("SGX device is enabled\n");
			return 0;
			case SGX_DISABLED_REBOOT_REQUIRED:
			printf("SGX device has been enabled. Please reboot your machine.\n");
			return -1;
			case SGX_DISABLED_LEGACY_OS:
			printf("SGX device can't be enabled on an OS that doesn't support EFI interface.\n");
			return -1;
			case SGX_DISABLED:
			printf("SGX device not found.\n");
			return -1;
			default:
			printf("Unexpected error.\n");
			return -1;
		}
	}

	
}
```
$ ./sgx_feature 
SGX device is enabled

**Comment by bronzeMe** [comment]
JHI service was not enabled successfully.
sudo systemctl enable jhi
Failed to issue method call: No such file or directory

PSW installed failed:

**$ sudo ./sgx_linux_x64_psw_2.1.102.43402.bin** 
Unpacking Intel SGX PSW Package ... done.
Verifying the integrity of the install package ... done.
Installing Intel SGX PSW Package ... done.
/tmp/sgx-psw-eHJwjG ~/Downloads/linux-sgx-master/linux/installer/bin
install -d /opt/intel/sgxpsw
install -d /opt/intel/sgxpsw/scripts
install -d /usr/lib
cp -r package/* /opt/intel/sgxpsw
install scripts/* /opt/intel/sgxpsw/scripts
mv /opt/intel/sgxpsw/lib64/libsgx_uae_service.so /usr/lib
mv /opt/intel/sgxpsw/lib64/libsgx_urts.so /usr/lib
rmdir /opt/intel/sgxpsw/lib64
~/Downloads/linux-sgx-master/linux/installer/bin
Installing aesmd.service service ...Failed to issue method call: No such file or directory

**Comment by andyzyb** [comment]
JHI failure only impacts platform service and other SGX functions should work.

**Comment by bronzeMe** [comment]
Thanks a lot, I tried it on a new OS version: Ubuntu 16.04 x64, it works well.

**Comment by llly** [comment]
aesmd service is not working properly. Can you paste result of
```
$ service aesmd status
```
and check whether `/lib/systemd/system/aesmd.service` exist?

**Comment by bronzeMe** [comment]
Thank you so much, it works well on Ubuntu 16.04!!
