### ISSUE TITLE
Clean up time-related OCALLs before public preview

### ISSUE THREAD

**Issue by mikbras** [intel/linux-sgx#293]
Open Enclave currently supports the following time-related OCALLs:
- OE_OCALL_STRFTIME
- OE_OCALL_GETTIMEOFDAY
- OE_OCALL_CLOCK_GETTIME
- OE_OCALL_NANOSLEEP

All of these are wrappers for calling POSIX functions on the host. These do not translate onto Windows and should be replaced before public preview, else it will be harder to remove them from the interface later on.

The **strftime()** function can be implemented on the enclave side and should be removed. The other three should be replaced with the following:
- OE_OCALL_TIME - Get microseconds elapsed since epoch (1970).
- OE_OCALL_SLEEP - Sleep for N microseconds.

Microseconds provides a more than sufficient granularity since OCALL overhead is way above the nanoseconds range.

**Comment by mikbras** [comment]
Here are reference implementations.

```
void oe_sleep(uint64_t milliseconds)
{
#if defined(_MSC_VER)
    Sleep((DWORD)milliseconds);
#elif defined(__linux__)
    struct timespec ts;
    ts.tv_sec = (long)(milliseconds / 1000);
    ts.tv_nsec = (long)((milliseconds % 1000) * 1000 * 1000);
    nanosleep(&ts, NULL);
#endif
}
```
/* return microseconds elapsed since epoch or 0 on failure */
uint64_t oe_time()
{
#if defined(_MSC_VER)

    FILETIME ft;
    ULARGE_INTEGER x;

    GetSystemTimeAsFileTime(&ft);
    x.u.LowPart = ft.dwLowDateTime;
    x.u.HighPart = ft.dwHighDateTime;
    x.QuadPart -= 0X19DB1DED53E8000;

    return = x.QuadPart / 10UL;

#elif defined(OE_HAVE_CLOCK_GETTIME)

    struct timespec ts;

    if (clock_gettime(CLOCK_REALTIME, &ts) != 0)
        return 0;

    uint64_t sec = ((uint64_t)ts.tv_sec * 1000000UL);
    uint64_t usec = ((uint64_t)ts.tv_nsec / 1000UL);

    return sec + usec;

#elif defined(__linux__)

    struct timeval tv;

    if (gettimeofday(&tv, NULL) != 0)
        return 0;

    return (uint64_t)tv.tv_sec * 1000000UL + (uint64_t)tv.tv_usec;

#endif
}
```

**Comment by andyzyb** [comment]
Does this issue go to the wrong project?

**Comment by mikbras** [comment]
This issue opened by accident against the wrong repository. My apologies.
