### ISSUE TITLE
Missing sgx_tcb_evaluation_flag definition

### ISSUE THREAD

**Issue by jethrogb** [intel/linux-sgx#306]
I've received an attestation report from IAS with `platform_info_blob.sgx_tcb_evaluation_flags = 0x0008`. This value is not defined in `psw/ae/aesm_service/source/upse/platform_info_blob.h`.

**Comment by llly** [comment]
Thanks for reporting.  New flag bit has been added to Platform Information Blob from IAS. Accordingly, we'll update definitions of the flag.
