### ISSUE TITLE
OCaml and SGX

### ISSUE THREAD

**Issue by ivanatodvuk** [intel/linux-sgx#315]
Hi,

I got stuck trying to run OCaml code within an SGX enclave and would
very much appreciate some help.

I so far managed to write a C wrapper around my OCaml code using the
functionalities described here:
https://caml.inria.fr/pub/docs/manual-ocaml/intfc.html

Now, to link the code, I have to load the OCaml runtime using
-lcamlrun_pic (-lcamlrun is not PIC compatible).

The problem is now that camlrun_pic uses standard libraries quite
heavily.  It looks like I could add the missing functionalities by doing
something like that:
http://www.tatetian.io/2016/01/25/file-io-inside-intel-sgx-enclave/

Do you think that's the right approach?  Is there an easier one?

Thanks!

**Comment by ZongminGu** [comment]
Porting the run time support libraries is not an easy task. You need to clearly review the camlrun implementation and port it into enclave. The OCall will help you, but sometimes, it will bring security issue too, be careful. If the camlrun needs pthread support, then the situation is worse, you may need to redesign it.

**Comment by ivanatodvuk** [comment]
Hi,

@ZongminGu  thank you for your reply. 

We are still trying to run some OCaml code within an Intel SGX enclave. Now we have some new challenges.

Our OCaml code is called by a C wrapper using the method described
here:  https://caml.inria.fr/pub/docs/manual-ocaml/intfc.html

Because Intel SGX doesn't support the entire standard C library, we had
to create ocalls for the functions that are used by ocamlrun but not
supported by SGX.  Using the functionalities provided by Intel SGX, we
managed to create an .so library containing our OCaml code along with
the C wrapper.  This .so library is what is meant to run in an SGX
enclave (we so far only implemented the ocalls that we needed, and not
all missing functionalities from ocamlrun).

Our problem is now that when we call caml_startup from within our C
wrapper (in order to start the OCaml code), the code seem to simply call
'exit' and stop there.  Does anyone know why this call to caml_startup
would call 'exit'?

We managed to create a simple example, which can be found in the attachment.

Please note that we use ocaml 4.06.1 and gcc 7.3.0

[hello-enclave_small_example.tar.gz](https://github.com/intel/linux-sgx/files/2461229/hello-enclave_small_example.tar.gz)
