### ISSUE TITLE
the samplecode 'RemoteAttestation' doesn't work

### ISSUE THREAD

**Issue by EighteenZi** [intel/linux-sgx#318]
When I knocked in 'make' in `RemoteAttestation`, the error appeared as below.
```
service_provider/ecp.cpp:38:30: fatal error: sample_libcrypto.h: No such file or directory
```
I found `ServiceProvider_Include_Paths` not included in compiling `service_provider`. I put it at the end of the CXX command, but I got other errors as below
```
error: ‘stderr’ was not declared in this scope
error: ‘fprintf’ was not declared in this scope
```
But <stdio.h> has been added in the file...
I add `iostream` line in the front of the file, but the errors still exist..

Maybe I have the wrong version of gcc or g++, but other examples can work well. 

Any help would be appreciated.

**Comment by andyzyb** [comment]
Did you install the SDK?  The RemoteAttestation sample code is designed to be part of SDK and should be built after SDK is installed.  If you build it from the source tree pull from github, there might be issues like above.

**Comment by EighteenZi** [comment]
```
under the SDK installed folder
```
it works.

And I tried another way as follows.
I have the source code of "linux-sgx", and I copied the directory of 'sample_libcrypto' from the path 'linux-sgx/sdk/sample_libcrypto', and libsample_libcrypto.so to 'RemoteAttestation', and it worked also.

Thanks.

**Comment by fyuan12** [comment]
> ```
> under the SDK installed folder
> ```
> 
> it works.
> 
> And I tried another way as follows.
> I have the source code of "linux-sgx", and I copied the directory of 'sample_libcrypto' from the path 'linux-sgx/sdk/sample_libcrypto', and libsample_libcrypto.so to 'RemoteAttestation', and it worked also.
> 
> Thanks.

So what I did was to `make` inside `linux-sgx/sdk/sample_libcrypto` and move the entire folder `sample_libcrypto` into `linux-sgx/SampleCode/RemoteAttestation`, and it worked!
