### ISSUE TITLE
LocalAttestation Works in Hardware Mode but Fails in Simulation Mode Because libsgx_urts_sim.so Cannot Be Found

### ISSUE THREAD

**Issue by vedantroy** [intel/linux-sgx#333]
I have a computer with Intel SGX hardware support. I installed the SDK and the PSW. I then compiled and ran the LocalAttestation sample with `SGX_MODE=SIM`. However, when I executed the command `./app`, I got the error:
`./app: error while loading shared libraries: libsgx_urts_sim.so: cannot open shared object file: No such file or directory
`

Is this a problem with my installation of SGX, or a bug in linux-sgx itself? 

Note - the program works if I compile it in hardware mode. 

Also, running the command "find / -type f -name "libsgx_urts_sim.so" gives the following results:
```
/home/myusername/.local/share/Trash/files/sgxsdk/lib64/libsgx_urts_sim.so
/home/myusername/linux-sgx/build/linux/libsgx_urts_sim.so
/home/myusername/linux-sgx/linux/installer/common/sdk/output/package/lib64/libsgx_urts_sim.so
/home/myusername/linux-sgx/sdk/simulation/urtssim/linux/libsgx_urts_sim.so
```

I also found the file in 
`/opt/intel/sgxsdk/sdk_libs//opt/intel/sgxsdk/sdk_libs/libsgx_urts_sim.so`

I think the error may have to do with the following problems I get when I open the sample project in my IDE:

![sgx_error_1](https://user-images.githubusercontent.com/8407819/47599959-2d61da00-d987-11e8-95a1-e99575eea8a1.png)

Additionally, my IDE can't seem to find the files for:

```
#include "sgx_eid.h"
#include "sgx_urts.h"
```

Infact, it can't find header files for any SGX library. Is the SGX sdk supposed to be in the same directory as my actual project?

**Comment by vedantroy** [comment]
Thanks for the help. How do I know which libsgx_urts_sim.so is the correct one? Also should I update my include path to include "/opt/intel/sgxsdk/include", so the header files are recognized?

**Comment by vedantroy** [comment]
Not sure if this correct, but I fixed the issue by running the above command in the directory of my project. I had assumed that running the command once would set the environment variables everywhere, but it seems like I need to set the environment variables for each of my projects.

**Comment by andyzyb** [comment]
It should set the environment for the user which runs this command. But it only persists for the current session.

**Comment by vedantroy** [comment]
Would it be a good idea to put this command in my .bashrc so I don't have to run it repeatedly?

**Comment by andyzyb** [comment]
Yes, you can have it in .bashrc to avoid executing it every time.
