### ISSUE TITLE
Use std::string inside enclave 

### ISSUE THREAD

**Issue by vedantroy** [intel/linux-sgx#344]
Is it possible to use std::string, or an sgx equivalent inside the equivalent? I included string.h from "/opt/intel/sgxsdk/include/stlport", but std::string still isn't working.

**Comment by ZongminGu** [comment]
You need "#include <string>" in the code.

**Comment by andyzyb** [comment]
What error have you seen?   A proper way will be installing the SDK, and using "#include <string>" in the code.

**Comment by andyzyb** [comment]
There is the sample code for C++ classes:
https://github.com/intel/linux-sgx/tree/master/SampleCode/Cxx11SGXDemo

The using of string is in:
https://github.com/intel/linux-sgx/blob/master/SampleCode/Cxx11SGXDemo/Enclave/TrustedLibrary/Libcxx.cpp

Also how to set the path of C++ header files in Makefile:
https://github.com/intel/linux-sgx/blob/master/SampleCode/Cxx11SGXDemo/Makefile
......
Enclave_Include_Paths := -IEnclave -I$(SGX_SDK)/include -I$(SGX_SDK)/include/libcxx -I$(SGX_SDK)/include/tlibc 
.....
$(SGX_SDK) should be where you install the SDK

**Comment by vedantroy** [comment]
The error was as @ZongminGu said. I needed to use `#include <string>` instead of `#include <string.h>`
