### ISSUE TITLE
SampleCommonLoader: init enclave error! error code - 0x1001

### ISSUE THREAD

**Issue by SujayYadalam94** [intel/linux-sgx#353]
When I run the 'SampleCommonLoader' out-of-the-box example under SampleCode, I get the below error:
init enclave error! error code - 0x1001

1) My debugging tells me that the issue is with the get_launch_token call. Can somebody tell me what I am doing wrong? 

2) I don't see other examples which make use of the loader layer APIs such as 'enclave_create()', 'enclave_load_data()' and 'enclave_initialize()'. I want to build an application using these APIs instead of the commonly used sgx_create_enclave API. Any pointers?

**Comment by andyzyb** [comment]
How you build and run the sample code? Have you successfully installed SGX driver and Platform software?

**Comment by SujayYadalam94** [comment]
Yes, I have successfully installed the PSW and the driver. I have got other examples running on my system.
To build and run the code, I followed the steps in the ReadMe included in the project folder.

**Comment by xiangquanliu** [comment]
Do you use the in-kernel driver or out-of-tree driver? please check with ls /dev/sgx or ls /dev/isgx. Thanks!

**Comment by SujayYadalam94** [comment]
I am using the out-of-tree driver or the isgx.

**Comment by xiangquanliu** [comment]
So please check if aesmd service is started.

**Comment by SujayYadalam94** [comment]
The aesmd service is loaded and active.

**Comment by xiangquanliu** [comment]
This is bug with out of tree driver. And it will be fixed in coming weeks. Thanks.

**Comment by ZongminGu** [comment]
The bug should be fixed. Please update the code.
