### ISSUE TITLE
build_pages function is wrong

### ISSUE THREAD

**Issue by SujayYadalam94** [intel/linux-sgx#357]
I believe that there is a bug in the `CLoader::build_pages(...)` function inside psw/urts/loader.cpp.

The function has a `while(offset < size)`, inside which the `add_enclave_page()` function is called.
The second parameter to the `add_enclave_page()` is `GET_PTR(void, source ,0)`. I think this should be changed to `GET_PTR(void, source, offset)`.

Consider a scenario when build_pages is called with size > SE_PAGE_SIZE, in that case the while loop will execute more than once. However, the 2nd parameter, i.e. the source address will remain the same but it should have been incremented by the SE_PAGE_SIZE.

I tried changing the '0' to 'offset' but my enclave initialization failed. 

I would be glad if someone could explain why the source pointer is not incremented inside the while loop.

**Comment by lzha101** [comment]
`GET_PTR(void, source ,0)` is the pointer of the source data. The loader ensures the source data size not greater than SE_PAGE_SIZE in the calling functions.  I think `CLoader::build_pages()` is designed to build one page for one call or build several pages for which each page has the same data.  Building several pages for one call could provide benefits to build stack/heap.  You can read the code `CLoader::build_context()` for more info. Only replacing '0' with 'offset' in `GET_PTR(void, source ,0)` is not correct.

**Comment by SujayYadalam94** [comment]
" I think CLoader::build_pages() is designed to build one page for one call or build several pages for which each page has the same data".

If that is the intended functionality, then this requires no change. The function should have been called build_page instead of build_pages.
