### ISSUE TITLE
Launching enclaves in enclave-production mode

### ISSUE THREAD

**Issue by shpark** [intel/linux-sgx#372]
Hello

I am trying to do some security experiments on Intel SGX enclaves. Without product license, however, I cannot launch enclave in **enclave-production** mode on my machine. As far as I know, hardware debug mode and pre-release launch enclaves in enclave-debug mode and don't provide full protection that can be achieved by Intel SGX. Is there any way that I can try out release mode enclaves on my machine, without requesting commercial keys?

And where can I find more detailed comparison between different enclave modes? I've read this [article](https://software.intel.com/en-us/blogs/2016/01/07/intel-sgx-debug-production-prelease-whats-the-difference) but I think I don't fully understand the differences.

**Comment by andyzyb** [comment]
The major difference is you will get different keys (if you are using sgx_get_key or other crypto functions) inside Enclave.  Also the debug mode Enclave can be debugged, means its memory can be read and written by a debugger.

**Comment by jsraynor** [comment]
Hello.

Short answer is no, you cannot launch an enclave in production mode without signing a commercial license agreement with Intel.  To launch in production mode, your enclave signing key needs to be whitelisted.  For more info, see these links:

[https://software.intel.com/en-us/sgx/commercial-use-license-request](url)
[https://software.intel.com/sites/default/files/managed/78/4a/overview-signing-whitelisting-intel-sgx-enclaves.pdf](url)

Regards.

Scott

**Comment by shpark** [comment]
@jsraynor Thanks for the information! I am closing this issue.
