### ISSUE TITLE
Not able to install MEI driver required by PSW

### ISSUE THREAD

**Issue by gokhalesushant65** [intel/linux-sgx#374]
I am trying to fire 'make'  mei-7.1.20-25 , I get the error as can be seen in the text file attached.
[MEI_driver_make_error.txt](https://github.com/intel/linux-sgx/files/2900933/MEI_driver_make_error.txt)

How should I resolve the error?

**Comment by andyzyb** [comment]
The MEI driver is usually part of Linux kernel. It seems not necessary to build another MEI driver.

**Comment by gokhalesushant65** [comment]
I am running a virtual machine using KVM and QEMU.  I am not able to see the device /dev/mei0 nor the modules into the kernel. Is there anything I am missing?

**Comment by andyzyb** [comment]
The MEI device may not be virtualized or assigned to guest OS, so you won't be able to use it.

**Comment by gokhalesushant65** [comment]
ok. Thanks. Will close the issue for now.

**Comment by OriENtKids** [comment]
Using virtual machine should follow QEMU or KVM architecture’s SGX, which is different than this repo.
