### ISSUE TITLE
Intermittent segfault during static destruction of Simulation enclave manager

### ISSUE THREAD

**Issue by exFalso** [intel/linux-sgx#375]
We see intermittent segfaults during simulation enclave memory unmapping in https://github.com/intel/linux-sgx/blob/master/sdk/simulation/uinst/enclave_mngr.cpp#L169. It's manifesting intermittently in the presence other active ecalling threads during shutdown.

The destructor is called during process exit as part of static deinit, so it should be safe to simply remove this unmapping.

In general we see issues with enclave shutdown in the presence of multiple threads that have entered the enclave. `sgx_destroy_enclave` simply hangs trying to acquire a lock if there are other busy ecalling threads, and sometimes causes a raise of SIGSEGV or SIGILL if an enclave thread is blocked in an ocall. Although sometimes it seems to do the right thing and return an ENCLAVE_LOST error code.

Currently our "solution" is to piggyback on process shutdown and only load a single enclave per host process. The more I look into it the less I see how a "graceful" shutdown could work without the cooperation of the enclave, as it would need to somehow interrupt in-flight threads. What are the plans with this feature?

**Comment by ZongminGu** [comment]
In general, we hope user could sync all the threads which is doing ecall before sgx_destroy_enclave. We do not want interrupt the ecall in sgx_destroy_enclave. Please make sure all the ecall finished then to use sgx_destroy_enclave.

**Comment by andyzyb** [comment]
Close since no further response
