### ISSUE TITLE
make failing in Sample Enclave in Sample Code

### ISSUE THREAD

**Issue by maharishib** [intel/linux-sgx#387]
Output of make:

make[1]: Entering directory '/opt/intel/sgx-step/linux-sgx/SampleCode/SampleEnclave'
GEN  =>  App/Enclave_u.h
CC   <=  App/Enclave_u.c
In file included from App/App.cpp:46:0:
/opt/intel/sgx-step/libsgxstep/debug.h:29:6: warning: "NO_SGX" is not defined, evaluates to 0 [-Wundef]
 #if !NO_SGX
      ^~~~~~
In file included from App/App.cpp:48:0:
/opt/intel/sgx-step/libsgxstep/enclave.h:23:6: warning: "NO_SGX" is not defined, evaluates to 0 [-Wundef]
 #if !NO_SGX
      ^~~~~~
CXX  <=  App/App.cpp
CXX  <=  App/Edger8rSyntax/Types.cpp
CXX  <=  App/Edger8rSyntax/Pointers.cpp
CXX  <=  App/Edger8rSyntax/Arrays.cpp
CXX  <=  App/Edger8rSyntax/Functions.cpp
CXX  <=  App/TrustedLibrary/Thread.cpp
CXX  <=  App/TrustedLibrary/Libcxx.cpp
CXX  <=  App/TrustedLibrary/Libc.cpp
-L/opt/intel/sgxsdk/lib64 -lsgx_urts -L/opt/intel/sgxssl//lib64/ -lsgx_usgxssl -L/opt/intel/sgx-step/libsgxstep/ -lsgx-step -lpthread  -lsgx_uae_service
g++ App/Enclave_u.o App/App.o App/Edger8rSyntax/Types.o App/Edger8rSyntax/Pointers.o App/Edger8rSyntax/Arrays.o App/Edger8rSyntax/Functions.o App/TrustedLibrary/Thread.o App/TrustedLibrary/Libcxx.o App/TrustedLibrary/Libc.o -o app -L/opt/intel/sgxsdk/lib64 -lsgx_urts -L/opt/intel/sgxssl//lib64/ -lsgx_usgxssl -L/opt/intel/sgx-step/libsgxstep/ -lsgx-step -lpthread  -lsgx_uae_service
App/App.o: In function `main':
/opt/intel/sgx-step/linux-sgx/SampleCode/SampleEnclave/App/App.cpp:220: undefined reference to `register_enclave_info()'
collect2: error: ld returned 1 exit status
Makefile:261: recipe for target 'app' failed
make[1]: *** [app] Error 1
make[1]: Leaving directory '/opt/intel/sgx-step/linux-sgx/SampleCode/SampleEnclave'
Makefile:206: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ZongminGu** [comment]
Can you please share the /opt/intel/sgx-step/libsgxstep/debug.h here?

**Comment by maharishib** [comment]
This issue was fixed by compiling with g++4.8
