### ISSUE TITLE
SGX 2.5 release `make` fails due to git module command

### ISSUE THREAD

**Issue by shpark** [intel/linux-sgx#390]
From the `Makefile` of SDK 2.5,
```
all: dcap_source sdk psw

# dcap_source:
# 	git submodule update --init --recursive
```
Simply running `make` from the source code downloaded from [here](https://github.com/intel/linux-sgx/releases/tag/sgx_2.5) won't work due to `git submodule` command

I had to manually download the source code for DataCenterAttestationPrimitives.

IMHO It would be good if the release source tar bells download source codes from the archive.

**Comment by llly** [comment]
Submodule is standard usage to include another repo. Github webpage can track Submodule as "repo@revision".
Is https proxy needed on your machine? If yes, https proxy for git must be configured. Otherwise you can try `git clone --recursive --branch [tag] [repo]`.

**Comment by shpark** [comment]
Thanks for your response.

By the way what I wanted to point out is that [this](https://github.com/intel/linux-sgx/releases/tag/sgx_2.5) source tar bell is not provided with `.git`, thus `make all` will fail.

It is natural to use `git submodules` for the `master` branch, but release source tar bell should download the source code from the archives, or wherever.

I don't know what is the best practice of handling the 3rd party libraries, yet at this point I want to mention that [some projects](https://github.com/facebook/rocksdb/blob/master/Makefile#L1722) avoid calling `git submodules` and instead download the dependencies from the archive,  while building the project.

**Comment by llly** [comment]
We'll add downloading tarball in Makefile along with `git submodule` command. 
`linux-sgx` project directly uses source code of `DataCenterAttestationPrimitives`, not only links to the binaries.  Developers can track local changes.

**Comment by shpark** [comment]
Good to here from you. I opened a pull request as a suggestion. Thanks!

**Comment by llly** [comment]
Thank you. Will review your PR.
