### ISSUE TITLE
Does Intel® SGX work with Intel® MKL?

### ISSUE THREAD

**Issue by chasex** [intel/linux-sgx#392]
We need to do some BLAS in enclave. I have tried Eigen3, but it doesn't work with SGX.  Since Intel® MKL is from the same manufacturer, I want to know if it works with Intel® SGX?

**Comment by chasex** [comment]
The data must keep in enclave, so I can't call untrusted BLAS via OCall.

**Comment by andyzyb** [comment]
Intel SGX software doesn't support MKL inside enclave at this point.

**Comment by chasex** [comment]
@andyzyb Thanks for your reply. Is there a plan to support MKL in the future? And any advice to do linear algebra calculation in enclave at this moment?

**Comment by andyzyb** [comment]
MKL support is not in the plan yet.  You can look at other open source projects and see whether possible to port to Enclave environment.

**Comment by chasex** [comment]
@andyzyb It seems like SGX not even supporting Intel intrinsic instructions (SSE/AVX), I don't find any *mmintrin.h in $(SGX_SDK)/include/tlibc

**Comment by ZongminGu** [comment]
In order to support intrinsic, you need to include these header files into your enclave project. They are not in the SGX project, because intrinsics are naturally supported by SGX. If you find anything wrong, please let us know.

**Comment by chasex** [comment]
@ZongminGu According to Intel® SGX Developer Reference
```
C/C++ calls to System provided C/C++/STL standard libraries:
A trusted version of these libraries is supplied with the Intel® Software Guard Extensions SDK and they can be used instead.
```
In SampleCode Makefile, gcc compiler is 
`-nostdinc -I/opt/intel/sgxsdk/include -I/opt/intel/sgxsdk/include/tlibc -I/opt/intel/sgxsdk/include/libcxx`, which means standard system directories for header files, only the directories you have specified with -I options. However, there isn't any intrinsic header files(*mmintrin.h) in sgxsdk include path, so it's really confuse me.

**Comment by ZongminGu** [comment]
The sample code is a sample, which focus on demo SGX basic functions. If you want to use some advanced features you need to updated it to include your own header files. BTW: If you can contribute the BSD based intrinsic header files, it is appreciated.

**Comment by chasex** [comment]
@ZongminGu Thank you very much, it's really help me a lot. After including some intrinsic header files from standard system directories, I succeed running Eigen inside SGX. Will see If I can contribute later :)

**Comment by ndokmai** [comment]
Thank you for everyone's comment. I follow the advice and create a sample code for this here: https://github.com/ndokmai/eigen-sgx

**Comment by duanbing** [comment]
Any new work about this port?

**Comment by lzha101** [comment]
@duanbing if you are asking MKL inside enclave, the answer is still NO.  MKL is not supported inside SGX enclave. But we provide a DNNL inside SGX enclave, in case it is helpful for you.

**Comment by duanbing** [comment]
@lzha101  Excited to know DNNL had been ported to SGX enclave. One more question, Could you share with me the doc of how to build TensorFlow on DNNL?

**Comment by lzha101** [comment]
@duanbing suppose you are asking building TensorFlow on DNNL **outside SGX enclave**. We didn't try that. 
Just found a webpage. Hope it could help you.
https://software.intel.com/content/www/us/en/develop/articles/intel-optimization-for-tensorflow-installation-guide.html

**Comment by dimitrijejankov** [comment]
Is there any update on mkl support?
