### ISSUE TITLE
sgx_uae_service.h references the bool type but doesn't #include <stdbool.h>

### ISSUE THREAD

**Issue by jmechalas** [intel/linux-sgx#393]
As of 2.5, sgx_uae_service.h references the bool type without defining it first.

Example:
```
$ cat foo.c
#include <sgx_uae_service.h>
$ gcc -c foo.c -I /opt/intel/sgxsdk/include/
In file included from foo.c:1:0:
/opt/intel/sgxsdk/include/sgx_uae_service.h:280:45: error: unknown type name \u2018bool\u2019; did you mean \u2018_Bool\u2019?
                                             bool refresh_att_key,
                                             ^~~~
                                             _Bool
```

sgx_uae_service.h needs the following added to it:

```
#include <stdbool.h>
```

**Comment by llly** [comment]
This is a bug. bool should not be used in C style headers. Will fix it.

**Comment by Anthony-Mai** [comment]
I am seeing the same problem today. Why is this not fixed yet? What should I replace the bool with?

**Comment by llly** [comment]
Several interfaces about QuoteEx will be updated in the coming 2.6 release.
You can replace it with `int` currently.

**Comment by llly** [comment]
This issue is fixed in [sgx_2.6](https://github.com/intel/linux-sgx/tree/sgx_2.6).
sgx_uae_service.h doesn't use `bool` anymore.
