### ISSUE TITLE
Where can I find whitelist allowed by Intel LE?

### ISSUE THREAD

**Issue by shpark** [intel/linux-sgx#394]
I am currently looking at the process of launching enclaves in release mode.

AFAIU Intel LE, signed by Intel, is downloaded by `download_prebuilt.sh` and `aesmd.service` determines  whether release-mode signed enclave can be launched based on the whitelist.

Where is this whitelist stored? Is it shipped with Intel LE or stored on Intel server?

If I request a license to get a signing key, how and when Intel LE learns about my new signing key?

**Comment by andyzyb** [comment]
Whitelist is shipped with Intel LE , and it will also be updated through network.  

You need to register to Intel to get your signing key in whitelist.

Check issue #372 to find more information.
