### ISSUE TITLE
linksgx.sh does not identify correct driver to load if both in-tree and out-of-tree drivers are part of the image

### ISSUE THREAD

**Issue by garywest** [intel/linux-sgx#400]
I have an image that has both kernel drivers (in-tree and out-of-tree). This allows me to select the flex launch policy of Unlocked or "Intel Locked".

With both drivers loaded, the out-of-tree driver always creates the device /dev/isgx.

**Comment by andyzyb** [comment]
Co-existence of 2 drivers are not supported.
