### ISSUE TITLE
Can't seem to debug using Intellij CLion

### ISSUE THREAD

**Issue by elichai** [intel/linux-sgx#403]
Hi,
When I use `sgx-gdb` in my terminal it works fine: 
```
add-symbol-file '/home/elichai2/CLionProjects/enigma/enigma-core/enigma-core/bin/enclave.signed.so' 0x7fffc0069040 -readnow -s .interp 0x7fffc0000270  -s .note.gnu.build-id 0x7fffc000028c
-s .gnu.hash 0x7fffc00002b0  -s .dynsym 0x7fffc00002e0  -s .dynstr 0x7fffc0000358  -s .gnu.version 0x7fffc0000392  -s .gnu.version_d 0x7fffc00003a0  -s .rela.dyn 0x7fffc00003d8  -s .plt 0x7
fffc0068ff0  -s .plt.got 0x7fffc0069000  -s .nipx 0x7fffc071ed80  -s .rodata 0x7fffc071f640  -s .niprod 0x7fffc0883700  -s .eh_frame_hdr 0x7fffc0883f40  -s .eh_frame 0x7fffc08b4c08  -s .gcc
_except_table 0x7fffc0959f50  -s .tbss 0x7fffc0b8cfe0  -s .init_array 0x7fffc0b8cfe0  -s .fini_array 0x7fffc0b8cfe8  -s .data.rel.ro 0x7fffc0b8d040  -s .dynamic 0x7fffc0babec0  -s .got 0x7f
ffc0bac060  -s .data 0x7fffc0bc2000  -s .nipd 0x7fffc0bc2e94  -s .bss 0x7fffc0bc2ea0
```
full: https://paste.ubuntu.com/p/ZcpXmybqv3/

But when I try to make CLion use it I get weird python casting errors:
like: 
```
Thread 2 "tests::test_enc" hit Breakpoint 12, enigma_core_app::tests::test_enclave_internal () at src/lib.rs:83
83	        let ret = unsafe { ecall_run_tests(enclave.geteid(), &db_ptr as *const RawPointer, &mut result) };
Traceback (most recent call last):
  File "/opt/sgxsdk/lib64/gdb-sgx-plugin/gdb_sgx_plugin.py", line 591, in stop
    gdb.execute(gdb_cmd, False, True)
gdb.error: syntax error in expression, near `)0x7ffff4127370 = 0'.
```
full: https://paste.ubuntu.com/p/zDf5RmDcFw/

Any ideas what are they? how can I fix this?

@dingelish maybe you'll have some insight too.

Thanks!

**Comment by dingelish** [comment]
Yeah. That's exactly what I don't know how to solve. But I guess you probably running GDB>7.12, and most probably using Ubuntu 18 and GDB 8. The result is that current sgx-gdb would throw a Python exception on every ocall as you pointed out. Everything runs smoothly if switching back to old version such as Ubuntu 16.04 + GDB 7.11/7.12.

I would believe that either sgx-gdb python components or the [C](https://github.com/intel/linux-sgx/tree/master/sdk/debugger_interface/linux) part are not compatible with a higher version of GDB.

**Comment by dingelish** [comment]
I tried to use gdb 8 f in a terminal only with sgx-gdb plugins enabled. When python throws that exception, I find that the `set` functions are not working in that state. You can simply `sgx-gdb` what you want and triggers that exception and then try to do this:
```
set *(uintptr_t *)0x7ffff4127370  = 0
```
And python would throw the same error. The line is at gdb_sgx_plugin.py:455
https://github.com/intel/linux-sgx/blob/master/sdk/debugger_interface/linux/gdb-sgx-plugin/gdb_sgx_plugin.py#L455

**Comment by elichai** [comment]
Hmm I'll try to manually compile a lower version of GDB.

but somehow in the terminal it does work for me.
I get these python errors only in CLion, although it's the same gdb :/

**Comment by ZongminGu** [comment]
Hi elichai, can you please help to confirm the GDB version which has the issue?

**Comment by dingelish** [comment]
@ZongminGu I can confirm that this 100% happens on a Ubuntu 18.04 system with gdb install from its default `apt` source.

Here's my testbed.

```
$ cat /etc/issue
Ubuntu 18.04.2 LTS \n \l

$ gdb --version
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".

$ readelf -d /usr/bin/gdb | grep python
 0x0000000000000001 (NEEDED)             Shared library: [libpython3.6m.so.1.0]
```

**Comment by dingelish** [comment]
😅Just re-run sgx-gdb on this testbed and no more exception ... Don't know what happened...

**Comment by elichai** [comment]
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git

**Comment by elichai** [comment]
For me the exceptions are only when it's used with CLion, but maybe dingelish has more exceptions I'm not aware of

**Comment by ZongminGu** [comment]
I tried GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git. It works in the terminal. I suppose you need to debug CLion.
