### ISSUE TITLE
About Time ？

### ISSUE THREAD

**Issue by zhq0918** [intel/linux-sgx#406]
Is the time in enclave the same as out enclave？and how i can check the time in Enclave？ I checkd the developer manual and found the function which named sgx_get_trusted_time, but no example that how print the time. thanks

**Comment by andyzyb** [comment]
If you are looking for wall clock time, it cannot be retrieved from inside Enclave.

**Comment by zhq0918** [comment]
@andyzyb thank you for your answer.
