### ISSUE TITLE
Fatal error with include of c++ libraries in header files of Common folder

### ISSUE THREAD

**Issue by ArnaudCarrere** [intel/linux-sgx#407]
Hi SGX developers,

When I tried to customize one of the SampleCode examples called PowerTransition, I figured out that adding a `#include <string>` in a header file of the Common directory produces a fatal error at compilation : `fatal error: string: No such file or directory compilation terminated.`

It is the same for all C++ libraries, but C libraries like string.h work fine. Unfortunately, I need to use C++ specific libraries like vectors. How can I solve it ? In the Makefile ?

Thanks in advance !

**Comment by andyzyb** [comment]
Which file did you include <string> in?

**Comment by llly** [comment]
Need to add `-I$(SGX_SDK)/include/libcxx` to g++ command, see `Enclave_Include_Paths` in Makefile of sample code.

**Comment by johnvenn** [comment]
in "PowerTransition" Sampleproject, the Common folder is to define some data types that could be used by both untrusted and trusted environment. 

I guess you define a vector in Common/types.h, the types.h file is used for the interface between untrusted/trusted environment, which is included in the "Enclave/Enclave.edl" file, I don't think sgx_edger8r supports C++ types.

**Comment by ArnaudCarrere** [comment]
> Need to add `-I$(SGX_SDK)/include/libcxx` to g++ command, see `Enclave_Include_Paths` in Makefile of sample code.

Here are my include paths : 
`App_Include_Paths := -I$(SGX_SDK)/include -I./Common`
`Enclave_Include_Paths := -I$(SGX_SDK)/include -I$(SGX_SDK)/include/tlibc -I$(SGX_SDK)/include/libcxx -I./Common`

As you can see, libcxx is already included for the enclave but not for the app. Does the problem come from there ?

Unfortunately, when I add `I$(SGX_SDK)/include/libcxx` to the app path, I get a bunch of errors like ` error: unknown type name` or `error: conflicting types for ‘increase_and_seal_data’`...

**Comment by ArnaudCarrere** [comment]
> Which file did you include in?

Here are my include paths in the Makefile :
`App_Include_Paths := -I$(SGX_SDK)/include -I./Common`
`Enclave_Include_Paths := -I$(SGX_SDK)/include -I$(SGX_SDK)/include/tlibc -I$(SGX_SDK)/include/libcxx -I./Common`

**Comment by ArnaudCarrere** [comment]
> in "PowerTransition" Sampleproject, the Common folder is to define some data types that could be used by both untrusted and trusted environment.
> 
> I guess you define a vector in Common/types.h, the types.h file is used for the interface between untrusted/trusted environment, which is included in the "Enclave/Enclave.edl" file, I don't think sgx_edger8r supports C++ types.

Okay... In this issue, they said that C++ types aren't supported, you should be right.
[https://stackoverflow.com/questions/41901884/c-arguments-to-sgx-enclave-edge-functions](url)

But I keep thinking that it should be possible because in the following project, they actually use C++ libraries in the common folder. [https://github.com/olegabu/sgx-netting](url) What do you think about that ?

**Comment by andyzyb** [comment]
SGX SDK supports C++ language and some libraries being used inside enclave, but you can not use the C++ class in EDL file which will generate the code to across Enclave boundary.

**Comment by johnvenn** [comment]
> > in "PowerTransition" Sampleproject, the Common folder is to define some data types that could be used by both untrusted and trusted environment.
> > I guess you define a vector in Common/types.h, the types.h file is used for the interface between untrusted/trusted environment, which is included in the "Enclave/Enclave.edl" file, I don't think sgx_edger8r supports C++ types.
> 
> Okay... In this issue, they said that C++ types aren't supported, you should be right.
> [https://stackoverflow.com/questions/41901884/c-arguments-to-sgx-enclave-edge-functions](url)
> 
> But I keep thinking that it should be possible because in the following project, they actually use C++ libraries in the common folder. [https://github.com/olegabu/sgx-netting](url) What do you think about that ?

I don't think C++ classes/templates supported in edl file, in your case, the "types.h" was included in the edl file. You can define another header in Common folder, e.g. myt.h, there you can define vector that could be used in App and Enclave.
