### ISSUE TITLE
EDL can't define const array

### ISSUE THREAD

**Issue by elichai** [intel/linux-sgx#409]
Hi, I'm passing as an input an array and I wanted it to be clear it's const.
But trying either `[in] const uint8_t pubkey[64]` or `[in] uint8_t const pubkey[64]` returns `unpected token: pubkey` (or `const`).

trying to make it a const pointer to an array returns `Pointer array not allowed - `pubkey' is a pointer array.`

What should I do?

**Comment by llly** [comment]
You can use ` [in, count=64]  const uint8_t *pubkey`

**Comment by elichai** [comment]
But I want the result to be `const pubkey[64]`so whoever looks at the header understand that this should be a pointer to 64 bytes. (array)

**Comment by rodolfoams** [comment]
@elichai That syntax is not legal even if you were using C/C++ directly.
If you want the parameter of the function to be a const pointer to an array of 64 bytes, you should use something similar to what @llly proposed:

`[in, size=64] const uint8_t *pubkey`

**Comment by rodolfoams** [comment]
@elichai The syntax shown by @llly is very clear to me. To pass a const array of 64 bytes as parameter, you should use `[in, size=64] const uint8_t *pubkey`. The `size` option clearly shows that the pointer should have 64 bytes.

**Comment by elichai** [comment]
@rodolfoams @llly I meant that in the resulted header it isn't visible.
you can't see in the `Enclave_X.h` that it's supposed to be a 64 byte array.

**Comment by andyzyb** [comment]
Not all the syntax of C is supported in EDL, it may be different ways to achieve the same effects.  Try to remove "const",  for "in" parameter (as it clearly means) it will not be changed after returned from enclave.

**Comment by elichai** [comment]
I think i'll just wrap the array in a struct and pass a const pointer to that struct.

**Comment by andyzyb** [comment]
Yes, that should work as well.
