### ISSUE TITLE
RemoteAttestation sample lacks verification of MRENCLAVE by the ISV

### ISSUE THREAD

**Issue by brenzi** [intel/linux-sgx#410]
In your RemoteAttestation sample, You lay out the protocol how an ISV can be convinced that the client runs a genuine SGX enclave on SGX HW.

But in the sample, you leave an important part to the reader:
https://github.com/intel/linux-sgx/blob/de4c4816dc8cc92234d880d36e79f074dcc480d3/SampleCode/RemoteAttestation/service_provider/service_provider.cpp#L680

As an ISV I'd like to be sure that the MRENCLAVE included in the MSG3 quote matches *MY* enclave. As I understand, your sample just verifies that *SOME* enclave is genuine, but how can I be sure that it's actually mine and not some fake enclave leaking my provisioning secrets?

I'd expect the build process to tell me the MRENCLAVE for the source code I'm building. Then I can compare that to the MRENCLAVE in the quote.

Or am I mistaken?

**Comment by rodolfoams** [comment]
Hi @brenzi,
you are correct. You still need to know what MRENCLAVE is expected.

You can obtain the MRENCLAVE at build time using the `sgx_sign` utility.
I have a sample code for doing that in [this repository](https://github.com/rodolfoams/sgx-retrieve-identity).

Regards,
Rodolfo

**Comment by ZongminGu** [comment]
below command can help you 
`sgx_sign dump -enclave enclave.signed.so -dumpfile out.log`

**Comment by brenzi** [comment]
cool, thanks
