### ISSUE TITLE
old enclaves fail calling sgx_create_pse_session under HW compilation

### ISSUE THREAD

**Issue by D-Nice** [intel/linux-sgx#412]
We have 1 enclave written in C/C++ and another in Rust back near the end of last year (different and separate implementations). 

Now trying to run them again, and neither apparently works any longer. They make use of the sgx_create_pse_session call and error out on any calls to it. This only occurs in the case of HW compiled binaries (both previous ones from last year that worked fine, and freshly compiled ones). Via sim mode, all works fine.

Quite confident the environments they are running on (NUCs) should be good, as one is in an unchanged state from when the enclaves originally ran on it, with the exact same binaries that ran present, but now error out, and a new one was setup, which still yields the same issues.

Re-compilation and environment setup was done with versions 1.9, 2.5, and 2.3 without success.

The error returned is 0x4001 indicating SGX_ERROR_SERVICE_UNAVAILABLE
but as per the above, all needed drivers, modules, PSW & SDK should be up, as we have double checked them, but the oddity is the breakages occurring on an untouched environment since they last ran just fine.

**Comment by andyzyb** [comment]
Using PSE service needs other software being installed, including iclsclient and DAL software.  It looks like an environment issue.   Do you see any warning message during installing PSW, like icls_init failed?

**Comment by D-Nice** [comment]
I've tried using the following environment via docker: https://hub.docker.com/r/tozd/sgx/dockerfile

which appears to contain all the needed software, in case it is missing from my host environment, and still getting the same issue there.

After, I tried reinstalling PSW, to see if there is any message regarding icls, and in fact it noted that iclsclient or the like was missing. Therafter I uninstalled both sdk and psw on the host sytem, and re-installed them based on the above docker script, which includes both DAL/JHI and iclsclient. Installing the PSW this time around did not yield any warnings. However, still getting the same error code for a pse session.

**Comment by D-Nice** [comment]
After recompiling the enclave, under that environment, it began working. I am guessing if I had recompiled under the docker environment, it would have worked as well.

Thanks for the help!

Still, I'm a bit weary to depend on enclaves if they can end up breaking on an unchanged environment, is this to be expected, in which case anything sealed under MRENCLAVE method should be considered slightly above ephemeral at best? 

Answer to the last question would be appreciated, to understand the stability and resilience one can expect from an enclave/SGX, however, my specific specific problem for this published issue can be considered resolved :)

**Comment by andyzyb** [comment]
It is not expected to break old enclave in the same environment. Unfortunately it is just not clear why the issue occurred.

**Comment by D-Nice** [comment]
Ok, thanks for the update, I'll close this for now, and monitor for any such occurrences in the future and report if it happens to re-occur, with hopefully some more info if it does happen.
