### ISSUE TITLE
Default installation path

### ISSUE THREAD

**Issue by sniperyyc** [intel/linux-sgx#413]
Hi all,

I followed the installation guide in the readme and installed driver/sdk/psw as default. When I tried to compile the sample code, there is one step: "source ${sgx-sdk-install-path}/environment". How can I find out "${sgx-sdk-install-path}/environment" inside my system? Is there any default folder? Any help would be appreciated. 

Thanks!

**Comment by ZongminGu** [comment]
${sgx-sdk-install-path} means the folder where you did install the SDK. In that folder, there is a file named environment.

**Comment by sniperyyc** [comment]
> ${sgx-sdk-install-path} means the folder where you did install the SDK. In that folder, there is a file named environment.

@ZongminGu Thanks a lot for your reply! I used the default option to install the SDK and I did not find the installation path from the Makefile. Is there a way to know where the SDK is installed? Thanks!

**Comment by ZongminGu** [comment]
Please try to find it under "/opt/intel".

**Comment by sniperyyc** [comment]
@ZongminGu Thanks for your help! I have found the corresponding path.
