### ISSUE TITLE
Mutex implementation changes in v1.0.7

### ISSUE THREAD

**Issue by liqinggd** [intel/linux-sgx#416]
Hi, here is a question
I find that you change the mutex implementation.
in v1.0.6, the Mutex is calling sgx_thread_mutex_ interfaces in Intel's sgx_tstdc library. However in v1.0.7，the Mutex implementation is a Rust version of Intel's sgx_thread_mutex. 
I want to know why you change the Mutex implementation?

**Comment by ZongminGu** [comment]
The mutex implementation is below.
https://github.com/intel/linux-sgx/blob/master/common/inc/sgx_thread.h

**Comment by andyzyb** [comment]
@liqinggd  I guess this issue should be posted to rust-sgx-sdk, instead of sgx-sdk?

**Comment by liqinggd** [comment]
Sorry， this issue should be posted to rust-sgx-sdk.
