### ISSUE TITLE
-1 was returned for std::map max_size()

### ISSUE THREAD

**Issue by tyler-lee** [intel/linux-sgx#423]
Hi, I try to get the max_size of std::map. I just printed the `max_size()` value in `SampleCode/Cxx11SGXDemo`:

![image](https://user-images.githubusercontent.com/6070539/61344234-194a6980-a883-11e9-84c3-9298cf9d434d.png)

It showed that `-1` was returned. At first, I guess `-1` means for unlimited, but it does limited after a simple test.

Does SDK support `max_size()` operation? If yes, what does `-1` mean?

**Comment by johnvenn** [comment]
max_size() is a theoretical value, it's not a runtime value, it should be related with the RAM capacity.

**Comment by tyler-lee** [comment]
> max_size() is a theoretical value, it's not a runtime value, it should be related with the RAM capacity.

I tested unordered_map<int, char>, it was limited to no more than 21,000 elements, while there was 32GB free RAM available.

**Comment by johnvenn** [comment]
you can try to expand the heapmaxsize in your enclave config file

**Comment by tyler-lee** [comment]
> you can try to expand the heapmaxsize/stackmaxsize in your enclave config file if you want the unordered_map to contain more elements

It works. Thanks.
