### ISSUE TITLE
sgx_create_pse_session() returns 0x4001.

### ISSUE THREAD

**Issue by anand10717** [intel/linux-sgx#431]
Hi all,

Im using Ubuntu 16.04 and latest linux-sgx-sdk and psw. I have followed build and install guide as in README.

>sudo service aesmd status 

above command retruns following
 

> ● aesmd.service - Intel(R) Architectural Enclave Service Manager
   Loaded: loaded (/lib/systemd/system/aesmd.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-08-13 18:41:17 IST; 3s ago
  Process: 30337 ExecStart=/opt/intel/libsgx-enclave-common/aesm/aesm_service (code=exited, status=0/SUCCESS)
  Process: 30330 ExecStartPre=/bin/chmod 0755 /var/run/aesmd/ (code=exited, status=0/SUCCESS)
  Process: 30328 ExecStartPre=/bin/chown -R aesmd:aesmd /var/run/aesmd/ (code=exited, status=0/SUCCESS)
  Process: 30323 ExecStartPre=/bin/mkdir -p /var/run/aesmd/ (code=exited, status=0/SUCCESS)
  Process: 30318 ExecStartPre=/opt/intel/libsgx-enclave-common/aesm/linksgx.sh (code=exited, status=0/SUCCESS)
 Main PID: 30339 (aesm_service)
   CGroup: /system.slice/aesmd.service
           └─30339 /opt/intel/libsgx-enclave-common/aesm/aesm_service
Aug 13 18:41:16 anand-3985 systemd[1]: Starting Intel(R) Architectural Enclave Service Manager...
Aug 13 18:41:17 anand-3985 systemd[1]: Started Intel(R) Architectural Enclave Service Manager.
Aug 13 18:41:17 anand-3985 aesm_service[30339]: [ADMIN]White List update requested
Aug 13 18:41:17 anand-3985 aesm_service[30339]: [ADMIN]Platform Services initializing
Aug 13 18:41:17 anand-3985 aesm_service[30339]: [ADMIN]Platform Services initialization failed due to DAL error
Aug 13 18:41:17 anand-3985 aesm_service[30339]: The server sock is 0x2051930
Aug 13 18:41:18 anand-3985 aesm_service[30339]: [ADMIN]White list update request successful for Version: 57

In Application while calling sgx_create_pse_session() im getting 0x4001 (AE service did not respond or the requested service is not supported).

Waht are the possible reasons? and solutions?

**Comment by yongtaohu** [comment]
Hi,

To run sgx_create_pse_session(), you need to install Intel(R) Management
Engine Interface and iCLSClient in your system.

Ananda kumar <notifications@github.com> 于2019年8月13日周二 下午9:21写道：

**Comment by anand10717** [comment]
>  install Intel(R) Management Engine Interface and iCLSClient 

are they available for ubuntu 16? seems MEI only available for window OS.

**Comment by andyzyb** [comment]
MEI driver in part of Linux kernel, but iclsclient is not widely available for different OSes.
