### ISSUE TITLE
Interface design in `sgx_ecc256_compute_shared_dhkey`

### ISSUE THREAD

**Issue by LuminousXLB** [intel/linux-sgx#439]
[Code Here](https://github.com/intel/linux-sgx/blob/master/common/inc/sgx_tcrypto.h#L632-L642)

Why `sgx_ec256_private_t` and `sgx_ec256_public_t` wasn't declared `const` in the header? It should not be modified during ECDH computing, isn't it?

**Comment by LuminousXLB** [comment]
The same for [`sgx_ecdsa_sign`](https://github.com/intel/linux-sgx/blob/master/common/inc/sgx_tcrypto.h#L666-L678)

**Comment by andyzyb** [comment]
It could be "const" if not being modified inside function.  No harm, more a coding style issue.
