### ISSUE TITLE
How to proceed with decryption of a long or non-contiguous buffers inside enclave in multiple rounds?

### ISSUE THREAD

**Issue by arefasvadi** [intel/linux-sgx#440]
There are some functions in the SDK that deal with encryption of (maybe long) buffers in multiple rounds that do the bookkeeping in a context struct for AES GCM **(sgx_aes_gcm128_enc_[init,update,get_mac])**. I want to see if I can basically decrypt a big encrypted buffer, block by block (say 64K). I understand that we must verify the MAC for successful decryption. However, I would like to process the blocks of this buffer, and eventually, for the last buffer with the help of context metadata, I can check the condition of the MAC and raise an exception if MAC is not valid. I can relate why such functionality has not been ported to SDK, but I'm wondering if currently, that's feasible with the SDK using functions that exist in **"ipp/ippcp.h"** to have multiple rounds of decryption update.

**Comment by andyzyb** [comment]
Then you probably need to use the IPP function.

**Comment by arefasvadi** [comment]
> Then you probably need to use the IPP function.

Thanks. With the help of [https://software.intel.com/en-us/ipp-crypto-reference-2019-aes-gcm-functions](https://software.intel.com/en-us/ipp-crypto-reference-2019-aes-gcm-functions) I think things are working right now.
