### ISSUE TITLE
Executing SampleEnclave failed

### ISSUE THREAD

**Issue by xiaofo09** [intel/linux-sgx#441]
I am using Ubuntu 16.04.
I installed driver, psw and sdk following version.

sgx_linux_x64_driver_2.5.0_2605efa.bin 
libsgx-enclave-common_2.6.100.51363-xenial1_amd64.deb 
sgx_linux_x64_sdk_2.6.100.51363.bin

I executed environment shell script and SampleEnclave code. but following error occurred.

```
xiaofo@xiaofo-desktop:~/Desktop/sgxsdk/SampleCode/SampleEnclave$ make
make[1]: Entering directory '/home/xiaofo/Desktop/sgxsdk/SampleCode/SampleEnclave'
Fatal error: exception Sys_error("./Enclave_u.h: Permission denied")
Makefile:225: recipe for target 'App/Enclave_u.h' failed
make[1]: *** [App/Enclave_u.h] Error 2
make[1]: Leaving directory '/home/xiaofo/Desktop/sgxsdk/SampleCode/SampleEnclave'
Makefile:184: recipe for target 'all' failed
make: *** [all] Error 2
```

I tried executing it through root privilege. but failed.

```
xiaofo@xiaofo-desktop:~/Desktop/sgxsdk/SampleCode/SampleEnclave$ sudo make
[sudo] password for xiaofo: 
make[1]: Entering directory '/home/xiaofo/Desktop/sgxsdk/SampleCode/SampleEnclave'
make[1]: *** No rule to make target '/opt/intel/sgxsdk/bin/x64/sgx_edger8r', needed by 'App/Enclave_u.h'.  Stop.
make[1]: Leaving directory '/home/xiaofo/Desktop/sgxsdk/SampleCode/SampleEnclave'
Makefile:184: recipe for target 'all' failed
make: *** [all] Error 2
```

I downloaded SGX linux 2.6 from https://download.01.org/intel-sgx/linux-2.6/ubuntu16.04-server/
but driver file name indicates version 2.5

**Comment by johnvenn** [comment]
Please Try to reinstall sdk -- sgx_linux_x64_sdk_2.6.100.51363.bin.

It seems "sgx_edger8r", the proxy tool was missing. This tool is to generate "Enclave_u.h" and "Enclave_t.h"

**Comment by xiaofo09** [comment]
I tried it again. but the error occurred again.

```
xiaofo@xiaofo-desktop:~/Desktop/sgxsdk/SampleCode/SampleEnclave$ make
touch: cannot touch '.config_HW_DEBUG_x64': Permission denied
Makefile:219: recipe for target '.config_HW_DEBUG_x64' failed
make: *** [.config_HW_DEBUG_x64] Error 1
xiaofo@xiaofo-desktop:~/Desktop/sgxsdk/SampleCode/SampleEnclave$ sudo make
make[1]: Entering directory '/home/xiaofo/Desktop/sgxsdk/SampleCode/SampleEnclave'
make[1]: *** No rule to make target '/opt/intel/sgxsdk/bin/x64/sgx_edger8r', needed by 'App/Enclave_u.h'.  Stop.
make[1]: Leaving directory '/home/xiaofo/Desktop/sgxsdk/SampleCode/SampleEnclave'
Makefile:184: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by xiaofo09** [comment]
Ah. I had a mistake.
I installed sdk with root privilege.
it works now.

**Comment by SHUJAA14** [comment]
> Ah. I had a mistake.
> I installed sdk with root privilege.
> it works now.

I am facing the same problem even after reinstalling SDK is there any reason

**Comment by SHUJAA14** [comment]
> Please Try to reinstall sdk -- sgx_linux_x64_sdk_2.6.100.51363.bin.
> 
> It seems "sgx_edger8r", the proxy tool was missing. This tool is to generate "Enclave_u.h" and "Enclave_t.h"

make: *** [Makefile:215: .config_HW_DEBUG_x64] Error 1
I been trying for two weeks to run sdk on my pc i keep getting this error

**Comment by kdping** [comment]
> > Please Try to reinstall sdk -- sgx_linux_x64_sdk_2.6.100.51363.bin.
> > It seems "sgx_edger8r", the proxy tool was missing. This tool is to generate "Enclave_u.h" and "Enclave_t.h"
> 
> make: *** [Makefile:215: .config_HW_DEBUG_x64] Error 1 I been trying for two weeks to run sdk on my pc i keep getting this error

hello, have you solved this error yet? I encountered the same error:
touch: cannot touch '.config_HW_DEBUG_x64': Permission denied
make: *** [Makefile:214: .config_HW_DEBUG_x64] Error 1

**Comment by kdping** [comment]
> > > Please Try to reinstall sdk -- sgx_linux_x64_sdk_2.6.100.51363.bin.
> > > It seems "sgx_edger8r", the proxy tool was missing. This tool is to generate "Enclave_u.h" and "Enclave_t.h"
> > 
> > 
> > make: *** [Makefile:215: .config_HW_DEBUG_x64] Error 1 I been trying for two weeks to run sdk on my pc i keep getting this error
> 
> hello, have you solved this error yet? I encountered the same error: touch: cannot touch '.config_HW_DEBUG_x64': Permission denied make: *** [Makefile:214: .config_HW_DEBUG_x64] Error 1

I make succeeded, use sudo make
