### ISSUE TITLE
Is there any way that we can get a trusted relative time in microseconds or milliseconds?

### ISSUE THREAD

**Issue by LuminousXLB** [intel/linux-sgx#446]
I've found that SGX SDK provides a `sgx_get_trusted_time`, which gets trusted time from the AE service. However, it only returns relative timestamp in seconds, which is far from precise. Apart from that, it is not available on my Ubuntu Desktop, which seems to be the result of lack of iCLSClient and I even cannot find an installation instruction on Intel(R) Management Engine.

Is there any way that we can get a trusted relative time in microseconds or milliseconds in an enclave?

**Comment by andyzyb** [comment]
There is no such function provided.

**Comment by LuminousXLB** [comment]
I'm really sorry to hear that.
But could you please help me find the instruction on installing Intel ME and iCLSClient (or other things I need to successfully run the `sgx_get_trusted_time`)?

**Comment by andyzyb** [comment]
Intel MEI device should be enabled if the kernel is supporting it. There is no other action to take. 

For iclsClient, please send email to sgx_program@intel.com for more information.

**Comment by LuminousXLB** [comment]
> Intel MEI device should be enabled if the kernel is supporting it. There is no other action to take.
> 
> For iclsClient, please send email to [sgx_program@intel.com](mailto:sgx_program@intel.com) for more information.

I sent a mail to sgx_program on Sept.30, but no reply until now. How long will it take for me to get a reply about that?

**Comment by andyzyb** [comment]
Sorry for late response. We are not recommending this features and it may be removed in future release due to limited support of iclsclient for different Linux distros.

**Comment by LuminousXLB** [comment]
> Sorry for late response. We are not recommending this features and it may be removed in future release due to limited support of iclsclient for different Linux distros.

But then will there be other methods that we can use to get a trusted time (evan a relative time is ok) within enclave?

**Comment by andyzyb** [comment]
You can try "rdtsc" instruction, but it may be impacted by CPU frequency, etc., so it won't be a secure time source depending on your usage.   I don't know other ways to get a time source.

**Comment by LuminousXLB** [comment]
> You can try "rdtsc" instruction, but it may be impacted by CPU frequency, etc., so it won't be a secure time source depending on your usage. I don't know other ways to get a time source.

I tried to use this function to call `RDTSC`
``` C++
static inline uint64_t rdtsc(void)
{
    uint32_t hi, lo;

    __asm__ __volatile__("rdtsc"
                         : "=a"(lo), "=d"(hi));

    return (uint64_t(hi) << 32) | uint64_t(lo);
}

```
It works with using SGX and also works in simulation mode. But when I build it with
``` bash
make SGX_MODE=HW SGX_PRERELEASE=1
```
It crashed with a runtime error:
```
[1]    13648 illegal hardware instruction (core dumped)  ./app
```
Could you please help to address the problem?

Here's the output of running [SGX-hardware](https://github.com/ayeks/SGX-hardware)
```
eax: 906ea ebx: 100800 ecx: 7ffafbff edx: bfebfbff
stepping 10
model 14
family 6
processor type 0
extended model 9
extended family 0
smx: 1

Extended feature bits (EAX=07H, ECX=0H)
eax: 0 ebx: 29c6fbf ecx: 40000000 edx: 9c002400
sgx available: 1
sgx launch control: 1

CPUID Leaf 12H, Sub-Leaf 0 of Intel SGX Capabilities (EAX=12H,ECX=0)
eax: 1 ebx: 0 ecx: 0 edx: 241f
sgx 1 supported: 1
sgx 2 supported: 0
MaxEnclaveSize_Not64: 1f
MaxEnclaveSize_64: 24

CPUID Leaf 12H, Sub-Leaf 1 of Intel SGX Capabilities (EAX=12H,ECX=1)
eax: 36 ebx: 0 ecx: 1f edx: 0

CPUID Leaf 12H, Sub-Leaf 2 of Intel SGX Capabilities (EAX=12H,ECX=2)
eax: b0200001 ebx: 0 ecx: 5d80001 edx: 0

CPUID Leaf 12H, Sub-Leaf 3 of Intel SGX Capabilities (EAX=12H,ECX=3)
eax: 0 ebx: 0 ecx: 0 edx: 0

CPUID Leaf 12H, Sub-Leaf 4 of Intel SGX Capabilities (EAX=12H,ECX=4)
eax: 0 ebx: 0 ecx: 0 edx: 0

CPUID Leaf 12H, Sub-Leaf 5 of Intel SGX Capabilities (EAX=12H,ECX=5)
eax: 0 ebx: 0 ecx: 0 edx: 0

CPUID Leaf 12H, Sub-Leaf 6 of Intel SGX Capabilities (EAX=12H,ECX=6)
eax: 0 ebx: 0 ecx: 0 edx: 0

CPUID Leaf 12H, Sub-Leaf 7 of Intel SGX Capabilities (EAX=12H,ECX=7)
eax: 0 ebx: 0 ecx: 0 edx: 0

CPUID Leaf 12H, Sub-Leaf 8 of Intel SGX Capabilities (EAX=12H,ECX=8)
eax: 0 ebx: 0 ecx: 0 edx: 0

CPUID Leaf 12H, Sub-Leaf 9 of Intel SGX Capabilities (EAX=12H,ECX=9)
eax: 0 ebx: 0 ecx: 0 edx: 0
```

**Comment by ZongminGu** [comment]
RDTCS only supported on SGX2 platform.

**Comment by andyzyb** [comment]
This seems because you have old SGX enabled processor which doesn't support "rdtsc" instruction inside enclave.  Sorry, I cannot tell what it is from the output.

RDTSC and RDTSCP are legal inside an enclave for processors that support SGX2 (subject to the value of CR4.TSD).
For processors which support SGX1 but not SGX2, RDTSC and RDTSCP will cause #UD.

**Comment by LuminousXLB** [comment]
> This seems because you have old SGX enabled processor which doesn't support "rdtsc" instruction inside enclave. Sorry, I cannot tell what it is from the output.
> 
> RDTSC and RDTSCP are legal inside an enclave for processors that support SGX2 (subject to the value of CR4.TSD).
> For processors which support SGX1 but not SGX2, RDTSC and RDTSCP will cause #UD.

Thanks for your kind reply. Although I didn't find a way to read CR4.TSD within an enclave, I'm now sure that my processor doesn't support SGX2 according to the result of `CPUID`.
![image](https://user-images.githubusercontent.com/23524048/66378269-ad8d1e00-e9e5-11e9-81e2-6853d4c4d4c1.png)

**Comment by LuminousXLB** [comment]
> Intel MEI device should be enabled if the kernel is supporting it. There is no other action to take.
> 
> For iclsClient, please send email to [sgx_program@intel.com](mailto:sgx_program@intel.com) for more information.

By the way, I used [this sample](https://github.com/torvalds/linux/tree/master/samples/mei) to check the support of Intel MEI device. I post it here in case others may need it. Remember to run it with `sudo`.

**Comment by naishai** [comment]
There are several academic solutions (or suggestions) for getting secure time in SGX. 
You can read one here: https://dl.acm.org/citation.cfm?id=3193119
In the introduction they also discuss other solutions.
