### ISSUE TITLE
sgx_report_attestation_status in v2.7 release does not work

### ISSUE THREAD

**Issue by dingelish** [intel/linux-sgx#457]
Hi there,

I've tested `sgx_report_attestation_status` on several platforms and they all failed with error `SGX_ERROR_SERVICE_UNAVAILABLE`, no matter what the input is. My testbeds include Ubuntu 16.04/18.04 and Centos 7 on:
* Xeon E3-1280v5
* Xeon E3-1280v6
* Xeon E-2186g
* Core i7-8809G
* Core i7-8086K
* Core i9-9900K

All testbeds are set up from scratch, and I think the failure is reproducible.

**Comment by andyzyb** [comment]
Thanks for reporting the issues. Looks it is caused by platform service being removed from the build.  We are looking at how to fix/work around this issue.

**Comment by dingelish** [comment]
Thanks!

We still wonder the solution would be the removal of all platform service APIs, or add the platform service back? If it is going to be removed, what's the alternatives? I think we still needs APIs like `sgx_report_attestation_status`

**Comment by andyzyb** [comment]
I think the solution will be likely keeping the API sgx_report_attetation_status, but removing its dependency on platform service.

**Comment by dingelish** [comment]
Hi @andyzyb , check into see if there is an estimated time of arrival for this update. Thanks!

**Comment by andyzyb** [comment]
A PR #461 merged, pleas try.

**Comment by dingelish** [comment]
Thanks!

The patched version does compile. I overwrote `libepid_quote_service_bundle.so` and `aesm_service` to libsgx-enclave-common with the patched ones. But `sgx_report_attestation_status` returns `SGX_ERROR_INVALID_PARAMETER`. Could you please check if it works with this `platformInfoBlob`? 
```
1502006500000800000606020401800100000000000000000008000009000000020000000000000B5F2061FF31353F4350EB79119F7058B18FC57A19A42CFEF2BC3C8A0957C1BEA2D1451C19A6FD63264962E56A6F5B6E5BFBF9BAB0D6E9991558D3BFB019B4EB3AD2
```
Thanks!

**Comment by dingelish** [comment]
Resolved.

Confirmed that this patch works! Thanks!

btw, will you update the 2.7 release to include this patch? Thanks!

**Comment by andyzyb** [comment]
Will not update Linux 2.7, but we'll make a new release soon to include this fix.

**Comment by dingelish** [comment]
Thank you @andyzyb !
