### ISSUE TITLE
Does the sgx_emmt tool return the total memory consumption of the enclave?

### ISSUE THREAD

**Issue by bronzeMe** [intel/linux-sgx#458]
Hi, 
as described in Intel developer reference,
"Currently the enclave memory measurement tool provides the following two
functions:
1. Get the stack peak usage value for the enclave.
2. Get the heap peak usage value for the enclave."
What does the "heap (or stack) peak usage" means? 
(1)Does  the heap peak usage  indicate  the sum of all allocated heap memory?
(2)Or is it just a max point of all the size of allocating on heap memory? i.e., the enclave may allocate heap memory 5 times, each allocation size is 2KB,3KB,4KB,1KB,6KB, respectively. So the heap peak value is 6KB rather than the sum of them (2+3+4+1+6=16KB)?

**Comment by ZongminGu** [comment]
@bronzeMe "peak" means the max value. For example, one case: allocate 2K->allocate 3K->free 2K->allocate 4K -> allocate 1K-> free 1K-> allocate 6K->free 6K ->free 4K->free 3K. Then the Peak value is:
2+3-2+4+1-1+6=13K.

**Comment by bronzeMe** [comment]
@ZongminGu , thanks a lot for your reply, I got it.
By the way, I want to measure the total memory consumption of the enclave. For example,
when loading  and running an encalve, is there any way to measure the size of EPC memory allocated for this enclave?

**Comment by ZongminGu** [comment]
@bronzeMe I suppose you are using SGX1 hardware, because most of the machine on the market is SGX1 machine. On SGX1 platform, the  EPC size if fixed at the build time. The signing tool tells you the EPC size. Below is one example:

<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>0x40000</StackMaxSize>
    <HeapMaxSize>0x100000</HeapMaxSize>
    <TCSNum>10</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
</EnclaveConfiguration>
tcs_num 10, tcs_max_num 10, tcs_min_pool 1
The required memory is 4153344B.
The required memory is 0x3f6000, 4056 KB.

**Comment by bronzeMe** [comment]
@ZongminGu Yes, my CPU just supports SGX1 version. I also got a sentence"The required memory is 74625024B".
In my view,  the EPC size returned at the build time is based on the Enclave Configuration FIle (.xml), but the actual size of the EPC used by this enclave at runtime may less or larger the build time EPC size, right or not?

**Comment by ZongminGu** [comment]
@bronzeMe Your enclave exactly needs 74625024B EPC. If the free EPC size is less than 74625024B, then you will trigger the EPC swap.

**Comment by andyzyb** [comment]
@bronzeMe, the EPC actually being allocated is the same(calculated) as your specified in config file, but it may not be actually required by your program.  After you measure the heap/stack size with the tool like EMMT, you can change your config file to match the exact need, and get a better EPC size during signing.

**Comment by bronzeMe** [comment]
@andyzyb @ZongminGu Thanks,
How do we get the EPC size at build time,  "StackMaxSize+HeapMaxSize+the size of the executable file (e.g.,enclave.signed.so)"?

**Comment by andyzyb** [comment]
Signing tool will report it during signing process.

**Comment by bronzeMe** [comment]
@andyzyb Thank you, I will try it.
