### ISSUE TITLE
with 2.7 sdk & psw, aesmd does not works.

### ISSUE THREAD

**Issue by Doresimon** [intel/linux-sgx#465]
I have installed v2.7 environment, and I tested all Samples in /opt/intel/sgxsdk/SampleCode, 
everything works well except the `SealedData` sample, it always returned 0x4001 error code,
which means `Platform service is unavalibale`. 

Is that a problem only I have meet?

Also i have noticed that the `aesmd` service won't connect to `jhi` service at v2.7, so how can i use platform service in a right way ?

**Comment by andyzyb** [comment]
Platform service has been removed in the release.   Sorry for still having the sample code of using platform service and it will be removed in the near future.
