### ISSUE TITLE
Error while executing "make psw"

### ISSUE THREAD

**Issue by maaaay** [intel/linux-sgx#466]
Hi,
While I run the command "make psw", the error occurs. Does anyone know what's wrong with that?
Thanks!

make -C psw/ USE_OPT_LIBS=1
make[1]: Entering directory '/home/may/linux-sgx/psw'
make -C uae_service/linux/
make[2]: Entering directory '/home/may/linux-sgx/psw/uae_service/linux'
g++ -Wnon-virtual-dtor -std=c++11 -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -UDEBUG -DNDEBUG -ffunction-sections -fdata-sections -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type -Waddress -Wsequence-point -Wformat-security -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow -Wcast-align -Wconversion -Wredundant-decls -DITT_ARCH_IA64 -fPIC -Werror -Wno-unused-parameter -g -DPROTOBUF_INLINE_NOT_IN_HEADERS=0  -I. -I/home/may/linux-sgx/common -I/home/may/linux-sgx/common/inc -I/home/may/linux-sgx/common/inc/internal  -I/home/may/linux-sgx/psw/ae/common -I/home/may/linux-sgx/psw/ae/inc -I/home/may/linux-sgx/psw/ae/inc/internal -I/opt/intel/sgxsdk/include -I/home/may/linux-sgx/external/epid-sdk -I../../../psw/ae/aesm_service/source/core/ipc -I../uae_wrapper/inc -I../../../psw/ae/aesm_service/source/core/ipc -I/home/may/linux-sgx/psw/ae/aesm_service/source -I/home/may/linux-sgx/psw/ae/aesm_service/source/common -c ../uae_wrapper/src/AEServicesImpl.cpp -o AEServicesImpl.o
cc1plus: error: /opt/intel/sgxsdk/include: No such file or directory [-Werror=missing-include-dirs]
cc1plus: all warnings being treated as errors
Makefile:190: recipe for target 'AEServicesImpl.o' failed
make[2]: *** [AEServicesImpl.o] Error 1
make[2]: Leaving directory '/home/may/linux-sgx/psw/uae_service/linux'
Makefile:52: recipe for target 'uae_service' failed
make[1]: *** [uae_service] Error 2
make[1]: Leaving directory '/home/may/linux-sgx/psw'
Makefile:70: recipe for target 'psw' failed
make: *** [psw] Error 2

**Comment by andyzyb** [comment]
Please look at the README.  You need to install the SDK before building PSW.

**Comment by maaaay** [comment]
> Please look at the README. You need to install the SDK before building PSW.

Thank you!

**Comment by SuviSree** [comment]
i have installed the sdk, and there were no errors in it. still the above error comes for me.

**Comment by bliu40** [comment]
yep, the same. I have installed sdk successfully, however, the same errors show up.

**Comment by strongcourage** [comment]
Hi all, I faced the same issue, and still can't successfully build PSW. Anyone know how to fix this issue ?

**Comment by lzha101** [comment]
What's the error message? Did you source the environment after SDK installation succeeds?

**Comment by strongcourage** [comment]
@lzha101 I had the following error "cc1plus: error: /opt/intel/sgxsdk/include: No such file or directory [-Werror=missing-include-dirs]". I can run the EnclaveTest example, but still can't compile Intel PSW.

**Comment by sunlinkun** [comment]
> 

You should put sgxsdk under the path / opt / Intel /

**Comment by strongcourage** [comment]
@sunlinkun Thank you for your suggestion. I searched for sgxsdk and found a zip file at `linux-sgx/linux/installer/common/sdk/output/sgxsdk_1.0.orig.zip`. I unzip it and copy `include`, `bin` and `buildenv.mk` to `/opt/intel/sgxsdk` (note that I need to create this folder as it doesn't exist). 

Then, I can run the command `make psw DEBUG=1` without any errors :). However, when I build PSW Install by running `make deb_psw_pkg DEBUG=1`, I got errors relevant to shared libraries: `/usr/local/bin/ld: cannot find -lsgx_trts, -lsgx_tstdc, -lsgx_pthread, -lsgx_tcxx, -lsgx_tcrypto, -lsgx_tservice`. Any idea? Thank you.

**Comment by lzha101** [comment]
SGX SDK could be installed to anyplace. Before build PSW or sample code, please refer to https://github.com/intel/linux-sgx#install-the-intelr-sgx-sdk-1 to install the SDK and then source the environment :
`$ source ${sgx-sdk-install-path}/environment`

**Comment by strongcourage** [comment]
@lzha101: thank you very much, it works! :)

**Comment by sho4510** [comment]
I installed PSW with recent trial and error
  $ Source $ {SGX-SDK-Install-Path}/ENVIRONMENT environment setting
I was able to do it by repeating the cd .. in the same terminal and returning to ~/linux-sgx $ and performing make psw. It doesn't seem to respond with a new terminal. Also, do not execute make deb_psw_pkg with psw/ae/le ~/linux-sgx $.
​
