### ISSUE TITLE
How to add printf in Enclave*.cpp?

### ISSUE THREAD

**Issue by hjlee9182** [intel/linux-sgx#468]
![sdfsf](https://user-images.githubusercontent.com/46337218/69408651-cb6ed200-0d4a-11ea-8b84-746828c53fca.PNG)
![2222](https://user-images.githubusercontent.com/46337218/69408655-cd389580-0d4a-11ea-8a5d-19ce0331ff87.PNG)

I want to write code "printf(~~)".
But when I add printf , Make doesn't work.
How to add this?

++) "cout " also doesn't work...
![this](https://user-images.githubusercontent.com/46337218/69409883-2dc8d200-0d4d-11ea-8adc-40a9e878860f.PNG)

**Comment by light1021** [comment]
@hjlee9182 
add this to your Enclave code.
`#include <stdio.h> /* vsnprintf */
#include <string.h>

/* 
 * printf: 
 *   Invokes OCALL to display the enclave buffer to the terminal.
 */
int printf(const char* fmt, ...)
{
    char buf[BUFSIZ] = { '\0' };
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(buf, BUFSIZ, fmt, ap);
    va_end(ap);
    ocall_print_string(buf);
    return (int)strnlen(buf, BUFSIZ - 1) + 1;
}`

You can find this in the [SampleCode](https://github.com/intel/linux-sgx/blob/master/SampleCode/SampleEnclave/Enclave/Enclave.cpp) project.

**Comment by hjlee9182** [comment]
@light1021 
Is '.edl' file is Enclave*.edl file?

**Comment by light1021** [comment]
Yes, exactly

**Comment by hjlee9182** [comment]
@light1021 
But it doesn't work... :(
Make Mode=SIM
![ㄹ라](https://user-images.githubusercontent.com/46337218/69412718-cca3fd00-0d52-11ea-9c63-a86a3abb576f.PNG)

**Comment by light1021** [comment]
There is some error with your function prototype. you should use ```const char*```, other than "const char" before "fmt". 🆒

**Comment by hjlee9182** [comment]
@light1021 
Wow that's work!
But I have one more question?
Do I have to add all the other functions like this? ( like atoi..)

**Comment by light1021** [comment]
You can refer to this document [Intel_SGX_Developer_Reference_Linux_2.7.1_Open_Source.pdf](https://download.01.org/intel-sgx/sgx-linux/2.7.1/docs/Intel_SGX_Developer_Reference_Linux_2.7.1_Open_Source.pdf). It lists functions which are not supported inside SGX Enclaves in it's Appendix.

**Comment by hjlee9182** [comment]
@light1021 
Very Thanks. When I have question again . I did again. Thanks!!
