### ISSUE TITLE
Issues with SealedData Example

### ISSUE THREAD

**Issue by adilahmad17** [intel/linux-sgx#475]
Hey, 

I was trying to test SGX's trusted time and monotonic counters using the SealedData example. From a previous issue (https://github.com/intel/linux-sgx/issues/93), I realized that you have to install JHI for this to work. Therefore, I installed JHI using the following Intel repo (https://github.com/intel/dynamic-application-loader-host-interface). Then, I re-installed the SGX SDK entirely. However, I still get the same error:

````
Replay Protected DRM operation:
cannot get platform service capability, error code = 0x4001
Initialization the DRM failed.

Replay Protected DRM update limitation:
cannot get platform service capability, error code = 0x4001
Initialization the DRM failed.
````
I used `lsmod` to ensure that `mei` is installed on my `4.4.0-165-generic #193-Ubuntu SMP` machine. 

Is there something that I am missing?

Any help regarding this is much appreciated.

Thanks!
Adil

**Comment by andyzyb** [comment]
Sorry, platform service is no longer supported since 2.7 release

**Comment by adilahmad17** [comment]
Thanks for the reply. Is it possible to use platform service with the older versions?
I am trying the version 2.3 and I get the same error.

Also, can you tell me why PS has been discontinued? Is there an alternative for
trusted timers and counters?

**Comment by andyzyb** [comment]
Platform service is depending on iclsclient which is not available now, so even you use old release, you cannot get the iclsclilent software.   I don't know the alternatives.

**Comment by adilahmad17** [comment]
Hmm, thanks for the information. Any ideas as to why this has been discontinued? It seems like an important building block for lots of interesting ideas.

I was wondering whether a developer could write their own code to sort of emulate the platform service enclave and securely communicate with the ME firmware? 

Sorry for the many questions!

**Comment by andyzyb** [comment]
Mainly the reason I mentioned above, lacking of iclsclient support makes this feature unusable.  The same problem you'll encounter to write your own platform service enclave because it won't be able to create a secure channel between platform service enclave and ME firmware.

**Comment by adilahmad17** [comment]
Okay, I understand. Thanks a bunch for all your replies! :)

**Comment by wsjswy** [comment]
> Mainly the reason I mentioned above, lacking of iclsclient support makes this feature unusable. The same problem you'll encounter to write your own platform service enclave because it won't be able to create a secure channel between platform service enclave and ME firmware.

It means  Sealeddata function can not be used now?

**Comment by andyzyb** [comment]
Right, it will be removed soon.

**Comment by wsjswy** [comment]
> Right, it will be removed soon.

Is there any other way to save data outside the enclave?

**Comment by andyzyb** [comment]
You can use sgx_seal_data API to seal the data inside Enclave, and pass that data outside the enclave to save.
