### ISSUE TITLE
Eclipse version

### ISSUE THREAD

**Issue by patricia93sousa** [intel/linux-sgx#48]
Hi. I'm with a lot of troubles to put this working with Eclipse. I think that it was because of the versions... You know how can I find the versions that you recommend?

**Comment by haitaohuang** [comment]
Eclipse Mars is supported by the SGX plugin, it can be found here: http://www.eclipse.org/downloads/packages/release/mars/r

**Comment by patricia93sousa** [comment]
And the version of eclipse pde ? I'm getting errors in the build.sh that
refers to the eclipse pde.

Em 01/12/2016 4:02 da tarde, "haitaohuang" <notifications@github.com>
escreveu:

**Comment by haitaohuang** [comment]
https://github.com/01org/linux-sgx/blob/master/Linux_SGXEclipsePlugin/readme.txt

**Comment by patricia93sousa** [comment]
Yes i know , but i dont know where i can get this version. I make a lot of
search. Thanks :)

Em 01/12/2016 4:08 da tarde, "haitaohuang" <notifications@github.com>
escreveu:

https://github.com/01org/linux-sgx/blob/master/Linux_
SGXEclipsePlugin/readme.txt

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/01org/linux-sgx/issues/48#issuecomment-264214966>, or mute
the thread

**Comment by haitaohuang** [comment]
You should be able to install from within Eclipse Mars via update site:http://download.eclipse.org/eclipse/updates/4.5/
If you click the contents link on that page from browser, you can see it down in plugins directory
That url should be the default site url you have in Mars.

**Comment by patricia93sousa** [comment]
One question, this works with a simulation mode? I.e., I doesn't have an SGX processor compatible

**Comment by patricia93sousa** [comment]
After the installation of Eclipse Mars and PDE I got the same error:

Caused by: /home/patriciarvsousa/linux-sgx/Linux_SGXEclipsePlugin/build_config/allElements.xml:16: The following error occurred while executing this line:
/home/patriciarvsousa/eclipse/plugins/org.eclipse.pde.build_3.9.100.v20150521-1524/scripts/genericTargets.xml:109: java.lang.IllegalArgumentException: invalid version "1.0.0.v.1": invalid qualifier "v.1"
	at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:568)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:443)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.eclipse.ant.internal.core.ant.EclipseSingleCheckExecutor.executeTargets(EclipseSingleCheckExecutor.java:34)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
	... 62 more

Can anyone help me with this?
I show more details of the logs if it is necessary.

Thanks.

**Comment by xiangquanliu** [comment]
This is caused by the invalid qualifier. Here is the document about how to set the qualifier.
http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Ftasks%2Fpde_version_qualifiers.htm&cp=4_2_1_5

**Comment by patricia93sousa** [comment]
I don't know if it is correct but I set the qualifier something like
"qualifier="v12345"" , and this generates to me the folder that it is
supposed: "updateside" under the build_directory.
Now, I'm trying to import the zip file to the eclipse to install the plugin
but I got:

"Unexpected exception while loading
jar:file:/home/patricia/IntelSGXLinux/linux-sgx/Linux_SGXEclipsePlugin/build_directory/updatesite/sgx-eclipse-plugin/Intel-sgx-eclipse-plugin.zip!/.
Unexpected exception while loading
jar:file:/home/patricia/IntelSGXLinux/linux-sgx/Linux_SGXEclipsePlugin/build_directory/updatesite/sgx-eclipse-plugin/Intel-sgx-eclipse-plugin.zip!/.
Format "format(n[.n=0;[.n=0;[.S=[A-Za-z0-9_-];='';]]])" was unable to parse
1.6.100.v.1"


I don't iknow how to solve this type of problems. Can you help me? I don't
know if it is something related with the plugin.



Patrícia Sousa

2016-12-02 2:41 GMT+00:00 xiangquanliu <notifications@github.com>:

**Comment by xiangquanliu** [comment]
Hi,
It seems that the qualifier is still "v.1". So could you please show how to set the environment variable "RELEASE_ID" before running the build.sh? 

Thanks.

**Comment by svartkanin** [comment]
Hi,
I'm also facing some issues installing the SGX Plugin in Eclipse.
I installed the correct version of Eclipse, PDE and was able to build the .zip successfully.
But When trying to install the plugin in Eclipse under "Install New Software -> adding the .zip -> select SGX Eclipse Plugin (1.6.100.1)", Eclipse does not seem to respond anymore, it just keeps on loading!?

**Comment by xiangquanliu** [comment]
Hi,
I don't know if this issue only exists in installing SGX plugin or also in other eclipse plugin. So I can only give a common suggestion - try to run eclipse with "-clean" parameter and then check if this issue is still there.

**Comment by llly** [comment]
No more reports for this issue.
