### ISSUE TITLE
Missing packages in 2.8 Linux release

### ISSUE THREAD

**Issue by dingelish** [intel/linux-sgx#483]
Hi there,

It seems for Ubuntu `bionic`, two packages are missing in 2.8 release: libsgx-dcap-default-qpl-dbg, and libsgx-dcap-ql-dbg.

```
The following packages have unmet dependencies:
 libsgx-dcap-default-qpl-dbg : Depends: libsgx-dcap-default-qpl (= 1.3.101.3-bionic1) but 1.4.100.4-bionic1 is to be installed
 libsgx-dcap-ql-dbg : Depends: libsgx-dcap-ql (= 1.3.101.3-bionic1) but 1.4.100.4-bionic1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

Are these two packages no longer provided? Thanks!

**Comment by andyzyb** [comment]
Please install libsgx-dcap-default-qpl-dbgsym and libsgx-dcap-ql-dbgsym, instead of *-dbg.
