### ISSUE TITLE
Problem running SGX examples (Sample Code)

### ISSUE THREAD

**Issue by cezane** [intel/linux-sgx#494]
I followed these instructions to install the driver, the psw and the sdk (Ubuntu 18.04): https://download.01.org/intel-sgx/sgx-linux/2.8/docs/Intel_SGX_Installation_Guide_Linux_2.8_Open_Source.pdf

When I run in the SIM mode, the SampleEnclave code works:
```
/workspace/linux-sgx/SampleCode/SampleEnclave$ ./app
Checksum(0x0x7fff104286b0, 100) = 0xfffd4143
Info: executing thread synchronization, please wait...  
Info: SampleEnclave successfully returned.
Enter a character before exit ...
```

When I run in the HW mode, I get the following error:
```
~/workspace/linux-sgx/SampleCode/SampleEnclave$ ./app
Info: Please make sure SGX module is enabled in the BIOS, and install SGX driver afterwards.
Error: Invalid SGX device.
Enter a character before exit ...
```

Can anyone help?

**Comment by llly** [comment]
Please check SGX option in BIOS menu. It should be Enabled or Software Control. Then uninstall and install SGX driver.

**Comment by cezane** [comment]
I had checked this option before (software controlled) and also reinstalled the SGX driver, but without success.

**Comment by jsraynor** [comment]
If you do not have an "Enabled" option in your BIOS that you can manually select, you will probably need some software that actually Enables SGX if currently in Software Controlled mode.  See this thread for more info:  https://github.com/intel/linux-sgx/issues/354

**Comment by LalaNguyen** [comment]
Hi,

I also encountered the same error after installed sgx v2.8 and tried to run the SampleEnclave with hardware debug mode. I used to install sgx v2.4 on the same computer without this "no SGX device issues".
I had checked the SGX "ENABLED" option in BIOS and also reinstalled the driver, the sdk and the psw a couple times without success. I tried the installation procedure on both 18.04 and 16.04. My platform information for ubuntu 16.04 is as followed:

$uname -r
4.15.0-50-generic

$lsmod | grep sgx
isgx                   49152  0

$modinfo isgx x
filename:       /lib/modules/4.15.0-50-generic/kernel/drivers/intel/sgx/isgx.ko
license:        Dual BSD/GPL
version:        2.6.0
author:         Jarkko Sakkinen <jarkko.sakkinen@linux.intel.com>
description:    Intel SGX Driver
srcversion:     277B61CFBD922CCE608DD38
alias:          acpi*:INT0E0C:*
depends:        
retpoline:      Y
name:           isgx
vermagic:       4.15.0-50-generic SMP mod_unload 

$dmesg | grep sgx
[  798.430778] isgx: loading out-of-tree module taints kernel.
[  798.430804] isgx: module verification failed: signature and/or required key missing - tainting kernel
[  798.431368] intel_sgx: Intel SGX Driver v2.6.0
[  798.431380] intel_sgx INT0E0C:00: EPC bank 0x70200000-0x75f80000
[  798.432287] intel_sgx: second initialization call skipped

I build the sdk and the psw that are cloned directly from the github folder. I build them with debug information. My commands for installing the sdk and psw are as follows:

#SDK
sudo ./linux/installer/bin/sgx_linux_x64_sdk_2.8.100.3.bin

#PSW
sudo dpkg -i ./linux/installer/deb/libsgx-enclave-common/libsgx-enclave-common_2.8.100.3-xenial1_amd64.deb ./linux/installer/deb/libsgx-launch/libsgx-launch_2.8.100.3-xenial1_amd64.deb ./linux/installer/deb/libsgx-uae-service/libsgx-uae-service_2.8.100.3-xenial1_amd64.deb ./linux/installer/deb/libsgx-urts/libsgx-urts_2.8.100.3-xenial1_amd64.deb ./linux/installer/deb/sgx-aesm-service/sgx-aesm-service_2.8.100.3-xenial1_amd64.deb ./linux/installer/deb/libsgx-epid/libsgx-epid_2.8.100.3-xenial1_amd64.deb ./linux/installer/deb/libsgx-quote-ex/libsgx-quote-ex_2.8.100.3-xenial1_amd64.deb

**Comment by LalaNguyen** [comment]
Ok I fixed my issue. I forgot to install both the libsgx-ae-le (launch enclave) and the libsgx-aesm-launch-plugin. It seems the plugin is required because the problem persists even when the libsgx-ae-le was solely installed. After installing the twos, I can run the SampleEnclave in hardware debug mode.

**Comment by andyzyb** [comment]
Good to know it is resolved.
