### ISSUE TITLE
when I use sgx_rijndael128GCM_decrypt to decrypt ciphertext,  undefined reference to `consttime_memequal'

### ISSUE THREAD

**Issue by penpendandan** [intel/linux-sgx#499]
hello,
when I use sgx_rijndael128GCM_decrypt founctions, I encountered the following bug:
/home/dandan/sgxsdk/sgxsdk/lib64/libsgx_tcrypto.a(sgx_aes_gcm.o): In function `sgx_rijndael128GCM_decrypt':
sgx_aes_gcm.cpp:(.text.sgx_rijndael128GCM_decrypt+0x293): undefined reference to `consttime_memequal'
collect2: error: ld returned 1 exit status

I use cmake to build my program,the CMakeLists.txt in Enclave is as follows:
`IF(${SGX_MODE} EQUAL HW)
SET(Trts_Library_Name sgx_trts)
SET(Service_Library_Name sgx_tservice)
ELSE()
SET(Trts_Library_Name sgx_trts_sim)
SET(Service_Library_Name sgx_tservice_sim)
ENDIF()

SET(Crypto_Library_Name sgx_tcrypto)
FILE(GLOB_RECURSE Enclave_C_Files "*.c")
INCLUDE_DIRECTORIES(${PROJECT_SOURCE_DIR}/Include ${PROJECT_SOURCE_DIR}/Enclave ${SGX_SDK}/include ${SGX_SDK}/include/tlibc $(SGX_SDK)/include/libcxx)
SET(Enclave_C_Flags "${SGX_COMMON_CFLAGS} -nostdinc -fvisibility=hidden -fpie -ffunction-sections -fdata-sections -fstack-protector-strong")
SET(Enclave_Cpp_Flags "${Enclave_C_Flags} -std=c++11 -nostdinc++")
SET(Enclave_Link_Flags "${SGX_COMMON_CFLAGS} -Wl,--no-undefined -nostdlib -nodefaultlibs -nostartfiles -L${SGX_LIBRARY_PATH} -Wl,--whole-archive -lsgx_tswitchless -l${Trts_Library_Name} -Wl,--no-whole-archive -Wl,--start-group -lsgx_tstdc -lsgx_tcxx -l${Crypto_Library_Name} -l${Service_Library_Name} -Wl,--end-group -Wl,-Bstatic -Wl,-Bsymbolic -Wl,--no-undefined -Wl,-pie,-eenclave_entry -Wl,--export-dynamic -Wl,--defsym,__ImageBase=0 -Wl,--gc-sections -Wl,--version-script=${PROJECT_SOURCE_DIR}/Enclave/Enclave.lds")

SET(CMAKE_CXX_STANDARD 11)
SET(CMAKE_C_FLAGS ${Enclave_C_Flags})
SET(CMAKE_CXX_FLAGS ${Enclave_Cpp_Flags})
SET(CMAKE_SHARED_LINKER_FLAGS ${Enclave_Link_Flags})
LINK_DIRECTORIES(${SGX_LIBRARY_PATH})
ADD_LIBRARY(enclave SHARED ${Enclave_C_Files} ../build/Enclave_t.c)
TARGET_LINK_LIBRARIES(enclave ${Trts_Library_Name})
TARGET_LINK_LIBRARIES(enclave sgx_tpbc sgx_tgmp)
TARGET_LINK_LIBRARIES(enclave sgx_tcxx sgx_tstdc ${Crypto_Library_Name} ${Service_Library_Name})
`
I found consttime_memequal founction in sdk/tlibc/string/consttime_memequal.c, so how do I fixed it? thanks!

**Comment by yhu14** [comment]
This symbol is in libsgx_tstdc.a. You can check if this library is linked correctly, and you may try to put libsgx_tstdc.a behind of cryto library in Makefile, sometimes static library sequence matters.

**Comment by penpendandan** [comment]
ok,Thanks! this problem has been fixed. I switched the order of static library.







At 2020-02-20 21:44:49, "Hu Yongtao" <notifications@github.com> wrote:

This symbol is in libsgx_tstdc.a. You can check if this library is linked correctly, and you may try to put libsgx_tstdc.a behind of cryto library in Makefile, sometimes static library sequence matters.
