### ISSUE TITLE
the official getting start code of DNNL can not run on SGX 

### ISSUE THREAD

**Issue by yy738686337** [intel/linux-sgx#501]
I can not run the code on SGX in **simulation** mode on **VPS**.
Error occurs on this line:
![image](https://user-images.githubusercontent.com/18733845/75115031-2f7c9b80-5696-11ea-96b5-4199d9408810.png)
when I press 'step over' then got this error:
![image](https://user-images.githubusercontent.com/18733845/75115064-6b176580-5696-11ea-899a-c9b4c43a15d4.png)
This is the configure file of Enclave:
![image](https://user-images.githubusercontent.com/18733845/75115085-9601b980-5696-11ea-8b05-3ce27cd9d14f.png)
I would appreciate it if you could help me solving this problem.
Thank u

**Comment by lzha101** [comment]
From your configuration file, seems you didn't configure any reserved memory. Would you please change the configuration file following the provided sample [Enclave.config.xml](https://github.com/intel/linux-sgx/blob/master/SampleCode/SampleDNNL/Enclave/Enclave.config.xml) and try again?

**Comment by yy738686337** [comment]
> From your configuration file, seems you didn't configure any reserved memory. Would you please change the configuration file following the provided sample [Enclave.config.xml](https://github.com/intel/linux-sgx/blob/master/SampleCode/SampleDNNL/Enclave/Enclave.config.xml) and try again?

It works! Thank you very much. It was my fault. I didn't read the instructions carefully.

**Comment by CharlesLiu7** [comment]
@Otis4631 @lzha101 I also run `SampleDNNL` in official SampleCode successfully in simulation mode, but failed in hardware mode. Here is my error message:
