### ISSUE TITLE
Third-party changes to rts_cmd.h may conflict with Intel changes

### ISSUE THREAD

**Issue by carmenyh** [intel/linux-sgx#504]
Asylo currently adds ECALL commands to [common/inc/internal/rts_cmd.h](https://github.com/intel/linux-sgx/blob/e0a51c4974fc1207eebc95f400db4fb4c799eba6/common/inc/internal/rts_cmd.h#L32), as seen [here](https://github.com/google/asylo/blob/421c663bd2cef12aa8c6e0cef5b9b551bfecc4c5/asylo/distrib/sgx_x86_64/linux_sgx_2_6.patch#L305). When updating to use linux-sgx 2.8, the Asylo macros defined constants that conflicted with [the macro Intel added for 2.8](https://github.com/intel/linux-sgx/blob/e0a51c4974fc1207eebc95f400db4fb4c799eba6/common/inc/internal/rts_cmd.h#L41). Could a range of these constants be set aside for third-party use to prevent future conflicts?

**Comment by andyzyb** [comment]
We probably can define a reserved area for third-party, like

#define RESERVED_FOR_3RD_PARTY_START  -1000
#define RESERVED_FOR_3RD_PARTY_END     -2000

**Comment by andyzyb** [comment]
@carmenyh  any thought for the proposal?

**Comment by carmenyh** [comment]
The reserved area works, but would it be possible to have the range start at 100? That's where Asylo moved the constants to in the [patch for linux-sgx 2.8](https://github.com/google/asylo/blob/46377c10878253823d959ba67e60f5aeca5ab206/asylo/distrib/sgx_x86_64/linux_sgx_2_8.patch#L315).

**Comment by andyzyb** [comment]
Sure. We can do this:  -100 ~ -1000
