### ISSUE TITLE
Sealing API vs Protected FS with auto-keys

### ISSUE THREAD

**Issue by dimakuv** [intel/linux-sgx#507]
I am trying to understand the difference between the sealing API and the Protected FS API.

In particular, it looks like the SGX application may use any of the two APIs to achieve the same result:
- `sgx_seal_data()` and others from `libtSeal` (https://github.com/intel/linux-sgx/tree/master/sdk/tseal)
- `sgx_fopen_auto_key()` and others from Protected FS (https://github.com/intel/linux-sgx/blob/master/common/inc/sgx_tprotected_fs.h)

There are of course small differences in the APIs themselves and in the metadata stored in files. However, I fail to see any benefit of using `libtSeal` in comparison to Protected FS.

Is `libtSeal` only for legacy code and may be considered deprecated? Why I as a developer would *not* want to use Protected FS for sealing? Can I assume that for new applications, I should always use Protected FS and ignore `libtSeal`?

**Comment by omeg** [comment]
AFAIK:
- `libtSeal` allows you to use `SGX_KEYPOLICY_MRSIGNER` or `SGX_KEYPOLICY_MRENCLAVE` while ProtectedFS only uses `SGX_KEYPOLICY_MRSIGNER`.
- ProtectedFS has slightly bigger overhead due to complicated file structure, `libtSeal` just encrypts the whole data blob with a minimal header.
- `libtSeal` is limited to `uint32_t` as data size while ProtectedFS uses `size_t` (didn't test whether very large sizes actually work though).

**Comment by dimakuv** [comment]
Thank you @omeg for comments! Hopefully, the original developers and maintainers could also chime in.

The first point seems like an implementation issue. I guess ProtectedFS could easily add this option.

The third point means that ProtectedFS is the only option for large files.

The second point is the most interesting: ProtectedFS seems to have more performance overhead, more space overhead (to store metadata per block), and more TCB overhead. I wonder if these overheads are significant.

**Comment by andyzyb** [comment]
ProtectedFS is to provide a similar file operation APIs (sgx_fopen, sgx_fread, etc.) with encryption for enclave. So the write/read will eventually reach the real file on the system. 

While Seal API is just to encrypt/decrypt the data inside enclave, and you need to handle the save/restore (typically thought some ECALL/OCALL) if it is necessary.  

Basically they are different levels of abstraction.

**Comment by dimakuv** [comment]
Thanks you @andyzyb!

However, from the application developer point of view, the only meaningful usage of the Seal API is to store something to disk, isn't it? I see no point in using Seal API to e.g. keep data in untrusted RAM or send it on the network (it is meaningless for the network case since only the same platform can unseal it).

If the above is correct, then it looks like Seal API is superseded by ProtectedFS for the only usage it is relevant -- keeping secret data on disk. Or is there some other usage that I'm missing?

**Comment by andyzyb** [comment]
I think it provides more choices with this kind of low level APIs (Sealing API).  In most of cases, yes, the data needs to be persistent.  But there are other case, for example, you can send encrypted data (like temporary data) from one enclave to the other enclave (on the same machine) and it can just be passed through memory and not through disk.

**Comment by dimakuv** [comment]
@andyzyb Thanks for great explanations!

Indeed, I overlooked this case. Thanks again, closing this issue.
