### ISSUE TITLE
unrecognized option -mlfence-after-load

### ISSUE THREAD

**Issue by lengyijun** [intel/linux-sgx#511]
```
as: unrecognized option '-mlfence-after-load=yes'
```

build on Ubuntu18.04.2 x64 
how can I fix it?

```
$ g++ --version
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
```

**Comment by troublesprouter** [comment]
I'm getting the same error. Was this fixed?

**Comment by troublesprouter** [comment]
Thanks. I'm coming across all sorts of errors (including https://github.com/intel/linux-sgx/issues/945#issue-1665369763) in trying to set up this repo with ECDSA capabilities together with Apache Teaclave (incubating) SGX SDK.

I'm using Ubuntu 20.04 and I've tried many permutations including both docker approaches, several attempts at manual installation, etc.

I can spin up another VM with the right operating system just for this task.

What's the simplest way to get linux-sgx with ECDSA signing + [incubator-teaclave-sgx-sdk](https://github.com/apache/incubator-teaclave-sgx-sdk) going?

Much appreciated.
