### ISSUE TITLE
Missing dbgsym packages for 2.9+xenial

### ISSUE THREAD

**Issue by dingelish** [intel/linux-sgx#514]
It seems Intel released the *-dbgsym packages for ubuntu 16.04
https://download.01.org/intel-sgx/sgx-linux/2.9/distro/ubuntu16.04-server/debian_pkgs/debug

But they are not listed in the offical repo
https://download.01.org/intel-sgx/sgx_repo/ubuntu/dists/xenial/main/binary-amd64/Packages

Is this normal? should we expect the dbgsym packages listed or not? Thanks!

**Comment by andyzyb** [comment]
dbgsym packages are need for Ubuntu 18.04, but not needed for Ubuntu 16.04.
