### ISSUE TITLE
Why does abort() raise SIGILL?

### ISSUE THREAD

**Issue by cstwhh** [intel/linux-sgx#517]
https://github.com/intel/linux-sgx/blob/0280f97a0766ab028d7fc0132f5251e5401b89e5/sdk/trts/linux/trts_pic.S#L581

abort () will call the instruction `ud2`, which will raise a SIGILL instead of SIGABRT. Why is abort () implemented this way?

**Comment by andyzyb** [comment]
Below is a typical implementation for abort in Linux:

       The abort() function first unblocks the SIGABRT signal, and then
       raises that signal for the calling process (as though raise(3) was
       called).  This results in the abnormal termination of the process
       unless the SIGABRT signal is caught and the signal handler does not
       return (see longjmp(3)).

It involves syscalls in raise function, but syscall is not supported inside Enclave and there is no easy way to send a signal to the process from inside Enclave.  So using ud2 is a simple way to mimic the behavior of abort.
