### ISSUE TITLE
Ubuntu 20.04 LTS prebuilt support?

### ISSUE THREAD

**Issue by jasl** [intel/linux-sgx#523]
Ubuntu 20.04 LTS will release this month, does SGX SDK has plan to support it before it released??

I tried to install prebuilt deb on 19.10 and meet dependencies conflicts.

**Comment by andyzyb** [comment]
Not planned to support Ubuntu 20.04 before its official release.  It may take some time to verify on the new OS version and make changes to the code base.

**Comment by dingelish** [comment]
You may refer to my patches to support 20.04 :-)

https://github.com/apache/incubator-teaclave-sgx-sdk/commit/a740c3a40dcdcd8282f75ddc7cfc2ab9ae26f0c4

**Comment by andyzyb** [comment]
@dingelish thanks for the patch.  I think now the major issue for Ubuntu 20.04 is #515.

**Comment by kaimast** [comment]
> You may refer to my patches to support 20.04 :-)
> 
> [apache/incubator-teaclave-sgx-sdk@a740c3a](https://github.com/apache/incubator-teaclave-sgx-sdk/commit/a740c3a40dcdcd8282f75ddc7cfc2ab9ae26f0c4)

Was this ever merged into this repo? I am still getting build errors on 20.04.

**Comment by lzha101** [comment]
@kaimast  Are you using the latest code release? Suppose the 2.10 release could support building on 20.04.

**Comment by kaimast** [comment]
I still get this error when building. My installation has GCC 9.3.

```
g++ -c -Wnon-virtual-dtor -std=c++11 -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -UDEBUG -DNDEBUG -ffunction-sections -fdata-sections -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type -Waddress -Wsequence-point -Wformat-security -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow -Wcast-align -Wconversion -Wredundant-decls -DITT_ARCH_IA64 -ffreestanding -nostdinc -fvisibility=hidden -fpie -fno-strict-overflow -fno-delete-null-pointer-checks -B/usr/local/bin -mindirect-branch-register -fcf-protection=none -mfunction-return=thunk-extern -fno-plt -Wa,-mlfence-after-load=yes -Wa,-mlfence-before-indirect-branch=memory -Wa,-mlfence-before-ret=shl -nostdinc++ -Werror -fno-exceptions -fno-rtti -I/home/kai/linux-sgx/common/inc/internal -I/home/kai/linux-sgx/common/inc -I/home/kai/linux-sgx/common/inc/tlibc -I/home/kai/linux-sgx/common/../sdk/trts -I/home/kai/linux-sgx/psw sethread_mutex.cpp -o sethread_mutex.o
as: unrecognized option '-mlfence-after-load=yes'
```
Removing these option from buildenv.mk "fixes" it, but that does not seem safe.

**Comment by kaimast** [comment]
Also, when building the PSW I get this error, but I think it might be a separate bug:
```
./linux/installer/bin/build-installpkg.sh psw
Create the dest dir
Error !!!: src file not exist /home/kai/linux-sgx/build/linux/libsgx_qe3.signed.so
make: *** [Makefile:99: psw_install_pkg] Error 1
```

**Comment by fqiu1** [comment]
1. You need to run the download_prebuilt.sh to get the updated toolset to support the new options.
2. The second issue is a bug and you can following command in linux-sgx repo to workaround it:
```bash
./external/dcap_source/QuoteGeneration/download_prebuilt.sh && cp ./external/dcap_source/QuoteGeneration/psw/ae/data/prebuilt/libsgx_qe3.signed.so build/linux
```

**Comment by LihengChen9** [comment]
> I still get this error when building. My installation has GCC 9.3.
> 
> ```
> g++ -c -Wnon-virtual-dtor -std=c++11 -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -UDEBUG -DNDEBUG -ffunction-sections -fdata-sections -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type -Waddress -Wsequence-point -Wformat-security -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow -Wcast-align -Wconversion -Wredundant-decls -DITT_ARCH_IA64 -ffreestanding -nostdinc -fvisibility=hidden -fpie -fno-strict-overflow -fno-delete-null-pointer-checks -B/usr/local/bin -mindirect-branch-register -fcf-protection=none -mfunction-return=thunk-extern -fno-plt -Wa,-mlfence-after-load=yes -Wa,-mlfence-before-indirect-branch=memory -Wa,-mlfence-before-ret=shl -nostdinc++ -Werror -fno-exceptions -fno-rtti -I/home/kai/linux-sgx/common/inc/internal -I/home/kai/linux-sgx/common/inc -I/home/kai/linux-sgx/common/inc/tlibc -I/home/kai/linux-sgx/common/../sdk/trts -I/home/kai/linux-sgx/psw sethread_mutex.cpp -o sethread_mutex.o
> as: unrecognized option '-mlfence-after-load=yes'
> ```
> 
> Removing these option from buildenv.mk "fixes" it, but that does not seem safe.

Maybe you miss this step  
$ sudo cp external/toolset/{current_distr}/{as,ld,ld.gold,objdump} /usr/local/bin
$ which as ld ld.gold objdump

**Comment by jasl** [comment]
Since Ubuntu 20.04.1 released several days, any update about prebuilt PSW deb?

**Comment by LihengChen9** [comment]
> Since Ubuntu 20.04.1 released several days, any update about prebuilt PSW deb?

(in linux-sgx2.10)just add some check for gcc version, in order to avoid some conflict about compile options.  More details can be found in commit

**Comment by jasl** [comment]
> > Since Ubuntu 20.04.1 released several days, any update about prebuilt PSW deb?
> 
> (in linux-sgx2.10)just add some check for gcc version, in order to avoid some conflict about compile options. More details can be found in commit

Sorry, I mean push prebuilts to https://download.01.org/intel-sgx/sgx-linux/2.11/distro/

**Comment by PU007** [comment]
> 构建时仍然出现此错误。我的安装具有GCC 9.3。
> 
> ```
> g++ -c -Wnon-virtual-dtor -std=c++11 -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -UDEBUG -DNDEBUG -ffunction-sections -fdata-sections -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type -Waddress -Wsequence-point -Wformat-security -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow -Wcast-align -Wconversion -Wredundant-decls -DITT_ARCH_IA64 -ffreestanding -nostdinc -fvisibility=hidden -fpie -fno-strict-overflow -fno-delete-null-pointer-checks -B/usr/local/bin -mindirect-branch-register -fcf-protection=none -mfunction-return=thunk-extern -fno-plt -Wa,-mlfence-after-load=yes -Wa,-mlfence-before-indirect-branch=memory -Wa,-mlfence-before-ret=shl -nostdinc++ -Werror -fno-exceptions -fno-rtti -I/home/kai/linux-sgx/common/inc/internal -I/home/kai/linux-sgx/common/inc -I/home/kai/linux-sgx/common/inc/tlibc -I/home/kai/linux-sgx/common/../sdk/trts -I/home/kai/linux-sgx/psw sethread_mutex.cpp -o sethread_mutex.o
> as: unrecognized option '-mlfence-after-load=yes'
> ```
> 
> 从buildenv.mk中删除这些选项可以“修复”它，但这似乎并不安全。

I have the same problem. Have you solved it ？

**Comment by lzha101** [comment]
> > 构建时仍然出现此错误。我的安装具有GCC 9.3。
> > ```
> > g++ -c -Wnon-virtual-dtor -std=c++11 -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -UDEBUG -DNDEBUG -ffunction-sections -fdata-sections -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type -Waddress -Wsequence-point -Wformat-security -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow -Wcast-align -Wconversion -Wredundant-decls -DITT_ARCH_IA64 -ffreestanding -nostdinc -fvisibility=hidden -fpie -fno-strict-overflow -fno-delete-null-pointer-checks -B/usr/local/bin -mindirect-branch-register -fcf-protection=none -mfunction-return=thunk-extern -fno-plt -Wa,-mlfence-after-load=yes -Wa,-mlfence-before-indirect-branch=memory -Wa,-mlfence-before-ret=shl -nostdinc++ -Werror -fno-exceptions -fno-rtti -I/home/kai/linux-sgx/common/inc/internal -I/home/kai/linux-sgx/common/inc -I/home/kai/linux-sgx/common/inc/tlibc -I/home/kai/linux-sgx/common/../sdk/trts -I/home/kai/linux-sgx/psw sethread_mutex.cpp -o sethread_mutex.o
> > as: unrecognized option '-mlfence-after-load=yes'
> > ```
> > 
> > 
> > 从buildenv.mk中删除这些选项可以“修复”它，但这似乎并不安全。
> 
> I have the same problem. Have you solved it ？

Please follow the README https://github.com/intel/linux-sgx/blob/master/README.md#prerequisites to utilize mitigation toolset for SGX build.
```   
$ git clone https://github.com/intel/linux-sgx.git
$ cd linux-sgx && make preparation   
$ sudo cp external/toolset/{current_distr}/{as,ld,ld.gold,objdump} /usr/local/bin
$ which as ld ld.gold objdump
```

**Comment by lzha101** [comment]
> > > Since Ubuntu 20.04.1 released several days, any update about prebuilt PSW deb?
> > 
> > 
> > (in linux-sgx2.10)just add some check for gcc version, in order to avoid some conflict about compile options. More details can be found in commit
> 
> Sorry, I mean push prebuilts to https://download.01.org/intel-sgx/sgx-linux/2.11/distro/ and APT source

You can find the binaries for Ubuntu20.04 under folder https://download.01.org/intel-sgx/sgx-linux/2.12/distro/ubuntu20.04-server/
