### ISSUE TITLE
Incorrect type for parameter p_signature in sgx_ecdsa_verify() and sgx_ecdsa_verify_hash()

### ISSUE THREAD

**Issue by jaakristioja** [intel/linux-sgx#524]
In `sgx_tcrypto.h` the functions [`sgx_ecdsa_verify()`](https://github.com/intel/linux-sgx/blob/78135a5786615b4c88f8c5352cd7e0b6045c8510/common/inc/sgx_tcrypto.h#L707) and [`sgx_ecdsa_verify_hash()`](https://github.com/intel/linux-sgx/blob/78135a5786615b4c88f8c5352cd7e0b6045c8510/common/inc/sgx_tcrypto.h#L738) take as input a signature to verify via the parameter `p_signature` which is currently of type `sgx_ec256_signature_t *` (pointer to  `sgx_ec256_signature_t`). Please note that the signature is only used as input, therefore its type should instead be `sgx_ec256_signature_t const *` (pointer to constant `sgx_ec256_signature_t`).

**Comment by lzha101** [comment]
Thanks for your suggestion. This should be a known issue. I guess we still keep this because these are published APIs.  Changing this may break existing code build. 
Just did an experiment - seems it doesn't break existing code build.  We can change it in later release.

**Comment by Hans-Giebenrath** [comment]
Just noting that this issue can be closed, this is fixed already quite a while. Thanks!
