### ISSUE TITLE
Symbol lookup error when running RemoteAttestation sample code

### ISSUE THREAD

**Issue by lemonviv** [intel/linux-sgx#529]
Hi, 

I ran the RemoteAttestation sample code with hardware mode (the building process is succeed) and I got the following error:

`./app: symbol lookup error: ./app: undefined symbol: sgx_thread_wait_untrusted_event_timeout_ocall`

The simulation mode of this sample ran correctly, and both hardware and simulation modes of the LocalAttestation sample also ran correctly. The SGX SDK version is 2.7.1 on ubuntu system.

Any suggestion would be highly appreciated.

Thanks and best regards,
Yuncheng

**Comment by llly** [comment]
Are there anly modification to SDK or sample code?  We only have an ocall by the name of `sgx_thread_wait_untrusted_event_ocall` in `include/sgx_tstdc.edl` of SGX SDK. You can check this file.

**Comment by lemonviv** [comment]
Hi Xun, 

Yes, it was a problem of the modified SDK. I re-install the official version and it works. Thank you.

Best regards,
Yuncheng
