### ISSUE TITLE
sgx-gdb does not work

### ISSUE THREAD

**Issue by promach** [intel/linux-sgx#533]
I have the following log with sgx-gdb usage.

I have already tried to follow the instructions given at https://github.com/apache/incubator-teaclave-sgx-sdk/wiki/Setup-gdb-7.11-on-Ubuntu-18.04-for-VSCode---sgx-gdb-remote-debugging , but it does not help to solve the problem. 

sgx-gdb still cannot enter and debug enclave function compiled in hardware mode.

> Starting program: /home/rog/Downloads/SGX101_sample_code/HelloEnclave/app 
> detect urts is loaded, initializing
> Function "notify_gdb_to_update" not defined.
> Function "sgx_debug_load_state_add_element" not defined.
> Function "sgx_debug_unload_state_remove_element" not defined.
> Function "urts_add_tcs" not defined.
> Python Exception <class 'gdb.error'> No symbol "g_debug_enclave_info_list" in current context.: 
> [Thread debugging using libthread_db enabled]

**Comment by hyjiang** [comment]
In order to use sgx-gdb, you need to install below enclave common load & urts debug packages.

libsgx-enclave-common-dbgsym
libsgx-urts-dbgsym

**Comment by promach** [comment]
@hyjiang The problem is that I had already installed both.`libsgx-enclave-common-dbgsym` and `libsgx-urts-dbgsym`

**Comment by andyzyb** [comment]
@promach, would you please help list the SGX packages installed on your system?

**Comment by promach** [comment]
@andyzyb 
 
> rog@rog-GL502VMK:~$ sudo apt list --installed | grep -i sgx
> 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> libsgx-ae-epid/now 2.8.100.3-bionic1 amd64 [installed,local]
> libsgx-ae-le/now 2.8.100.3-bionic1 amd64 [installed,local]
> libsgx-ae-pce/now 2.8.100.3-bionic1 amd64 [installed,local]
> libsgx-ae-qe3/now 1.4.100.4-bionic1 amd64 [installed,local]
> libsgx-aesm-ecdsa-plugin/now 2.8.100.3-bionic1 amd64 [installed,local]
> libsgx-aesm-epid-plugin/now 2.8.100.3-bionic1 amd64 [installed,local]
> libsgx-aesm-launch-plugin/now 2.8.100.3-bionic1 amd64 [installed,local]
> libsgx-aesm-pce-plugin/now 2.8.100.3-bionic1 amd64 [installed,local]
> libsgx-aesm-quote-ex-plugin/now 2.8.100.3-bionic1 amd64 [installed,local]
> libsgx-dcap-default-qpl/now 1.4.100.4-bionic1 amd64 [installed,local]
> libsgx-dcap-default-qpl-dev/now 1.4.100.4-bionic1 amd64 [installed,local]
> libsgx-enclave-common/now 2.9.101.2-bionic1 amd64 [installed,local]
> libsgx-enclave-common-dbgsym/now 2.9.101.2-bionic1 amd64 [installed,local]
> libsgx-enclave-common-dev/now 2.9.101.2-bionic1 amd64 [installed,local]
> libsgx-epid/now 2.8.100.3-bionic1 amd64 [installed,local]
> libsgx-epid-dev/now 2.8.100.3-bionic1 amd64 [installed,local]
> libsgx-launch/now 2.8.100.3-bionic1 amd64 [installed,local]
> libsgx-launch-dbgsym/now 2.8.100.3-bionic1 amd64 [installed,local]
> libsgx-launch-dev/now 2.8.100.3-bionic1 amd64 [installed,local]
> libsgx-quote-ex/now 2.8.100.3-bionic1 amd64 [installed,local]
> libsgx-quote-ex-dev/now 2.8.100.3-bionic1 amd64 [installed,local]
> libsgx-uae-service/now 2.8.100.3-bionic1 amd64 [installed,local]
> libsgx-urts/now 2.8.100.3-bionic1 amd64 [installed,local]
> libsgx-urts-dbgsym/now 2.8.100.3-bionic1 amd64 [installed,local]
> sgx-aesm-service/now 2.8.100.3-bionic1 amd64 [installed,local]
> sgx-dcap-pccs/now 1.4.100.4-bionic1 amd64 [installed,local]
> rog@rog-GL502VMK:~$ 
>

**Comment by promach** [comment]
@iovoi There are still people unable to use sgx-gdb due to [similar issue](https://software.intel.com/en-us/forums/intel-software-guard-extensions-intel-sgx/topic/806016)

**Comment by xxu36** [comment]
Verified on my local ubuntu 1804, the issue mentioned can only be reproduced when I did not install or explicit uninstalled the `libsgx-urts-dbgsym` package.

Can you provide the result of running `dpkg-query --listfiles libsgx-urts-dbgsym` ? 
On my system, the result is something like: 
```
/.
/usr  
/usr/lib  
/usr/lib/debug
/usr/lib/debug/.build-id
/usr/lib/debug/.build-id/a9
/usr/lib/debug/.build-id/a9/3b6464c9a3103ad3cb5d68cdec3eb70ffb5395.debug
/usr/share
/usr/share/doc
/usr/share/doc/libsgx-urts-dbgsym
```
And dong a `nm /usr/lib/debug/.build-id/a9/3b6464c9a3103ad3cb5d68cdec3eb70ffb5395.debug | grep notify_gdb_to_update` will give me back `000000000000e7d0 t notify_gdb_to_update`

**Comment by promach** [comment]
@xxu36 

```
rog@rog-GL502VMK:~$ dpkg-query --listfiles libsgx-urts-dbgsym
/.
/usr
/usr/lib
/usr/lib/debug
/usr/lib/debug/.build-id
/usr/lib/debug/.build-id/a9
/usr/lib/debug/.build-id/a9/3b6464c9a3103ad3cb5d68cdec3eb70ffb5395.debug
/usr/share
/usr/share/doc
/usr/share/doc/libsgx-urts-dbgsym
rog@rog-GL502VMK:~$ nm /usr/lib/debug/.build-id/a9/3b6464c9a3103ad3cb5d68cdec3eb70ffb5395.debug | grep notify_gdb_to_update
000000000000e7d0 t notify_gdb_to_update
```

After updating `libsgx-urts-dbgsym` from version 2.8.100.3 to [version 2.9.101.2](https://download.01.org/intel-sgx/latest/linux-latest/distro/ubuntu18.04-server/debian_pkgs/debug/libsgx-urts-dbgsym/libsgx-urts-dbgsym_2.9.101.2-bionic1_amd64.deb), it returns different file but with similar output.

```
rog@rog-GL502VMK:~$ dpkg-query --listfiles libsgx-urts-dbgsym
/.
/usr
/usr/lib
/usr/lib/debug
/usr/lib/debug/.build-id
/usr/lib/debug/.build-id/30
/usr/lib/debug/.build-id/30/26bba61d251a5a9d4e7c10dd286047a3970f96.debug
/usr/share
/usr/share/doc
/usr/share/doc/libsgx-urts-dbgsym
rog@rog-GL502VMK:~$ nm /usr/lib/debug/.build-id/30/26bba61d251a5a9d4e7c10dd286047a3970f96.debug | grep notify_gdb_to_update
000000000000f960 t notify_gdb_to_update
rog@rog-GL502VMK:~$ 
```

**Comment by xxu36** [comment]
Thanks for the info. So the debug symbol package is there and the functions are defined. GDB should find that package when it runs. 
We can query the directories GDB searches for separate debugging information files using `show debug-file-directory` after GDB runs. On my system, the result is `/usr/lib/debug` just as expected. what's the result on your system?

**Comment by promach** [comment]
@xxu36 

```
rog@rog-GL502VMK:~/Downloads/SGX101_sample_code/HelloEnclave$ sgx-gdb ./app
GNU gdb (GDB) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Source directories searched: /opt/intel/sgxsdk/sgxsdk/lib64/gdb-sgx-plugin:$cdir:$cwd
Setting environment variable "LD_PRELOAD" to null value.
Reading symbols from ./app...done.
(gdb) show debug-file-directory
The directory where separate debug symbols are searched for is "/usr/local/lib/debug".
(gdb) 
```

**Comment by xxu36** [comment]
So, the GDB on your system uses `/usr/local/lib/debug` as the search directory. To work around, you can try to change it using `set debug-file-directory /usr/lib/debug` and see whether that works.

**Comment by promach** [comment]
@xxu36 @iovoi

ok, that helps a lot !!!

sgx-gdb seems to be working now !

```
(gdb) set debug-file-directory /usr/lib/debug
(gdb) show debug-file-directory
The directory where separate debug symbols are searched for is "/usr/lib/debug".
(gdb) break Enclave/Enclave.cpp:40
No source file named Enclave/Enclave.cpp.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (Enclave/Enclave.cpp:40) pending.
(gdb) run
Starting program: /home/rog/Downloads/SGX101_sample_code/HelloEnclave/app 
detect urts is loaded, initializing
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
add-symbol-file '/home/rog/Downloads/SGX101_sample_code/HelloEnclave/enclave.signed.so' 0x7ffff5000570 -s .interp 0x7ffff5000238  -s .note.gnu.build-id 0x7ffff5000254  -s .gnu.hash 0x7ffff5000278  -s .dynsym 0x7ffff50002b0  -s .dynstr 0x7ffff5000358  -s .gnu.version 0x7ffff50003b6  -s .gnu.version_d 0x7ffff50003c8  -s .rela.dyn 0x7ffff5000400  -s .plt 0x7ffff5000550  -s .plt.got 0x7ffff5000560  -s .nipx 0x7ffff50105e0  -s .rodata 0x7ffff50110a0  -s .niprod 0x7ffff5011800  -s .eh_frame_hdr 0x7ffff50120c0  -s .eh_frame 0x7ffff50125b0  -s .fini_array 0x7ffff5214d80  -s .data.rel.ro 0x7ffff5214da0  -s .dynamic 0x7ffff5214e30  -s .got 0x7ffff5214fb0  -s .data 0x7ffff5215000  -s .nipd 0x7ffff5215170  -s .bss 0x7ffff5215180 
rbp = 0x7fffffffdc80
rsp = 0x7fffffffdc70

Breakpoint 1, ecall_get_offset () at Enclave/Enclave.cpp:56
56		temp = secret[0]; //Bring secrete into cache.
(gdb) n
57		return (size_t)(secret-(char*)array1);
(gdb) n
58	} 
(gdb) n
sgx_ecall_get_offset (pms=0x7fffffffdc10) at Enclave/Enclave_t.c:60
60		ms->ms_retval = ecall_get_offset();
(gdb) n
63		return status;
(gdb) n
64	}
(gdb)
```

**Comment by xxu36** [comment]
Contacted with our team member, the where the debug symbol package will be installed depends on the system, such as Ubuntu 1804. That said, the path is standardized. Seems your GDB is built from source code and the version is different from that of the GDB in 1804 official release, that is the situation we currently cannot support. So seems manually set the search directory is the best choice.

**Comment by promach** [comment]
@xxu36 

so for sgx-gdb, we can actually use the latest version 9.1 of gdb instead of version 7.11 ?

If not, how to make `set debug-file-directory /usr/lib/debug` persistent across `gdb` running instance ?

**Comment by xxu36** [comment]
I think for GDB, you can just use what the system provides:  `apt install gdb`

**Comment by xxu36** [comment]
For persistence of the config to your GDB in use, I think you can take a look at `/opt/intel/sgxsdk/bin/sgx-gdb` and append the command `set debug-file-directory /usr/lib/debug` to the proper place at the last line. But this only works for you with the current SDK, with a new SDK installation, it will be overridden.

**Comment by xxu36** [comment]
@promach  If no more issue, please kindly close it, thanks
