### ISSUE TITLE
Is there any way to verify a SGX application is safe?

### ISSUE THREAD

**Issue by justalittlenoob** [intel/linux-sgx#535]
For example, i have 2 version of an application.
APPv1: SGX is NOT used.
APPv2: SGX is used.

How can i do to make other people believe APPv2 is safer than APPv1?

Any advice would be appreciated.

**Comment by andyzyb** [comment]
The remote attestation is the process to verify if the code is actually running inside enclave. Is it what you are looking for?

**Comment by justalittlenoob** [comment]
@andyzyb   
Thank you for your advice. As i am new to SGX. I may not understand it properly. I hope you can correct me.    

For example, when I buy a high bandwidth network card, I can see that it is better than a low bandwidth network card through the DL/UL speed. When I buy a large capacity storage device, I can see from the data capacity that it is better than a low capacity device.  

The remote attestation is more like a theoretical proof. It doesn't feel intuitive. Is there any tool/method can be used to both "APPv1" and "APPv2", and produce different results? Based on this result, I can definitely say "My SGX app is safer" to others (People who don't know much programming/computer).

**Comment by andyzyb** [comment]
I don't know a tool can tell what is more secure, instead of educating the users for the technology your are using.  Or you can invent some mechanism to report the security status of app when it is launched by the user.

**Comment by justalittlenoob** [comment]
> I don't know a tool can tell what is more secure, instead of educating the users for the technology your are using. Or you can invent some mechanism to report the security status of app when it is launched by the user.

@andyzyb I got it. Thank you again for your advice:)
