### ISSUE TITLE
Cannot compile SDK with gcc 5

### ISSUE THREAD

**Issue by jhand2** [intel/linux-sgx#537]
When building the SDK on Ubuntu 16.04, compilation fails with

```
g++: error: unrecognized command line option ‘-fno-plt’
```

Ubuntu 16.04 uses GCC 5.4 by default, but `-fno-plt` was added in GCC 6

**Comment by lzha101** [comment]
'-fno-plt' will be only added when building mitigation version SDK.  Are you building the mitigation version SDK with default GCC on Ubuntu 16.04? Note that mitigation build requires **GCC 7.3 or above**.

**Comment by jhand2** [comment]
How do I build without mitigations?

**Comment by lzha101** [comment]
You can run `$ make sdk_no_mitigation` to build SDK binaries without mitigations.  And ` $make sdk_install_pkg_no_mitigation` could generate an SDK installer without mitigations.

**Comment by jhand2** [comment]
I would recommend updating the build/install docs to reflect that you no longer support building the sdk on Ubuntu 16.04 (even if you produce psw packages for 16.04).

While it is technically possible to upgrade the version of GCC, it also requires updating the libc version which can potentially break other packages.

**Comment by lzha101** [comment]
You can find below content in the [README:](https://github.com/intel/linux-sgx#prerequisites)

> Note: To build Intel(R) SGX SDK, gcc version is required to be 7.3 or above and glibc version is required to be 2.27 or above. For Ubuntu 16.04, Red Hat Enterprise Linux 7.4, CentOS 7.5, Fedora 27, SUSE Linux Enterprise Server 12, you may need to update gcc and glibc version.

The mitigation build is recommended for all the OSes.  So we make this as a prerequisites to build SDK.  

And in SDK release notes, we also highlight this version requirement.

Anyhow, thanks for your recommendation. It's helpful for future release.

**Comment by jhand2** [comment]
Thanks
