### ISSUE TITLE
Support for Debian 10

### ISSUE THREAD

**Issue by gaia** [intel/linux-sgx#539]
Xeon E-2176G, running Debian 10 Buster (kernel 5.3.18-3)

```
# cpuid | grep SGX:
      SGX: Software Guard Extensions supported = true
```

How would I approach running the ubuntu version on Debian? Or is there another path?

PS: the vendor supplied BIOS only supports SGX via SPS, not via Intel ME.

**Comment by andyzyb** [comment]
You can try to build the SDK and PSW with the source code following README.  The existing packages built for other OSes (Ubuntu, etc.) cannot be guaranteed to run on different OS.
