### ISSUE TITLE
Docker aesm_service: error while loading libCppMicroServices.so.4.0.0 

### ISSUE THREAD

**Issue by justalittlenoob** [intel/linux-sgx#540]
I am trying to build SGX environment in docker. But there is an error when starting AESM service. 
 Any advice would be appreciated. Thanks.

The steps is as below:
start a docker container  
`sudo docker run --env http_proxy --env https_proxy -t -i ubuntu:18.04 /bin/bash` 

in the container:
1. `git clone https://github.com/intel/linux-sgx.git`
2. `apt-get install build-essential ocaml ocamlbuild automake autoconf libtool wget python libssl-dev git cmake perl -y`  
3. `apt-get install libssl-dev libcurl4-openssl-dev protobuf-compiler libprotobuf-dev debhelper cmake reprepro -y`  
4. `cd linux-sgx`
4. `./download_prebuilt.sh`
5. `make sdk_install_pkg_no_mitigation`
6. `cd linux/installer/bin/`
7. `./sgx_linux_x64_sdk_2.9.101.2.bin`
8. `cd ../../../`
9. `make psw_install_pkg`
10. `apt-get install -y libcurl4 libprotobuf10 libssl1.1 make module-init-tools`
11. `cd linux/installer/bin/`
12. `./sgx_linux_x64_psw_2.9.101.2.bin --no-start-aesm`
13. `source /opt/intel/sgxsdk/environment`
14. `cd /opt/intel/sgxpsw/aesm`
15. `./aesm_service --no-daemon`
./aesm_service: error while loading shared libraries: libCppMicroServices.so.4.0.0: cannot open shared object file: No such file or directory

16. `root@b55334731478:/opt/intel/sgxpsw/aesm# ls -l`
total 28504
-rwxr-xr-x 1 root root   112928 May  8 14:59 aesm_service
-rw-r--r-- 1 root root      556 May  8 14:59 aesmd.conf
-rw-r--r-- 1 root root      909 May  8 14:59 aesmd.service
drwxr-xr-x 2 root root     4096 May  8 14:59 bundles
-rw-r--r-- 1 root root     1808 May  8 14:59 le_prod_css.bin
**-rwxr-xr-x 1 root root 21288936 May  8 14:59 libCppMicroServices.so.4.0.0**
-rwxr-xr-x 1 root root    18192 May  8 14:59 libdcap_quoteprov.so
-rwxr-xr-x 1 root root   817808 May  8 14:59 libipc.so
-rwxr-xr-x 1 root root    34032 May  8 14:59 liboal.so
-rwxr-xr-x 1 root root    49168 May  8 14:59 libsgx_default_qcnl_wrapper.so
-rw-r--r-- 1 root root   698648 May  8 14:59 libsgx_le.signed.so
-rw-r--r-- 1 root root   839728 May  8 14:59 libsgx_pce.signed.so
-rwxr-xr-x 1 root root    72976 May  8 14:59 libsgx_pce_logic.so
-rw-r--r-- 1 root root  1296560 May  8 14:59 libsgx_pve.signed.so
-rw-r--r-- 1 root root  1280144 May  8 14:59 libsgx_qe.signed.so
-rw-r--r-- 1 root root   830392 May  8 14:59 libsgx_qe3.signed.so
-rwxr-xr-x 1 root root   128136 May  8 14:59 libsgx_qe3_logic.so
-rwxr-xr-x 1 root root  1616016 May  8 14:59 liburts_internal.so
-rwxr-xr-x 1 root root    50808 May  8 14:59 libutils.so
-rwxr-xr-x 1 root root     1936 May  8 14:59 linksgx.sh

**Comment by llly** [comment]
You can run `LD_LIBRARY_PATH=/opt/intel/sgxpsw/aesm /opt/intel/sgxpsw/aesm/aesm_service --no-daemon` in step 16.

**Comment by justalittlenoob** [comment]
> You can run `LD_LIBRARY_PATH=/opt/intel/sgxpsw/aesm /opt/intel/sgxpsw/aesm/aesm_service --no-daemon` in step 16.

Thanks. It indeed works. But there is another question. After the AESM service started. How can i do the following job?(such as run the sgx sample code), because the terminal is take over by the --no-daemon service.

`root@3e6ba36f819c:/# source /opt/intel/sgxsdk/environment`    
`root@3e6ba36f819c:/# LD_LIBRARY_PATH=/opt/intel/sgxpsw/aesm`
`root@3e6ba36f819c:/# /opt/intel/sgxpsw/aesm/aesm_service --no-daemon`
The path of system bundle: System Bundle
ecdsa_quote_service_bundle_name:2.0.0
epid_quote_service_bundle_name:2.0.0
le_launch_service_bundle_name:2.0.0
linux_network_service_bundle_name:2.0.0
pce_service_bundle_name:2.0.0
quote_ex_service_bundle_name:2.0.0
system_bundle:4.0.0
aesm_service[17]: [ADMIN]White List update requested
aesm_service[17]: The server sock is 0x563990180800
aesm_service[17]: [ADMIN]White list update request successful for Version: 74

**Comment by llly** [comment]
Use ` LD_LIBRARY_PATH=/opt/intel/sgxpsw/aesm /opt/intel/sgxpsw/aesm/aesm_service --no-daemon &`.
you can use ctrl-z, `bg`, `fg` command for background execution.

**Comment by justalittlenoob** [comment]
@llly  I truly appreciate your timely help.
