### ISSUE TITLE
What does "tiny" refer to?

### ISSUE THREAD

**Issue by eozturk1** [intel/linux-sgx#548]
What does `tiny` refer to for implementations under `member/tiny`? Is it space usage or the computation cost? If either one, is there a more optimized version available?

**Comment by llly** [comment]
Are you talking about `external/epid-sdk/epid/member/tiny`? It's external open source code https://github.com/Intel-EPID-SDK/epid-sdk.

**Comment by eozturk1** [comment]
Yes! Doesn't `tiny` refer to any optimizations in the code, e.g., space or computation?

We are trying to optimize `epid` further and were wondering whether `tiny` comes with compilation options for tweaking the optimizations mentioned above?

**Comment by eozturk1** [comment]
Sorry, got the repos confused. Moving this question there.
