### ISSUE TITLE
How to run sample code with AMD processor with SGX_MODE=SIM?

### ISSUE THREAD

**Issue by brucechin** [intel/linux-sgx#549]
Configurations:
1. Ryzen 3700X processor.
2. Ubuntu 18.04
3. linux SGX SDK version 2.5
If more detail is needed, I can provide at your request.

I can compile the SampleCode/LocalAttestation project on my AMD machine. Here is the result:

> make SGX_MODE=SIM

> buildenv.mk:55: "import SGX SDK environment variable"
> for dir in AppInitiator AppResponder EnclaveInitiator EnclaveResponder App; do \
> 	make -C $dir; \
> done
> make[1]: Entering directory '/home/liankeqin/repos/linux-sgx/SampleCode/LocalAttestation/AppInitiator'
> CC   <=  EnclaveInitiator_u.c
> CXX   <=  App.cpp
> CC   <=  UntrustedEnclaveMessageExchange.cpp
> CXX   <=  ../util/fifo.cpp
> GEN  =>  appinitiator
> make[1]: Leaving directory '/home/liankeqin/repos/linux-sgx/SampleCode/LocalAttestation/AppInitiator'
> make[1]: Entering directory '/home/liankeqin/repos/linux-sgx/SampleCode/LocalAttestation/AppResponder'
> CC  <=  EnclaveResponder_u.c
> CXX  <=  Thread.cpp
> CXX  <=  App.cpp
> CXX  <=  CPServer.cpp
> CXX  <=  CPTask.cpp
> GEN  =>  appresponder
> make[1]: Leaving directory '/home/liankeqin/repos/linux-sgx/SampleCode/LocalAttestation/AppResponder'
> make[1]: Entering directory '/home/liankeqin/repos/linux-sgx/SampleCode/LocalAttestation/EnclaveInitiator'
> GEN  =>  EnclaveInitiator_t.h
> CC   <=  EnclaveInitiator_t.c
> CXX  <=  Utility_E1.cpp
> CXX  <=  EnclaveMessageExchange.cpp
> CXX  <=  EnclaveInitiator.cpp
> LINK => libenclave_initiator.so
> <EnclaveConfiguration>
>     <ProdID>0</ProdID>
>     <ISVSVN>0</ISVSVN>
>     <StackMaxSize>0x40000</StackMaxSize>
>     <HeapMaxSize>0x100000</HeapMaxSize>
>     <TCSNum>1</TCSNum>
>     <TCSPolicy>1</TCSPolicy>
>     <DisableDebug>0</DisableDebug>
> </EnclaveConfiguration>
> tcs_num 1, tcs_max_num 1, tcs_min_pool 1
> The required memory is 1925120B.
> Succeed.
> SIGN =>  libenclave_initiator.signed.so
> make[1]: Leaving directory '/home/liankeqin/repos/linux-sgx/SampleCode/LocalAttestation/EnclaveInitiator'
> make[1]: Entering directory '/home/liankeqin/repos/linux-sgx/SampleCode/LocalAttestation/EnclaveResponder'
> GEN  =>  EnclaveResponder_t.h
> CC   <=  EnclaveResponder_t.c
> CXX  <=  EnclaveResponder.cpp
> CXX  <=  Utility_E2.cpp
> CXX  <=  EnclaveMessageExchange.cpp
> LINK => libenclave_responder.so
> <EnclaveConfiguration>
>     <ProdID>1</ProdID>
>     <ISVSVN>0</ISVSVN>
>     <StackMaxSize>0x40000</StackMaxSize>
>     <HeapMaxSize>0x100000</HeapMaxSize>
>     <TCSNum>1</TCSNum>
>     <TCSPolicy>1</TCSPolicy>
>     
>     <DisableDebug>0</DisableDebug>
>     <MiscSelect>0</MiscSelect>
>     <MiscMask>0xFFFFFFFF</MiscMask>
> </EnclaveConfiguration>
> tcs_num 1, tcs_max_num 1, tcs_min_pool 1
> The required memory is 1945600B.
> Succeed.
> SIGN =>  libenclave_responder.signed.so
> make[1]: Leaving directory '/home/liankeqin/repos/linux-sgx/SampleCode/LocalAttestation/EnclaveResponder'
> make[1]: Entering directory '/home/liankeqin/repos/linux-sgx/SampleCode/LocalAttestation/App'
> CC   <=  EnclaveInitiator_u.c
> CC   <=  EnclaveResponder_u.c
> CXX   <=  App.cpp
> CC   <=  UntrustedEnclaveMessageExchange.cpp
> GEN  =>  app
> make[1]: Leaving directory '/home/liankeqin/repos/linux-sgx/SampleCode/LocalAttestation/App'
> The project has been built in hardware debug mode.

When I tried to run the ./bin/app, It failed:

> failed to load enclave.

Is there any possibility for me to run the SGX app in simulator mode with AMD processor? Thanks!

**Comment by llly** [comment]
You need to `cd bin` then `./app`. In this sample code, relative path is used to find the enclave file .

**Comment by brucechin** [comment]
> You need to `cd bin` then `./app`. In this sample code, relative path is used to find the enclave file .

I have tried in bin/ folder and got the same error:

> failed to load enclave.

**Comment by llly** [comment]
Try `make clean` and `make SGX_MODE=SIM`. 
I saw your log in first post contains `The project has been built in hardware debug mode.`.  It should be `The project has been built in simulation debug mode.`.
