### ISSUE TITLE
Unable to make and install PSW

### ISSUE THREAD

**Issue by shegs01** [intel/linux-sgx#550]
Hi,

I am currently working on a project involving Intel SGX on hardware mode using a system that has FLC (on Ubuntu 18.04.4). I have successfully installed sgxsdk and ran a sample code in SIM mode.

However, when I run "make psw" on ubuntu 18.04, I get this error:
fatal: not a git repository (or any of the parent directories): .git
curl --output dcap_source.tar.gz -L --tlsv1 https://github.com/intel/SGXDataCenterAttestationPrimitives/archive/DCAP_1.6.tar.gz
make: curl: Command not found
Makefile:62: recipe for target 'dcap_source' failed
make: *** [dcap_source] Error 127

After downloading the DCAP_1.6 file shown in the error above, I could not install QuoteGeneration as I get this error:
dpkg: error: cannot access archive 'libsgx-ae-pce_*.deb': No such file or directory

Every step before the Dcap Quote Generation installation worked. Github link to QuoteGeneration: https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/QuoteGeneration

Can anyone help?

Thanks in advance.

**Comment by llly** [comment]
you don't need to build DCAP or install DCAP by yourself. 
Did you `apt-get install curl` and make again to fix the DCAP failure or download it manually?
You can install curl since you are not using git repo, then build and install SGX PSW following README of linux-sgx repo.

**Comment by shegs01** [comment]
Hi llly,

Thanks for your response. Yes, after installing curl using "apt-get install curl", I was able to proceed with PSW installation. However, I encountered another problem, after trying to install the library using "sudo apt-get install libssl-dev libcurl4-openssl-dev libprotobuf-dev" I get this error:

The following packages have unmet dependencies:
 libsgx-aesm-pce-plugin : Depends: libsgx-ae-pce (>= 2.9.101.2-bionic1) but it is not going to be installed
 libsgx-pce-logic : Depends: libsgx-ae-pce (>= 2.8) but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

I also get the same errors when I try to install PSW with "apt-get install libsgx-launch libsgx-urts", "apt-get install libsgx-epid libsgx-urts", and "apt-get install libsgx-quote-ex libsgx-urts" 

I have also tried 'apt --fix-broken install' but that didn't work either.

Finally, because I was prompted which mode I wanted during installation of PSW, I selected default. I tried to run a sample code in hardware mode and I got this error:

Failed to load enclave

Was the error I encountered during PSW installation causing this "Failed to load enclave" error?

Can you please help with this? Thanks for all your help.

**Comment by fqiu1** [comment]
Would you please paste the output of "sudo apt-get install libsgx-ae-pce"?

**Comment by shegs01** [comment]
Hi fqiu1,

Thanks, I have pasted the output of "sudo apt-get install libsgx-ae-pce" below:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libevent-core-2.1-6 libfwup1 php7.2 php7.2-curl php7.2-gd php7.2-mysql
  php7.2-xmlrpc
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  libsgx-ae-pce
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
5 not fully installed or removed.
Need to get 0 B/208 kB of archives.
After this operation, 945 kB of additional disk space will be used.
Get:1 file:/home/shegs/linux-sgx-master/linux/installer/deb/sgx_debian_local_repo bionic/main amd64 libsgx-ae-pce amd64 2.9.101.2-bionic1 [208 kB]
(Reading database ... 183670 files and directories currently installed.)
Preparing to unpack .../libsgx-ae-pce_2.9.101.2-bionic1_amd64.deb ...
Unpacking libsgx-ae-pce (2.9.101.2-bionic1) ...
dpkg: error processing archive /home/shegs/linux-sgx-master/linux/installer/deb/sgx_debian_local_repo/pool/main/s/sgx-aesm-service/libsgx-ae-pce_2.9.101.2-bionic1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libsgx_pce.signed.so', which is also in package libsgx-dcap-ql 1.0.100.46460-bionic1.0
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /home/shegs/linux-sgx-master/linux/installer/deb/sgx_debian_local_repo/pool/main/s/sgx-aesm-service/libsgx-ae-pce_2.9.101.2-bionic1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by fqiu1** [comment]
According to the output, it shows the root cause is: You've installed libsgx-dcap-ql 1.0.100.46460-bionic1.0 which is incompatible with the new modularized installer. 
You can uninstall the old installation and retry, you can check [upgrade-from-a-legacy-installation](https://github.com/intel/linux-sgx#upgrade-from-a-legacy-installation) for detail.

**Comment by shegs01** [comment]
Thanks, PSW finally installed in default mode without any errors. 

However, when I compile and run code samples in Hardware mode I get this error:

"failed to load enclave."

This are the steps I followed:

source /opt/intel/sgxsdk/environment
cd /opt/intel/sgxsdk/SampleCode/LocalAttestation
make 
cd bin
./app

How do I resolve this? I really appreciate all your help. Thanks.

**Comment by fqiu1** [comment]
Can you run SampleEnclave successfully?

**Comment by shegs01** [comment]
Hi fqui1, 

Yes, not sure if this is what the output should look like:

Steps taken:
source /opt/intel/sgxsdk/environment
cd /opt/intel/sgxsdk/SampleCode/SampleEnclave
make
./app

Output:
Checksum(0x0x7fff6e0a38f0, 100) = 0xfffd4143
Info: executing thread synchronization, please wait...  
Info: SampleEnclave successfully returned.
Enter a character before exit ...
f

Is there a reason why it failed to load enclave in hardware mode for LocalAttestation?

Thanks

**Comment by shegs01** [comment]
I can now run SGX in hardware mode without any issues. The problem enclave failed to load was because I was running SGX in the wrong directory. See steps taken below:

Steps taken:
source /opt/intel/sgxsdk/environment
cd /opt/intel/sgxsdk/SampleCode/LocalAttestation
make
cd bin
./app

Output:
succeed to load enclaves.
succeed to establish secure channel.
Succeed to exchange secure message...
Succeed to close Session...

Thanks to IIIy and fqui1. This issue is now closed. Thanks again.
