### ISSUE TITLE
Failed to build psw installer using 'make deb_psw_pkg'

### ISSUE THREAD

**Issue by Teeina** [intel/linux-sgx#551]
I have a fresh setup of Ubuntu18.04 and i want to install all dependencies for SGX. After i followed the steps in the readme to install psw, i met an issue like this:

make deb_psw_pkg
...
make[3]: Leaving directory '/home/ruoyu/SGX/linux-sgx-master/external/dcap_source/QuoteGeneration/installer/linux/deb/libsgx-dcap-def                     ault-qpl/libsgx-dcap-default-qpl-1.6.100.2'
   dh_install
   dh_installdocs
   dh_installchangelogs
   dh_perl
   dh_link
   dh_strip_nondeterminism
   dh_compress
   dh_fixperms
   dh_missing
   dh_strip
   dh_makeshlibs
   dh_shlibdeps
dpkg-shlibdeps: error: cannot find library libsgx_default_qcnl_wrapper.so.1 needed by debian/libsgx-dcap-default-qpl/usr/lib64/x86_64-linux-gnu/libdcap_quoteprov.so.1.6.100.2 (ELF format: 'elf64-x86-64' abi: '0201003e00000000'; RPATH: '')
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/libsgx-dcap-default-qpl/usr/lib64/x86_64-linux-gnu/libsgx_default_qcnl_wrapper.so.1.6.100.2 debian/libsgx-dcap-default-qpl/usr/lib64/x86_64-linux-gnu/libdcap_quoteprov.so.1.6.100.2 were not linked against libdl.so.2 (they use none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/libsgx-dcap-default-qpl/usr/lib64/x86_64-linux-gnu/libsgx_default_qcnl_wrapper.so.1.6.100.2 debian/libsgx-dcap-default-qpl/usr/lib64/x86_64-linux-gnu/libdcap_quoteprov.so.1.6.100.2 were not linked against libpthread.so.0 (they use none of the library's symbols)
dpkg-shlibdeps: error: cannot continue due to the error above
Note: libraries are not searched in other binary packages that do not have any shlibs or symbols file.
To help dpkg-shlibdeps find private libraries, you might need to use -l.
dh_shlibdeps: dpkg-shlibdeps -Tdebian/libsgx-dcap-default-qpl.substvars debian/libsgx-dcap-default-qpl/usr/lib64/x86_64-linux-gnu/libdcap_quoteprov.so.1.6.100.2 debian/libsgx-dcap-default-qpl/usr/lib64/x86_64-linux-gnu/libsgx_default_qcnl_wrapper.so.1.6.100.2 returned exit code 2
dh_shlibdeps: Aborting due to earlier error
debian/rules:8: recipe for target 'binary' failed
make[2]: *** [binary] Error 2
make[2]: Leaving directory '/home/ruoyu/SGX/linux-sgx-master/external/dcap_source/QuoteGeneration/installer/linux/deb/libsgx-dcap-ault-qpl/libsgx-dcap-default-qpl-1.6.100.2'
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
Makefile:72: recipe for target 'deb_sgx_dcap_default_qpl_pkg' failed
make[1]: *** [deb_sgx_dcap_default_qpl_pkg] Error 2
make[1]: Leaving directory '/home/ruoyu/SGX/linux-sgx-master/external/dcap_source/QuoteGeneration'
Makefile:111: recipe for target 'deb_libsgx_dcap_default_qpl' failed
make: *** [deb_libsgx_dcap_default_qpl] Error 2

However, i could find the 'libsgx_default_qcnl_wrapper.so.1' located in the same directory as 'libdcap_quoteprov.so.1.6.100.2'. So why does it report missing?

**Comment by xiangquanliu** [comment]
Just tested on a clean Ubuntu 18.04.4 LTS and didn't find any build issues. So could pls provide the exact version number of your OS. Thanks!

**Comment by lengyijun** [comment]
I meet the same problem in deepin

**Comment by Teeina** [comment]
> Just tested on a clean Ubuntu 18.04.4 LTS and didn't find any build issues. So could pls provide the exact version number of your OS. Thanks!
I'm using Ubuntu 18.04.3

**Comment by xiangquanliu** [comment]
> I meet the same problem in deepin 15.11

Currently deepin is not supported.

**Comment by fqiu1** [comment]
According to your log:

> dpkg-shlibdeps: error: cannot find library libsgx_default_qcnl_wrapper.so.1 needed by debian/libsgx-dcap-default-qpl/usr/**lib64**/x86_64-linux-gnu/libdcap_quoteprov.so.1.6.100.2 (ELF format: 'elf64-x86-64' abi: '0201003e00000000'; RPATH: '')

On my ubuntu 18.04 system, different path is used: 
debian/libsgx-dcap-default-qpl/usr/**lib**/x86_64-linux-gnu

I guess you're using a different Distro with Redhat alike Filesystem Hierarchy Standard to build deb package. It is not tested.

**Comment by Teeina** [comment]
> According to your log:
> 
> > dpkg-shlibdeps: error: cannot find library libsgx_default_qcnl_wrapper.so.1 needed by debian/libsgx-dcap-default-qpl/usr/**lib64**/x86_64-linux-gnu/libdcap_quoteprov.so.1.6.100.2 (ELF format: 'elf64-x86-64' abi: '0201003e00000000'; RPATH: '')
> 
> On my ubuntu 18.04 system, different path is used:
> debian/libsgx-dcap-default-qpl/usr/**lib**/x86_64-linux-gnu
> 
> I guess you're using a different Distro with Redhat alike Filesystem Hierarchy Standard to build deb package. It is not tested.

Oh...So a possible solution can only be changing the OS?

**Comment by fqiu1** [comment]
Yes, I think so.

**Comment by xiangquanliu** [comment]
Just tested on Ubuntu 18.04.3 LTS and didn't find any errors.

**Comment by Teeina** [comment]
> Just tested on Ubuntu 18.04.3 LTS and didn't find any errors.
May i know the steps you used?
And are you able to find the logs related to the 'libsgx_default_qcnl_wrapper.so.1'?
Thanks.

**Comment by xiangquanliu** [comment]
Just followed the README.  There are no logs related to the 'libsgx_default_qcnl_wrapper.so.1' since no errors.  I am curious about the gcc version on your OS. Could you please check the gcc version and the output of command `gcc --print-multi-os-director`?

**Comment by Teeina** [comment]
> Just followed the README. There are no logs related to the 'libsgx_default_qcnl_wrapper.so.1' since no errors. I am curious about the gcc version on your OS. Could you please check the gcc version and the output of command `gcc --print-multi-os-directory`?

Here's the output:
$ gcc --print-multi-os-directory
../lib64
$ gcc --version
gcc (GCC) 9.1.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by xiangquanliu** [comment]
The  gcc version should be 7.5 on the new installed Ubuntu 18.04.3 LTS. Do you use the manual compiled gcc?

**Comment by Teeina** [comment]
> The gcc version should be 7.5 on the new installed Ubuntu 18.04.3 LTS. Do you use the manual compiled gcc?

Yes. I download the tar file for GCC from GNU sites. Let me try to down grade it to 7.5.

**Comment by xiangquanliu** [comment]
So please use the system default gcc.

**Comment by Teeina** [comment]
> So please use the system default gcc.

A downgrade didn't work for me. Seems like that i need to refresh the whole system...

**Comment by Teeina** [comment]
A refresh of the system with gcc 7.5 works
