### ISSUE TITLE
Unable to compile Switchless Sample Code. Ubuntu 18.04/SDK 2.9.1

### ISSUE THREAD

**Issue by ibalajiarun** [intel/linux-sgx#564]
The Switchless sample code fails to compile on Ubuntu 18.04 with SDK 2.9.1. SampleEnclave compiles and runs well, so I suspect it is specific to the switchless library. It seems that there is an issue linking the binary. 

```
❯ make
GEN  =>  App/Enclave_u.h
CC   <=  App/Enclave_u.c
CXX  <=  App/App.cpp
/usr/bin/ld: /opt/sgxsdk/lib64/libsgx_uswitchless.a(sl_uswitchless_untrusted.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /opt/sgxsdk/lib64/libsgx_uswitchless.a(sl_uswitchless_untrusted.o): unable to initialize decompress status for section .debug_info
/opt/sgxsdk/lib64/libsgx_uswitchless.a: member /opt/sgxsdk/lib64/libsgx_uswitchless.a(sl_uswitchless_untrusted.o) in archive is not an object
collect2: error: ld returned 1 exit status
Makefile:213: recipe for target 'app' failed
make: *** [app] Error 1
```

**Comment by lzha101** [comment]
The error should be caused by different binutils tools.    
You can follow the [README Prerequisites](https://github.com/intel/linux-sgx#prerequisites) to download the mitigation tools from [01.org](https://download.01.org/intel-sgx/latest/linux-latest/as.ld.objdump.gold.r1.tar.gz) and copy them to /usr/local/bin. And then build the sample again.

> Copy the mitigation tools from external/toolset to /usr/local/bin and make sure they have execute permission:
  $ sudo cp external/toolset/{as,ld,ld.gold,objdump} /usr/local/bin
  $ which as ld ld.gold objdump

**Comment by ibalajiarun** [comment]
That fixed it. Thank you!

I couldn't find that on the Ubuntu 18.04 Installation Guide on 01.org. May be it is helpful to add it there as well. Thanks!

**Comment by lzha101** [comment]
Thanks for the advice. Actually the description is indeed included in the Installation Guide https://download.01.org/intel-sgx/latest/linux-latest/docs/Intel_SGX_Installation_Guide_Linux_2.9.1_Open_Source.pdf, Page 12

> On Ubuntu* 18.4 and Red Hat* Enterprise Linux 8.0, download the mitigation
tools which is named as.ld.objdump.gold.r1.tar.gz from here and unzip them to
the directory of /usr/local/bin. Make sure that these tools have execute
permission.
