### ISSUE TITLE
Error when compiling in pre-release mode

### ISSUE THREAD

**Issue by svartkanin** [intel/linux-sgx#57]
I have downloaded the example applications and tried to compile the remote attestation example in pre-release mode "make SGX_MODE=HW SGX_PRERELEASE=1"
The compilation runs without errors, but when executing the generated application I receive a missing library error:

`./app: error while loading shared libraries: libsgx_urts.so: cannot open shared object file: No such file or directory`

**Comment by yuyuany** [comment]
Have you installed Intel SGX PSW on your platform. Your compiled the sample code in hardware mode, so you need run the application on the Intel SGX enabled platform, with SGX PSW installed. See README.md for the hardware requirement and how to install SGX driver/psw.
If you have only Intel SGX SDK installed,  you can try the sample code in simulation mode. Here are some examples:
    a. Simulation Mode, Debug build:
        $ make SGX_MODE=SIM
    b. Simulation Mode, Pre-release build:
        $ make SGX_MODE=SIM SGX_PRERELEASE=1 SGX_DEBUG=0
    c. Simulation Mode, Release build:
        $ make SGX_MODE=SIM SGX_DEBUG=0

**Comment by svartkanin** [comment]
Sorry I was busy with other stuff...
I have tried to install SGX PSW now but I receive an error when executing the command 

`make psw_install_pkg`

`In file included from ../../../psw/ae/common/inc/ProtobufSerializer.h:39:0,
                 from ../uae_wrapper/src/AEServicesImpl.cpp:73:
../../../psw/ae/common/proto/messages.pb.h:3731:6: error: "PROTOBUF_INLINE_NOT_IN_HEADERS" is not defined [-Werror=undef]
 #if !PROTOBUF_INLINE_NOT_IN_HEADERS`

**Comment by zhaohuidu** [comment]
Please refer to http://stackoverflow.com/questions/34474091/protobuf-inline-not-in-headers
You could add -DPROTOBUF_INLINE_NOT_IN_HEADERS=0 in Makefile

**Comment by zhaohuidu** [comment]
It seems you are using protobuf3.x.
You could add -DPROTOBUF_INLINE_NOT_IN_HEADERS=0 in Makefile for
aesm_service and uae_service
such as in Makefile of aesm_service:
PROTPBUF_CXXFLAGS := -fstack-protector -fPIC -Wall -Werror -D_GLIBCXX_USE_CXX11_ABI=0  _**-DPROTOBUF_INLINE_NOT_IN_HEADERS=0**_

CXXFLAGS += -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 **_-DPROTOBUF_INLINE_NOT_IN_HEADERS=0_**

and in Makefile of uae_service
PROTPBUF_CXXFLAGS := -fstack-protector -fPIC -Wall -Werror **_-DPROTOBUF_INLINE_NOT_IN_HEADERS=0_**

**Comment by svartkanin** [comment]
I added the additional flag in the following Makefiles:

`psw/ae/aesm_service/Makefile:PROTPBUF_CXXFLAGS := -fstack-protector -fPIC -Wall -Werror -DPROTOBUF_INLINE_NOT_IN_HEADERS=0
psw/uae_service/linux/Makefile:PROTPBUF_CXXFLAGS := -fstack-protector -fPIC -Wall -Werror -DPROTOBUF_INLINE_NOT_IN_HEADERS=0`

But I still receive the same error!?
I'm have the following Protobuffer libraries installed:

`ii  libmirprotobuf3:amd64                       0.21.0+16.04.20160330-0ubuntu1                amd64        Display server for Ubuntu - RPC definitions
ii  libprotobuf-c-dev                           1.2.1-1                                       amd64        Protocol Buffers C static library and headers (protobuf-c)
ii  libprotobuf-c1                              1.2.1-1                                       amd64        Protocol Buffers C shared library (protobuf-c)
ii  libprotobuf-dev:amd64                       2.6.1-1.3                                     amd64        protocol buffers C++ library (development files)
ii  libprotobuf-lite9v5:amd64                   2.6.1-1.3                                     amd64        protocol buffers C++ library (lite version)
ii  libprotobuf9v5:amd64                        2.6.1-1.3                                     amd64        protocol buffers C++ library
ii  protobuf-c-compiler                         1.2.1-1                                       amd64        Protocol Buffers C compiler (protobuf-c)
ii  protobuf-compiler                           2.6.1-1.3                                     amd64        compiler for protocol buffer definition files`

**Comment by svartkanin** [comment]
Okay I was able to skip over this error by commenting out the line 
`#if !PROTOBUF_INLINE_NOT_IN_HEADERS``
in the messages.pb.h file.

But now I receive other errors regarding undefined references to the Google Protobuffers:

`messages.pb.cc:(.text+0x12b94): undefined reference to `google::protobuf::internal::ArenaStringPtr::AssignWithDefault(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, google::protobuf::internal::ArenaStringPtr)'`

**Comment by llly** [comment]
The version of protoc and protobuf-compiler you installed don't match.  Check the following commands and results from my Ubuntu.
`
$ which protoc
/usr/bin/protoc
$ sudo dpkg -S /usr/bin/protoc
protobuf-compiler: /usr/bin/protoc
$ protoc --version
libprotoc 2.6.1
$ apt-show-versions protobuf-compiler
protobuf-compiler:amd64/xenial 2.6.1-1.3 uptodate
`
Maybe you installed another protobuf from source code. If so, uninstall it.
