### ISSUE TITLE
Parallel encryption/decryption not working

### ISSUE THREAD

**Issue by brucechin** [intel/linux-sgx#576]
I use `sgx_rijndael128GCM_decrypt` and `sgx_rijndael128GCM_encrypt` to build a encrypted database prototype according to https://github.com/SabaEskandarian/ObliDB. Well, this works fine but I want to further improve its performance by batching read/writing multiple data blocks to reduce the number of ocall/ecall overhead. I found that 70% of the batching read/write time is spent on encryption and decryption(the rest is the ocall/ecall switch overhead), so I try to parallelize the encryption and decryption(for example, if batch size is 128 blocks, i want to assign 8 threads for decryption or encryption, and each thread is responsible for 16 data blocks).

I can not create multiple threads within the enclave, so I create a thread pool outside using `boost::asio::thread_pool pool(10);`. I successfully do multithreading **nested** simple computing(ecall->ocall->create multiple threads and each one calls ecall functions to enter again to do some computing). The code looks like:

```
void ecall_init_test() {
	ocall_thread_compute(10);
}

void ocall_thread_compute(int num_threads) {

    for (int i=0; i < num_threads; i++) {
        boost::asio::post(pool, []() {ecall_compute(global_eid);});//enter enclave again in parallel to execute something
    }

    pool.join();
}

void ecall_compute() {
	ocall_print_string("compute!\n");
	double s = 0;
	for (long i = 0; i < 150000000L; i++ ) {
		s += (1.0/i);
	}
}
```

However, when I replace the ecall_compute() with decryption and encryption functions, It does not work... A reminder, the ciphertext and plaintext are heap memory allocated in enclave. I post the decryption code chain here.

The call chain is readBlock(within enclave now) -> ocall_read_block -> ecall_decryptBlock.

```
int **readBlock**(int structureId, int index, Linear_Scan_Block *block)
{
	int blockSize = sizeof(Linear_Scan_Block);
	int encBlockSize = sizeof(Encrypted_Linear_Scan_Block);
	int i = index;
	Linear_Scan_Block *real = (Linear_Scan_Block *)malloc(blockSize);
	Encrypted_Linear_Scan_Block *realEnc = (Encrypted_Linear_Scan_Block *)malloc(encBlockSize);
	**_ocall_read_block_**(structureId, i, realEnc, real);
	memcpy(block, real->data, BLOCK_DATA_SIZE); 
	free(real);
	free(realEnc);

	return 0;
}

void **ocall_read_block**(int structureId, int index, void *encData, void *decData)
{ 
    int encBlockSize = sizeof(Encrypted_Linear_Scan_Block);
    memcpy(encData, oblivStructures[structureId] + ((long)index * encBlockSize), encBlockSize);
    boost::asio::post(pool, [encData, decData]() {  
       sgx_status_t ret = **_ecall_decryptBlock_**(global_eid, (int *)&status, encData, decData);
       printf("dec code %d\n", ret);
    });
    pool.join();

}

int **ecall_decryptBlock**(void *ct, void *pt, sgx_aes_gcm_128bit_key_t *key)
{
	sgx_status_t ret = SGX_SUCCESS;
	int retVal = 0;
	ret = **_sgx_rijndael128GCM_decrypt_**(key, ((Encrypted_Linear_Scan_Block *)ct)->ciphertext, sizeof(Linear_Scan_Block), (unsigned char *)pt, ((Encrypted_Linear_Scan_Block *)ct)->iv, 12, NULL, 0, &((Encrypted_Linear_Scan_Block *)ct)->macTag);
	if (ret != SGX_SUCCESS)
		retVal = 1;
	return retVal;
}
```

I wonder if anyone has successfully implemented (nested. enter the enclave, then ocall to create some threads to enter enclave in parallel to execute something) parallel encryption/decryption within the enclave before? Thanks!

**Comment by guzongmin** [comment]
I remeber that the SDK provides pthread APIs inside enclave. So you could create those threads without your own Ocall/Ecall, the SDK helps you to do that.

**Comment by brucechin** [comment]
> I remeber that the SDK provides pthread APIs inside enclave. So you could create those threads without your own Ocall/Ecall, the SDK helps you to do that.

I will try to use this way. Thanks for your suggestion!

**Comment by brucechin** [comment]
I should not do the threadpool.join() which will terminates the pool.
