### ISSUE TITLE
Can't load enclaves on hardware mode

### ISSUE THREAD

**Issue by Kruemelmonster3** [intel/linux-sgx#585]
Hi,
so I just can't get sgx to work in hardware mode and I have no idea why. The build and installation of everything went without an error yet when I try the LocalAttestation sample code I get: 
`failed to load enclave`
and when I try the SampleEnclave code I get:
`Info: Please make sure SGX module is enabled in the BIOS, and install SGX driver afterwards.
Error: Invalid SGX device.
Enter a character before exit ...`

The thing is SGX is enabled (and was enabled before the installation) in the BIOS, but I also ran sgx-software-enable to verify and it returned: 
`Intel SGX is already enabled on this system`

The driver also seems to be running perfeclty: 
/dev/isgx exists and dmesg only gives me the following sgx related outputs:
```
[    2.343195] isgx: loading out-of-tree module taints kernel.
[    2.343217] isgx: module verification failed: signature and/or required key missing - tainting kernel
[    2.343431] intel_sgx: Intel SGX Driver v2.6.0
[    2.343447] intel_sgx INT0E0C:00: EPC bank 0xc0200000-0xc5f80000
[    2.348863] intel_sgx: second initialization call skipped
```
The aesmd service also returns the status active(running).
Simulation mode also works perfectly fine so I'm kinda confused what is happening here.
Does anyone have an idea?

**Comment by Kruemelmonster3** [comment]
Nevermind, reinstalled it multiple times and it works now

**Comment by ltinerary** [comment]
```root@fan-QiTianM435-N000:/etc/intel/grapheneSource/graphene/Examples/pytorch-confidential# dmesg | grep sgx
[    5.630357] isgx: loading out-of-tree module taints kernel.
[    5.630439] isgx: module verification failed: signature and/or required key missing - tainting kernel
[    5.631168] intel_sgx: Intel SGX Driver v2.11.0
[    5.631209] intel_sgx INT0E0C:00: EPC bank 0x90200000-0x96000000
[    5.634943] intel_sgx: second initialization call skipped
[ 8217.904945] ksgxswapd: done
[ 8217.907894] intel_sgx: second release call skipped
[ 8912.903300] intel_sgx: Intel SGX Driver v2.11.0
[ 8912.903310] intel_sgx INT0E0C:00: EPC bank 0x90200000-0x96000000
[ 8912.904296] intel_sgx: second initialization call skipped
```
my linux kelnel is `5.9.0-050900-generic`，and I can run some example extra a remote attestation example.
so i checked `dmesg | grep sgx`and found this logs.
