### ISSUE TITLE
Bad libusgx_switchless.a in SGX 2.11 prebuilt SDK package

### ISSUE THREAD

**Issue by dingelish** [intel/linux-sgx#595]
```
/usr/bin/ld: /opt/sgxsdk/lib64/libsgx_uswitchless.a(sl_uswitchless_untrusted.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /opt/sgxsdk/lib64/libsgx_uswitchless.a(sl_uswitchless_untrusted.o): unable to initialize decompress status for section .debug_info
/opt/sgxsdk/lib64/libsgx_uswitchless.a: member /opt/sgxsdk/lib64/libsgx_uswitchless.a(sl_uswitchless_untrusted.o) in archive is not an object
collect2: error: ld returned 1 exit status
```

to reproduce, please `docker build` the following Dockerfiles. they all result in the above error message

Ubuntu 18.04:
```Dockerfile
FROM ubuntu:18.04
RUN apt update && apt install -y build-essential curl
RUN cd /root && \
    curl -o sdk.bin https://download.01.org/intel-sgx/sgx-linux/2.11/distro/ubuntu18.04-server/sgx_linux_x64_sdk_2.11.100.2.bin && \
    chmod +x sdk.bin && \
    echo -e 'no\n/opt' | ./sdk.bin

RUN bash -c "source /opt/sgxsdk/environment && cd /opt/sgxsdk/SampleCode/Switchless && make"
```

Centos 8
```Dockerfile
FROM centos:8

RUN dnf group install -y 'Development Tools'

RUN cd /root && \
    curl -o sdk.bin https://download.01.org/intel-sgx/sgx-linux/2.11/distro/centos8.1-server/sgx_linux_x64_sdk_2.11.100.2.bin && \
    chmod +x sdk.bin && \
    echo -e 'no\n/opt' | ./sdk.bin

RUN bash -c "source /opt/sgxsdk/environment && cd /opt/sgxsdk/SampleCode/Switchless && make"
```

**Comment by lzha101** [comment]
Generally, this error should be related to different binutils used.  The SDK installer on download.01.org are built with the mitigation LVI binutils. Could you try to configure the LVI binutils in the Docker as well?

**Comment by dingelish** [comment]
interesting. i can confirm use the prebuilt bintuils can fix this issue. one more question: does this means that switchless feature **_requires_** the latest binutils?

**Comment by lzha101** [comment]
I don't think so. It should depend on what binutils version is used to build the SDK. If you build your own SGX SDK installer with the system default binutils, suppose you can build the sample successfully with the system binutils as well.  
To avoid the binutils incompatible errors, it is better to keep the same binutils to build the SDK and the final binaries.

**Comment by dingelish** [comment]
understand. could you please confirm that the prebuilt static libraries in Intel SDK are compiled using the toolchain provided in as.ld.objdump.gold.r2.tar.gz ? thanks!

**Comment by lzha101** [comment]
Yes.  All the SDK installers for [2.11 release](https://download.01.org/intel-sgx/sgx-linux/2.11/distro/) provided in download.01.org are built with the prebuilt toolchain [as.ld.objdump.gold.r2.tar.gz](https://download.01.org/intel-sgx/sgx-linux/2.11/as.ld.objdump.gold.r2.tar.gz).  And the prebuilt static libraries on that release are also built with that toolchain.

**Comment by dingelish** [comment]
awesome! and could we have the exact source code (git hash is good)and configurations (like the argument of `./configure`) for that copy of toolchain? thanks!

**Comment by lzha101** [comment]
The toolchain is based on https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=a09f656b267b9a684f038fba7cadfe98e2f18892,  built with default configurations.

**Comment by dingelish** [comment]
@lzha101 thanks so much for your help!
