### ISSUE TITLE
[sgx_2.6 - docker + nix] cmake ...: dontUseCmakeConfigure: unbound variable 

### ISSUE THREAD

**Issue by sbellem** [intel/linux-sgx#597]
Following the instructions at https://github.com/intel/linux-sgx/tree/sgx_2.6/linux/docker#follow-the-below-steps-to-setup-the-enclave-build-environment, building the docker image fails:

```shell
$ docker build -t sgx.build.env linux/docker
...
/nix/store/y3jx54b8cjbk1igr8r74v156qiakrcf8-lw4xr0x2p6xyfgbk961lxh8vnnx7vn2r-cmake-3.12.1/nix-support/setup-hook: line 94: dontUseCmakeConfigure: unbound variable
The command '/bin/sh -c . /home/user/.nix-profile/etc/profile.d/nix.sh && nix-shell' returned a non-zero code: 1
```

**Comment by haitaohuang** [comment]
Can you use later versions in https://github.com/intel/linux-sgx/tree/master/linux/reproducibility?

**Comment by sbellem** [comment]
> Can you use later versions in https://github.com/intel/linux-sgx/tree/master/linux/reproducibility?

Thanks for the quick reply!

Yes I thought about that but the problem is that I am working with a system that requires sgx 2.6 explicitly as of now. I'd like to jump to the latest version as soon as possible but for now it's a bit out of reach.

I am not familiar with Nix, so I am not sure on how to go about to troubleshoot this. I welcome any recommendation!

Do you think it'd be feasible to fix the problem with sgx 2.6?

**Comment by haitaohuang** [comment]
You should be able to just replace the Dockerfile in 2.6 with the one from latest, and follow rest of the steps in the same.

**Comment by andyzyb** [comment]
There are many issues to fix to support reproducible build for SGX 2.6.  There is no plan to back support it.

**Comment by sbellem** [comment]
Ok, thanks @haitaohuang and @andyzyb for the quick reply.

**Comment by sbellem** [comment]
@andyzyb and @haitaohuang Just to be sure I understand correctly, the reproducible enclave build is available in 2.10 and 2.11, but not 2.9.1. I have currently managed to move up to 2.9.1 (from 2.6), and I don't see and reproducible enclave build code (Dockerfile, etc) for 2.9.1. I will try to move up to 2.11, but in the meantime I could benefit from your insights regarding implementing reproducible enclave builds with 2.9.1.

Thanks!

**Comment by lzha101** [comment]
Yes. The reproducibility support for prebuilt AE/libraries and SDK was added in 2.10 release. We provide a reproducible branch  https://github.com/intel/linux-sgx/tree/sgx_2.10_reproducible for the reproducibility support.  Not sure about your motivation. If you want to verify the reproducibility, you need to use that branch instead of the master branch.

**Comment by sbellem** [comment]
Thanks @lzha101 for the feedback. I am interested in being able to reproduce enclave builds as described in https://github.com/intel/linux-sgx/blob/master/linux/reproducibility/README.md#reproducible-enclave-build.

> Sometimes, user would get a signed enclave from third party, user may want to confirm the enclave is the right one they should use.

If I understood correctly, the approach you provide allows one to re-build the enclave and compare it with the one that was received from an "un-trusted" source, thus validating whether the "untrusted" enclave can be trusted, assuming one has the requirements you mention, i.e.: 

> 1. stable source code
> 2. clean and secure environment
> 3. auditable build tool chain
 
Example:

```shell
$ sha256sum untrusted-enclave.so re-built-enclave.so
3ad9ee45d711ab5488f0569464e139999d12503538a0c00b6d000e7cfbfbba10  untrusted-enclave.so
3ad9ee45d711ab5488f0569464e139999d12503538a0c00b6d000e7cfbfbba10  re-built-enclave.so
```

**Comment by lzha101** [comment]
Yes, you are right. But you should not be able to directly compare the signed enclave using the command you provided in the comment. You can refer to the [README](https://github.com/intel/linux-sgx/blob/sgx_2.10_reproducible/linux/reproducibility/ae_reproducibility_verifier/README.md) for enclave's reproducibility  verification.

**Comment by sbellem** [comment]
Ah ok, thanks for the correction!

**Comment by sbellem** [comment]
I'll close this issue as I think my original question was very well answered. Thanks @lzha101 @andyzyb and @haitaohuang!
