### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by jmg-duarte** [intel/linux-sgx#606]
Hello everyone!

Recently I've built the SGX SDK for Ubuntu 18.04 LTS, since according to the README there is no support for 20.04.
However, during the build I noticed there were artifacts produced for 20.04 but not for 16.04.

Maybe I did something weird, maybe something is missing from my view or maybe _it is as it should be_.

However I'm posting this issue as I think the documentation should be kept as up-to-date as possible.

**Comment by lzha101** [comment]
> However, during the build I noticed there were artifacts produced for 20.04 but not for 16.04.

Could you show us an example or log for better understanding your question?

**Comment by jmg-duarte** [comment]
```
linux-sgx on master 
laptop in Δ ls external/toolset/
centos8.1  fedora31  fedora32  nix  rhel8.0  rhel8.1  rhel8.2  sles15.2  ubuntu18.04  ubuntu20.04
```

This is the `external/toolset/` folder after running `make preparation`.

As you can see, Ubuntu20.04 is present and 16.04 is not. The README however, still mentions 16.04
