### ISSUE TITLE
Question: are http(s)_proxy build args really necessary in docker scripts for reproducible builds

### ISSUE THREAD

**Issue by sbellem** [intel/linux-sgx#607]
I just wonder whether the `http_proxy` and `https_proxy` build args are really necessary in https://github.com/intel/linux-sgx/blob/b9b071b54476e93ba21ae4f8dc41394970667cdd/linux/reproducibility/build_and_launch_docker.sh#L282-L283.

**Comment by haitaohuang** [comment]
It is needed to build docker image behind firewall because there are steps in Dockerfile to download files over network. Once the image is built it is run without network.

**Comment by sbellem** [comment]
The thing that I am struggling to understand is where are these build arguments declared? Shouldn't they be declared via the `ARG` keyword in the `Dockerfile`? I am basing my current understanding on the [`--build-arg` documentation](https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg).

**Comment by sbellem** [comment]
Ok, I did not know that there were pre-defined `ARG` variables: https://docs.docker.com/engine/reference/builder/#predefined-args.

> Docker has a set of predefined `ARG` variables that you can use without a corresponding `ARG` instruction in the `Dockerfile`.
>
> * `HTTP_PROXY`
> * `http_proxy`
> * `HTTPS_PROXY`
> * `https_proxy`
> ...
