### ISSUE TITLE
Make psw error

### ISSUE THREAD

**Issue by carllei1** [intel/linux-sgx#611]
I am trying to run make psw as described in the README file but I am getting:

 error: /opt/intel/sgxsdk/include: No such file or directory [-Werror=missing-include-dirs]

I have built the Intel(R) SGX SDK installer by running make sdk_install_pkg. I can also see the generated installer in linux/installer/bin/. (the file is sgx_linux_x64_sdk_2.11.100.2.bin ). Is there something else that might be causing this error?
-----------------------------------------------------------------------------------------------------------------
make -C psw/ USE_OPT_LIBS=1
make[1]: Entering directory '/home/carl/linux-sgx/psw'
make -C uae_service/linux/
make[2]: Entering directory '/home/carl/linux-sgx/psw/uae_service/linux'
g++ -Wnon-virtual-dtor -std=c++11 -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -UDEBUG -DNDEBUG -ffunction-sections -fdata-sections -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type -Waddress -Wsequence-point -Wformat-security -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow -Wcast-align -Wconversion -Wredundant-decls -DITT_ARCH_IA64 -fPIC -Werror -Wno-unused-parameter -g -DPROTOBUF_INLINE_NOT_IN_HEADERS=0 -Wno-deprecated-declarations  -I. -I/home/carl/linux-sgx/common -I/home/carl/linux-sgx/common/inc -I/home/carl/linux-sgx/common/inc/internal  -I/home/carl/linux-sgx/psw/ae/common -I/home/carl/linux-sgx/psw/ae/inc -I/home/carl/linux-sgx/psw/ae/inc/internal -I/opt/intel/sgxsdk/include -I/home/carl/linux-sgx/external/epid-sdk -I../../../psw/ae/aesm_service/source/core/ipc -I../uae_wrapper/inc -I../../../psw/ae/aesm_service/source/core/ipc -I/home/carl/linux-sgx/psw/ae/aesm_service/source -I/home/carl/linux-sgx/psw/ae/aesm_service/source/common -c ../uae_wrapper/src/AEServicesImpl.cpp -o AEServicesImpl.o
cc1plus: error: /opt/intel/sgxsdk/include: No such file or directory [-Werror=missing-include-dirs]
cc1plus: all warnings being treated as errors
Makefile:182: recipe for target 'AEServicesImpl.o' failed
make[2]: *** [AEServicesImpl.o] Error 1
make[2]: Leaving directory '/home/carl/linux-sgx/psw/uae_service/linux'
Makefile:49: recipe for target 'uae_service' failed
make[1]: *** [uae_service] Error 2
make[1]: Leaving directory '/home/carl/linux-sgx/psw'
Makefile:61: recipe for target 'psw' failed
make: *** [psw] Error 2
------------------------------------------------------------------------------------------------------------------

**Comment by strongcourage** [comment]
Hi @carllei1, I faced the same issue when compiling Intel PSW. How did you manage to fix this issue? Thanks.

**Comment by sunlinkun** [comment]
> Hi @carllei1, I faced the same issue when compiling Intel PSW. How did you manage to fix this issue? Thanks.

Hi, have you solved this problem？

**Comment by strongcourage** [comment]
Hi @sunlinkun, I still had this problem when compiling Intel PSW, but I can successfully run the example TestEnclave with Intel SDK installer. However, I think it is better to install Intel PSW :). If you know how to fix this issue, please let me know. Thank you.

**Comment by peter-jim** [comment]
I had same error with this, how do you solve this problem. I am try to development with rust.  Is right I choose use linux-sgx to development my project? I had find [incubator-teaclave-sgx-sdk](https://github.com/apache/incubator-teaclave-sgx-sdk). To be honest SGX is hard to code.

**Comment by peter-jim** [comment]
I solve this problem。 before we 'make psw', we need to install sgx sdk。    

 linux/installer/bin/ {.%%}.bin

**Comment by andyzyb** [comment]
@peter-jim This repo only supports C/C++. If you want to develop SGX Enclave with rust, you'd better to look for other projects, like teaclave.
