### ISSUE TITLE
Why there did not have C sample

### ISSUE THREAD

**Issue by CanYouGiveMeAName** [intel/linux-sgx#613]
All sgx sample is C++ project. But real code is all C. I can not find C++ feature. This confused me very much.
For meet some problem when link some C static libary.

**Comment by andyzyb** [comment]
This SDK supports both C and C++ languages, so you are free to use any of them.  What do you mean by "real code is all C"?

**Comment by CanYouGiveMeAName** [comment]
> This SDK supports both C and C++ languages, so you are free to use any of them. What do you mean by "real code is all C"?

I mean there did have a purn C demo. All project under sample is C++ project but write in C style.

**Comment by CanYouGiveMeAName** [comment]
Create purn C project successfully.
