### ISSUE TITLE
Reproducible build for sdk gives sgx*_2.10.100.1.bin instead of sgx*_2.10.100.2.bin

### ISSUE THREAD

**Issue by sbellem** [intel/linux-sgx#617]
The current download on the website at https://download.01.org/intel-sgx/sgx-linux/2.10/distro/ubuntu18.04-server/  is  `sgx_linux_x64_sdk_2.10.100.2.bin` meanwhile the build generated using the reproducible environment with docker and nix is
`sgx_linux_x64_sdk_2.10.100.1.bin`.

**Comment by lzha101** [comment]
The official reproducible SDK installer is https://download.01.org/intel-sgx/sgx-linux/2.10/distro/nix_reproducibility/sgx_linux_x64_sdk_reproducible_2.10.100.1.bin.  
It could be reproducible with the reproducible branch `sgx_2.10_reproducible`, under the reproducible environment.

**Comment by sbellem** [comment]
Ah, I see, thanks! I had overlooked the [nix_reproducibility](https://download.01.org/intel-sgx/sgx-linux/2.10/distro/nix_reproducibility/) directory, and was just looking under the `ubuntu18.04-server/` directory.
