### ISSUE TITLE
Problem when include proto

### ISSUE THREAD

**Issue by CanYouGiveMeAName** [intel/linux-sgx#619]
I gegerate proto code with protoc. And get problem when add in project.

First I treied to generate C code.
Makefile:
Enclave/tee.pb-c.c: Enclave/tee.pb.h
Enclave/tee.pb.o: Enclave/tee.pb.cc
	@$(CC) $(Enclave_C_Flags) -IEnclave/third_party/include -lprotobuf Enclave/third_party/lib/libprotobuf-c.a -c $< -o $@
	@echo "CC   <=  $<"
 Error is:
/usr/local/bin/ld: Enclave/third_party/lib/libprotobuf-c.a(protobuf-c.o): in function `protobuf_c_service_invoke_internal':
/opt/lq/protobuf-c-1.3.3/protobuf-c/protobuf-c.c:3509: undefined reference to `__assert_fail'

Then I tried to generate C++.
Makefile:
Enclave/tee.pb.cc: Enclave/tee.pb.h
Enclave/tee.pb.o: Enclave/tee.pb.cc
	@$(CC) $(Enclave_CPP_Flags) -IEnclave/third_party/include -lprotobuf Enclave/third_party/lib/libprotobuf.a -c $< -o $@
	@echo "CC   <=  $<"
 Error is:
Enclave/third_party/include/google/protobuf/io/coded_stream.h:134:10: fatal error: sys/param.h: No such file or directory
 #include <sys/param.h>  // __BYTE_ORDER

How can I include proto? Please help. Thx

**Comment by lzha101** [comment]
Are you trying to use protobuf inside enclave?  Then you may need to do some porting work by yourself.

The first error message shows your protobuf lib requires the `__assert_fail` during linking. From the Makefile snippet you paste here, there is no info about how you link your project.
The second error message shows your protobuf requires system header files. `Enclave_CPP_Flags` may include the options `-nostdinc` , `-nostdinc++` and result in this error.

**Comment by CanYouGiveMeAName** [comment]
> Are you trying to use protobuf inside enclave? Then you may need to do some porting work by yourself.
> 
> The first error message shows your protobuf lib requires the `__assert_fail` during linking. From the Makefile snippet you paste here, there is no info about how you link your project.
> The second error message shows your protobuf requires system header files. `Enclave_CPP_Flags` may include the options `-nostdinc` , `-nostdinc++` and result in this error.

For first question: I may found the reason.
Assert.h that under sgx-sdk does not deaclre `__assert_fail` .
But in linux lib, it contains.
