### ISSUE TITLE
Receiving Error 400 from IAS

### ISSUE THREAD

**Issue by sicmas16** [intel/linux-sgx#62]
Hello,
I've used IAS successfully to retrieve the SigRL from it, but when verifying the Quote enclave I kepp getting an error 400. Here is the relevant code:

`ret = sgx_ra_proc_msg2(this->enclave->getContext(),
	                               this->enclave->getID(),
	                               sgx_ra_proc_msg2_trusted,
	                               sgx_ra_get_msg3_trusted,
	                               p_msg2,
	                               size,
	                               &p_msg3,
	                               &msg3_size);`

this call returns with SGX_SUCCESS. Then I take the quote, convert it to a std::string and and encode it to Base64:

`std::string quoteStr = ConvertToString(p_msg3->quote);`
`quoteStr = EncodeToBase64(quoteStr);`

This quote will then be put in JSON format as described here https://software.intel.com/sites/default/files/managed/3d/c8/IAS_1_0_API_spec_1_1_Final.pdf, 
which gives me 
`{"isvEnclaveQuote": "MDIwMDAxMDBlMzBhMDAwMDA0MDA...RiMjUyYTgxOGE4NTIzMzQxZDY3"}`

When I now send this as a payload to the IAS it always returns with a "400 Bad Request", which according to the API above, indicates an invalid payload!?

Am I doing something wrong here with the encoding?

Thanks

**Comment by llly** [comment]
Is length of quoteStr the same as quote size in p_msg3?

**Comment by sicmas16** [comment]
No the lengths are not the same.
I got the length for the `p_msg3->quote` from the example program for Windows, which was hardcoded their and turned out to be `1116`!?

I calculate the `quoteStr` like this:

`ostringstream convert;`
`for (int a = 0; a < size; a++) {`
`     convert << setfill('0') << setw(2) << hex << (int)arr[a];`
`}`
string str = convert.str();`

whereas `size` would be the mentioned `1116` and `arr` the p_msg3->quote

The received length of the `quoteStr` is then `2232`

**Comment by llly** [comment]
quote is is msg3_size -sizeof(sgx_ra_msg3_t), seams it's right.

**Comment by sicmas16** [comment]
Yes for which i receive 

`msg3_size => 1452`
`sizeof(sgx_ra_msg3_t) => 336`
`quote size => 1116`

so what is the problem then?

**Comment by sicmas16** [comment]
Can someone please tell me how to fix/debug this problem since it's quite urgent!?

Thank you

**Comment by andyzyb** [comment]
Did you subscribe to Intel® SGX Development Services?

**Comment by andyzyb** [comment]
Please look at below link if you haven't subscribed the service.

https://software.intel.com/formfill/sgx-onboarding

**Comment by andyzyb** [comment]
See if the sample code below does any help.

https://github.com/01org/linux-sgx/issues/59

**Comment by llly** [comment]
Not sure whether ConvertToString() is needed. In sample of spec, isvEnclaveQuote": "AAEAAAEAA..."  is Base64 of 0x0000.... instead of "00....".

**Comment by light1021** [comment]
I meet this problem too, I get such quote:
`436 bytes:
{
0x2, 0x0, 0x1, 0x0, 0xb2, 0x13, 0x0, 0x0,
0x4, 0x0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0,
0x83, 0xe4, 0x9e, 0x18, 0x4f, 0xf, 0x6c, 0xbd,
0xee, 0x6c, 0x2f, 0x26, 0xdb, 0xec, 0x7c, 0xe,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x3, 0x5, 0xff, 0xff, 0x1, 0x2, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x37, 0xf6, 0x80, 0x28, 0x1e, 0x38, 0x42, 0x87,
0x79, 0x2a, 0x88, 0x67, 0x43, 0x7b, 0xb0, 0x2e,
0xdd, 0xcb, 0xc1, 0x5f, 0xa7, 0x6c, 0xe4, 0xda,
0xf6, 0xe, 0xb7, 0x19, 0xf7, 0x92, 0x85, 0x1,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x60, 0x27, 0x7a, 0xd2, 0xfd, 0xfc, 0x57, 0xe9,
0x80, 0xe8, 0x76, 0xe7, 0xf8, 0x78, 0xac, 0x19,
0x9, 0x88, 0xe, 0xa5, 0x38, 0x7, 0x95, 0xa7,
0xe8, 0xea, 0x98, 0xb1, 0x57, 0x84, 0x1f, 0x85,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x25, 0xc8, 0x35, 0xe3, 0x9c, 0xea, 0x72, 0xd8,
0xb9, 0xb7, 0x25, 0xc, 0xbb, 0xf1, 0xcf, 0x82,
0x3, 0x1c, 0xc5, 0x72, 0xd9, 0xe3, 0x16, 0xb8,
0xd4, 0x8b, 0x42, 0x5a, 0x8c, 0x40, 0x9b, 0xd9,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
0xa8, 0x2, 0x0, 0x0
}`

and I transform it to json:

` Attestation playload: {"isvEnclaveQuote":"AgABALITAAAEAAQAAAAAAIPknhhPD2y97mwvJtvsfA4AAAAAAAAAAAAAAAAAAAAAAwX//wECAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAHAAAAAAAAADf2gCgeOEKHeSqIZ0N7sC7dy8Ffp2zk2vYOtxn3koUBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgJ3rS/fxX6YDoduf4eKwZCYgOpTgHlafo6pixV4QfhQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlyDXjnOpy2Lm3JQy78c+CAxzFctnjFrjUi0JajECb2QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqAIAAAAAAACxAgAAAAAAACOklJzqdPvfh2+yvH06ipmi2npjSK6BvM/BMwCy+7mZr4yUVOciFego4ybomhifcQZXN+zhdSIEyZYE7FOOm50XQ2kB9jZLBT+gT+lsLtR0Ngv7UcA9sFT/nf+9k7MryXv6Jo27x5bZRFppZNfpQq0l1rODnhElWtpLTD4Nog6Tn31vVAFsSg7bJwYw1oUIoxNNZaISIS+syQYpnB+DIT/JsBBi25E/zhKXFlINFDdtAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkAAAAAAAAAAQAAAAAAAACCBDJ1xu5mkPMuv4sAAAAJjddXFCb3hL+qcehfVbbVGL0YhK4eStNKsQs1LqVln88NAAAAAAAAAG0AAAAAAAAAJx7icyZpiWhwpd3VHLr0R1eEuKY6/d82XutJtkdZmpW81pNsj7I0K68IcU11+r9tcxo5p0XEFWH7bQkDgwlvyhPe4iH6SItGiHcwpMbNeqtGshPnIIUGipMhZw61pN4fqcfkV/rsl5U4fP2Oitd519WTdOmVIdiVkbsZ2XA77kLmTRnLIPRUQaqauWw9Oyy0PlVMuNH/5msZoI0cT9nyR0zXoKcdz3j1J/XBpJ4mFCxNC4CZIzxScAChL4uEDYgsuZjqWeXUrNVZitHQGYZOU+ASO4n8UuKGTaqvEqcx2lwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgLzJm0d/AACgvMmbR38AAA0AAAAAAAAAwBDIm0d/AAAAeIwAAAAAALh1jAAAAAAADAAAAP////8BAAAA"}`

Have you solved this problem?

**Comment by andyzyb** [comment]
Old issue
