### ISSUE TITLE
Unable to reproduce sdk with nix-based environment

### ISSUE THREAD

**Issue by sbellem** [intel/linux-sgx#629]
When following the steps from https://github.com/intel/linux-sgx/tree/sgx_2.10_reproducible/linux/reproducibility or https://github.com/intel/linux-sgx/tree/sgx_2.12_reproducible/linux/reproducibility I do not get the same sdk (`sgx_linux_x64_sdk_2.12.100.1.bin`) file with respect to the sha256sum. Beside not getting the same sha256 as the one published at https://download.01.org/intel-sgx/sgx-linux/2.12/SHA256SUM_linux_2.12.cfg, i.e.:

```cfg
27d2b23441765b8e3488f5d8d301a2ad03ebd4aba4b9c6b2396f65f6499dc784  distro/nix_reproducibility/sgx_linux_x64_sdk_reproducible_2.12.100.1.bin
```

repeated builds yield `sgx_linux_x64_sdk_2.12.100.1.bin` files with different sha256sums, e.g.:

```shell
$ git clone --recursive --branch sgx_2.12_reproducible https://github.com/intel/linux-sgx.git
$ cd linux-sgx/linux/reproducibility/
```

```shell
$ ./build_and_launch_docker.sh -t sdk
$ sha256sum code_dir/out/sdk/sgx_linux_x64_sdk_2.12.100.1.bin 
7af1a2c6a1abb5a3c522bcc849b044d5d9c67943206fc54c32810e741d67d38e  code_dir/out/sdk/sgx_linux_x64_sdk_2.12.100.1.bin
```

```shell
$ ./build_and_launch_docker.sh -t sdk
$ sha256sum code_dir/out/sdk/sgx_linux_x64_sdk_2.12.100.1.bin 
86f6b3f0e8bf134f48829ee2de28e3c78e511318f344046fe60881e0d298408d  code_dir/out/sdk/sgx_linux_x64_sdk_2.12.100.1.bin
```

```shell
$ ./build_and_launch_docker.sh -t sdk
$ sha256sum code_dir/out/sdk/sgx_linux_x64_sdk_2.12.100.1.bin 
621ce85fda1ebb41b29c49820e89c5f0bcbeb9b2079c97b72b38875459834dd8  code_dir/out/sdk/sgx_linux_x64_sdk_2.12.100.1.bin
```

Am I misunderstanding or overlooking something? I do not get this problem with the  `binutils` and `ipp-crypto` binaries as their sha256sums match the pre-built ones that can be downloaded.

**Comment by lzha101** [comment]
SDK reproducibility doesn't mean the SDK installer itself should be reproducible, but means the SDK content can be reproducible. You need to install the SDK installer to extract the SDK content ( *.a, *.so, header files, etc) and verify the content.

**Comment by sbellem** [comment]
Ah ok I see, thanks!

What about the enclaves built with the sample code, such as `SampleEnclave` etc, should they be reproducible, when using the same SDK?

**Comment by lzha101** [comment]
I think so, if you build the sample in the reproducible environment with the reproducible SDK.

**Comment by sbellem** [comment]
Ok, thank you! And to be sure I understand correctly, if using the reproducible environment and building and signing the enclaves under the sample code, both resulting files, `enclave.so` and `enclave.signed.so` (since the private key does not change) should be reproducible, including having identical hashes? Am I understanding correctly?

**Comment by sbellem** [comment]
> if using the reproducible environment and building and signing the enclaves under the sample code, both resulting files, `enclave.so` and `enclave.signed.so` (since the private key does not change) should be reproducible, including having identical hashes?

The `enclave.signed.so` may differ as it depends on the date when it is signed, because the message signed contains metadata which contains the UTC date.

Will close this issue, as the original problem has been resolved.
