### ISSUE TITLE
404 for 2.12 "Prebuilt Optimized Libraries Binaries" on download page

### ISSUE THREAD

**Issue by sbellem** [intel/linux-sgx#630]
On https://01.org/intel-software-guard-extensions/downloads, the link (https://download.01.org/intel-sgx/sgx-linux/2.12/optimized_libs_2.12.tar.gz) to download **Prebuilt Optimized Libraries Binaries** leads to a 404.

Same problem occurs with sgx 2.10.

**Comment by lzha101** [comment]
Thanks for reporting this. I've updated the broken URLs on 01.org.  Please let us know if any future issue.

**Comment by sbellem** [comment]
Thanks! It works now! Will close this issue.
