### ISSUE TITLE
fatal error: ippcp.h: 没有那个文件或目录

### ISSUE THREAD

**Issue by sqq0216** [intel/linux-sgx#632]
I dowload the linux sdk code, and I want to make the sdk/sample_libcrypto uising the Makefile, but there is an error:
```
sample_libcrypto.cpp:47:19: fatal error: ippcp.h: 没有那个文件或目录
 #include "ippcp.h"
```
what should I do?
thanks

**Comment by lzha101** [comment]
Please run the download_prebuilt.sh before build. Or you can run `$ make preparation `in the top folder.
