### ISSUE TITLE
Cannot run sample code with Valgrind

### ISSUE THREAD

**Issue by rahulramsaha** [intel/linux-sgx#638]
Hi, i'm new to SGX and i've been experimenting with the different Sample codes available. I believe i've set up the SDK, driver and the other prerequisites successfully but when trying to execute the the generated binaries (app) with Valgrind, i got an unexpected result : 

Normal execution : 

```
~/linux-sgx/SampleCode/SampleEnclave$ ./app
Checksum(0x0x7ffc67f955f0, 100) = 0xfffd4143
Info: executing thread synchronization, please wait...  
Info: SampleEnclave successfully returned.
Enter a character before exit ...
```

Execution with Valgrind : 
```
linux-sgx/SampleCode/SampleEnclave$ valgrind ./app
==10909== Memcheck, a memory error detector
==10909== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==10909== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==10909== Command: ./app
==10909== 
Info: Please make sure SGX module is enabled in the BIOS, and install SGX driver afterwards.
Error: Invalid SGX device.
Enter a character before exit ...
```

I haven't found much online about executing SGX programs with Valgrind and therefore i'm not sure if i'm doing something wrong or if SGX simply doesn't support Valgrind. Any help would be appreciated, thanks !

os : Ubuntu 18.04

**Comment by lzha101** [comment]
Tried the same steps on my local machine. Seems the case fails at the line https://github.com/intel/linux-sgx/blob/master/psw/urts/se_detect.cpp#L40. The CPUID info in Valgrind shows SGX is not supported, which is not true.

Valgrind is actually an emulator and seems it emulates a wrong CPUID in this case. A similar issue could be found [here](https://stackoverflow.com/questions/48697579/valgrind-changes-cpuid-value)

So IMO, SGX doesn't support Valgrind unless Valgrind makes some changes.

**Comment by lzha101** [comment]
On the simulation mode, valgrind also reports some unhandled instruction bytes as below:
```
vex amd64->IR: unhandled instruction bytes: 0xF 0xC7 0xF0 0x73 0xFB 0x89 0x45 0xFC 0x8B 0x45
vex amd64->IR:   REX=0 REX.W=0 REX.R=0 REX.X=0 REX.B=0
vex amd64->IR:   VEX=0 VEX.L=0 VEX.nVVVV=0x0 ESC=0F
vex amd64->IR:   PFX.66=0 PFX.F2=0 PFX.F3=0
```
` 0xF 0xC7 0xF0` is RDRADN. Valgrind starts to support RDRAND from Release 3.15.0 (12 April 2019). See https://www.valgrind.org/docs/manual/dist.news.html. On my machine, the valgrind is 3.13.

**Comment by rahulramsaha** [comment]
Thanks a lot @lzha101 for the help, i had no idea this issue spanned so deeply. So following your advice, i built the project in simulation mode with the current release of Valgrind, 3.16.1, and for the most part it seems to be working !
