### ISSUE TITLE
Can't decrypt rsa3072, when encrypted with openssl standard

### ISSUE THREAD

**Issue by clangenb** [intel/linux-sgx#641]
We get an `sgx_error_unexpected` when trying to decrypt something in the enclave with `sgx_crypto_helpers`that has been encrypted with node-rsa. However, we are successfully able to decrypt with openssl using the same code.

```
openssl pkeyutl -in cypher -decrypt -inkey priv -pkeyopt rsa_padding_mode:oaep -pkeyopt rsa_oaep_md:sha256 -pkeyopt rsa_mgf1_md:sha256
```
Note: we can reproduce successful decryption with openssl with `rsa_mgf1_md:sha1` and encrypting with this setting accordingly.

It should not be a problem with the endians of the pubkey export as the pubkey is sent in json format.

Encryption is performed [here.](https://github.com/encointer/encointer-wallet-flutter/blob/681e78a9e3c0a4cdf0c1361a1417c70c16a06287/lib/js_service_encointer/test/service/utils/rsa.test.js#L12)

**Comment by brenzi** [comment]
endianness can be the issue:
https://github.com/intel/linux-sgx/blob/04dd342ee794e6cda29366433fae73734cabc688/sdk/tlibcrypto/sgxssl/sgx_rsa_encryption.cpp#L105

Doesn't `BN_bn2lebinpad` indicate little-endianness?

I don't see why json format would ensure endianness.

**Comment by clangenb** [comment]
Was indeed the wrong endianness. changing the endianness resolved this.
