### ISSUE TITLE
Memory copy function overflows destination buffer

### ISSUE THREAD

**Issue by florianbecker** [intel/linux-sgx#642]
https://github.com/intel/linux-sgx/blob/8c7bbc3a5380e2309d3d5af0cb62633d80c96d1f/SampleCode/LocalAttestation/AppResponder/CPTask.cpp#L111

Possible Code Injection. Fast solution to keep src and dest the same will break the LAS.

**Comment by lzha101** [comment]
There seems no overflow with this memcpy().  
The `fifo_resp`  is a type of FIFO_MSG as below:
https://github.com/intel/linux-sgx/blob/8c7bbc3a5380e2309d3d5af0cb62633d80c96d1f/SampleCode/LocalAttestation/Include/fifo_def.h#L60-L64

While it is allocated on heap with the size (**sizeof(FIFO_MSG) + sizeof(SESSION_MSG1_RESP)**):
https://github.com/intel/linux-sgx/blob/8c7bbc3a5380e2309d3d5af0cb62633d80c96d1f/SampleCode/LocalAttestation/AppResponder/CPTask.cpp#L99-L100

**Comment by florianbecker** [comment]
If i'm right, this is the function fingerprint:
void* memcpy( void* dest, const void* src, std::size_t count );

So it overflows dest, because dest has a size of 1 and src and count a size of more than 4 (uint32_t)+??(sgx_dh_msg1_t). So you copy more byte from source to dest.

I have written the smallest example, with two uint32_t instead of uint32_t and sgx_dh_msg1_t so you see the sizeof and can hopefully validate the issue.

[main.c.zip](https://github.com/intel/linux-sgx/files/5740354/main.c.zip)

**Comment by lzha101** [comment]
You could take` fifo_resp->msgbuf` as a variable length array instead of an array with 1 element.  `fifo_resp` is allocated on heap with a larger size than `sizeof(FIFO_MSG_HEADER) + 1`. The extra memory is for `msgbuf`.
