### ISSUE TITLE
Error of “make preparation”

### ISSUE THREAD

**Issue by CanYouGiveMeAName** [intel/linux-sgx#646]
When I do “make preparation” before, get error:

fatal: Not a git repository (or any parent up to mount point /opt)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
make: *** [preparation] Error 128

I download code of release vesion. I do not known why it must be git repository. What's the relation of git and make?

And another question, I want to test run with Docker. Can I pull a images directly intsead of build by myself?

Thanks very much.

**Comment by lzha101** [comment]
Yes, because we are having several submodules, it requires the repo must be cloned by git currently just as the descripted in top [README](https://github.com/intel/linux-sgx/blob/master/README.md)

> Download the source code and prepare the submodules and prebuilt binaries:
   $ git clone https://github.com/intel/linux-sgx.git
   $ cd linux-sgx && make preparation

**Comment by lzha101** [comment]
> And another question, I want to test run with Docker. Can I pull a images directly intsead of build by myself?

Currently we don't release any docker images. So you need to build it by yourself.

**Comment by CanYouGiveMeAName** [comment]
> Yes, because we are having several submodules, it requires the repo must be cloned by git currently just as the descripted in top [README](https://github.com/intel/linux-sgx/blob/master/README.md)
> 
> > Download the source code and prepare the submodules and prebuilt binaries:
> > $ git clone https://github.com/intel/linux-sgx.git
> > $ cd linux-sgx && make preparation

Thanks.
But you known, we like to use release version in practical use. If clone, i had to use the latested or reset to corresponding commit.

**Comment by lzha101** [comment]
I'm afraid you have to do so.  You can checkout a tag via command `git checkout tags/<target_tag> -b <tag_name>`, it may help to avoid finding out the specific commit for one release.

**Comment by CanYouGiveMeAName** [comment]
> I'm afraid you have to do so. You can checkout a tag via command `git checkout tags/<target_tag> -b <tag_name>`, it may help to avoid finding out the specific commit for one release.

Yeah，I know. Still suggest to make it easy to build on release version.
Thanks.
