### ISSUE TITLE
Must support sgx if run with Docker？

### ISSUE THREAD

**Issue by CanYouGiveMeAName** [intel/linux-sgx#647]
I want to test run with Docker. According to README, it need to install  "SGX Flexible Launch Control driver". And this is based on sgx. Does it means my machine must support sgx? If so, I  do‘t’ undestand the value of docker. And it is not quick start.

Another question. In build_and_run_aesm_docker.sh, it contain "docker build --target " do not have option target. I should install a higher version docker?

Thanks very much!

**Comment by lzha101** [comment]
If your host machine doesn't support SGX,  you could try simulation mode.  It would meet your requirement. 

As to the docker option, I checked the docker version on my Ubuntu18.04. It is installed via `apt` with version 19.03.5 and it has the option '--target'.

**Comment by CanYouGiveMeAName** [comment]
Thanks！
