### ISSUE TITLE
Intel SGX PSW prebuilt binary installation issues.

### ISSUE THREAD

**Issue by anand10717** [intel/linux-sgx#650]
I am trying to install SGX 2.7 using [prebuilt binaries](https://download.01.org/intel-sgx/sgx-linux/2.7/distro/centos7.5-server/) in the Intel Xeon 2288G with CentOS 7.6.1810. 

Following the instructions from https://download.01.org/intel-sgx/sgx-linux/2.7/docs/Intel_SGX_Installation_Guide_Linux_2.7_Open_Source.pdf

SGX Driver and SGX SDK installations are done. But While installing SGX PSW I am getting the following error,

`Unpacking Intel SGX PSW Package ... done.
Verifying the integrity of the install package ... done.
Installing Intel SGX PSW Package ... done.
/tmp/sgx-psw-7yvWKJ /home/sas/sgx
install -d /opt/intel/sgxpsw
install -d /opt/intel/sgxpsw/scripts
install -d /usr/lib64
cp -r package/* /opt/intel/sgxpsw
install scripts/* /opt/intel/sgxpsw/scripts
mv /opt/intel/sgxpsw/lib64/libsgx_uae_service.so /usr/lib64
mv /opt/intel/sgxpsw/lib64/libsgx_epid.so /usr/lib64
mv /opt/intel/sgxpsw/lib64/libsgx_launch.so /usr/lib64
mv /opt/intel/sgxpsw/lib64/libsgx_platform.so /usr/lib64
mv /opt/intel/sgxpsw/lib64/libsgx_quote_ex.so /usr/lib64
mv /opt/intel/sgxpsw/lib64/libsgx_urts.so /usr/lib64
mv /opt/intel/sgxpsw/lib64/libsgx_enclave_common.so /usr/lib64
rmdir /opt/intel/sgxpsw/lib64
cd /usr/lib64 && \
mv libsgx_enclave_common.so libsgx_enclave_common.so.1.0.105.4 && \
ln -fs libsgx_enclave_common.so.1.0.105.4 libsgx_enclave_common.so.1 && \
ln -fs libsgx_enclave_common.so.1 libsgx_enclave_common.so && \
mv libsgx_launch.so libsgx_launch.so.1.0.100.4 && \
ln -fs libsgx_launch.so.1.0.100.4 libsgx_launch.so.1 && \
ln -fs libsgx_launch.so.1 libsgx_launch.so && \
mv libsgx_platform.so libsgx_platform.so.1.0.100.4 && \
ln -fs libsgx_platform.so.1.0.100.4 libsgx_platform.so.1 && \
ln -fs libsgx_platform.so.1 libsgx_platform.so && \
mv libsgx_epid.so libsgx_epid.so.1.0.100.4 && \
ln -fs libsgx_epid.so.1.0.100.4 libsgx_epid.so.1 && \
ln -fs libsgx_epid.so.1 libsgx_epid.so && \
mv libsgx_quote_ex.so libsgx_quote_ex.so.1.0.100.4 && \
ln -fs libsgx_quote_ex.so.1.0.100.4 libsgx_quote_ex.so.1 && \
ln -fs libsgx_quote_ex.so.1 libsgx_quote_ex.so
/home/sas/sgx

Installing aesmd.service service ...Created symlink from /etc/systemd/system/multi-user.target.wants/aesmd.service to /usr/lib/systemd/system/aesmd.service.
 done.
Job for aesmd.service failed because the control process exited with error code. See "systemctl status aesmd.service" and "journalctl -xe" for details.
`

**Comment by anand10717** [comment]
Update : 

It seems installtion guide missed out some dependencies.

'sudo yum install cmake ocaml ocaml-ocamlbuild wget python2 openssl-devel'

after installing above I am able to install PSW without any errors.

**Comment by lzha101** [comment]
Glad to know the problem is solved. Actually the installation guide has a section **Prerequisites** before installation, see Page 6. 

> 2. On Red Hat* Enterprise Linux 7.4, Red Hat Enterprise Linux 8.0, CentOS* 7.5
and Fedora 27:
$ sudo yum install openssl-devel libcurl-devel protobufdevel
