### ISSUE TITLE
Error running make sdk_install_pkg

### ISSUE THREAD

**Issue by jackg235** [intel/linux-sgx#651]
When I run ```make sdk_install_pkg```, I get the following error:
```
as: unrecognized option '-mlfence-after-load=yes'
make[3]: *** [sethread_mutex.o] Error 1
Makefile:56: recipe for target 'sethread_mutex.o' failed
make[3]: Leaving directory '/sgx/drivers/linux-sgx/sdk/tlibthread'
Makefile.source:94: recipe for target 'tlibthread' failed
make[2]: Leaving directory '/sgx/drivers/linux-sgx/sdk'
Makefile:50: recipe for target 'all' failed
make[2]: *** [tlibthread] Error 2
make[1]: *** [all] Error 2
make[1]: Leaving directory '/sgx/drivers/linux-sgx/sdk'
make: *** [sdk] Error 2
Makefile:69: recipe for target 'sdk' failed
The command '/bin/sh -c ./download_prebuilt.sh &&     make clean &&     make sdk_install_pkg &&     make psw_install_pkg' returned a non-zero code: 2
```

Can someone assist?

**Comment by lzha101** [comment]
Seems you forgot to use the mitigation toolset. Please follow https://github.com/intel/linux-sgx/blob/master/README.md#prerequisites to use the toolset:

> Copy the mitigation tools corresponding to current OS distribution from external/toolset/{current_distr} to /usr/local/bin and make sure they have execute permission:
  $ sudo cp external/toolset/{current_distr}/{as,ld,ld.gold,objdump} /usr/local/bin
  $ which as ld ld.gold objdump

**Comment by jackg235** [comment]
> Seems you forgot to use the mitigation toolset. Please follow https://github.com/intel/linux-sgx/blob/master/README.md#prerequisites to use the toolset:
> 
> > Copy the mitigation tools corresponding to current OS distribution from external/toolset/{current_distr} to /usr/local/bin and make sure they have execute permission:
> > $ sudo cp external/toolset/{current_distr}/{as,ld,ld.gold,objdump} /usr/local/bin
> > $ which as ld ld.gold objdump

this worked, thanks a lot!

**Comment by aqqwwsszz** [comment]
When I encountered the make sdk error, I ran sudo cp external/toolset/{current_distr}/{as,ld,ld.gold,objdump} /usr/local/bin in the terminal
The command still reports an error, and the error message is as follows. How can I solve it? Hope to receive your reply Thank you!

![err0](https://user-images.githubusercontent.com/40340866/142868693-4a097545-aa37-49b9-9d52-82b27797aa44.png)
- [ ]

**Comment by FelixChan0829** [comment]
> When I encountered the make sdk error, I ran sudo cp external/toolset/{current_distr}/{as,ld,ld.gold,objdump} /usr/local/bin in the terminal The command still reports an error, and the error message is as follows. How can I solve it? Hope to receive your reply Thank you!
> 
> ![err0](https://user-images.githubusercontent.com/40340866/142868693-4a097545-aa37-49b9-9d52-82b27797aa44.png)
> 
> * [ ]

I meet the same issue as well. Have you fixed it?

**Comment by feknall** [comment]
> When I encountered the make sdk error, I ran sudo cp external/toolset/{current_distr}/{as,ld,ld.gold,objdump} /usr/local/bin in the terminal The command still reports an error, and the error message is as follows. How can I solve it? Hope to receive your reply Thank you!
> 
> ![err0](https://user-images.githubusercontent.com/40340866/142868693-4a097545-aa37-49b9-9d52-82b27797aa44.png)
> 
> * [ ]
@aqqwwsszz @FelixChan0829 
You must replace `{current_distr}` according to your distribution. Check directories in `external/toolset/` to find the current value. For example, I used `ubuntu20.04`.

**Comment by aqqwwsszz** [comment]
thank you！



发自我的iPhone


------------------ Original ------------------
From: Hamid Fazli ***@***.***&gt;
Date: Tue,Mar 15,2022 9:19 PM
To: intel/linux-sgx ***@***.***&gt;
Cc: aqqwwsszz ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [intel/linux-sgx] Error running make sdk_install_pkg (#651)





  
When I encountered the make sdk error, I ran sudo cp external/toolset/{current_distr}/{as,ld,ld.gold,objdump} /usr/local/bin in the terminal The command still reports an error, and the error message is as follows. How can I solve it? Hope to receive your reply Thank you!
 

  
[ ]
 @aqqwwsszz @FelixChan0829
 You must replace {current_distr} according to your distribution. Check directories in external/toolset/ to find the current value. For example, I used ubuntu20.04. 
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by FelixChan0829** [comment]
> > When I encountered the make sdk error, I ran sudo cp external/toolset/{current_distr}/{as,ld,ld.gold,objdump} /usr/local/bin in the terminal The command still reports an error, and the error message is as follows. How can I solve it? Hope to receive your reply Thank you!
> 
> @aqqwwsszz @FelixChan0829 The document is updated.
> 
> Try this one: `sudo cp external/toolset/{current_distr}/* /usr/local/bin`
> 
> You **must** replace `{current_distr}` according to your distribution.
> 
> Check directories in `external/toolset/` to find the current value. For example, I used `ubuntu20.04`. Then I executed `sudo cp external/toolset/ubuntu20.04/* /usr/local/bin`

Got it. Thanks!
