### ISSUE TITLE
How to download and build Intel(R) Deep Neural Network Library (DNNL)?

### ISSUE THREAD

**Issue by wrh0520** [intel/linux-sgx#653]
I tried to run the SampleDNNL, but when I tried to download and build the DNN library, I was failed. I was following the official documentations to download. How to deal with this problem?
Build the library.
      $ cd ./external/dnnl
      $ make
Makefile:84: recipe for target 'dnnl_src' failed

**Comment by lzha101** [comment]
Cannot reproduce the failure on Ubuntu18.04.  Does the above description include all the build log? 

The [external/dnnl/Makefile](https://github.com/intel/linux-sgx/blob/master/external/dnnl/Makefile) would download the correct dnnl source via  `git clone` and patch the source via `git am `before build.  You can try these commands separately and check if your git configuration is correct.
