### ISSUE TITLE
sgx_create_enclave hangs in infinite loop if EENTER faults

### ISSUE THREAD

**Issue by sean-jc** [intel/linux-sgx#66]
The signal handler installed by uRTS marks the SGX_ERROR_ENCLAVE_LOST if EENTER encounters an exception.  Up the stack, _create_enclave unconditionally retries __create_enclave if the return value is SGX_ERROR_ENCLAVE_LOST.  The intent of this code is to handle the scenario where the enclave is invalidated due to a power transition, in which case retrying __create_enclave will work, most of the time.  If EENTER faults for a different reason, e.g. a driver bug, then retrying __create_enclave will never succeed and the call to sgx_create_enclave will hang indefinitely.

At the very least, the do-while loop in _create_enclave needs to have a timeout counter to break out of the loop after an arbitrary number of failed attempts.  Ideally the retry logic would be exposed to the user, e.g. applications may want to control the number of retry attempts and preventing retries could be helpful for debugging.

**sig_handler.cpp**
```C
    else if(xip == get_eenterp()
            && SE_EENTER == xax)
    {
        assert(reinterpret_cast<tcs_t *>(xbx) == param->tcs);
        assert(ENCLU == (*xip & 0xffffff));
        SE_TRACE(SE_TRACE_NOTICE, "exception on EENTER\n");
        //enter_enlcave function will return with SE_ERROR_ENCLAVE_LOST
        context->uc_mcontext.gregs[REG_XIP] = reinterpret_cast<greg_t>(get_eretp());
        context->uc_mcontext.gregs[REG_XSI] = SGX_ERROR_ENCLAVE_LOST;
        return;
    }
```

**urts_com.h**
```C
    //Need to set the whole misc_attr instead of just secs_attr.
    do {
        ret = __create_enclave(parser, mh->base_addr, metadata, file, debug, lc, prd_css_file, enclave_id,
                               misc_attr);
        //SGX_ERROR_ENCLAVE_LOST caused by initializing enclave while power transition occurs
    } while(SGX_ERROR_ENCLAVE_LOST == ret);
```

**Comment by lzha101** [comment]
Even if we change the urts code to break out of the loop, applications will get an incorrect error code in this case.  
After some internal discussion, we decide to not fix this. Thanks.
