### ISSUE TITLE
error in docker

### ISSUE THREAD

**Issue by CanYouGiveMeAName** [intel/linux-sgx#661]
When run build_compose_run.sh and build_and_run_sample_docker.sh

Get error.

CFLAGS= CXXFLAGS= make -C /linux-sgx/external/vtune/linux/sdk/src/ittnotify/
make[6]: Entering directory '/linux-sgx/external/vtune/linux/sdk/src/ittnotify'
make[6]: Nothing to be done for 'all'.
make[6]: Leaving directory '/linux-sgx/external/vtune/linux/sdk/src/ittnotify'
g++ -Wnon-virtual-dtor -std=c++11 -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -UDEBUG -DNDEBUG -ffunction-sections -fdata-sections -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type -Waddress -Wsequence-point -Wformat-security -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow -Wcast-align -Wconversion -Wredundant-decls -DITT_ARCH_IA64 -DDISABLE_TRACE -fPIC -DSE_SIM -Werror -g -shared -Wl,-soname=libsgx_urts_sim.so enclave.o tcs.o loader.o se_detect.o enclave_mutex.o enclave_thread.o routine.o urts_xsave.o se_ocalls.o cpu_features.o cpu_features_ext.o node.o launch_checker.o  urts.o misc.o sig_handler.o debugger_support.o get_thread_id.o urts_trim.o urts_emodpr.o section.o elfparser.o enclave_creator_sim.o cpusvn_util.o crypto_evp_digest.o  enter_enclave.o xsave_gnu.o /linux-sgx/sdk/simulation/driver_api/driver_api.o /linux-sgx/sdk/simulation/assembly/linux/lowlib.o /linux-sgx/sdk/simulation/assembly/linux/sgxsim.o /linux-sgx/sdk/simulation/uinst/u_instructions.o /linux-sgx/sdk/simulation/uinst/enclave_mngr.o /linux-sgx/sdk/simulation/uinst/linux/set_tls.o /linux-sgx/sdk/simulation/uinst/linux/restore_tls.o -L/linux-sgx/common/se_wrapper -L/linux-sgx/sdk/simulation/uae_service_sim/linux -L/linux-sgx/external/vtune/linux/sdk/src/ittnotify/ -littnotify -ldl -lpthread -Wl,-z,relro,-z,now,-z,noexecstack -Wl,--version-script=/linux-sgx/psw/urts/linux/urts.lds -lwrapper -lcrypto -Wl,-Bdynamic -Wl,-Bsymbolic -lsgx_uae_service_sim -o libsgx_urts_sim.so
/usr/bin/ld: enclave.o: unable to initialize decompress status for section .debug_info
/usr/bin/ld: enclave.o: unable to initialize decompress status for section .debug_info
/usr/bin/ld: enclave.o: unable to initialize decompress status for section .debug_info
/usr/bin/ld: enclave.o: unable to initialize decompress status for section .debug_info
enclave.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
Makefile:136: recipe for target 'libsgx_urts_sim.so' failed
make[5]: *** [libsgx_urts_sim.so] Error 1
make[5]: Leaving directory '/linux-sgx/sdk/simulation/urtssim/linux'
Makefile:34: recipe for target 'all' failed
make[4]: Leaving directory '/linux-sgx/sdk/simulation/urtssim'
make[4]: *** [all] Error 2
Makefile:54: recipe for target 'urtssim' failed
make[3]: Leaving directory '/linux-sgx/sdk/simulation'
make[3]: *** [urtssim] Error 2
Makefile.source:244: recipe for target 'simulation' failed
make[2]: Leaving directory '/linux-sgx/sdk'
make[2]: *** [simulation] Error 2
Makefile:50: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/linux-sgx/sdk'
Makefile:64: recipe for target 'sdk_no_mitigation' failed
make: *** [sdk_no_mitigation] Error 2
The command '/bin/sh -c make sdk_install_pkg_no_mitigation' returned a non-zero code: 2

Please help, Thanks.

**Comment by lzha101** [comment]
Guess this is caused by the binutils mix usage.  Perhaps before you trigger the build in docker, you have some build history from host machine.  Suggest to cleanup the code repo and then retry the build in docker.

**Comment by CanYouGiveMeAName** [comment]
> Guess this is caused by the binutils mix usage. Perhaps before you trigger the build in docker, you have some build history from host machine. Suggest to cleanup the code repo and then retry the build in docker.

Thanks.

I read the Dockerfile. I feel that the steps are the same as installing the SDK in the operating system. So I want to install by bin file from https://download.01.org/intel-sgx/latest/linux-latest/distro/ubuntu18.04-server. But when install driver, get error

+ /opt/sgx_linux_x64_driver_1.36.2.bin
Unpacking Intel SGX Driver ... done.
Verifying the integrity of the install package ... done.
Installing Intel SGX Driver ...
/tmp/sgx-driver-ASYwgE /
install -d /opt/intel/sgxdriver/package
install -d /opt/intel/sgxdriver/scripts
cp -r package/* /opt/intel/sgxdriver/package
install scripts/* /opt/intel/sgxdriver/scripts
/

Creating symlink /var/lib/dkms/sgx/1.36.2/source ->
                 /usr/src/sgx-1.36.2

DKMS: add completed.
Error! Your kernel headers for kernel 4.15.0-118-generic cannot be found.
Please install the linux-headers-4.15.0-118-generic package,
or use the --kernelsourcedir option to tell DKMS where it's located

My machine support sgx. I had run sgx sample successfully.


Another problem. I can not find psw bin. Does it need in docker ？
