### ISSUE TITLE
Error installing 'libsgx-launch' package for PSW

### ISSUE THREAD

**Issue by oliverjohns** [intel/linux-sgx#663]
Im running Ubuntu 20.04 and SDK installation went fine, simulation mode works. But when I try to install Intel PSW I get an error. I run:

`sudo apt-get install libsgx-launch`

But then I get the following output and error:

> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  libsgx-launch : Depends: libprotobuf10 but it is not installable
>                  Recommends: libsgx-aesm-launch-plugin (>= 2.12.100.3-bionic1) but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.

I have done all the prior steps without an issue. I have installed libprotobuf-dev (3.6.1.3-2ubuntu5).

If I try to install the recommended libsgx-aesm-launch-plugin I get a similar error stating I have held broken packages.

Does anyone propose a fix?

**Comment by ScottR-Intel** [comment]
I've seen this type of dependency issue when pointing to the incorrect repo for the OS version.  Please confirm you're pointing to the 20.04/Focal repo and not an older repo, ie. 18.04/Bionic.

**Comment by oliverjohns** [comment]
> I've seen this type of dependency issue when pointing to the incorrect repo for the OS version. Please confirm you're pointing to the 20.04/Focal repo and not an older repo, ie. 18.04/Bionic.

Can you elaborate? Do you mean that im pointing to the wrong libprotobuf-dev package?

Thanks for helping out!

**Comment by ScottR-Intel** [comment]
To be able to install the SGX components via apt-get, you would have had to manually set up our SGX repo as mentioned in the [SGX Installation Guide for Linux](https://download.01.org/intel-sgx/latest/linux-latest/docs/Intel_SGX_Installation_Guide_Linux_2.12_Open_Source.pdf).  See page 8.  I will assume this is what you followed.  Depending on which version of Ubuntu you're using, the instruction to set up that repo in /etc/apt/sources.list.d/intel-sgx.list is different.  For 20.04, it should be pointing to the "focal" repo.  Please check the contents of the above file.

**Comment by oliverjohns** [comment]
> To be able to install the SGX components via apt-get, you would have had to manually set up our SGX repo as mentioned in the [SGX Installation Guide for Linux](https://download.01.org/intel-sgx/latest/linux-latest/docs/Intel_SGX_Installation_Guide_Linux_2.12_Open_Source.pdf). See page 8. I will assume this is what you followed. Depending on which version of Ubuntu you're using, the instruction to set up that repo in /etc/apt/sources.list.d/intel-sgx.list is different. For 20.04, it should be pointing to the "focal" repo. Please check the contents of the above file.

Thanks for helping out. I am positive that I am pointing to the focal repo, double checked it. I am running Xubuntu and lsb_release tells me:
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

Still not working unfortunately.

**Comment by ScottR-Intel** [comment]
Hi again.

I tried to reproduce on a fresh/clean install of Xubuntu 20.04 (xubuntu-20.04.2-desktop-amd64.iso) but was unable to do so.  This libprotobuf version was automatically downloaded and installed with no issue:  libprotobuf17_3.6.1.3-2ubuntu5_amd64.deb

The only other suggestion I can make is to apt-get purge all the sgx components and the libprotobuf package and try again.

More info below from my system:

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

cat /etc/apt/sources.list.d/intel-sgx.list
deb [arch=amd64] https://download.01.org/intel-sgx/sgx_repo/ubuntu focal main
