### ISSUE TITLE
Is there documentation on AESM?

### ISSUE THREAD

**Issue by sbellem** [intel/linux-sgx#665]
I am looking for documentation that explains what is AESM, its purpose, etc. Is there any? I assume it stands for Architectural/Application Enclave Service Manager ... as mentioned in https://github.com/intel/linux-sgx/blob/33f4499173497bdfdf72c5f61374c0fadc5c5365/psw/ae/aesm_service/config/aesmd_service/aesmd.conf#L1-L5

I would like to learn more about what it does. Thanks!

**Comment by llly** [comment]
Here is an introduction https://sgx101.gitbook.io/sgx101/sgx-bootstrap/enclave/interaction-between-pse-and-application-enclaves

**Comment by sbellem** [comment]
> Here is an introduction [Communication between Architectural and Application Enclaves](https://sgx101.gitbook.io/sgx101/sgx-bootstrap/enclave/interaction-between-pse-and-application-enclaves%60)

Thanks! That's very helpful. I think you left a backtick "`" by mistake at the end of the link (https://sgx101.gitbook.io/sgx101/sgx-bootstrap/enclave/interaction-between-pse-and-application-enclaves%60)

should be --> https://sgx101.gitbook.io/sgx101/sgx-bootstrap/enclave/interaction-between-pse-and-application-enclaves

**Comment by sbellem** [comment]
Will close this as the question has been answered. Thanks @llly!
