### ISSUE TITLE
tcmalloc in simulation mode error

### ISSUE THREAD

**Issue by MoeMahhouk** [intel/linux-sgx#670]
Hello there,

I have been developing a custom SGX benchmark tool for a while now and I linked libsgx_tcmalloc as a library. 
Everything used to work when using the sgxsdk versions 2.6 till 2.8.
However, once i patched the tool to the newest sdk's versions, running it with the hardware mode runs perfectly fine.
But in simulation mode it crashes immediately upon sgx_create() function with a segmentation fault when using sdk version 2.13.
With the sdk version 2.12, the tool runs well until the enclave finishes its work and ready to leave and it crashes immediately with double free error or free unallocated memory.
Not to mention, the same code is used for HW and SIM modes.

Could you please let me know if am doing something wrong or if this issue is already being investigated.

Thanks very much in advance

**Comment by xxu36** [comment]
Thanks for the feedback @MoeMahhouk 

 We've reproduced the same issue with 2.13 SDK and figured out the root cause. We are trying to fix the issue.

**Comment by lzha101** [comment]
Submitted a PR https://github.com/intel/linux-sgx/pull/683 to fix this issue.  @MoeMahhouk, please help to try if this could solve your problem. Thanks.
