### ISSUE TITLE
How does sgx_emmt determine the used heap size? Only monitor function 'malloc'/'calloc'/'realloc'/'free'?

### ISSUE THREAD

**Issue by AmbitionXiang** [intel/linux-sgx#685]
Hi, there. I want to know how the peak heap size returned by using sgx_emmt means for. 

For the following statement, I think the value return for sgx_emmt is near 13KB
In #458 , @ZongminGu said 

> "peak" means the max value. For example, one case: allocate 2K->allocate 3K->free 2K->allocate 4K -> allocate 1K-> free 1K-> allocate 6K->free 6K ->free 4K->free 3K. Then the Peak value is:
2+3-2+4+1-1+6=13K.

I insert some codes in functions 'malloc'/'calloc'/'realloc'/'free' to calculate the max value in the way stated above. But sometimes the value returned by sgx_emmt (e.g., 1GB) is much larger than the value I calculate (48MB). I don't know why. I guess there are something related to heap usage that is invisible for users. 

Does anyone have some ideas? Thank you.

**Comment by lzha101** [comment]
> I insert some codes in functions 'malloc'/'calloc'/'realloc'/'free' to calculate the max value in the way stated above

Could you detail how you calculate the max size?  Do you modify the memory operation functions in tlibc?

The malloc/calloc allocate memory on heap using sbrk(). In SGX, we use a global variable [g_peak_heap_used ](https://github.com/intel/linux-sgx/blob/master/sdk/tlibc/gen/sbrk.c#L41) to record the peak heap allocated for the executed enclave. sgx_emmt reads this variable during destroying enclave.  The memory management rule depends on the malloc implementation. Suppose it should not be simple data addition and subtraction.

**Comment by AmbitionXiang** [comment]
Oh, I understood. Thanks for your reply!
