### ISSUE TITLE
Can PCL protect the enclave code's confidentiality?

### ISSUE THREAD

**Issue by bronzeMe** [intel/linux-sgx#689]
Hi, I recently read the codes of [SampleEnclavePCL](https://github.com/intel/linux-sgx/tree/master/SampleCode/SampleEnclavePCL), and depend on my understanding, I have a question:  Can the PCL (protected code loader)  really protected the enclave code's confidentiality? 

At the build phase, the author of the enclave encrypts (using **sgx_encrypt** tool) his/her enclave using a key (called it **test_key.bin**, it is owned by the author), then the author signs the encrypted enclave and sends it to the remote cloud.

At the load phase, the **libsgx_pcl.a** linked statically to this enclave will decrypt the encrypted enclave, but, how does the author give the **test_key.bin** to  **libsgx_pcl.a** ? 

If the author simply send the test_key.bin to the remote cloud, the untrusted cloud can also decrypt the encrypted enclave using **sgx_encrypt**.

In the [SampleEnclavePCL](https://github.com/intel/linux-sgx/tree/master/SampleCode/SampleEnclavePCL),  there is a helper enclave called "seal enclave", and there is a hint "ISV must replace with secured key provisioning scheme, e.g. using remote attestation & TLS", which means the author should firstly create a secure channel with the "seal enclave" (a helper enclave used to get the test_key.bin) and then send the test_key.bin to the "seal enclave" , this "seal enclave" is responsible for creating a TLS with the author for receiving test_key.bin and then seals it using MRSIGNER, the simple seal enclave is also signed by the same author.  So the libsgx_pcl.a can unseal this encrypted test_key.bin sealed by the "seal enclave".

However, the untrusted cloud platform can also create a fake "seal enclave" to create a TLS with the author, then steal the test_key.bin, because that the logic of the "seal enclave" is simple, more important, the author cannot verify that if this "seal enclave" is developed by himself or not.

Remote attestation can only help the author  to ensure the remote platform is a real Intel SGX hardware platform, but it cannot verify the remote enclave running on the remote SGX CPU is the real enclave developed by the author or not.

Hence, it is a very important problem: how does the author of the enclave verify the remote enclave is really developed by himself?

**Comment by ScottR-Intel** [comment]
SGX Remote attestation does help you verify not only the SGX platform, but the identity and intactness of the remote enclave you'd like to send the key to.  For more info, see this [SGX RA Whitepaper](https://software.intel.com/content/www/us/en/develop/articles/code-sample-intel-software-guard-extensions-remote-attestation-end-to-end-example.html) and it's associated [code sample](https://github.com/intel/sgx-ra-sample).

**Comment by bronzeMe** [comment]
@ScottR-Intel Thank you so much for your reply, but there are still some doubts:

When building an enclave, the author uses the **sgx_sign** to sign his enclave code, the **sgx_sign** tool can calculate a measurement of this enclave, so the enclave's measurement is public, and SGX PCL does not encrypt this filed, so it is possible for the untrusted cloud the get this enclave measurement.

When performing SGX remote attestation, it  returns the enclave measurement to the author, however, it is possible for the untrusted cloud to patch the remote attestation codes and return the real measurement to the author, but actually running inside a fake enclave developed by the untrusted cloud.

**Comment by ScottR-Intel** [comment]
When performing SGX RA, one of the things your enclave will do is request a quote of itself and the platform, from the Quoting Enclave (QE), a special Architectural Enclave this is only allowed to do this.  This quote contains all the platform and enclave identity information and is encrypted with the Intel Attestation Service (IAS) public key, so only IAS can decrypt and verify.  Because of this, the quote cannot be faked.  Nor can the code that creates the quote (the QE) be patched.  Another good external description of this flow can be found [here](http://www.sgx101.com/portfolio/remote_attestation/).

**Comment by bronzeMe** [comment]
@ScottR-Intel Hi, "the quote cannot be faked",  but when the QE create a quote, it needs a enclave's (to be verified) report as input. So if an attacker can get the victim enclave's measurement it can create a fake enclave report to deceive the QE.  The QE will think this enclave report is generated by a real SGX CPU, the IAS will think this QUOTE is signed by a real QE, but the enclave identity in this QUOTE is fake.

As this [article](http://www.sgx101.com/portfolio/remote_attestation/) writes (as below), it is the author's duty to check the enclave's identity, 

"A positive Attestation Verification Report confirms the enclave as running a particular piece of code on a genuine intel SGX processor. **It is then the responsibility of the SP to validate the ISV enclave identity and serve an appropriate response back to the platform.**"

**Comment by ScottR-Intel** [comment]
The enclave calls the EREPORT (an SGX HW instruction) to create the report.  If you look at the actual [sgx_report structure](https://github.com/intel/linux-sgx/blob/c11985ef09a3c600055e05678252a3eceb5bbf1d/common/inc/sgx_report.h#L113), you'll notice it contains a MAC.  This MAC is filled in by the EREPORT instruction and is verifiable by the QE using EGETKEY to get the report key to do so.  Therefore, the report itself cannot be faked either.  Then, that known real report is what is added to the quote sent back to the SP to validate (with the help of IAS).

**Comment by bronzeMe** [comment]
Thank you so much @ScottR-Intel , it's so helpful ! 
So the MAC generated by the EREPORT instruction is a quite critical operation to guarantee that the enclave report cannot be faked.
An attacker may replace the measurement filed of an enclave report, but this can be detected by the QE by comparing the MAC.
