### ISSUE TITLE
Hardware Support

### ISSUE THREAD

**Issue by bradyjoestar** [intel/linux-sgx#694]
I searched the [SGX-hardware](https://github.com/ayeks/SGX-hardware) project and found it seems that the recently server(i.e 16-core cpu) not completely support SGX. 

Is there any plan for intel to support SGX on the high performance computing cpu?

Thanks a lot!

**Comment by ltinerary** [comment]
SGX Hardware Requirements：
    6th Generation Intel® Core™ Processor or newer
    Intel® SGX option enabled in BIOS.
And if you want use **ECDSA attestion**:
    8th Generation Intel® Core™ Processor or newer with Flexible Launch Control support*.
    Intel® Atom™ Processor with Flexible Launch Control support*.

You can find this in the [Guide](https://download.01.org/intel-sgx/sgx-linux/2.13/docs/Intel_SGX_Installation_Guide_Linux_2.13_Open_Source.pdf)

**Comment by ltinerary** [comment]
SGX Hardware Requirements：
- 6th Generation Intel® Core™ Processor or newer
- Intel® SGX option enabled in BIOS.

And if you want use **ECDSA attestion**:
- 8th Generation Intel® Core™ Processor or newer with Flexible Launch Control support*.
- Intel® Atom™ Processor with Flexible Launch Control support*.

You can find this in the [Guide](https://download.01.org/intel-sgx/sgx-linux/2.13/docs/Intel_SGX_Installation_Guide_Linux_2.13_Open_Source.pdf)
