### ISSUE TITLE
make preparation  failed

### ISSUE THREAD

**Issue by lengyijun** [intel/linux-sgx#695]
```
Fail to download file https://download.01.org/intel-sgx/sgx-linux/2.13.1/SHA256SUM_prebuilt_2.13.1.cfg
```

**Comment by lzha101** [comment]
Yes. Temporarily, please don't use the latest commit (63d0e65cfa49bb46a8dbe8745bb15aaf226faa97)  and use the previous commit instead.  We will make things ready and tag a new release. Please stay tune.
