### ISSUE TITLE
cd linux-sgx && make preparation

### ISSUE THREAD

**Issue by emrahsariboz** [intel/linux-sgx#696]
I receive the following error when I type "cd linux-sgx && make preparation" after cloning the  https://github.com/intel/linux-sgx.git

**Fail to download file https://download.01.org/intel-sgx/sgx-linux/2.13.1/optimized_libs_2.13.1.tar.gz
Makefile:53: recipe for target 'preparation' failed
make: *** [preparation] Error 255**

**Comment by llly** [comment]
2.13.1 packages from 01.org are temporarily unavailable. Currently you can use `sgx_2.13` release instead.
