### ISSUE TITLE
aesm_service returned error: 1

### ISSUE THREAD

**Issue by ltinerary** [intel/linux-sgx#702]
When I run  a **Grahene Dcap remote attestation** example([End-To-End Confidential PyTorch Workflow](https://graphene.readthedocs.io/en/latest/tutorials/pytorch/index.html#end-to-end-confidential-pytorch-workflow)),
I got an error with **aesm_service**:
```bash
error: aesm_service returned error: 1
error: load_enclave() failed with error -1
```
So I checked aesmd status,it looks work well:
```bash
root@ltinerary-QiTianM435-N000:/opt/intel/sgx-dcap-pccs/logs# service aesmd status
● aesmd.service - Intel(R) Architectural Enclave Service Manager
   Loaded: loaded (/lib/systemd/system/aesmd.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2021-04-27 15:01:23 CST; 26s ago
  Process: 7964 ExecStart=/opt/intel/sgx-aesm-service/aesm/aesm_service (code=exited, status=0/SUCCESS)
  Process: 7963 ExecStartPre=/bin/chmod 0750 /var/opt/aesmd/ (code=exited, status=0/SUCCESS)
  Process: 7962 ExecStartPre=/bin/chown -R aesmd:aesmd /var/opt/aesmd/ (code=exited, status=0/SUCCESS)
  Process: 7961 ExecStartPre=/bin/chmod 0755 /var/run/aesmd/ (code=exited, status=0/SUCCESS)
  Process: 7960 ExecStartPre=/bin/chown -R aesmd:aesmd /var/run/aesmd/ (code=exited, status=0/SUCCESS)
  Process: 7959 ExecStartPre=/bin/mkdir -p /var/run/aesmd/ (code=exited, status=0/SUCCESS)
  Process: 7953 ExecStartPre=/opt/intel/sgx-aesm-service/aesm/linksgx.sh (code=exited, status=0/SUCCESS)
 Main PID: 7965 (aesm_service)
    Tasks: 4 (limit: 4915)
   CGroup: /system.slice/aesmd.service
           └─7965 /opt/intel/sgx-aesm-service/aesm/aesm_service

4月 27 15:01:23 ltinerary-QiTianM435-N000 systemd[1]: Stopped Intel(R) Architectural Enclave Service Manager.
4月 27 15:01:23 ltinerary-QiTianM435-N000 systemd[1]: Starting Intel(R) Architectural Enclave Service Manager...
4月 27 15:01:23 ltinerary-QiTianM435-N000 systemd[1]: Started Intel(R) Architectural Enclave Service Manager.
4月 27 15:01:23 ltinerary-QiTianM435-N000 aesm_service[7965]: The server sock is 0x562684844330

```
And finally, in [aesm_error.h](https://github.com/intel/linux-sgx/blob/master/psw/ae/inc/internal/aesm_error.h) file,
I found the aesm error number means **AESM_UNEXPECTED_ERROR**.

What can I do for this error?
I have no idea.
Thanks.

### More Additional Information (2021.04.28)

- linux kernel : **5.4.114-custom**(patched with FSGSBASE)
- os : **ubuntu 18.04**
- cpu: **Intel(R) Core(TM) i7-10700**
- sgx driver:**DCAP driver(1.41)**

Maybe my operation is also related to this aesm service error：
When I intsall PCCS service and run the Graphene End-To-End Confidential PyTorch Workflow example（`SGX=1 ./pal_loader ./pytorch pytorchexample.py`），the PCCS logs showed Network request was 404：

<img width="948" alt="pccserror" src="https://user-images.githubusercontent.com/79144923/116353870-1affda00-a82a-11eb-87ba-1ae8997ad5ce.png">

I sloved the 404 error by Manually insert data into the PCCS database table _platform_tcbs_,

And then I run the Graphene End-To-End Confidential PyTorch Workflow example(`SGX=1 ./pal_loader ./pytorch pytorchexample.py`),it got **aesm service return error:1**.

Did this operation cause the aesm error?

That's all,Thanks!

**Comment by jiazhang0** [comment]
@ltinerary 

- Please clear pccs db (do backup and `rm pckcache.db`), set the `CachingFillMode` of pccs to `LAZY`, and then restart pccs.
- Run [DCAP sample programs](https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/SampleCode) and provide the results.
- Confirm whether you have already register the platform to Intel.
- Confirm whether you are using [SBX platform](https://github.com/alibaba/inclavare-containers/tree/master/hack/use-sbx-platform).

**Comment by ltinerary** [comment]
> @ltinerary
> 
> * Please clear pccs db (do backup and `rm pckcache.db`), set the `CachingFillMode` of pccs to `LAZY`, and then restart pccs.
> * Run [DCAP sample programs](https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/SampleCode) and provide the results.
> * Confirm whether you have already registered your platform to Intel.
> * Confirm whether you are using [SBX platform](https://github.com/alibaba/inclavare-containers/tree/master/hack/use-sbx-platform).

I followed the step1,and in the step2 ,I run the `DCAP sample programs`，it also get an error:
```bash
[set_extra_debug_info /etc/intel/gitSource/linux-sgx/psw/urts/enclave.cpp:591] Symbol 'g_peak_rsrv_mem_committed' is not found
[__create_enclave /etc/intel/gitSource/linux-sgx/psw/urts/urts_com.h:332] add tcs 0x7fb78250d000
[ecdsa_init_quote ../qe_logic.cpp:1241] Read ECDSA blob.
[read_persistent_data ../qe_logic.cpp:917] Couldn't find 'sgx_ql_read_persistent_data()' in the platform library. (null)
[ecdsa_init_quote ../qe_logic.cpp:1247] ECDSA Blob doesn't exist is persistent storage.  Try to use the cached version.
[ecdsa_init_quote ../qe_logic.cpp:1273] Invalid ECDSA Blob verificaton. 0xd004, generate a new key.
[ecdsa_init_quote ../qe_logic.cpp:1463] Generate and certify a new ECDSA attestation key
[ecdsa_init_quote ../qe_logic.cpp:1480] Get ATT Key.
[get_platform_quote_cert_data ../qe_logic.cpp:342] Found the sgx_ql_get_quote_config and sgx_ql_free_quote_config API.
[get_platform_quote_cert_data ../qe_logic.cpp:343] Request the Quote Config data.
[get_platform_quote_cert_data ../qe_logic.cpp:346] Error returned from the p_sgx_get_quote_config API. 0xe011
Error in sgx_qe_get_target_info. 0xe011
```
and in step3,I use this Primary key to config my pccs server.
> Confirm whether you have already registered your platform to Intel

![image](https://user-images.githubusercontent.com/79144923/117906212-0f6ee180-b307-11eb-91a5-372fae1a00d9.png)

But in step4,
How can I confirm I am using the SBX platform or not?
Thanks @jiazhang0

**Comment by jiazhang0** [comment]
@ltinerary 

Run the following commands to confirm whether you have a sbx platform:
```shell
strings /sys/firmware/efi/efivars/SgxRegistrationConfiguration-18b3bc81-e210-42b9-9ec8-2c5a7d4d89b6  | grep intel.com
```

If the result is `https://sbx.api.trustedservices.intel.com:443`, please  go to https://sbx.api.portal.trustedservices.intel.com/provisioning-certification to subscribe the sbx primary key. And then run the steps as mentioned in [this page](https://github.com/alibaba/inclavare-containers/tree/master/hack/use-sbx-platform).

**Comment by ltinerary** [comment]
> @ltinerary
> 
> Run the following commands to confirm whether you have a sbx platform:
> 
> ```shell
> strings /sys/firmware/efi/efivars/SgxRegistrationConfiguration-18b3bc81-e210-42b9-9ec8-2c5a7d4d89b6  | grep intel.com
> ```
> 
> If the result is `https://sbx.api.trustedservices.intel.com:443`, please go to https://sbx.api.portal.trustedservices.intel.com/provisioning-certification to subscribe the sbx primary key. And then run the steps as mentioned in [this page](https://github.com/alibaba/inclavare-containers/tree/master/hack/use-sbx-platform).

Thank you.
But I just run the command,I found this file didn't exsit in my computer.
```bash
root@fan-QiTianM435-N000:/sys/firmware/efi/efivars# ls -al | grep Sgx
-rw-r--r-- 1 root root   20 5月  12 10:15 CpuSetupSgxEpochData-b08f97ff-e6e8-4193-a997-5e9e9b0adb32
root@fan-QiTianM435-N000:/sys/firmware/efi/efivars# 
```
What does it mean that this file does not exist？

**Comment by jiazhang0** [comment]
> > @ltinerary
> > Run the following commands to confirm whether you have a sbx platform:
> > ```shell
> > strings /sys/firmware/efi/efivars/SgxRegistrationConfiguration-18b3bc81-e210-42b9-9ec8-2c5a7d4d89b6  | grep intel.com
> > ```
> > 
> > 
> >   
> >     
> >     
> > 
> >     
> >     
> > 
> >   
> > 
> > 
> > If the result is `https://sbx.api.trustedservices.intel.com:443`, please go to https://sbx.api.portal.trustedservices.intel.com/provisioning-certification to subscribe the sbx primary key. And then run the steps as mentioned in [this page](https://github.com/alibaba/inclavare-containers/tree/master/hack/use-sbx-platform).
> 
> Thank you.
> But I just run the command,I found this file didn't exsit in my computer.
> 
> ```shell
> root@fan-QiTianM435-N000:/sys/firmware/efi/efivars# ls -al | grep Sgx
> -rw-r--r-- 1 root root   20 5月  12 10:15 CpuSetupSgxEpochData-b08f97ff-e6e8-4193-a997-5e9e9b0adb32
> root@fan-QiTianM435-N000:/sys/firmware/efi/efivars# 
> ```
> 
> What does it mean that this file does not exist？

Please try these commands:

```shell
ls -l /sys/firmware/efi/vars/SgxRegistrationConfiguration-18b3bc81-e210-42b9-9ec8-2c5a7d4d89b6/
grep EFIVAR /boot/config-`uname -r` 
```

If both returns unexpected results, it proves the platform BIOS needs to be updated to the latest.

**Comment by ltinerary** [comment]
Here is my result:
```bash
root@fan-QiTianM435-N000:/etc/intel/gitSource/SGXDataCenterAttestationPrimitives# ls -l /sys/firmware/efi/vars/SgxRegistrationConfiguration-18b3bc81-e210-42b9-9ec8-2c5a7d4d89b6/
ls: cannot access '/sys/firmware/efi/vars/SgxRegistrationConfiguration-18b3bc81-e210-42b9-9ec8-2c5a7d4d89b6/': No such file or directory
root@fan-QiTianM435-N000:/etc/intel/gitSource/SGXDataCenterAttestationPrimitives# grep EFIVAR /boot/config-`uname -r`
CONFIG_EFIVAR_FS=y
```
and my BIOS is updated the latest version that the Lenovo can provided.
![image](https://user-images.githubusercontent.com/79144923/117915236-772d2880-b317-11eb-9739-1ba8633d6363.png)

**Comment by jiazhang0** [comment]
@ltinerary Could you provide the details of `lscpu`?

**Comment by ltinerary** [comment]
```bash
root@fan-QiTianM435-N000:/etc/intel/gitSource/SGXDataCenterAttestationPrimitives# lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              16
On-line CPU(s) list: 0-15
Thread(s) per core:  2
Core(s) per socket:  8
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               165
Model name:          Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
Stepping:            5
CPU MHz:             799.898
CPU max MHz:         4800.0000
CPU min MHz:         800.0000
BogoMIPS:            5799.77
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            16384K
NUMA node0 CPU(s):   0-15
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp pku ospke md_clear flush_l1d arch_capabilities
root@fan-QiTianM435-N000:/etc/intel/gitSource/SGXDataCenterAttestationPrimitives# 

```
**linux kernel** : 5.4.114-custom(patched with FSGSBASE)
**os** : ubuntu 18.04
**cpu**: Intel(R) Core(TM) i7-10700
**sgx driver**:DCAP driver(1.41)

Thanks.

**Comment by jiazhang0** [comment]
It looks like your machine is client platform not a server platform, so it should not be a multiple-socket platform and may be not related to SBX.

First, run this command to confirm whether you are using a uefi system:
```shell
ls -l /sys/firmware
```

In addition, run this sgx hw capability detection tool and show me the results:
```shell
https://github.com/ayeks/SGX-hardware
```

**Comment by ltinerary** [comment]
> ls -l /sys/firmware

```bash
root@fan-QiTianM435-N000:/etc/intel/gitSource/SGXDataCenterAttestationPrimitives# ls -l /sys/firmware
total 0
drwxr-xr-x  6 root root 0 5月  12 10:15 acpi
drwxr-xr-x  3 root root 0 5月  12 10:29 dmi
drwxr-xr-x  6 root root 0 5月  12 10:15 efi
drwxr-xr-x 27 root root 0 5月  12 10:29 memmap
```

The second commands result:
```bash
root@fan-QiTianM435-N000:/etc/intel/gitSource/SGX-hardware# ./test-sgx
eax: a0655 ebx: 9100800 ecx: 7ffafbff edx: bfebfbff
stepping 5
model 5
family 6
processor type 0
extended model 10
extended family 0
smx: 1

Extended feature bits (EAX=07H, ECX=0H)
eax: 0 ebx: 29c67af ecx: 40000018 edx: bc000400
sgx available: 1
sgx launch control: 1

CPUID Leaf 12H, Sub-Leaf 0 of Intel SGX Capabilities (EAX=12H,ECX=0)
eax: 1 ebx: 0 ecx: 0 edx: 241f
sgx 1 supported: 1
sgx 2 supported: 0
MaxEnclaveSize_Not64: 1f
MaxEnclaveSize_64: 24

CPUID Leaf 12H, Sub-Leaf 1 of Intel SGX Capabilities (EAX=12H,ECX=1)
eax: 36 ebx: 0 ecx: 21f edx: 0

CPUID Leaf 12H, Sub-Leaf 2 of Intel SGX Capabilities (EAX=12H,ECX=2)
eax: 90200001 ebx: 0 ecx: 5e00001 edx: 0
size of EPC section in Processor Reserved Memory, 94 M

CPUID Leaf 12H, Sub-Leaf 3 of Intel SGX Capabilities (EAX=12H,ECX=3)
eax: 0 ebx: 0 ecx: 0 edx: 0
size of EPC section in Processor Reserved Memory, 0 M

CPUID Leaf 12H, Sub-Leaf 4 of Intel SGX Capabilities (EAX=12H,ECX=4)
eax: 0 ebx: 0 ecx: 0 edx: 0
size of EPC section in Processor Reserved Memory, 0 M

CPUID Leaf 12H, Sub-Leaf 5 of Intel SGX Capabilities (EAX=12H,ECX=5)
eax: 0 ebx: 0 ecx: 0 edx: 0
size of EPC section in Processor Reserved Memory, 0 M

CPUID Leaf 12H, Sub-Leaf 6 of Intel SGX Capabilities (EAX=12H,ECX=6)
eax: 0 ebx: 0 ecx: 0 edx: 0
size of EPC section in Processor Reserved Memory, 0 M

CPUID Leaf 12H, Sub-Leaf 7 of Intel SGX Capabilities (EAX=12H,ECX=7)
eax: 0 ebx: 0 ecx: 0 edx: 0
size of EPC section in Processor Reserved Memory, 0 M

CPUID Leaf 12H, Sub-Leaf 8 of Intel SGX Capabilities (EAX=12H,ECX=8)
eax: 0 ebx: 0 ecx: 0 edx: 0
size of EPC section in Processor Reserved Memory, 0 M

CPUID Leaf 12H, Sub-Leaf 9 of Intel SGX Capabilities (EAX=12H,ECX=9)
eax: 0 ebx: 0 ecx: 0 edx: 0
size of EPC section in Processor Reserved Memory, 0 M
root@fan-QiTianM435-N000:/etc/intel/gitSource/SGX-hardware# 

```
----------

> It looks like your machine is client platform not a server platform, so it should not be a multiple-socket platform and may be not related to SBX.

Seeing this, I suddenly realized that I was installing the ubuntu 18.04 desktop version.
Does it matter?
And what does the `multiple-socket platform` mean?
Thanks~

**Comment by jiazhang0** [comment]
@ltinerary Your platform is sgx1 not sgx2, so they are different on remote attestation procedure. Basically sgx1 machine uses epid-based remote attestation and sgx2 machine (and certain customized sgx1.5 machine) uses ecdsa-based remote attestation. Therefore, you initially mentioned "PCCS service", which is the term used in the story of epid-based remote attestation. I mean Graphene End-To-End Confidential PyTorch Workflow example may be not runnable on your sgx1 machine. Please talk with Graphene community to confirm it.

**Comment by ltinerary** [comment]
Thanks very much for your reply, my platform is SGX1 for sure, but with FLC support, I thought the SGX1+FLC should be compatible with Dcap driver and ecdsa-based remote attestation. We have also a server SGX1+FLC running smoothly with PCCS service.

Here is the output of the ./test-sgx of that ecdsa-based server that works with ecdsa-based remote attestation:
```bash
(base) ubuntu@ingeborg:~/SGX-hardware$ ./test-sgx

eax: 906ed ebx: 100800 ecx: 7ffafbff edx: bfebfbff

stepping 13

model 14

family 6

processor type 0

extended model 9

extended family 0

smx: 1

Extended feature bits (EAX=07H, ECX=0H)

eax: 0 ebx: 29c67af ecx: 40000000 edx: bc000600

sgx available: 1

sgx launch control: 1

CPUID Leaf 12H, Sub-Leaf 0 of Intel SGX Capabilities (EAX=12H,ECX=0)

eax: 1 ebx: 0 ecx: 0 edx: 241f

sgx 1 supported: 1

sgx 2 supported: 0

MaxEnclaveSize_Not64: 1f

MaxEnclaveSize_64: 24

CPUID Leaf 12H, Sub-Leaf 1 of Intel SGX Capabilities (EAX=12H,ECX=1)

eax: 36 ebx: 0 ecx: 1f edx: 0

CPUID Leaf 12H, Sub-Leaf 2 of Intel SGX Capabilities (EAX=12H,ECX=2)

eax: 70200001 ebx: 0 ecx: bd80001 edx: 0

size of EPC section in Processor Reserved Memory, 189 M

CPUID Leaf 12H, Sub-Leaf 3 of Intel SGX Capabilities (EAX=12H,ECX=3)

eax: 0 ebx: 0 ecx: 0 edx: 0

size of EPC section in Processor Reserved Memory, 0 M

CPUID Leaf 12H, Sub-Leaf 4 of Intel SGX Capabilities (EAX=12H,ECX=4)

eax: 0 ebx: 0 ecx: 0 edx: 0

size of EPC section in Processor Reserved Memory, 0 M

CPUID Leaf 12H, Sub-Leaf 5 of Intel SGX Capabilities (EAX=12H,ECX=5)

eax: 0 ebx: 0 ecx: 0 edx: 0

size of EPC section in Processor Reserved Memory, 0 M

CPUID Leaf 12H, Sub-Leaf 6 of Intel SGX Capabilities (EAX=12H,ECX=6)

eax: 0 ebx: 0 ecx: 0 edx: 0

size of EPC section in Processor Reserved Memory, 0 M

CPUID Leaf 12H, Sub-Leaf 7 of Intel SGX Capabilities (EAX=12H,ECX=7)

eax: 0 ebx: 0 ecx: 0 edx: 0

size of EPC section in Processor Reserved Memory, 0 M

CPUID Leaf 12H, Sub-Leaf 8 of Intel SGX Capabilities (EAX=12H,ECX=8)

eax: 0 ebx: 0 ecx: 0 edx: 0

size of EPC section in Processor Reserved Memory, 0 M

CPUID Leaf 12H, Sub-Leaf 9 of Intel SGX Capabilities (EAX=12H,ECX=9)

eax: 0 ebx: 0 ecx: 0 edx: 0

size of EPC section in Processor Reserved Memory, 0 M
```
I do not really see the different (both SGX2:0, but with FLC:1)

Otherwise, how do you judge whether the machine could run with ecdsa or not? Thanks

**Comment by jiazhang0** [comment]
@ltinerary Absolutely, DCAP driver (and current sgx in-tree driver)  only supports the machines with FLC feature regardless of sgx1 or sgx2. ecdsa-based remote attestation is only available on sgx2 in principle, but there is an exception: Azure deploys some customized sgx1 machines with ecdsa-based remote attestation. So if we consider the exception, there is no accurate way to check whether a hardware supports ecdsa-based remote attestation. The easiest way to check is to run DCAP sample programs and see the results.

**Comment by ScottR-Intel** [comment]
Please see this article concerning FLC platforms:  https://www.intel.com/content/www/us/en/support/articles/000057420/software/intel-security-products.html

**Comment by ltinerary** [comment]
Thanks @jiazhang0 @ScottR-Intel .
I will check with the OEM.
