### ISSUE TITLE
How to calculate a enclave's MRSIGNER?

### ISSUE THREAD

**Issue by Keepmoving-ZXY** [intel/linux-sgx#717]
Hello, I have a more detailed understand sgx local attestation code, and the MRSIGNER value is hard-code:https://github.com/intel/linux-sgx/blob/82cd9d4cce8662dbc4b95b8f15d91b49a2d7aaf6/SampleCode/LocalAttestation/EnclaveInitiator/EnclaveInitiator.cpp#L52
but I don't know how to calculate value, so could you tell me how to calculate it?

**Comment by ENOTTY** [comment]
Use `sgx_sign dump`. For example, `sgx_sign dump -enclave /opt/intel/sgx-aesm-service/aesm/libsgx_le.signed.so -dumpfile /tmp/xxx` will dump the launch enclave metadata to `/tmp/xxx`. The MRSIGNER value is at the bottom.

**Comment by Keepmoving-ZXY** [comment]
oh, Intel has provide a tool to caluclate MRSIGNER value in [intel-ra-sample](https://github.com/intel/sgx-ra-sample/blob/master/mrsigner.c).   
The usage is:
```
sgx_sign dump -enclave libenclave_responder.signed.so -cssfile /tmp/responder_sig -dumpfile /tmp/responder_txt
```
then compile the mrsigner.c, the binary file called `signer`, finally `./signer /tmp/responder_sig` make effects.

**Comment by Keepmoving-ZXY** [comment]
@ENOTTY the way of yours is more convince, so thank you.
