### ISSUE TITLE
sgx_ippcp.h: No such file or directory

### ISSUE THREAD

**Issue by sbellem** [intel/linux-sgx#719]
When building `ipp-crypto` from source as per the [README.md](https://github.com/intel/linux-sgx/tree/master/external/ippcp_internal) under `./external/ippcp_internal/` the `sgx_ippcp.h` header file is missing, which causes problems when building the sdk. Not sure how one is supposed to build IPP Crypto from source and use it to build the SDK without this header file. The header file is listed in the `.gitignore` https://github.com/intel/linux-sgx/blob/82cd9d4cce8662dbc4b95b8f15d91b49a2d7aaf6/.gitignore#L28

The missing header file is in the optimized libs (e.g. https://download.01.org/intel-sgx/sgx-linux/2.13.3/optimized_libs_2.13.3.tar.gz) which I understand are pulled when running `download_prebuilt.sh`, but in this case the goal is to build the IPP Crypto dependency from source, hence there should be no need to fetch binaries.

**Comment by lzha101** [comment]
@sbellem, this header file is indeed required by SGX build and could be extracted from optimized lib package.

`download_prebuilt.sh`  is not only for the optimized libs. It also pulls the prebuilt AEs, binutils. 
And we have integrated the execution for this script to the first code preparation step. See [README.md prerequisites](https://github.com/intel/linux-sgx/blob/master/README.md#prerequisites)

> Download the source code and prepare the submodules and prebuilt binaries:
   $ git clone https://github.com/intel/linux-sgx.git
   $ cd linux-sgx && make preparation

If follow the steps, suppose you've downloaded the header files before you build the IPP libs.

**Comment by sbellem** [comment]
Hey @lzha101, thanks for replying. I'd like to better understand the reasoning behind the current approach. 

If for a moment we only consider the step of building the SGX SDK:

* Are the prebuilt AEs required?
* Can a recent version of `binutils >= 2.35.1` available from https://www.gnu.org/software/binutils/ be used instead of using the provided prebuilt?
* Besides the `sgx_ippcp.h` header file, is there anything else needed to build the SGX SDK?

Thank you!

**Comment by lzha101** [comment]
> Are the prebuilt AEs required?

AEs are not required for SDK but required for PSW/DCAP


> Can a recent version of binutils >= 2.35.1 available from https://www.gnu.org/software/binutils/ be used instead of using the provided prebuilt?

The preubuilt version we upload is built in a reproducible environment and the binaries are reproducible.  If you don't want to verify the reproducibility, I think you can use the official version. But I have no chance to validate it.

> Besides the sgx_ippcp.h header file, is there anything else needed to build the SGX SDK?

You can refer to the prerequisites in the top README.md for package dependency and find the code dependency from the top Makefile ( target `preparation`).
