### ISSUE TITLE
Debug std::string

### ISSUE THREAD

**Issue by Cheffu** [intel/linux-sgx#723]
GDB is not able to properly show the content of std::string. 
The problem might be related or even equal to pretty old and unsolved [Issue 251](https://github.com/intel/linux-sgx/issues/251), but I'm not sure.

Steps to reproduce:
* debug [SampleCode/SampleEnclave](https://github.com/intel/linux-sgx/tree/master/SampleCode/SampleEnclave)
* set breakpoint to Enclave/TrustedLibrary/Libcxx.cpp line 48
* view `std::string foo` in debugger

Result:
![image](https://user-images.githubusercontent.com/6339739/124121821-a5a4c580-da75-11eb-9d02-1df1cad8f7ca.png)

This behavior makes it basically impossible to debug an enclave processing strings.
The same is true for, e.g., std::map.

I'm using Ubuntu 20.04, gdb 9.2, and SGX SDK 2.13.3.

**Comment by haitaohuang** [comment]
Here is what I got with same versions of gdb, ubuntu, sdk

Breakpoint 1, ecall_exception () at Enclave/TrustedLibrary/Libcxx.cpp:46
46          std::string foo = "foo";
(gdb) p foo
$1 = {<std::__1::__basic_string_common<true>> = {<No data fields>},
  __r_ = {<std::__1::__libcpp_compressed_pair_imp<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, std::__1::allocator<char>, 2>> = {<std::__1::allocator<char>> = {<No data fields>},
      __first_ = {{__l = {__cap_ = 1869571590, __size_ = 0, __data_ = 0x0},
          __s = {{__size_ = 6 '\006', __lx = 6 '\006'},
            __data_ = "foo", '\000' <repeats 19 times>}, __r = {__words = {
              1869571590, 0, 0}}}}}, <No data fields>},
  static npos = 18446744073709551615}

Did u use some other debugger frontend?

**Comment by Cheffu** [comment]
My screenshot is from VSCode's debug UI instead of a direct gdb output.
But if you compare the outputs, they are equal. 
I just did not provide all the details.

A screenshot showing more details:
![image](https://user-images.githubusercontent.com/6339739/124283488-3ea61000-db4c-11eb-9700-d945175641a5.png)

If you look closely to our outputs, they deep down contain "foo". 
However, I still consider it basically impossible to debug an enclave processing strings with this debug output.
If you paste the same std::string to a location outside of an enclave, the debugger simply displays "foo", which is the only thing I'm interested in.

**Comment by haitaohuang** [comment]
This is dup of #251
