### ISSUE TITLE
SGX 2.14 AESM service cannot find the production signature for the LE enclave

### ISSUE THREAD

**Issue by dingxiangfei2009** [intel/linux-sgx#733]
This issue is referring to https://github.com/intel/linux-sgx/blob/5178e0c26b017a05ec41f6c8edf3cbe30736e2ee/psw/ae/aesm_service/source/oal/linux/aesm_util.cpp#L56

In PSW @ `v2.14`, the resolution of the signature file for LE fails, even though `le_prd_css.bin` is installed at `<installdir>/aesm` directory, while AESM service is trying to pick it up at `<installdir>/aesm/bundles` directory.

The reason is because possibly the LE loader code is moved into `lible_launch_service_bundle.so` located at `<installdir>/aesm/bundles` directory. Therefore, `aesm_get_path` resolves `AESM_LOCATION_EXE_FOLDER` constants to the `bundles` folder, instead of the directory in which the AESM executable actually resides, because this information is inferred from the dynamic loader.

A temporary fix on the user side is to move the signature BIN file into `bundles`, so that at least AESM can launch. However, the same issue may still stop other architecture enclaves from loading, including QE, PVE, PCE and so on.

Maybe we need a more declarative and robust way to infer the AESM service directory? Note that the SystemD service unit does designate an environment variable `AESM_PATH`, which seems much more authoritative.

**Comment by llly** [comment]
It should not happen.
`__builtin_return_address(0)` return the address of the current function `aesm_get_path`. `aesm_get_path` is in `liboal.so` instead of `lible_launch_service_bundle.so`.  `liboal.so` and `le_prd_css.bin` are both installed at `<installdir>/aesm`.

**Comment by dingxiangfei2009** [comment]
@llly `__builtin_return_address(0)` is actually the address to which `aesm_get_path` transfers the control at the end of its evaluation. You may refer to this [GCC documentation](https://gcc.gnu.org/onlinedocs/gcc/Return-Address.html) for its semantics.

So in this case, its caller *is* in `lible_launch_service_bundle.so`. This is what I see in the debugger.
![callstack](https://user-images.githubusercontent.com/6884440/126864737-c5963e0f-9e08-4dc3-8d50-69112ba61967.png)

I might be missing some contexts here. Is there a reason for the case that we need to consult with the dynamic linker to deduce the paths to these files?

**Comment by llly** [comment]
It's interesting.  You are right. It returns it's caller's addr. However `aesm_get_path` is a static function and its caller is in same source file
https://github.com/intel/linux-sgx/blob/5178e0c26b017a05ec41f6c8edf3cbe30736e2ee/psw/ae/aesm_service/source/oal/linux/aesm_util.cpp#L234
Maybe tail call optimization breaks the call stack. 
Can you provide you OS and gcc version?

**Comment by dingxiangfei2009** [comment]
Tail call optimization is enabled in this build, by inspecting the call site.

OS is Archlinux, with GCC 11.1.0.

**Comment by llly** [comment]
Thank you. I can reproduce this issue on Archlinux, gcc 11.1.0. Will create a PR to fix it.
