### ISSUE TITLE
Document --prefix option for sdk installer

### ISSUE THREAD

**Issue by sbellem** [intel/linux-sgx#734]
Is this option documented somewhere? When looking at the code, one can see that it's possible to pass `--prefix` to the installer to set a path where to install the sdk:

https://github.com/intel/linux-sgx/blob/5178e0c26b017a05ec41f6c8edf3cbe30736e2ee/linux/installer/bin/install-sgx-sdk.bin.tmpl#L96-L113

**Comment by lzha101** [comment]
We don't document this option. It seems easy to use this option. You can specify the prefix of SDK path with this option instead of the interactive mode:
`$ sgx_linux_x64_sdk_${version}.bin --prefix {SDK_INSTALL_PATH_PREFIX}`

**Comment by lzha101** [comment]
We have documented this option in README - https://github.com/intel/linux-sgx/tree/master#install-the-intelr-sgx-sdk-1

Close this issue.
