### ISSUE TITLE
All SGX download links appear to be broken...

### ISSUE THREAD

**Issue by yayoi-k** [intel/linux-sgx#741]
The download links on this page are broken:
https://01.org/intel-software-guard-extensions/downloads

The current links look like:
https://download.01.org/intel-sgx/sgx-dcap/1.11/linux/distro/ubuntu20.04-server/

However, in the past a working link looked similar to this:
https://download.01.org/intel-sgx/sgx-dcap/1.9/linux/distro/ubuntu20.04-server/sgx_linux_x64_driver_1.36.2.bin

However in the past I would have to use the following command to download the actual driver from said working link:
wget https://download.01.org/intel-sgx/sgx-dcap/1.9/linux/distro/ubuntu20.04-server/sgx_linux_x64_driver_1.36.2.bin

Please provide _working_ links or commands or whatever is necessary to actual obtain the driver.  Thank you

**Comment by lzha101** [comment]
Didn't see any broken download links on the webpage.

The driver is updated on DCAP 1.11 release. You can get the driver with below command:
`wget https://download.01.org/intel-sgx/sgx-dcap/1.11/linux/distro/ubuntu20.04-server/sgx_linux_x64_driver_1.41.bin`

**Comment by yayoi-k** [comment]
Thanks for the link you posted, that link you posted does work.  However I stand by my statement that no download links work on this page:
https://01.org/intel-software-guard-extensions/downloads

If you believe one of them does, please copy and paste it here to prove that.  

The links along the right side under DOWNLOADS all do not work.
![image](https://user-images.githubusercontent.com/2354113/131283700-91d897b9-6911-43b7-ab03-550d182385cd.png)

Links such as:
https://download.01.org/intel-sgx/sgx-linux/2.14/distro/ubuntu18.04-server/
https://download.01.org/intel-sgx/sgx-linux/2.14/distro/ubuntu20.04-server/
https://download.01.org/intel-sgx/sgx-linux/2.14/distro/rhel8.2-server/

Please demonstrate how these links work?

Thanks for looking into this.

**Comment by lzha101** [comment]
We have changed the post way to the OS level on 01.org for three years, because: 
1. The supported OSes are increased and the installers are more than before.  
2. We also provide the Debin repo which includes lots of packages.       

We cannot list all the installers and packages on the release webpage.

If my understanding is correct, you suggest us to provide the specific link for each installer on the webpage and then you can directly use the linkage with `wget`.  I think we will not plan to do this and we will continue follow current way.  You need to follow the link posted on[ 01.org](https://01.org/intel-software-guard-extensions/downloads) to [download.01.org ](https://download.01.org/intel-sgx/)to get the specific installer you want.

**Comment by yayoi-k** [comment]
Thank you for attempting to assist.  We're in some sort of twilight zone here in our conversation.

Facts:
- In your response, you posted the following link, which surprisingly does not work, this is the link you posted: https://download.01.org/intel-sgx/
![image](https://user-images.githubusercontent.com/2354113/131361988-4aa04746-ff75-4ed5-92b4-87f770e400fd.png)

Can we establish or can you dispute this fact?  Please prove that the link you provided works.  Works = some meaningful work of some kind can be accomplished with the link.  Please indicate how something meaningful can be accomplished with the link you provided.  Assume I know nothing and please show me how to somehow use the link you provided for something useful.

Similarly, all links I've tested on this page: https://01.org/intel-software-guard-extensions/downloads
Cannot be used for anything useful and cannot be used to accomplish anything.  They can't be used in a wget command as far as I can tell, and if visited with a web browser get a page cannot be displayed error.  Please explain to me how these links can be used for something?  If they cannot be used for anything and someone must use some other process, then they are bad links.

I don't think it would be so bad to provide working links one could use in the wget command, however if you choose not to do that, then please simply provide links that work, links that can lead to something useful, links that can be a part of accomplishing something.

As far as I can tell, all or most links on https://01.org/intel-software-guard-extensions/downloads cannot be used for anything.  If they can, please add instructions here and to the page as to how those links can be used.

I don't work at Intel and I cannot psychically translate this broken link https://download.01.org/intel-sgx/sgx-dcap/1.11/linux/distro/ubuntu20.04-server/
into this working link (wget command must be added, and then the link works): 
https://download.01.org/intel-sgx/sgx-dcap/1.11/linux/distro/ubuntu20.04-server/sgx_linux_x64_driver_1.41.bin

Lets not make technology and product success completely exclusive where one has to be an insider or developer and can somehow translate non-working links working links with information only you have.

Again look at my screenshot of your web page full of links and I challenge you to show how to turn the link ON THE PAGE into something useful.

Thanks again for trying.

-

**Comment by ENOTTY** [comment]
Hi @yayoi-k, All of those links work for me. In the past the SGX download pages have had issues being accessed from China. Could you kindly post your ISP and country that you are accessing the site from? Side note, I do not work for Intel.

**Comment by yayoi-k** [comment]
You're right!  Using a completely different internet connection solved the problem.  Very strange, but glad to know I wasn't losing my mind.  Thank again!
