### ISSUE TITLE
`edmm_utility.cpp`: no need to try to open the SGX driver

### ISSUE THREAD

**Issue by dimakuv** [intel/linux-sgx#756]
We encounter a benign error message from the Intel SGX SDK `edmm_utility.cpp` file:
```
[get_driver_type /home/sgx/jenkins/linux-ubuntuServer-release-build-trunk-214/build_target/PROD/label/Builder-UbuntuSrv18/label_exp/ubuntu64/linux-trunk-opensource/psw/urts/linux/edmm_utility.cpp:111]
Failed to open Intel SGX device.
```

This happens when we use the DCAP libraries `libdcap_quoteprov.so`, `libsgx_dcap_ql.so` and `libsgx_dcap_quoteverify.so` **from within the SGX enclave** (we are the developers of Gramine-SGX: https://github.com/gramineproject/gramine). As you can imagine, it is prohibited to try to open the Intel SGX driver from inside the SGX enclave. So we wonder: is there a way to supress this error message in any way? Why would the DCAP library even try to do some EDMM work, and why would the DCAP library try to open the SGX driver? Am I missing some switch or environment variable to supress the DCAP library from doing this?

The error doesn't affect anything but it is annoying to see. I don't remember this error in previous versions of Intel SGX SDK.

In fact, this is the code snippet where this error is printed: https://github.com/intel/linux-sgx/blob/e6d626d0badd08a9b5eaa8f51643980418925ffc/psw/urts/linux/edmm_utility.cpp#L111

I notice that this error message was bumped from "warning" to "production error" in Linux 2.13 Open Source Gold Release: https://github.com/intel/linux-sgx/commit/73b8b57aea306d1633cc44a2efc40de6f4217364#diff-3a4e3baf7ecd3c8e755803c751aff2e0870835c22a92b13944dd4b84e9d520da

**Comment by dimakuv** [comment]
We observed the same error message when using the DCAP libraries in a non-SGX "verification" program.

DCAP libraries can be used also in non-SGX environments, right? For example, our program only receives the SGX quote from the remote SGX enclave and invokes DCAP libraries to determine if the SGX quote is fine (for this, the DCAP libraries talk to the PCCS; no SGX hardware should be involved).

So why is there an assumption that DCAP libraries can access the SGX driver on the machine? It doesn't make sense to me.

**Comment by dimakuv** [comment]
https://github.com/intel/SGXDataCenterAttestationPrimitives/issues/107 -- I seem to hit this problem every 6 months, solve it and forget how I solved it :)

The solution is to use an environment variable `SGX_AESM_ADDR = 1`.

**Comment by llly** [comment]
Current `libsgx_dcap_quoteverify.so` always tries to load QVE enclave first.
There is a wrong package dependence that `libsgx-dcap-ql` depends on `libsgx-ae-qve`. In your case,  only `libsgx-dcap-ql` installed without `libsgx-ae-qve`(/usr/lib/x86_64-linux-gnu/libsgx_qve.signed.so for Ubuntu) can fix the message when using `libsgx_dcap_quoteverify.so`. 
I'll create a PR to fix it. But prebuilt installer packages in 01.org with the fix will not be available until next release.

**Comment by dimakuv** [comment]
Thanks @llly for the detailed answer! I hope it will get fixed in one of the next releases. For now, looks like we can use your proposed workaround.

**Comment by dimakuv** [comment]
@llly Feel free to close this issue. I'm leaving it open in case you want to mark it in your PR to be closed automatically (via "Fixes 756").
