### ISSUE TITLE
Build process is broken in cross compilation environments

### ISSUE THREAD

**Issue by jsakkine** [intel/linux-sgx#76]
libunwind fork included in cpprt fails to compile on cross compilation environments even if you patch autogen-linux.sh with an alternative HOST_OPT.

This has been a blocker for testing any kernel changes with SDK based tests for months now so it is better to make it visible here.

**Comment by andyzyb** [comment]
The libunwind project is not well supporting cross compiling itself.   So it likely needs to create different patches for different target OS.

**Comment by jsakkine-intel** [comment]
I would guess that it is the remaining part that breaks the compilation. There were some other build issues before but they are resolved. Is libunwind needed for enabling the enclave debugging? I'm just wondering if there could be a compilation option to compile the PSW and runtimes without any support for debugging. That would work as a workaround for my needs.

**Comment by andyzyb** [comment]
libunwind is only used in C++ runtime, if you don't need to use C++ code, then it can be disabled during build.

**Comment by jsakkine-intel** [comment]
Why the C++ runtime requires libunwind?

**Comment by andyzyb** [comment]
To support stack unwinding/manipulation during C++ exception inside Enclave.
