### ISSUE TITLE
how to use SE_SIM Macro in buildenv.mk

### ISSUE THREAD

**Issue by yilingxu** [intel/linux-sgx#765]
Hi, 

in buildenv.mk, I see folllow code: 
`ifdef SE_SIM
    COMMON_FLAGS += -DSE_SIM
endif`

if I run make sdk_no_mitigation SE_SIM=1, I will get follow error. My question is: The SE_SIM Macro in buildenv.mk could be open? If can, how to open? Thanks a lot.

`g++ -c -Wnon-virtual-dtor -std=c++11 -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -UDEBUG -DNDEBUG -DSE_SIM -ffunction-sections -fdata-sections -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type -Waddress -Wsequence-point -Wformat-security -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow -Wcast-align -Wconversion -Wredundant-decls -DITT_ARCH_IA64 -ffreestanding -nostdinc -fvisibility=hidden -fpie -fno-strict-overflow -fno-delete-null-pointer-checks -B/usr/local/bin  -nostdinc++ -Werror -fno-exceptions -fno-rtti -I/home/admin/dev/linux-sgx-origin/common/inc -I/home/admin/dev/linux-sgx-origin/common/inc/internal -I/home/admin/dev/linux-sgx-origin/common/inc/tlibc -I/home/admin/dev/linux-sgx-origin/sdk/tlibcxx/include -I/home/admin/dev/linux-sgx-origin/sdk/pthread -fPIC trts.cpp -o trts.o
trts.cpp:44:10: fatal error: t_instructions.h: No such file or directory
 #include "t_instructions.h"    /* for `g_global_data_sim' */
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
`

**Comment by lzha101** [comment]
SE_SIM is an internal macro. Please don't use it on your build command line.

**Comment by yilingxu** [comment]
你好，邮件已经收到，我会尽快给你回复。

**Comment by yilingxu** [comment]
> SE_SIM is an internal macro. Please don't use it on your build command line.

Thanks for your reply.

**Comment by lzha101** [comment]
It is internal used in our code/scripts for simulation mode libs generation. If you search the key word in the code, suppose you can get how we use it.

**Comment by yilingxu** [comment]
I got it, thanks.
