### ISSUE TITLE
Error in installing psw

### ISSUE THREAD

**Issue by saruvig** [intel/linux-sgx#766]
I get the following error while running make deb_psw_pkg
![image](https://user-images.githubusercontent.com/23428423/146734480-7271a334-9aa0-4783-a62c-7f132349daee.png)

I was able to successfully install SDK. My Kernel version is 5.11.0-1021-azure

**Comment by llly** [comment]
Run `source ${sgx-sdk-install-path}/environment` following README.

**Comment by saruvig** [comment]
Thanks. I followed the code and was able to build psw successfully.  But now when I try to build the local Debian package repository with the command: make deb_local_repo I get the following error.

![image](https://user-images.githubusercontent.com/23428423/146740608-8ec79bdc-6a7d-4569-b688-91259905c1f0.png)


Not able to understand this error.

**Comment by lzha101** [comment]
Please double confirm that you have installed the required tools for PSW build.  For ubuntu:

`  $ sudo apt-get install libssl-dev libcurl4-openssl-dev protobuf-compiler libprotobuf-dev debhelper cmake reprepro unzip`

**Comment by saruvig** [comment]
Thanks. Yes, the reprepro tool had to be installed. It is working now so closing this issue
