### ISSUE TITLE
Rely on `/dev/sgx_{enclave,provision}` instead of `/dev/sgx/{enclave,provision}`

### ISSUE THREAD

**Issue by veehaitch** [intel/linux-sgx#772]
The in-tree Linux kernel SGX driver creates the enclave device at `/dev/sgx_enclave` and the provisioning device at `/dev/sgx_provision`. In contrast, the out-of-tree DCAP driver used to create those devices nested below an `sgx` subdirectory, i.e., `/dev/sgx/enclave` and `/dev/sgx/provision`.

For backward compatibility, `linux-sgx` today ships udev rules to create symlinks from `/dev/sgx/enclave` to `/dev/sgx_enclave` and `/dev/sgx/provision` to `/dev/sgx_provision`. This seems reasonable; however, most—if not all—of the `linux-sgx` code still seems to reference the `enclave` and `provision` devices below `/dev/sgx/`:

https://github.com/intel/linux-sgx/blob/2ee53db4e8fd25437a817612d3bcb94b66a28373/psw/urts/linux/edmm_utility.cpp#L102

https://github.com/intel/linux-sgx/blob/2ee53db4e8fd25437a817612d3bcb94b66a28373/psw/urts/linux/edmm_utility.cpp#L152

https://github.com/intel/linux-sgx/blob/2ee53db4e8fd25437a817612d3bcb94b66a28373/psw/enclave_common/sgx_enclave_common.cpp#L472-L474

The comments suggest that the in-tree Linux driver creates the devices within `/dev/sgx/` which is clearly not the case.

**The current behavior causes all SGX applications to fail if the executing host uses the in-tree driver without a symbolic link `/dev/sgx/enclave -> ../sgx_enclave`.**

This is very relevant as systemd decided to not provide a symlink: https://github.com/systemd/systemd/pull/18944#issuecomment-795675952. Also, NixOS does not install any of the udev rules provided in this repository (too permissive). As far as I can tell, the SDK/PSW routines should try opening `/dev/sgx_{enclave,provision}` instead of `/dev/sgx/{enclave,provision}*`. At least, they should _also_ try the actual path of the SGX kernel devices, i.e., `/dev/sgx_enclave` and `/dev/sgx_provision`.

**Comment by lzha101** [comment]
Thanks for reporting this issue.  We have already updated the related modules to fix this in the internal repo some time ago. It will be included in the next release. Please stay tuned.

**Comment by haitaohuang** [comment]
this should already be resolved with new behavior that supports /dev/sgx_x nodes directly. symlink is optional and for backward compatibility only
