### ISSUE TITLE
cp: cannot stat 'external/toolset/{current_distr}/as' : No such file or directory

### ISSUE THREAD

**Issue by FelixChan0829** [intel/linux-sgx#778]
Hello, I am trying to build the "Prerequisites" part on Ubuntu 18.04. I have finished the `cd linux-sgx && make preparation`, and everything looks good. But when I tried `sudo cp external/toolset/{current_distr}/{as,ld,ld.gold,objdump} /usr/local/bin`, it shows "No such file ore directory". And it leads I cannot build the sdk. How can I fix it?
![4941642292763_ pic_hd](https://user-images.githubusercontent.com/61814345/149642896-3266f096-c4ed-4c94-a4ac-3d9634b8f7de.jpg)

**Comment by lzha101** [comment]
{current_distr} is a general express here. You need to replace it with the OS distro you are using. For your case, it is ubuntu18.04.

**Comment by FelixChan0829** [comment]
> {current_distr} is a general express here. You need to replace it with the OS distro you are using. For your case, it is ubuntu18.04.

@lzha101 Thank you for your reply. I have found the right path, but it still cannot find "ld.gold" file.
![4961642437321_ pic](https://user-images.githubusercontent.com/61814345/149807958-03f251bb-9d76-4c35-94ef-23658b5b737c.jpg)

**Comment by lzha101** [comment]
ld.gold is unnecessary. We have removed the dependency of ld.gold and remove this binary in some previous release. Seems the README is missed to update. Will update the README later.
