### ISSUE TITLE
Unmet build dependencies: debhelper (>= 8.0.0)

### ISSUE THREAD

**Issue by JaewonHur** [intel/linux-sgx#779]
I am trying to install SGX SDK and PSW on archlinux.

I installed all the required packages in the archlinux version (including `debhelper`),
but when I run `make deb_psw_pkg`, it says `error: Unmet build dependencies: debhelper (>= 8.0.0)`.
However I already have `debhelper` package version `13.4.1` (installed through `yay -S debhelper`).

Here's my system setting
**CPU: *Intel i7-8700***
**OS: *archlinux (endeavoros), kernel 5.15.13-arch1-1***
**debhelper version: *13.4.1***

Does anyone know the solution?

**Comment by llly** [comment]
Archlinux is not officially supported.  
Try this  instruction(https://wiki.archlinux.org/title/Creating_packages_for_other_distributions).
