### ISSUE TITLE
Questions about TLS data

### ISSUE THREAD

**Issue by LeoneChen** [intel/linux-sgx#786]
Why sgxsdk only support `__thread`, however do not support `thread_local`?

Why TLS data will be reused on switchless mode? Is there any policy to disable this feature?
![1643026205(1)](https://user-images.githubusercontent.com/35480440/150780598-e81154a4-d8ea-4283-99a2-22b3cde8d654.jpg)

**Comment by yanxue-intel** [comment]
Switchless should not used with TCS binding policy. The work thread need to handle different switchless ECALLS, so TLS data of worker thread does not need to be preserved.

**Comment by LeoneChen** [comment]
> Switchless should not used with TCS binding policy. The work thread need to handle different switchless ECALLS, so TLS data of worker thread does not need to be preserved.

Emm...  The question2 is that I want a feature that tworker will clear TLS data everytime it executes ecall, so the TLS data is cleared before entering ecall

**Comment by yanxue-intel** [comment]
Currently switchless doesn't support handling TLS data.

**Comment by LeoneChen** [comment]
> Currently switchless doesn't support handling TLS data.

Thanks, I got it. And how about question one?

**Comment by yanxue-intel** [comment]
__thread and thread_local only different keywords in GCC extension and C++11.

**Comment by LeoneChen** [comment]
> __thread and thread_local only different keywords in GCC extension and C++11.

The manual said sgxsdk only support `__thread`
![image](https://user-images.githubusercontent.com/35480440/153144741-4c31ee92-227c-435c-97ce-e76259da85f5.png)

When I use `thread_local` on c++ class object, compiler will complain `undefined reference to '__cxa_thread_atexit'`

**Comment by xxu36** [comment]
@LeoneChen `__thread` and `thread_local` are all used to declare thread local storage variables. `thread_local` is standardized in C++11 and needs C++ runtime support (i.e it needs `__cxa_thread_atexit()`). Currently in the SDK, we have not implemented this missing function.  So to use TLS variables in your application, you can just use `__thread` instead.

**Comment by LeoneChen** [comment]
> @LeoneChen `__thread` and `thread_local` are all used to declare thread local storage variables. `thread_local` is standardized in C++11 and needs C++ runtime support (i.e it needs `__cxa_thread_atexit()`). Currently in the SDK, we have not implemented this missing function. So to use TLS variables in your application, you can just use `__thread` instead.

But I think  maybe it's due to Enclave has no idea when thread will be truely destoryed, since after thread exiting enclave it can have two choice: 1) re-enter enclave and 2) truely destory, but sgxsdk do not know. Then there is no good time for sgxsdk to call `__cxa_thread_atexit()` and subsequent destructors

**Comment by LeoneChen** [comment]
> > @LeoneChen `__thread` and `thread_local` are all used to declare thread local storage variables. `thread_local` is standardized in C++11 and needs C++ runtime support (i.e it needs `__cxa_thread_atexit()`). Currently in the SDK, we have not implemented this missing function. So to use TLS variables in your application, you can just use `__thread` instead.
> 
> But I think maybe it's due to Enclave has no idea when thread will be truely destoryed, since after thread exiting enclave it can have two choice: 1) re-enter enclave and 2) truely destory, but sgxsdk do not know. Then there is no good time for sgxsdk to call `__cxa_thread_atexit()` and subsequent destructors

Today, I realize there is something incorrect. `thread_local` object will call `__tls_init` and `__cxa_thread_atexit` to register it's dtor, and dtor will be called in `__call_tls_dtors` when thread or executable exit.

How about provide `__tls_init` in SGXSDK to record all tls dtors and call these dtor at `sgx_destory_enclave`, which I think can emulate tls management and provide `thread_local` keyword support in SGXSDK
