### ISSUE TITLE
Support standard device paths: `/dev/sgx_*`

### ISSUE THREAD

**Issue by jarkkojs** [intel/linux-sgx#795]
I think one obvious thing that should be fixed in AESM is the device paths. E.g. then a trivial devtmpfs device export would just work without any udev daemon (or alike) is running. Now it's undoable. This prevents e.g. efficient kernel testing where you would preferably have all the user space in initramfs. Custom udev rules add unnecessary clutter and complexity. IMHO it would benefit of AESM to be compatible with systemd upstream (which includes all the udev shenanigans). This is not in my opinion too much asked.

Obviously `/dev/sgx/*` can still be supported with a trivial fallback procedure kind of thing.

**Comment by llly** [comment]
Do you mean we need to add `/dev/sgx_enclave` and `/dev/sgx_provision` to 
https://github.com/intel/linux-sgx/blob/f607f89ab1ac648c3e62a23991befdeb93f9bf9d/psw/ae/aesm_service/config/aesmd_service/aesmd.service#L29-L30
?
Yes.  AESM and other PSW components will support  `/dev/sgx_enclave` and `/dev/sgx_provision` in next release.

**Comment by jarkkojs** [comment]
Yes exactly! Good to hear, thank you.

**Comment by jarkkojs** [comment]
@npmccallum

**Comment by mythi** [comment]
> AESM and other PSW components will support /dev/sgx_enclave and /dev/sgx_provision in next release.

@llly I don't see a note about this in the release notes. Did it change?

**Comment by llly** [comment]
> > AESM and other PSW components will support /dev/sgx_enclave and /dev/sgx_provision in next release.
> 
> @llly I don't see a note about this in the release notes. Did it change?

Yes. SGX PSW, including AESM supports /dev/sgx_* now.

**Comment by jarkkojs** [comment]
OK great! Thank you!
