### ISSUE TITLE
A real remote attestation example using Intel service

### ISSUE THREAD

**Issue by mitar** [intel/linux-sgx#80]
It seems to me that current example uses a simulated remote attestation service and not the proper Intel ones? Could there be an example of a real remote attestation be provided, where the program doing the remote attestation connects to the Intel service to check if attestation is correct?

**Comment by andyzyb** [comment]
Please refer to the link below for remote attestation with Intel server.  You probably need to register SGX development service before getting access to Intel attestation server.

https://software.intel.com/formfill/sgx-onboarding

https://software.intel.com/sites/default/files/managed/3d/c8/IAS_1_0_API_spec_1_1_Final.pdf
