### ISSUE TITLE
error in build_and_run_aesm_docker

### ISSUE THREAD

**Issue by okcui** [intel/linux-sgx#800]
When run build_and_run_aesm_docker.sh, just show this, nothing occuered ; 
And I had run sgx and init Enclave successfully on my machine.
![image](https://user-images.githubusercontent.com/100447409/155808913-d913171c-cfea-4416-86df-908eea1e5482.png)

Please help.Thanks

**Comment by llly** [comment]
No error occurs. These lines are info message printed by AESM.
