### ISSUE TITLE
"No SOURCES given to target" error reported when trying to build SGX PSW on RHEL9.0 Beta

### ISSUE THREAD

**Issue by wfgenious** [intel/linux-sgx#801]
It reports the following error when trying to directly install PSW included in sgx-2.14.100.2-rhel.zip on RHEL9.0 Beta, so have to try building PSW from source code. We suspect it's probably a compatibility issue between cmake and PSW source code. Could u please help take a look? Many thanks. 

Error:

 Problem 1: conflicting requests

  - nothing provides libprotobuf.so.15()(64bit) needed by libsgx-epid-2.14.100.2-1.el8.x86_64

 Problem 2: conflicting requests

  - nothing provides libprotobuf.so.15()(64bit) needed by libsgx-launch-2.14.100.2-1.el8.x86_64

 Problem 3: conflicting requests

  - nothing provides libprotobuf.so.15()(64bit) needed by libsgx-quote-ex-2.14.100.2-1.el8.x86_64

 Problem 4: conflicting requests

  - nothing provides libprotobuf.so.15()(64bit) needed by sgx-aesm-service-2.14.100.2-1.el8.x86_64

However, it reports the following error when trying to build SGX PSW from source code on RHEL9.0 Beta:

-- Configuring done

CMake Error at qcnl/CMakeLists.txt:9 (add_library):

  No SOURCES given to target: sgx_default_qcnl_wrapper

CMake Error at qpl/CMakeLists.txt:8 (add_library):

  No SOURCES given to target: dcap_quoteprov

CMake Generate step failed.  Build files cannot be regenerated correctly.

make[3]: *** [Makefile:101: source/build/CMakeCache.txt] Error 1

make[3]: *** Deleting file 'source/build/CMakeCache.txt'

make[3]: Leaving directory '/root/sgx/linux-sgx/psw/ae/aesm_service'

make[2]: *** [Makefile:61: AESM] Error 2

make[2]: Leaving directory '/root/sgx/linux-sgx/psw/ae'

make[1]: *** [Makefile:52: AE] Error 2

make[1]: Leaving directory '/root/sgx/linux-sgx/psw'

make: *** [Makefile:62: psw] Error 2

**Comment by wfgenious** [comment]
anyone gets a chance to look into this issue? Thanks.

**Comment by lzha101** [comment]
> It reports the following error when trying to directly install PSW included in sgx-2.14.100.2-rhel.zip on RHEL9.0 Beta,

Could you please provide more info about the package ` sgx-2.14.100.2-rhel.zip`? Where did you get this package?

**Comment by wfgenious** [comment]
sgx-2.14.100.2-rhel.zip is an intel-provided package to facilitate the setup of SGX env and from my experiment it supports RHEL8.x but not RHEL9.0 Beta. I suppose that part can be omitted as it's used to explain the necessity of building PSW from source code.

**Comment by lzha101** [comment]
Please make sure you have installed all the dependency before build.  Seems the error message indicates you are missing the `protobuf-devel`. 
I tried the latest code on a RHEL9.0 beta VM - Everything works fine.

**Comment by wfgenious** [comment]
@lzha101 
Regarding missing protobuf-devel, you mean the error (section 1) reported when trying to install to install sgx-2.14.100.2-rhel.zip or (section 2) reported when trying to build PSW packages from source code? IMHO section 2 error doesn't look like protobuf-devel missing, and for section 1 does look like protobuf dependency, but IIRC i already checked that dependent packages were installed. 

section 1

**Problem 1: conflicting requests

nothing provides libprotobuf.so.15()(64bit) needed by libsgx-epid-2.14.100.2-1.el8.x86_64
Problem 2: conflicting requests

nothing provides libprotobuf.so.15()(64bit) needed by libsgx-launch-2.14.100.2-1.el8.x86_64
Problem 3: conflicting requests

nothing provides libprotobuf.so.15()(64bit) needed by libsgx-quote-ex-2.14.100.2-1.el8.x86_64
Problem 4: conflicting requests

nothing provides libprotobuf.so.15()(64bit) needed by sgx-aesm-service-2.14.100.2-1.el8.x86_64__**

section 2 

CMake Error at qcnl/CMakeLists.txt:9 (add_library):

No SOURCES given to target: sgx_default_qcnl_wrapper

CMake Error at qpl/CMakeLists.txt:8 (add_library):

No SOURCES given to target: dcap_quoteprov

CMake Generate step failed. Build files cannot be regenerated correctly.

make[3]: *** [Makefile:101: source/build/CMakeCache.txt] Error 1

make[3]: *** Deleting file 'source/build/CMakeCache.txt'

make[3]: Leaving directory '/root/sgx/linux-sgx/psw/ae/aesm_service'

make[2]: *** [Makefile:61: AESM] Error 2

make[2]: Leaving directory '/root/sgx/linux-sgx/psw/ae'

make[1]: *** [Makefile:52: AE] Error 2

make[1]: Leaving directory '/root/sgx/linux-sgx/psw'

make: *** [Makefile:62: psw] Error 2

**Comment by lzha101** [comment]
What I mean in previous reply is for section 1.

As to the `No SOURCE` error in section 2, you need to check whether you prepare the dcap submodule correctly. For example, `CMake Error at qcnl/CMakeLists.txt:9 `
https://github.com/intel/linux-sgx/blob/f607f89ab1ac648c3e62a23991befdeb93f9bf9d/psw/ae/aesm_service/source/qcnl/CMakeLists.txt#L7-L9

Please make sure the submodule source is also latest and corresponding to the latest linux-sgx source.

**Comment by wfgenious** [comment]
@lzha101 
i am trying to build PSW on Ubuntu 22.04 pre-release (5.15.0-xxx) and hit exactly the same errors as i did on RHEL9.0 Beta. Can u elaborate on the details "you need to check whether you prepare the dcap submodule correctly"?  My steps are quite straightforward. Did i miss anything? I suppose in-tree SGX driver is already a DCAP-ready driver.

**Preparation:**
-fresh OS installation(it comes with in-tree SGX driver)
-enable SGX under BIOS
-git clone https://github.com/intel/linux-sgx.git
-apt-get install protobuf-compiler ocaml cmake debhelper
-cd linux-sgx
-make preparation
-cp external/toolset/{current_distr}/{as,ld,ld.gold,objdump} /usr/local/bin
-which as ld ld.gold objdump to confirm the above command has been run successfully

**build and install SDK**
-make sdk which will build sdk installation scripts
-run the installation scripts to finish SDK installation

**build and install PSW**
-make psw to build PSW deb files

**Comment by wfgenious** [comment]
@lzha101 
This issue has been solved after running either "make preparations" or "git submodule update --init --remote" which will pull necessary modules from internet. Thanks for your solid support.
