### ISSUE TITLE
The retry mechanism invalid when two threads call sgx_create_enclave concurrently

### ISSUE THREAD

**Issue by GYShit** [intel/linux-sgx#804]
sgxsdk version: 2.15.1
linux-sgx-driver: 2.11
kernel-ver: 5.10.0

DESC: The error occurred when my APP call **sgx_create_enclave()** concurrently in two threads. I find the retry mechanism invalid because of **load_enclave()** just return **SGX_ERROR_MEMORY_MAP_FAILURE** instead of  **SGX_ERROR_MEMORY_MAP_CONFLICT**, and I find there is no way to return **SGX_ERROR_MEMORY_MAP_CONFLICT.**

So, I think the retry mechanism should judge val **SGX_ERROR_MEMORY_MAP_FAILURE** on the other hand return **SGX_ERROR_MEMORY_MAP_CONFLICT** when memory map conflict.

**Comment by GYShit** [comment]
anyone gets a chance to look into this issue? Thanks.

**Comment by JunjunGu1** [comment]
SGX_ERROR_MEMORY_MAP_CONFLICT is different from SGX_ERROR_MEMORY_MAP_FAILURE.
SGX_ERROR_MEMORY_MAP_FAILURE  means that mmap memory for enclave failed.
SGX_ERROR_MEMORY_MAP_CONFLICT means that page mapping conflict in driver.
So when your app return SGX_ERROR_MEMORY_MAP_FAILURE, you may call sgx_create_enclave to create enclave again.

**Comment by GYShit** [comment]
> mmap

**Comment by GYShit** [comment]
https://github.com/intel/linux-sgx/pull/805/files

**Comment by GYShit** [comment]
https://github.com/intel/linux-sgx/pull/805/files
