### ISSUE TITLE
How to use PBC (Pairing-Based Cryptography)  library in SGX 

### ISSUE THREAD

**Issue by Frinklin-Wang** [intel/linux-sgx#821]
I am new guys about Intel sgx.
I want to calculate bilinear mappings in enclaves.
How do I link the pbc library in Enclave?(OS is Linux)
Any suggestion will help!!!
Thank you very much!

**Comment by andyzyb** [comment]
Not sure I understand the question. What is pbc library?

**Comment by Frinklin-Wang** [comment]
> 

https://crypto.stanford.edu/pbc/

**Comment by andyzyb** [comment]
Then you need to add this library in the link option. For example, in SampleCode/SampleEnclave/Makefile, the link option is defined as below, you can add more libraries if needed.  

Enclave_Link_Flags := $(MITIGATION_LDFLAGS) $(Enclave_Security_Link_Flags) \
    -Wl,--no-undefined -nostdlib -nodefaultlibs -nostartfiles -L$(SGX_TRUSTED_LIBRARY_PATH) \
        -Wl,--whole-archive -l$(Trts_Library_Name) -Wl,--no-whole-archive \
        -Wl,--start-group -lsgx_tstdc -lsgx_tcxx -l$(Crypto_Library_Name) -l$(Service_Library_Name) -Wl,--end-group \
        -Wl,-Bstatic -Wl,-Bsymbolic -Wl,--no-undefined \
        -Wl,-pie,-eenclave_entry -Wl,--export-dynamic  \
        -Wl,--defsym,__ImageBase=0 -Wl,--gc-sections   \
        -Wl,--version-script=Enclave/Enclave.lds

**Comment by Frinklin-Wang** [comment]
Hi andyzyb,
Thank you for your reply.I can't understand this code means.Could you please tell me where should I add?

**Comment by andyzyb** [comment]
This is link option. You can add your library like  "**-lsgx_tcxx**" (this is to add a lib name **libsgx_tcxx.a**. 

Please refer to gcc manual if you want to understand more on link options.

**Comment by Frinklin-Wang** [comment]
I add  a lib named libgcc.a(directory is ~/download/PBC/lib). 
"-Wl,--start-group -lsgx_tstdc -lsgx_tcxx -libgcc -l$(Crypto_Library_Name) -l$(Service_Library_Name) -Wl,--end-group \"
When I makefile ,there is an error is "/usr/bin/ld: no found -libgcc .collect2: error: ld returned 1 exit status"
How should i solve this problem？

**Comment by andyzyb** [comment]
You should set the path for linker, like "-L$(SGX_TRUSTED_LIBRARY_PATH)".

**Comment by Frinklin-Wang** [comment]
I set “SGX_PBC ?= .../down/PBC” and
“SGX_TRUSTED_LIBRARY_PATH:= -IInclude -IEnclave -I$(SGX_PBC)/lib -I$(SGX_PBC)/include/pbc-0.5.14/include -I$(SGX_PBC)/pbc-0.5.14/param ”
But I add "-libpbc" in "-Wl,--start-group -lsgx_tstdc -lsgx_tcxx -libpbc -l$(Crypto_Library_Name) -l$(Service_Library_Name) -Wl,--end-group \"
There is still an error "/usr/bin/ld: no found-libpbc
collect2: error: ld returned 1 exit status
make: *** [Makefile:218：enclave.so] error1"
How should I do？

**Comment by andyzyb** [comment]
Please be careful of option.  "-L", not "-l" for path setting.   I am also not sure where you set "SGX_TRUSTED_LIBRARY_PATH" in the Makefile, but don't overwrite it, just add your additional paths.

**Comment by Frinklin-Wang** [comment]
In my Makefile the code as follows:
Enclave_Cpp_Files := Enclave/Enclave.cpp
Enclave_Include_Paths := -IInclude -IEnclave -I$(SGX_SDK)/include -I$(SGX_SDK)/include/tlibc -I$(SGX_SDK)/include/stlport 

Enclave_C_Flags := $(SGX_COMMON_CFLAGS) -nostdinc -fvisibility=hidden -fpie -fstack-protector $(Enclave_Include_Paths)
Enclave_Cpp_Flags := $(Enclave_C_Flags) -std=c++03 -nostdinc++

SGX_TRUSTED_LIBRARY_PATH:= -IInclude -IEnclave -I$(SGX_PBC)/lib -I$(SGX_PBC)/include/pbc-0.5.14/include -I$(SGX_PBC)/pbc-0.5.14/param 

Enclave_Link_Flags := $(SGX_COMMON_CFLAGS) -Wl,--no-undefined -nostdlib -nodefaultlibs -nostartfiles -L$(SGX_LIBRARY_PATH) -L$(SGX_TRUSTED_LIBRARY_PATH)\
	-Wl,--whole-archive -l$(Trts_Library_Name) -Wl,--no-whole-archive \
	-Wl,--start-group -lsgx_tstdc -lsgx_tcxx  -l$(Crypto_Library_Name) -l$(Service_Library_Name) -Wl,--end-group \
	-Wl,-Bstatic -Wl,-Bsymbolic -Wl,--no-undefined \
	-Wl,-pie,-eenclave_entry -Wl,--export-dynamic  \
	-Wl,--defsym,__ImageBase=0 \
	-Wl,--version-script=Enclave/Enclave.lds
This can make success.But when I add "-libgcc" in "-Wl,--start-group -lsgx_tstdc -lsgx_tcxx  -l$(Crypto_Library_Name) -l$(Service_Library_Name) -Wl,--end-group \" like "-Wl,--start-group -lsgx_tstdc -lsgx_tcxx -libgcc -l$(Crypto_Library_Name) -l$(Service_Library_Name) -Wl,--end-group \".It will have an above error.

**Comment by andyzyb** [comment]
There are several things mismatched and confusing in your Makefile. For example, what is the definition of SGX_PBC,  you set "SGX_TRUSTED_LIBRARY_PATH", but also use "-L$(SGX_LIBRARY_PATH)",  why you make "SGX_TRUSTED_LIBRARY_PATH" more like "Enclave_Include_Paths ", etc.   

Please review and make sure your changes are correct.

**Comment by Frinklin-Wang** [comment]
At the makefile beginning，I define the “SGX_PBC ?= .../down/PBC”.
This can make success if I'm not add  when I add "-libpbc" in "-Wl,--start-group -lsgx_tstdc -lsgx_tcxx -l$(Crypto_Library_Name) -l$(Service_Library_Name) -Wl,--end-group " 
But if I add "-libgcc" in  "-Wl,--start-group -lsgx_tstdc -lsgx_tcxx  -l$(Crypto_Library_Name) -l$(Service_Library_Name) -Wl,--end-group ".It will have an an error.
"/usr/bin/ld: no found-libpbc
collect2: error: ld returned 1 exit status
make: *** [Makefile:219：enclave.so] erroe 1"
I am not sure my code is right.If it is convenient, could you please give me a detailed tutorial to help me solve the problem of importing the pbc library?
Thank you so much!!

**Comment by hiroki-chen** [comment]
> At the makefile beginning，I define the “SGX_PBC ?= .../down/PBC”. This can make success if I'm not add when I add "-libpbc" in "-Wl,--start-group -lsgx_tstdc -lsgx_tcxx -l$(Crypto_Library_Name) -l$(Service_Library_Name) -Wl,--end-group " But if I add "-libgcc" in "-Wl,--start-group -lsgx_tstdc -lsgx_tcxx -l$(Crypto_Library_Name) -l$(Service_Library_Name) -Wl,--end-group ".It will have an an error. "/usr/bin/ld: no found-libpbc collect2: error: ld returned 1 exit status make: *** [Makefile:219：enclave.so] erroe 1" I am not sure my code is right.If it is convenient, could you please give me a detailed tutorial to help me solve the problem of importing the pbc library? Thank you so much!!

The command for linking library to your application should be `-lpbc` rather than `-libpbc`. Linux system links dynamic library by omitting the `lib` prefix. For example, if you want to link the file `libpbc.so`, you add the linker flag `-lpbc`, and that would be enough for you.

**Comment by Frinklin-Wang** [comment]
> > At the makefile beginning，I define the “SGX_PBC ?= .../down/PBC”. This can make success if I'm not add when I add "-libpbc" in "-Wl,--start-group -lsgx_tstdc -lsgx_tcxx -l$(Crypto_Library_Name) -l$(Service_Library_Name) -Wl,--end-group " But if I add "-libgcc" in "-Wl,--start-group -lsgx_tstdc -lsgx_tcxx -l$(Crypto_Library_Name) -l$(Service_Library_Name) -Wl,--end-group ".It will have an an error. "/usr/bin/ld: no found-libpbc collect2: error: ld returned 1 exit status make: *** [Makefile:219：enclave.so] erroe 1" I am not sure my code is right.If it is convenient, could you please give me a detailed tutorial to help me solve the problem of importing the pbc library? Thank you so much!!
> 
> The command for linking library to your application should be `-lpbc` rather than `-libpbc`. Linux system links dynamic library by omitting the `lib` prefix. For example, if you want to link the file `libpbc.so`, you add the linker flag `-lpbc`, and that would be enough for you.

Thank you for your advise!

**Comment by hiroki-chen** [comment]
我已经收到电子邮件，马上回复。I have received your email and will reply as soon as possible.Ich habe Ihre E-Mail erhalten und beantworte sie am schnellsten.

**Comment by hiroki-chen** [comment]
我已经收到电子邮件，马上回复。I have received your email and will reply as soon as possible.Ich habe Ihre E-Mail erhalten und beantworte sie am schnellsten.
