### ISSUE TITLE
Error while making psw . 

### ISSUE THREAD

**Issue by yashwanthresham** [intel/linux-sgx#825]
In file included from /home/yashwanth/Downloads/linux-sgx/psw/urts/loader.cpp:35:
/home/yashwanth/Downloads/linux-sgx/common/inc/internal/arch.h:40:10: fatal error: sgx_report2.h: No such file or directory
   40 | #include "sgx_report2.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:154: loader.o] Error 1
make[2]: Leaving directory '/home/yashwanth/Downloads/linux-sgx/psw/urts/linux'
make[1]: *** [Makefile:46: urts] Error 2
make[1]: Leaving directory '/home/yashwanth/Downloads/linux-sgx/psw'
make: *** [Makefile:62: psw] Error 2

Above error occurs when i try to make psw DEBUG =1
installed sgxsdk in /opt/intel/
built sdk .

**Comment by lzha101** [comment]
Could you please check if you have installed the latest SGX SDK before building PSW?  `sgx_report2.h` is introduced from 2.16 release.

**Comment by yashwanthresham** [comment]
Thanks its working now after installing 2.16 release. 
But it shows use correct urts library from psw package .

**Comment by Chen-Xintong** [comment]
I met the same error, did you have solve it? @yashwanthresham

**Comment by SicherZoeng** [comment]
I also meet this problem.
When I executed the following command:
`find -name sgx_report2.h`
I got this output:
```
./linux/installer/common/sdk/output/package/include/sgx_report2.h
./common/inc/sgx_report2.h
```
, which meant that there are sgx_report2.h file. 
I also find in arch.h, there is:
```
#include "sgx_report.h";
#include "sgx_report2.h"
```
When I executed the following command:
`find -name sgx_report.h`
I got this output:
```
./linux/installer/common/sdk/output/package/include/sgx_report.h
./common/inc/sgx_report.h
```
,which meant that the sgx_report.h file is placed in the same place with sgx_report2.h, so if sgx_report.h can be found, sgx_report2.h can also be found, but confusingly, sgx_report2.h can not be found, while sgx_report.h can be found.

**Comment by lzha101** [comment]
@SicherZoeng you need to install the SDK installer and source the environment. Refer to https://github.com/intel/linux-sgx#install-the-intelr-sgx-sdk-1.

**Comment by SicherZoeng** [comment]
> @SicherZoeng you need to install the SDK installer and source the environment. Refer to https://github.com/intel/linux-sgx#install-the-intelr-sgx-sdk-1.

I forgot to execute 'sgx_linux_x64_sdk_${version}.bin' after executed 'make sdk_install_pkg'.
Thank you a lot for helping! Have a nice day!
