### ISSUE TITLE
error on build make deb_psw_pkg  on Ubuntu 18.04 

### ISSUE THREAD

**Issue by dancedwolf** [intel/linux-sgx#827]
When I  make installer psw ,I get a erro: dpkg-shlibdeps: error: no dependency information found for /usr/local/lib/libprotobuf.so.25 (used by debian/sgx-aesm-service/opt/intel/sgx-aesm-service/aesm/libipc.so)
I build protobuf by source code;

make[2]: Entering directory '/home/turing/linux-sgx/linux/installer/deb/sgx-aesm-service/sgx-aesm-service-2.15.101.1'
dh_shlibdeps -l /home/turing/linux-sgx/build/linux
dpkg-shlibdeps: warning: can't extract name and version from library name 'libutils.so'
dpkg-shlibdeps: warning: can't extract name and version from library name 'libutils.so'
dpkg-shlibdeps: warning: can't extract name and version from library name 'libutils.so'
dpkg-shlibdeps: warning: can't extract name and version from library name 'liburts_internal.so'
dpkg-shlibdeps: warning: can't extract name and version from library name 'liburts_internal.so'
dpkg-shlibdeps: warning: can't extract name and version from library name 'liburts_internal.so'
dpkg-shlibdeps: warning: can't extract name and version from library name 'liboal.so'
dpkg-shlibdeps: warning: can't extract name and version from library name 'liboal.so'
dpkg-shlibdeps: warning: can't extract name and version from library name 'liboal.so'
dpkg-shlibdeps: warning: can't extract name and version from library name 'liboal.so'
dpkg-shlibdeps: warning: can't extract name and version from library name 'liboal.so'
dpkg-shlibdeps: warning: can't extract name and version from library name 'liboal.so'
dpkg-shlibdeps: warning: can't extract name and version from library name 'liboal.so'
dpkg-shlibdeps: warning: can't extract name and version from library name 'liboal.so'
dpkg-shlibdeps: warning: can't extract name and version from library name 'liboal.so'
dpkg-shlibdeps: warning: can't extract name and version from library name 'libutils.so'
dpkg-shlibdeps: warning: can't extract name and version from library name 'libutils.so'
dpkg-shlibdeps: warning: can't extract name and version from library name 'libutils.so'
dpkg-shlibdeps: warning: can't extract name and version from library name 'liboal.so'
dpkg-shlibdeps: warning: can't extract name and version from library name 'liboal.so'
dpkg-shlibdeps: warning: can't extract name and version from library name 'liboal.so'
dpkg-shlibdeps: error: no dependency information found for /usr/local/lib/libprotobuf.so.25 (used by debian/sgx-aesm-service/opt/intel/sgx-aesm-service/aesm/libipc.so)
Hint: check if the library actually comes from a package.
dh_shlibdeps: dpkg-shlibdeps -Tdebian/sgx-aesm-service.substvars -l/home/turing/linux-sgx/build/linux debian/sgx-aesm-service/opt/intel/sgx-aesm-service/aesm/libCppMicroServices.so.4.0.0 debian/sgx-aesm-service/opt/intel/sgx-aesm-service/aesm/liboal.so debian/sgx-aesm-service/opt/intel/sgx-aesm-service/aesm/libutils.so debian/sgx-aesm-service/opt/intel/sgx-aesm-service/aesm/libipc.so debian/sgx-aesm-service/opt/intel/sgx-aesm-service/aesm/aesm_service debian/sgx-aesm-service/opt/intel/sgx-aesm-service/aesm/liburts_internal.so debian/sgx-aesm-service/opt/intel/sgx-aesm-service/aesm/bundles/liblinux_network_service_bundle.so returned exit code 255
dh_shlibdeps: Aborting due to earlier error
debian/rules:11: recipe for target 'override_dh_shlibdeps' failed
make[2]: *** [override_dh_shlibdeps] Error 255
make[2]: Leaving directory '/home/turing/linux-sgx/linux/installer/deb/sgx-aesm-service/sgx-aesm-service-2.15.101.1'
debian/rules:8: recipe for target 'binary' failed
make[1]: *** [binary] Error 2
make[1]: Leaving directory '/home/turing/linux-sgx/linux/installer/deb/sgx-aesm-service/sgx-aesm-service-2.15.101.1'
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
Makefile:115: recipe for target 'deb_sgx_aesm_service' failed

My local lib path :
<img width="730" alt="image" src="https://user-images.githubusercontent.com/21101310/165543733-e260c352-00d7-4778-8082-d73b504da0ba.png">

**Comment by llly** [comment]
You can try to change this line
https://github.com/intel/linux-sgx/blob/e1a37bdc381672509e49e34885730437366194e4/linux/installer/deb/sgx-aesm-service/sgx-aesm-service-1.0/debian/rules#L11
to
`dh_shlibdeps -l $(LINUX_BUILD_DIR) --dpkg-shlibdeps-params=--ignore-missing-info`

**Comment by dancedwolf** [comment]
> --dpkg-shlibdeps-params=--ignore-missing-info

thanks ,It's ok!
