### ISSUE TITLE
sgx_get_quote returns SGX_SUCCESS  with "stack smashing detected"

### ISSUE THREAD

**Issue by ZhufengYe** [intel/linux-sgx#832]
HI! I am a new commer to sgx development and trying to implement the remote attestation process in my paper. According my protocol designed, the key exchange process is not necessary so I try to get rid of it. My goal is to simply obtain a signature by the sgx-signing key on the running code and some enclave-generated stuff.

I refer to the _Intel(R) Software Guard Extensions Developer Reference for Linux* OS_ and consider _sgx_init_quote_, _sgx_calc_quote_size_, _sgx_get_quote_ and _sgx_create_report_ as what I am looking for. So the untrusted part is generally as below:

```
    uint32_t ret = 0;
    uint32_t quote_size = 0;
    uint32_t len = 32;

    sgx_epid_group_id_t p_gid = {0};
   
    sgx_target_info_t p_target_info;
    memset(&p_target_info, '0', sizeof(p_target_info)); 
    
    sgx_report_t report;
    memset(&report, '0', sizeof(report));
    
    sgx_spid_t spid;
    memset(&spid, '0', sizeof(spid));

    sgx_quote_t p_quote;
    memset(&p_quote, '0', sizeof(p_quote));

    ret = sgx_init_quote(&p_target_info, &p_gid);
    fprintf(stdout, "The init_quote state is %d.\n", ret);

    ret = sgx_calc_quote_size(NULL, 0, &quote_size);
    fprintf(stdout, "The quote state is %d and the quote size is %d\n", ret, quote_size);

    ecall_get_report(global_eid, &report, &p_target_info, sizeof(report), sizeof(p_target_info));
    ret = sgx_get_quote(&report, SGX_LINKABLE_SIGNATURE, &spid, NULL, NULL, 0, NULL, &p_quote, quote_size);
    
    if(ret == 0){ 
        fprintf(stdout, "Quote successfully!\n");
    }
    else
        fprintf(stdout, "Error code: %d\n", ret);
```

Also, to get the report inside enclave with _sgx_create_report_ function, I add the _ecall_get_report_ function myself to take the report structure outside for _sgx_get_quote_ fucntion, which is as below:

```
void ecall_get_report(
    sgx_report_t *report,
    sgx_target_info_t *target_info,
    uint32_t r_len,
    uint32_t t_len
){
    sgx_report_data_t report_data;
    memset(&report_data, '0', sizeof(report_data));
    uint32_t ret = 0;

    ret = sgx_create_report(target_info, &report_data, report);

    if(ret == 0)
        ocall_print_string("The return value of sgx_create_report is normal.");
    else
        ocall_print_string("The return value of sgx_create_report is abnormal.");
```

The Enclave.edl is as below:

```
enclave {
    include "sgx_report.h"
    trusted {

    public void ecall_get_report(
        [out, size = r_len] sgx_report_t *report,
        [in, size = t_len] sgx_target_info_t *target_info,
        uint32_t r_len,
        uint32_t t_len
    );
    };

};

```

Now everything is just fine and _sgx_get_quote_ returns SGX_SUCCESS except that "stack smashing detected" warning occurs:

```
*** stack smashing detected ***: <unknown> terminated
Aborted (core dumped)
```

sgx-gdb also provides the following information:

```
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
```

The RemoteAttestation sample code can be run perfectly in either the HW or SIM mode. The above error also appears in both modes. I am unfamiliar with sgx development and I guess I might overlook some important details throughout a successful quotation.

Any suggestion?

Thanks!

**Comment by llly** [comment]
You need to prepare quote buffer like
```
    sgx_quote_t *p_quote;
    ret = sgx_calc_quote_size(NULL, 0, &quote_size);
    p_quote = (sgx_quote_t *)malloc(quote_size);
```

**Comment by ZhufengYe** [comment]
> You need to prepare quote buffer like
> 
> ```
> 
>     sgx_quote_t *p_quote;
> 
>     ret = sgx_calc_quote_size(NULL, 0, &quote_size);
> 
>     p_quote = (sgx_quote_t *)malloc(quote_size);
> 
> ```

Thanks llly! I should've been more careful. Now the problem has been fixed!

**Comment by ZhufengYe** [comment]
> You need to prepare quote buffer like
> 
> ```
> 
>     sgx_quote_t *p_quote;
> 
>     ret = sgx_calc_quote_size(NULL, 0, &quote_size);
> 
>     p_quote = (sgx_quote_t *)malloc(quote_size);
> 
> ```

Thanks llly! I should've been more careful. Now the problem has been fixed!
