### ISSUE TITLE
sgx-gdb can't show thread local variable correctly

### ISSUE THREAD

**Issue by LeoneChen** [intel/linux-sgx#839]
sgx-gdb seems use gdb default logic to search `thread local variable`, however TLS data of Enclave is stored in Enclave's ThreadData layout, so Enclave TLS data is showed by sgx-gdb incorrectly

**Comment by lzha101** [comment]
Yes. Currently, this is a known limitation for sgx-gdb to show the thread local variables inside enclave. You can dump the thread data to find out your tls value as a workaround.

**Comment by LeoneChen** [comment]
Ok, I got it. Thanks for your reply~
