### ISSUE TITLE
Illegal Instruction Crash After EPID Attestation

### ISSUE THREAD

**Issue by xanderdunn** [intel/linux-sgx#841]
We've had a very perplexing and very difficult to debug crash in our SGX1 enclave for a handful of months.
Intel SGX SDK 2.16. 
Intel(R) Xeon(R) E-2288G CPU.

It's our understanding that the `Illegal Instruction` error is the error we should expect on any kind of enclave crash, whether it's out of TCS, out of memory, an `assert()` was called, SIGSEGV, etc. 

Debugging steps we've tried: 
- Increase `TCSNum`, increase `TCSMaxNum`. We've got only two threads running here, we don't expect this to be a problem. No effect. As seen in #809. 
- Adding sleeps to the two threads in an attempt to modify any data races. No effect.
- Force `-fno-stack-protector` as seen in #240 and #164.
- Allocate variously sized values to the heap or stack. The attempt is to see if modifying the heap or stack pushes memory corruption into a different location. No effect.
- We attached the binary to sgx-gdb and initially it hit the same crash, but it had no symbols. So, we installed the SGX debug symbols: `sudo apt install libsgx-enclave-common-dbgsym libsgx-urts-dbgsym`. With the symbols installed, running exactly the same binary in sgx-gdb runs perfectly fine and does not hit the crash. It always works. This makes it incredibly difficult to debug this as the crash disappears in the debugger. However, this should tell us something about the nature of the bug. 
- By peppering the code with print statements we find it is crashing here:
```
    if (response != nullptr && !try_parse_json_string(string(http_response.buffer, http_response.size), response)) {
```
We print the JSON on the line before and it is valid. We perform the same call on the same JSON as a unit test and it parses it without issue. Where the crash occurs across builds isn't always the same line of code. In the past we've often seen it occur on various calls to `free()` in our code. We're confident in the memory management of most portions of our code, as we've run the unit tests with the address sanitizer enabled outside the enclave.

It's important to emphasize that the crash is 100% deterministic, it is not occurring probabilistically. Given an exact set of conditions, it occurs or does not occur with 100% reproducibility. 

Our current hypothesis is that something happening with EPID IAS v3 attestation is silently causing memory corruption in some memory that we own and then it becomes apparent at some later time when we attempt to use the corrupted memory. Our EPID attestation has been written based on Intel's sample. We do not see this crash occurring on runs where we do not perform remote attestation. In addition, we have a fork of this product that uses DCAP attestation and it has never encountered this crash either. 

Does the Intel team have any additional debugging steps they would recommend here? This is a production code base and reducing it to a minimal reproducing example will take considerable effort and may very well remove the bug.

**Comment by llly** [comment]
> We print the JSON on the line before
Do you mean print out of enclave? Is `http_response` a function parameter of EDL and  passed from app to encalve?

**Comment by xanderdunn** [comment]
Thanks for taking a look @llly!

Yes, to debug this we add `print` ocalls throughout the enclave to pinpoint the line of code where the crash occurs. We're printing the JSON as a c_string. Note that the crash occurs with or without any print statements.

We are using enclave-terminated TLS here, and our complete set of ecalls is extremely small. `http_response` is not passed to the enclave, it is created within the enclave.  The code in the enclave looks like this:
```
// Calling the request callback for blocking requests
HttpResponse http_response;
struct evhttp_request* req = evhttp_request_new(http_blocking_request_callback, &http_response);
ASSERT(req != nullptr, "Failed to create request.");

...
// Add the request body
...

// Add the request headers. Each connection will only be used for one request.
...
    evhttp_make_request(conn, req, http_verb, (path + query_string).c_str());
...
    if (response != nullptr && !try_parse_json_string(string(http_response.buffer, http_response.size), response)) {
...
```

This is all within the enclave. It exits the enclave at the networking layer with ocalls to perform the TCP/TLS.

**Comment by llly** [comment]
Then, is the pointer `response` a valid pointer with enough buffer inside enclave? I don't find other issues in your case.

**Comment by xanderdunn** [comment]
We never figured out the cause of this issue. Our solution was to port our full codebase from Intel SGX SDK to [OpenEnclave SDK](https://github.com/openenclave/openenclave). The issue has never exhibited with OpenEnclave.
