### ISSUE TITLE
What's the magic of sgx-gdb

### ISSUE THREAD

**Issue by LeoneChen** [intel/linux-sgx#850]
I‘ve read code about `sgx-gdb` and it's gdb script, but I don't understand why `sgx-gdb` can trace into Enclave when singlestep `ENCLU` instruction while normal `gdb` can't. What's the magic of sgx-gdb?

I'm just get to know about gdb script. Thanks for any help~

**Comment by gilanghamidy** [comment]
You can read the Python script `gdb_sgx_plugin.py` and the stuff inside `sdk/debugger_interface` for the detail. 

As far as I understand, when the enclave encounters a debug instruction (INT3), the enclave exits asynchronously, and the URTS catch the interrupt and read the information that is stored inside the TCS. This information is passed to the GDB via a fake-breakpoint which points to a NOP function inside the SGX: `notify_gdb_to_update`, which is then handled by the Python script, which performs unpacking the TCS frame and translates that into the current state of the execution inside the enclave (current instruction address, registers, etc).

The memory itself is readable through the `ENCLS[EDBGRD]` instruction, which handled by the SGX driver's `mmap` handler (`sgx_vma_access`). So GDB will be directly able to see the content inside the enclave memory.

If the enclave is not in debug configuration, the processor ignores the debug interrupt and the `ENCLS[EDBGRD]` 

CMIIW. That's what I learned by reading the `gdb_sgx_plugin.py` when I tried to mess with SGX debugger ;)

**Comment by LeoneChen** [comment]
Thanks for your replay, and more discussions are welcome~

`notify_gdb_to_update` is used to update stack frame when ocall, otherwise debugger can't get in-Enclave stack frame, since after ocall, it's already at untrusted code.
```cpp
// psw/urts/linux/debugger_support.cpp
extern "C" void push_ocall_frame(uintptr_t frame_point, tcs_t* tcs, CTrustThread *trust_thread)
{
    ...
    if((enclave->get_debug_info()->elrange_start_address == reinterpret_cast<uint64_t>(enclave->get_start_address())) || 
        ((enclave->get_debug_info()->enclave_type & ET_SIM) ==ET_SIM))
    {
        notify_gdb_to_update(enclave->get_start_address(), tcs, (uintptr_t)container_of(frame_point, ocall_frame_t, xbp));
    }
    else
    {
        notify_gdb_to_update(reinterpret_cast<void*>(enclave->get_debug_info()->elrange_start_address), 
            tcs, (uintptr_t)container_of(frame_point, ocall_frame_t, xbp));
    }
}
```

However, I currently found `se_ptrace.c` hook the `ptrace` used by gdb to perform the operation I'm interested in.

![1654503820370](https://user-images.githubusercontent.com/35480440/172123987-9c9aefc5-2175-4ce7-8e6b-ec14ee7d4490.png)

With this, `sgx-gdb` can go from `ENCLU` to `enclave_entry`

![1654503577131](https://user-images.githubusercontent.com/35480440/172123269-75fa8035-920e-4cd4-ba5d-1a0102f2e316.png)
![1654503639874](https://user-images.githubusercontent.com/35480440/172123426-251dfacb-f51d-45fb-be07-b8f1c28e7f30.jpg)

`sgx-gdb` hook orginal ptrace via `LD_PRELOAD=$SGX_LIBRARY_PATH/libsgx_ptrace.so`

![1654503730561](https://user-images.githubusercontent.com/35480440/172123698-b384b763-7c22-477e-9760-7548b7544105.png)

**Comment by LeoneChen** [comment]
But I still don't know how `libsgx_ptrace.so`(contains`se_memory.c`, `se_trace.c` and `ptrace_version.c`) let sgx-gdb go from `ENCLU` to `enclave_entry`

**Comment by lzha101** [comment]
It is not done by libsgx_ptrace.so. ` ENCLU` is an SGX instruction. For your case, it will execute `ENTER` leaf and back to the trusted enclave entry point. You can refer to Intel SDM for details.

**Comment by LeoneChen** [comment]
Thanks for reply~

But normal gdb without libsgx_ptrace.so can't step from ENCLU(EENTER) to enclave_entry, which makes me feel weird

**Comment by lzha101** [comment]
Because normal gdb cannot access enclave memory, that's why you see it stops at the line below EENTER. Using sgx-gdb, it will enable the DEBUG bit in TCS ( done in the python script) and make the enclave memory accessible via EDBGRD/EDBGWR instruction. So it can stop inside enclave.

**Comment by LeoneChen** [comment]
I get it. Thank @gilanghamidy and @lzha101 answers！
