### ISSUE TITLE
Vtune SGX HotSpots don't have Flame Graph?

### ISSUE THREAD

**Issue by LeoneChen** [intel/linux-sgx#851]
Hi, I currently can get Flame Graph when only generate HotSpots.

![image](https://user-images.githubusercontent.com/35480440/173235915-304245cd-c6f3-48df-8cd3-3f572a035689.png)

But after generating SGX HotSpot, there is no Flame Graph, while other windows exist(e.g. Top-down Tree, but showed messively)

![image](https://user-images.githubusercontent.com/35480440/173235950-345b02bc-4841-49d2-b300-efd5ea3db746.png)

Is it due to sgx-hotpots only run on hardware event-based sampling and can't get call stack info?(according to [syntax page](https://www.intel.com/content/www/us/en/develop/documentation/vtune-help/top/command-line-interface/running-command-line-analysis/run-sgx-hotspots-analysis-command-line.html))

![image](https://user-images.githubusercontent.com/35480440/173237741-9049db1c-002d-4dd6-adfd-89b90c22fd4e.png)

**Comment by jinghe-INTC** [comment]
On the manual page of [Frame Graph](https://www.intel.com/content/www/us/en/develop/documentation/vtune-help/top/reference/user-interface-reference/window-flame-graph.html), it is said 

> If you are running the analysis in **Hardware Event-Based Sampling** mode, check the **Collect Stacks** option.

However sgx-hotspots is only available in command line. Have you tried the command such as
`vtune -collect sgx-hotspots -knob enable-stack-collection=true ./app`
?

**Comment by LeoneChen** [comment]
Thanks for reply!

I've tried `enable-stack-collection=true` on `sgx-hotspots`, it doesn't work, which is as expected according to [doc](https://www.intel.com/content/www/us/en/develop/documentation/vtune-help/top/command-line-interface/running-command-line-analysis/run-sgx-hotspots-analysis-command-line.html).

![image](https://user-images.githubusercontent.com/35480440/173495105-3409458a-cde3-40d5-8fde-e33924b95606.png)

Currently, I think we can generate normal hotspot for simulation mode Enclave, it's useful for me, may be helpful for others.

**Comment by jinghe-INTC** [comment]
So it looks to me it is not possible to get the Flame Graph with sgx-hotspots. You could contact Intel VTune development for support.

**Comment by LeoneChen** [comment]
Ok, I've asked in Intel Forums, thanks again!

**Comment by nkvignesh** [comment]
> enable-stack-collection=true

With this option in knob under sgx-hotspots, Now I am able to get the flame graph using the latest vtune.
