### ISSUE TITLE
[BUG] fs register is wrongly set in simulation mode

### ISSUE THREAD

**Issue by LeoneChen** [intel/linux-sgx#854]
**SDK version**
sgx v2.15.1 (I've not test newer version, but I think it exits)

**BUG**
`SET_FS_GS_0(tib);` in [here](https://github.com/intel/linux-sgx/blob/master/sdk/simulation/uinst/linux/set_tls.c#L62) only set `fs:0x0` to address of Enclave ThreadData(or called thread local storage, TLS), but `fs` itself is not changed to ThreadData, and thus `fs` it still point to TLS address of host application, this is problematic, i.e. `fs:0x0` point to Enclave TLS, while `fs` point to Host App TLS.

This can lead to two problem:
1. In binary code, enclave program may both use `fs` or `fs:0x0` to get address of TLS, but these two are different (which makes my project broken)
2. If binary code use `fs` (host app TLS) to get address of thread data for `__thread` variable, when thread data of Enclave is larger then host app TLS total size, then the calculated address of `__thread` variable may point to unmaped address

**Comment by lzha101** [comment]
On simulation mode, we do not have a good way to switch the FS/GS as HW mode does.  You may  see we previously accepted the PR #621 and then reverted it. The reason we reverted it is we cannot handle it well with simulation exception handling support. 
Simulation mode only provides some basic functionalities to simulate HW behavior for the person who doesn't have HW and wants to try SGX.  As you said, we don't support all the compilation/link ways to support simulation TLS.  We took this as a known limitation during the development process.  But if you have any good idea to help to remove this limitation, you can submit a PR.  It will be be appreciated.
