### ISSUE TITLE
Add sgx_get_debug_info to sgx_urts.h

### ISSUE THREAD

**Issue by theShmoo** [intel/linux-sgx#857]
## Motivation

The main motivation for this is that we would like to retrieve memory information of our enclaves in our test environments. We want to report the heap and stack peaks of our enclaves in a summary report, which is requested every x seconds. This report data helps us analyze the current state of the system.

This change should be quite simple to implement in the SDK and would help us with this information.

## Implementation

I would like to see `sgx_get_debug_info` in `sgx_urts.h` for the `sgx_urts_sim.so` to be able to get debug information of a running enclave.

The signature should be:

```c
sgx_status_t SGXAPI sgx_get_debug_info(
	const sgx_enclave_id_t enclave_id,
	sgx_debug_info_t* debug_info);
```

and the implementation:

```c
extern "C" sgx_status_t sgx_get_debug_info(
	const sgx_enclave_id_t enclave_id,
	sgx_debug_info_t* debug_info)
{
    if (!debug_info)
        return SGX_ERROR_INVALID_PARAMETER;

    CEnclave* enclave = CEnclavePool::instance()->get_enclave(enclave_id);
    if (!enclave) {
        return SGX_ERROR_INVALID_ENCLAVE_ID;
    }
    *debug_info = enclave->get_debug_info();
    return SGX_SUCCESS;
}
```

also the lds file needs to be adapted.

**Comment by lzha101** [comment]
Could you provide the motivation to request this API here? I think you want a copy for the `debug_enclave_info_t` structure, right? This info is generated by urts and used by sgx-gdb.  IMO,  there seems no need to know the info if you don't debug your enclave. While if you use sgx-gdb to debug your enclave, you can easily see this info.

**Comment by theShmoo** [comment]
The main motivation for this is that we would like to retrieve memory information of our enclaves in our test environments. We want to report the heap and stack peaks of our enclaves in a summary report, which is requested every x seconds. This report data helps us analyze the current state of the system. 

This change should be quite simple to implement in the SDK and would help us with this information.

**Comment by theShmoo** [comment]
Kind reminder 🙂

**Comment by theShmoo** [comment]
@lzha101 Kind reminder :)

**Comment by lzha101** [comment]
@theShmoo, have you tried this approach to get the heap/stack peak values? I just realize a fact that even if we export the API to give you a copy of the `debug_enclave_info_t` structure, you still cannot get the heap/stack peak values, because you cannot read the enclave memory outside in a non-debug session.  

To get the heap/stack usage at runtime, a possible approach is to get the info from enclave and return the result outside.  While the returned result is not very accurate.  But this is not related to  the `debug_enclave_info_t` structure.

**Comment by theShmoo** [comment]
Thank you very much for you response and looking deeper into this topic.

ok. so only if I connect gdb I can read these values. That's sad... Do you have any tipps on how to achieve this any other ways?

**Comment by lzha101** [comment]
@theShmoo, we have simulation mode and HW mode. For HW mode, you cannot directly access enclave memory outside, unless you are in a gdb session. While the simulation mode doesn't have the limitation.  Do you only want the simulation mode?

**Comment by theShmoo** [comment]
Yeah! We for our test environment we use the simulation mode!

**Comment by lzha101** [comment]
@theShmoo then we think it may be not much value for us to implement this in our repo ( only workable for simulation mode, no HW mode support). But you can maintain a patch by yourselves to support the simulation mode only. As you said, the implementation is simple.

**Comment by theShmoo** [comment]
Ok thank you very much for your help! I think we can close this issue.
