### ISSUE TITLE
 https://download.01.org/intel-sgx/sgx-linux/2.17/SHA256SUM_prebuilt_2.17.cfg Reusing existing connection to download.01.org:443. HTTP request sent, awaiting response... ^C

### ISSUE THREAD

**Issue by SakuraLxm** [intel/linux-sgx#859]
wget --no-cookie --no-check-certificate  https://download.01.org/intel-sgx/sgx-linux/2.17/SHA256SUM_prebuilt_2.17.cfg

i can not download this file..help me

**Comment by lzha101** [comment]
Yes, last Friday, the 01.org was inaccessible and we have reported this to the maintainers.   They confirmed that the outage caused this and they made it back to online last weekend.   I just tried, seems everything works fine.
