### ISSUE TITLE
 make deb_local_repo err

### ISSUE THREAD

**Issue by SakuraLxm** [intel/linux-sgx#863]
![image](https://user-images.githubusercontent.com/22929594/176108275-c55a986e-754a-46c6-b206-d8b42fe46967.png)
i can download this file

**Comment by SakuraLxm** [comment]
![image](https://user-images.githubusercontent.com/22929594/176109497-acd78802-ac4b-47bc-9b87-6845fb5cc941.png)

**Comment by lzha101** [comment]
Please check whether `/linux-sgx/linux/installer/deb/sgx_debian_local_repo` is a valid path. From your previous closed issue #862, seems your path should be `/root/linux-sgx/linux/installer/deb/sgx_debian_local_repo`.

**Comment by SakuraLxm** [comment]
thanks.i fix it yesterday.

- 
![image](https://user-images.githubusercontent.com/22929594/176350276-a29c009b-fdf9-4aab-be0a-f4b04c22c0a2.png)
 now,

![image](https://user-images.githubusercontent.com/22929594/176350223-a26c6e2b-9fed-4588-9830-262e5ce11a66.png)
and i have reboot my server ,but is does not work well
