### ISSUE TITLE
how to choose hardware with intel sgx

### ISSUE THREAD

**Issue by acknowledgexiongdei** [intel/linux-sgx#867]
In [here](https://ark.intel.com/content/www/us/en/ark/search/featurefilter.html?productType=873&2_SoftwareGuardExtensions=Yes%20with%20Intel%C2%AE%20ME), I can check whether the processor supports SGX

But I am not sure what ME and SPS do?

And which mainboard support SGX, Where can I check it？

Thank you very much!

**Comment by llly** [comment]
SGX with either ME or SPS can work. Usually, ME is on desktop and embedded processors, and SPS is on server processors.
Better to contact mainboard supplier to conform SGX support, though most mainboards support SGX from my perspective. You can check BIOS options.

**Comment by acknowledgexiongdei** [comment]
> SGX with either ME or SPS can work. Usually, ME is on desktop and embedded processors, and SPS is on server processors. Better to contact mainboard supplier to conform SGX support, though most mainboards support SGX from my perspective. You can check BIOS options.

Thank you very much!!!
