### ISSUE TITLE
Missing tag 2.17.1

### ISSUE THREAD

**Issue by bon000** [intel/linux-sgx#869]
Hi,
after your announcements of a new release 2.17.1 https://01.org/intel-softwareguard-extensions/downloads/intel-sgx-linux-2.17.1-release, we have noticed that there isn't yet a GitHub release/tag for SGX 2.17.1  https://github.com/intel/linux-sgx/releases.
Is this planned?
Many thanks
Regards

**Comment by andyzyb** [comment]
Thanks for the notice.  I just added the tag for the release.
