### ISSUE TITLE
Is sgk necessary?

### ISSUE THREAD

**Issue by legolego621** [intel/linux-sgx#870]
Hello, please advise.
Is sgk (install ./linux/installer/bin/sgx_linux_x64_sdk_2.17.101.1.bin) necessary for libsgx-* packages to work correctly?
I already have collected packages. I'm only interested in the need for an sdk.

**Comment by lzha101** [comment]
SDK installer is necessary to build the libsgx-* packages. For runtime, it should not be necessary.

**Comment by legolego621** [comment]
Thanks
