### ISSUE TITLE
What is the difference between DCAP and OOT Driver

### ISSUE THREAD

**Issue by acknowledgexiongdei** [intel/linux-sgx#871]
I wanna to know the difference between DCAP and OOT Driver?
And how to choose it?

Thank you very much!!

**Comment by llly** [comment]
OOT Driver is an early version SGX driver and it doesn't support Flexible Launch Control (FLC). 
DCAP driver supports FLC and is under maintain.
Best solution is using a 5.11 or higher Linux Kernel and you don't need to install SGX driver manually.

**Comment by acknowledgexiongdei** [comment]
> 

Thank you very much!!
