### ISSUE TITLE
Can't find SGX PSW installer for RHEL

### ISSUE THREAD

**Issue by srieyulianti** [intel/linux-sgx#872]
Hi,

I am wondering why do you not provide PSW binary installer for RHEL in [here](https://download.01.org/intel-sgx/latest/linux-latest/distro/rhel8.4-server/). I can only find SDK binary and the driver there. How can I get the PSW binary as like the SDK without manually compiling from this repo? 

Regards,
Sri Yulianti

**Comment by hyjiang** [comment]
`sgx_rpm_local_repo.tgz` is the PSW repo, you need to configure the repo before installing PSW. 
Maybe it's better to read the installation guide first.

**Comment by srieyulianti** [comment]
Ok, thanks @hyjiang !
