### ISSUE TITLE
Error in make deb_local_repo

### ISSUE THREAD

**Issue by graziadonghia** [intel/linux-sgx#879]
Hello, I'm trying to install SGX PSW. I successfully installed SGX SDK but I'm having troubles with PSW.
When I run `make deb_psw_pkg` everything is ok - I only receive this warning message: `warning: Compatibility levels before 10 are deprecated (level 9 in use) -` but when I run `make deb_local_repo` I receive this error:

`dpkg-buildpackage: info: full upload (original source is included)
/home/grace/linux-sgx/external/dcap_source/QuoteGeneration
make[1]: Leaving directory '/home/grace/linux-sgx/external/dcap_source/QuoteGeneration'
cp -f external/dcap_source/QuoteGeneration/installer/linux/deb/libtdx-attest/libtdx-attest*deb ./linux/installer/deb/sgx-aesm-service/
./linux/installer/common/local_repo_builder/local_repo_builder.sh debian build
make: *** [Makefile:245: deb_local_repo] Error 249`

How can I fix this?
My operating system is POP-OS 21.10 so I'm following the Ubuntu guide.

**Comment by xiangquanliu** [comment]
Please check if 'POP-OS 21.10' is one of the config items in linux/installer/deb/local_repo_tool/conf/distributions and add it if it isn't.

**Comment by graziadonghia** [comment]
Thank you. This is the content of `distribution` file:

`Origin: Intel Corporation
Label: Intel Corporation
Codename: xenial
Architectures: amd64
Components: main
Description: ubuntu/xenial repository for SGX PSW
DebIndices: Packages .

Origin: Intel Corporation
Label: Intel Corporation
Codename: bionic
Architectures: amd64
Components: main
Description: ubuntu/bionic repository for SGX PSW
DebIndices: Packages .

Origin: Intel Corporation
Label: Intel Corporation
Codename: focal
Architectures: amd64
Components: main
Description: ubuntu/focal repository for SGX PSW
DebIndices: Packages .

Origin: Intel Corporation
Label: Intel Corporation
Codename: hirsute
Architectures: amd64
Components: main
Description: ubuntu/hirsute repository for SGX PSW
`
How can I add my distribution? I don't know the exact syntax.
