### ISSUE TITLE
Performance regression in SGX SDK 2.17.1

### ISSUE THREAD

**Issue by qzheng527** [intel/linux-sgx#897]
After updating SGX SDK 2.17.1 from 2.16, some performance test in Occlum (especially IO performance) got big regression.
Are there any big changes between SGX SDK 2.17.1 and 2.16 that may cause the regression?

**Comment by lzha101** [comment]
@qzheng527 the latest SGX 2.18 has some changes to improve the performance. Could you retry your performance test on it?

**Comment by qzheng527** [comment]
@lzha101 Thanks for the update.
Occlum will have updated the SDKto 2.18 in the coming weeks. We will do the performance test then.
