### ISSUE TITLE
Support for C++17

### ISSUE THREAD

**Issue by p-vernaeckt** [intel/linux-sgx#898]
Hi.

Is there a plan for C++17 support in a near future? I've been trying to use [Chaiscript](https://github.com/ChaiScript/ChaiScript) in an SGX enclave, but it relies on C++17 features such as variants.

🤞🏻

**Comment by p-vernaeckt** [comment]
Oh sweet! Any ETA?

**Comment by lzha101** [comment]
C++17 support is included in the 2.18 release. So close this issue.
