### ISSUE TITLE
Version-Inconsistency in Developer Reference vs. Release Notes

### ISSUE THREAD

**Issue by hallojs** [intel/linux-sgx#901]
Hi!

The latest developer reference states on page 153 that the trusted version of the protobuf library is based on Google's Protocol Buffers v3.14 The release notes name an upgrade to v3.20. Is 3.20 the correct version? Maybe it would be a good idea to update the version in the developer reference.

Thank you! :)

**Comment by lzha101** [comment]
Yes, you are right. The version of protobuf in developer reference is out of date. We will update it in later release. Thanks.

**Comment by hallojs** [comment]
Thank you!
