### ISSUE TITLE
Differences between Enclave Common Loaders and SGX SDK API

### ISSUE THREAD

**Issue by qinkunbao** [intel/linux-sgx#903]
Hello,

Intel SGX Enclave Common Loaders provide a series of APIs other than SGX SDK. 

For example, 
1. creating an enclave:
(Common Loader) ``enclave_create``
(SGX SDK)  ``sgx_create_enclave``

2. destroying an enclave:
(Common Loader) ``enclave_delete``
(SGX SDK) ``sgx_destroy_enclave``

There are no ways to make ecalls/ocalls through Enclave Common Loader library, though.

# Questions
1. What are the differences between Enclave Common Loader and SGX SDK? It seems that Enclave Common Loader has fewer dependecies than SGX SDK.
2. The example {https://github.com/intel/linux-sgx/tree/master/SampleCode/SampleCommonLoader} from enclave common loaders does not make any ecalls or ocalls. What is the purpose of the example?

Thank you in advance.

**Comment by lzha101** [comment]
>1. What are the differences between Enclave Common Loader and SGX SDK? It seems that Enclave Common Loader has fewer dependecies than SGX SDK.

The APIs in Enclave Common Loader are basic low level APIs, related to SGX instructions and will talk to SGX driver. It is a shared object, not only used in SGX SDK but also used in OE SDK or other SDKs.  The APIs in SGX SDK are more high level and will eventually call Enclave Common Loader APIs after some preparations. You should use the APIs from SGX SDK to load/unload your enclaves.

> 2. The example {[https://github.com/intel/linux-sgx/tree/master/SampleCode/SampleCommonLoader}](https://github.com/intel/linux-sgx/tree/master/SampleCode/SampleCommonLoader%7D) from enclave common loaders does not make any ecalls or ocalls. What is the purpose of the example?

IMO, this example is just to demonstrate how to call the low level APIs. It is useful for the person who want to write an SGX SDK, such as OE. It is not for end users who just want to use SGX SDK.

**Comment by qinkunbao** [comment]
Thanks for your reply. 

Oh, I thought APIs in SGX SDK talks to the driver directly via ioctl. 

It seems to me that
`enclave_create` = ECREATE.
`sgx_create_enclave` = Validation, ECREATE, EADD, EINIT, creating TCS, makes the first ecall to initialize the enclave.
