### ISSUE TITLE
Is Reference Launch Enclave available in a deb package?

### ISSUE THREAD

**Issue by hatena75** [intel/linux-sgx#908]
Hello,

I would like to use ref-LE, but the [ref.md](https://github.com/intel/linux-sgx/blob/master/psw/ae/ref_le/ref_le.md) only describes how to install PSW in .bin. So, for example, I get a dependency error when installing the deb package of DCAP's QuoteGenerationLibrary.

There is a deb package version in aesm, but is there any way to use Reference Launch Enclave with this?

**Comment by llly** [comment]
No currently. You can install all deb package except `sgx-aesm-service`. Because `aesm_servce` and some related components are different when build with `BUILD_REF_LE=1`. Should not mix it.
