### ISSUE TITLE
The aesmd.service file is abnormal after the OS is upgraded.

### ISSUE THREAD

**Issue by wufei832002** [intel/linux-sgx#910]
The aesmd.service file is abnormal after the OS is upgraded.

`Redirecting to /bin/systemctl status aesmd.service
● aesmd.service - Intel(R) Architectural Enclave Service Manager
   Loaded: loaded (/usr/lib/systemd/system/aesmd.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2022-11-15 16:28:23 CST; 7s ago
  Process: 14736 ExecStartPre=/opt/intel/sgxpsw/aesm/linksgx.sh (code=exited, status=0/SUCCESS)
  Process: 14741 ExecStartPre=/bin/mkdir -p /var/run/aesmd/ (code=exited, status=0/SUCCESS)
  Process: 14743 ExecStartPre=/bin/chown -R aesmd:aesmd /var/run/aesmd/ (code=exited, status=0/SUCCESS)
  Process: 14745 ExecStartPre=/bin/chmod 0755 /var/run/aesmd/ (code=exited, status=0/SUCCESS)
  Process: 14747 ExecStart=/opt/intel/sgxpsw/aesm/aesm_service (code=exited, status=200/CHDIR)`

journalctl log
`[root@localhost stdm]# journalctl -u aesmd.service
-- Logs begin at Tue 2022-11-15 16:07:23 CST, end at Tue 2022-11-15 16:25:29 CST. --
Nov 15 16:24:51 localhost.localdomain systemd[1]: Starting Intel(R) Architectural Enclave Service Manager...
Nov 15 16:24:51 localhost.localdomain systemd[1]: aesmd.service: Control process exited, code=exited, status=200/CHDIR
Nov 15 16:24:51 localhost.localdomain systemd[1]: aesmd.service: Failed with result 'exit-code'.
Nov 15 16:24:51 localhost.localdomain systemd[1]: Failed to start Intel(R) Architectural Enclave Service Manager.
Nov 15 16:25:06 localhost.localdomain systemd[1]: aesmd.service: Service RestartSec=15s expired, scheduling restart.
Nov 15 16:25:06 localhost.localdomain systemd[1]: aesmd.service: Scheduled restart job, restart counter is at 1.
Nov 15 16:25:06 localhost.localdomain systemd[1]: Stopped Intel(R) Architectural Enclave Service Manager.
Nov 15 16:25:06 localhost.localdomain systemd[1]: Starting Intel(R) Architectural Enclave Service Manager...
Nov 15 16:25:06 localhost.localdomain systemd[1]: aesmd.service: Control process exited, code=exited, status=200/CHDIR
Nov 15 16:25:06 localhost.localdomain systemd[1]: aesmd.service: Failed with result 'exit-code'.
Nov 15 16:25:06 localhost.localdomain systemd[1]: Failed to start Intel(R) Architectural Enclave Service Manager.
Nov 15 16:25:21 localhost.localdomain systemd[1]: aesmd.service: Service RestartSec=15s expired, scheduling restart.
Nov 15 16:25:21 localhost.localdomain systemd[1]: aesmd.service: Scheduled restart job, restart counter is at 2.
Nov 15 16:25:21 localhost.localdomain systemd[1]: Stopped Intel(R) Architectural Enclave Service Manager.
Nov 15 16:25:21 localhost.localdomain systemd[1]: Starting Intel(R) Architectural Enclave Service Manager...
Nov 15 16:25:21 localhost.localdomain systemd[1]: aesmd.service: Control process exited, code=exited, status=200/CHDIR
Nov 15 16:25:21 localhost.localdomain systemd[1]: aesmd.service: Failed with result 'exit-code'.
Nov 15 16:25:21 localhost.localdomain systemd[1]: Failed to start Intel(R) Architectural Enclave Service Manager.`

lsmod 

`[root@localhost stdm]# lsmod |grep sgx
isgx                   53248  0`

dmesg

`[root@localhost stdm]# dmesg|grep sgx
[  959.122041] isgx: module verification failed: signature and/or required key missing - tainting kernel
[  959.122856] intel_sgx: Intel SGX Driver v2.11.0
[  959.122868] intel_sgx INT0E0C:00: EPC bank 0x90200000-0x95f80000
[  959.123844] intel_sgx: second initialization call skipped`

**Comment by llly** [comment]
It's caused by aesm-service runtime dependency doesn't satisfied. For example, `libprotobuf.so.10` removed and `libprotobuf.so.17` installed, or `libprotobuf.so.23`.  You can update repository or build package then install it again.

**Comment by wufei832002** [comment]
I used libprotobuf.so.20 or do I have to use17 or 23?

`-rw-r--r--. 1 root root 7082592 May 28 17:00 libprotobuf.a
lrwxrwxrwx. 1 root root      21 May 28 17:00 libprotobuf.so -> libprotobuf.so.20.0.0
lrwxrwxrwx. 1 root root      21 May 28 17:00 libprotobuf.so.20 -> libprotobuf.so.20.0.0
-rwxr-xr-x. 1 root root 3108896 May 28 17:00 libprotobuf.so.20.0.0
`

**Comment by llly** [comment]
You'd better to remove `sgx-aesm-service` package and install it again after OS upgrade. And if you uses online repo, remember to update OS code in `intel-sgx.list`, for example, from `focal` to `jammy`.
