### ISSUE TITLE
Error in developer reference: Support for <random>

### ISSUE THREAD

**Issue by adrianlut** [intel/linux-sgx#913]
On Page 452, the [Intel SGX Developer Reference](https://download.01.org/intel-sgx/sgx-linux/2.17.1/docs/Intel_SGX_Developer_Reference_Linux_2.17.1_Open_Source.pdf) states, that the random header is not supported inside SGX files. However, it seems that the header is fully functional and included in tlibcxx since SDK version 2.8. See changes in 9ddec08fb98c1636ed3b1a77bbc4fa3520344ede. Basically, random_device calls sgx_read_rand to get randomness now.

Therefore I assume it is possible and fine to use the random header and the Developer Reference just has not been updated to reflect this. Is that correct?

After a quick search I found out that this issue has already been raised in the discussion of #428 but was never fixed.

**Comment by lzha101** [comment]
Yes, `random` has been supported for a long time and the Developer Reference is out of date. The doc fix will be included in next release.

**Comment by adrianlut** [comment]
I confirmed that this is fixed. Thank you!
