### ISSUE TITLE
SDK 2.18 - `clangd` code completion issues

### ISSUE THREAD

**Issue by Hans-Giebenrath** [intel/linux-sgx#914]
Hello and thank you a lot for C++17 support in the lates 2.18 release, we were very much looking forward to this.

I discovered an issue with code completion, maybe you can guide me or confirm this is a bug.

Code compiles fine on the command line running `make` with `gcc`/`g++`, tests are green, so nothing to report here.

However, in the text editor I use `clangd` for LSP capabilities, and this generates a lot of seemingly unrelated errors in header files.
Now, I think the main problem is that `clangd` is, well, clang, and thus it does not include the `__sgx` header. This is [only included for GCC](https://github.com/intel/linux-sgx/blob/b0af6e75ac519ad5002a68fda0b672feddc1c92d/sdk/tlibcxx/include/__config#L519).
The containing `#if` block is basically (inlined and pseudocode-ified, but you get the point)

```
#if clang
...
#elif GCC
#include <__sgx>
...
#elif ..
```

So `clangd` doesn't read the relevant header and thus will create a bunch of wild error messages.

Now, I get that you focus on support for GCC, but I think that working LSP support is very important today.
Do you face the same problem? Or is it rather some problem with my local development setup?

Workaround: Modifying the local SGX SDK seemed to work (unconditionally include `__sgx`), but for reasons this solution is suboptimal in our case. Hence I went with another way of trying harder to make `clangd` look like `gcc`, but only when generating the `compile_commands.json` file with `cmake`. Here is the relevant snippet, in case other people have the same problem (happy about any comments):

```
IF(CMAKE_EXPORT_COMPILE_COMMANDS)
    TARGET_COMPILE_OPTIONS(${TARGET}
        PRIVATE
            "-U__clang__"
            "-D__GNUC__=8"
            "-D__GNUC_MINOR__=2"
            "-D__GNUC_PATCHLEVEL__=0"
            "-D_Decimal32="
            "-D_Decimal64="
            "-D_Decimal128="
    )
ENDIF()
```

At least for now this seems to resolve all errors in the headers that I included and checked, but it might still miss some problem in a header which I did not yet use.

**Comment by xxu36** [comment]
Thanks for reporting this issue and the solution. 
Currently we do not support using clang to build the SDK. For LSP, we did not receive many requirements for its support so it is not on the plan.

**Comment by Hans-Giebenrath** [comment]
Thank you for clarification.

> we did not receive many requirements for its support

It could be that it previously worked without problem for everybody, such that no-one remembered to mention it explicitly as a requirement :D

Since it is not on your roadmap, I close the issue. (If you think that it is still some relevant issue to keep around, feel free to reopen it.)

**Comment by xxu36** [comment]
Sure, thank you.
> If you think that it is still some relevant issue to keep around, feel free to reopen it.

**Comment by csegarragonz** [comment]
Hi @xxu36,

I am running into a similar issue. I would like to clarify that this doesn't only happen when building the SDK, but also when building _any_ C++ project that uses the SDK headers.

I can build the SDK version `2.18.1` just fine, but when I try to include it in a C++ project that is built using `clang`, the compiler issues a bunch of compilation warnings related to missing headers.

I would like to point out that this used to work just fine before, so I think it is a regression.

Could you re-open the issue and take a look?
