### ISSUE TITLE
Error when execute ./app in SampleEnclave after make

### ISSUE THREAD

**Issue by SicherZoeng** [intel/linux-sgx#923]
When I executed `sudo make` in `/opt/intel/sgxsdk/SampleEnclave` and then execute the app using `./app`, I met this error:
```
./app: error while loading shared libraries: libsgx_urts.so.2: cannot open shared object file: No such file or directory
```

However, I found it under `/opt/intel/sgxsdk/lib64`:
```
cve_2020_0551_cf        libsgx_protobuf.a       libsgx_tstdc.a
cve_2020_0551_load      libsgx_pthread.a        libsgx_tswitchless.a
gdb-sgx-plugin          libsgx_ptrace.so        libsgx_ttls.a
libc++_Changes_SGX.txt  libsgx_quote_ex_sim.so  libsgx_uae_service_sim.so
libsgx_capable.a        libsgx_quote_ex.so      libsgx_uae_service.so
libsgx_capable.so       libsgx_tcmalloc.a       libsgx_ukey_exchange.a
libsgx_dcap_tvl.a       libsgx_tcrypto.a        libsgx_uprotected_fs.a
libsgx_epid_sim.so      libsgx_tcxx.a           libsgx_urts_sim.so
libsgx_epid.so          libsgx_tkey_exchange.a  libsgx_urts.so
libsgx_launch_sim.so    libsgx_tprotected_fs.a  libsgx_urts.so.2
libsgx_launch.so        libsgx_trts.a           libsgx_uswitchless.a
libsgx_omp.a            libsgx_trts_sim.a       libsgx_utls.a
libsgx_pcl.a            libsgx_tservice.a       libtdx_tls.a
libsgx_pclsim.a         libsgx_tservice_sim.a
```

I searched libsgx_urts.so.2 in the `~/linux-sgx/` directory using `find -name libsgx_urts.so.2`, I got this:
```
./build/linux/libsgx_urts.so.2
```
Then I searched libsgx_urts.so in that directory using `find -name libsgx_urts.so`, I got this:
```
./psw/urts/linux/libsgx_urts.so
./linux/installer/common/libsgx-urts/output/pkgroot/libsgx-urts/lib/libsgx_urts.so
./linux/installer/common/sdk/output/package/lib64/libsgx_urts.so
./build/linux/libsgx_urts.so
```
I wonder how to solve this problem. THANK YOU A LOT FOR HELPING!

**Comment by andyzyb** [comment]
Looks you updated the SDK, but not PSW which has new libsgx_urts.so

**Comment by SicherZoeng** [comment]
> Looks you updated the SDK, but not PSW which has new libsgx_urts.so

Thank you a lot! I did git clone the main branch of linux-sgx, then execute make sdk and make psw according to the README.md. So what should I do? Should I git clone the old version of linux-sgx?

**Comment by SicherZoeng** [comment]
> Looks you updated the SDK, but not PSW which has new libsgx_urts.so

Thanks a lot for helpful reply! I repeated make under root priviledge and apt install some relied packets for psw, then the problem was solved.
