### ISSUE TITLE
EPID SDK example inside enclave

### ISSUE THREAD

**Issue by joon5283** [intel/linux-sgx#926]
Hello, I have started playing with SGX.

I am trying to execute the EPID SDK example inside an enclave.
The example code is from [here](https://github.com/Intel-EPID-SDK/epid-sdk/blob/v7.0.0/example/signmsg/src/main.c). 

I compiled all the files inside the example and added similar content to the main function into Enclave.cpp function.

> sgx_status_t key_request(char *encMessageOut, size_t encMessageOutLen)
> {
>     EpidStatus result = kEpidErr;
> 
>     static char* basename_str = "temp";
>     size_t basename_size = strlen(basename_str);
> 
>     unsigned char* signed_sig_rl = NULL;
>     size_t signed_sig_rl_size = 0;
> 
>     size_t signed_pubkey_size = 0;
>     unsigned char* signed_pubkey = NewBufferFromFile("pubkey.bin", &signed_pubkey_size);
> 
>     size_t mprivkey_size = 0;
>     unsigned char* mprivkey = NewBufferFromFile("mprivkey.dat", &mprivkey_size);
> 
>     MemberPrecomp* member_precmp_ptr = NULL;
> 
>     EpidSignature* sig = NULL;
>     size_t sig_size = 0;
>     char* msg_str = "key request";
>     size_t msg_size = strlen(msg_str);
>     memcpy(key_request.bsm, msg_str, strlen(msg_str)+1);
> 
>     EpidCaCertificate cacert = {0};
>     if (0 != ReadLoud("cacert.bin", &cacert, sizeof(cacert)))
>     {
>         return NULL;
>     }
> 
>     result = SignMsg(msg_str, msg_size, basename_str, basename_size, signed_sig_rl,
>             signed_sig_rl_size, signed_pubkey, signed_pubkey_size, mprivkey,
>             mprivkey_size, member_precmp_ptr, &sig, &sig_size, &cacert);
> 
>     memcpy(encMessageOut, &sig, encMessageOutLen);
> 
>     return NULL;

Then, I generate a shared library by using 'gcc -shared signmsg.o prng.o libsignmsg.so'. and did similar things on example util files.
I linked the signmsg and util inside the Makefile and it shows an undefined reference error.

> /usr/local/bin/ld: Enclave.cpp:(.text.key_request+0x5f): undefined reference to `NewBufferFromFile(char const*, unsigned long*)'
> /usr/local/bin/ld: Enclave.cpp:(.text.key_request+0xdf): undefined reference to `ReadLoud(char const*, void*, unsigned long)'
> /usr/local/bin/ld: Enclave.cpp:(.text.key_request+0x12a): undefined reference to `SignMsg(void const*, unsigned long, void const*, unsigned long, unsigned char const*, unsigned long, unsigned char const*, unsigned long, unsigned char const*, unsigned long, MemberPrecomp*, void**, unsigned long*, EpidCaCertificate const*)'

Could you guide me on how to program the EPID SDK example file inside the Enclave? Any help will be appreciated.
Thank you so much for your help in advance.

**Comment by llly** [comment]
Shared library cannot be used in enclave.
SGX has a ported EPID SDK in `external/epid-sdk`. SGX Quoting Enclave uses it. You can cd to `psw/ae/qe` and make to see how EPID SDK for Enclave works.

**Comment by joon5283** [comment]
@llly Thanks for the suggestion. I will take a look quoting_enclave.cpp.

By the way, so is it impossible to use the SignMsg function of EPID example code inside Enclave? 
Because I only want to generate the signature and verify it using EPID. So, SignMsg and VerifySig functions are doing exactly the same as I want to do. 

Thanks for your help in advance.

**Comment by llly** [comment]
Yes. SignMsg function itself can work.
However, Enclave cannot access files directly. You need to rewrite functions to handle buffer instead of file in enclave, prepare buffer in app and pass the buffer to enclave through EDL function.

**Comment by joon5283** [comment]
@llly  I see. Thanks for letting me know.

Lastly, I have a last question about linking. 

> Enclave.cpp:(.text+0x66): undefined reference to EpidSignBasic(MemberCtx const*, void const*, unsigned long, void const*, unsigned long, BasicSignature*, BigNumStr*) /usr/local/bin/ld: Enclave.cpp:(.text+0x98): undefined reference to `EpidNrProve(MemberCtx const*, void const*, unsigned long, void const*, unsigned long, BasicSignature const*, SigRlEntry const*, NrProof*)'

I was trying to use EpidSignBasic function inside the enclave. Since these functions are defined in external/epid-sdk/epid/member/src/signbasic.c file. Furthermore, all of the files inside the src folder are compiled and they generate libmember.a. Therefore, I add linking as -L./epid-sdk/epid/member -lmember. However, the previous error does not disappear. Could you let me know what will be the problem?

Thank you so much for your help.

**Comment by llly** [comment]
try add `extern "C"` as quoting_enclave.cpp does.
```
#ifdef __cplusplus
extern "C" {
#endif
#include "epid/member/software_member.h"
#include "epid/member/src/write_precomp.h"
#include "epid/member/src/signbasic.h"
#include "epid/member/src/nrprove.h"
#ifdef __cplusplus
}
#endif
```

**Comment by joon5283** [comment]
@llly Yes. 

> Enclave.cpp:(.text+0x66): undefined reference to EpidSignBasic(MemberCtx const*, void const*, unsigned long, void const*, unsigned long, BasicSignature*, BigNumStr*) /usr/local/bin/ld: Enclave.cpp:(.text+0x98): undefined reference to `EpidNrProve(MemberCtx const*, void const*, unsigned long, void const*, unsigned long, BasicSignature const*, SigRlEntry const*, NrProof*)'

The above one disappears! Thanks. However, 

> /usr/local/bin/ld: Enclave/Enclave.o:(.rodata+0x1ab0): multiple definition of g_dyn_entry_table'; Enclave/Enclave_t.o:(.rodata+0x0): first defined here
> /usr/local/bin/ld: Enclave/Enclave.o:(.data.rel.ro.local+0x0): multiple definition of g_ecall_table'; Enclave/Enclave_t.o:(.data.rel.ro.local+0x0): first defined here

The above two errors happen. Could you give me advice on how to resolve it? I do not have any import in my edl file.

Thank you so much.

**Comment by llly** [comment]
Remove `#include Enclave_t.c` from `Enclave.c` because you also link it.

**Comment by joon5283** [comment]
I really appreciate your help. Compilation works well now. Thank you so much!!!!
