### ISSUE TITLE
RSA public key copy

### ISSUE THREAD

**Issue by joon5283** [intel/linux-sgx#927]
Hello, thanks for providing such a great tool.

I am playing with RSA encryption and decryption. What I am trying to do is generate RSA public key inside an enclave.
Then, copy the public key to the output of the function. 
Next, an application will pass the copy of the public key to the enclave again and encrypt the data with the copied public key.

The process is like the one below.
**inside Enclave**
sgx_create_rsa_key_pair (...)
sgx_create_rsa_pub1_key(pub_key); // void *pub_key
memcpy(messageOut, (unsigned long *)pub_key, size);

**Inside App**
another_function(messageOut)

**another_function inside enclave**
void *new_pub_key;
new_pub_key = (void *)messageIn;

If performing the above process, the result of *(unsigned char *)(pub_key + i) and *(unsigned char *)(new_pub_key + i) is identical which means the content of the key seems copied properly.
However, when I try to execute sgx_rsa_pub_encrypt_sha256(new_pub_key), it returns 1 which is SGX_ERROR_UNEXPECTED.
Is there any way to copy the RSA public key properly? My ultimate goal is to generate the RSA public key inside and Enclave and sends it to clients through socket programming.

Thanks for your help in advance. Have a great holiday.

**Comment by lzha101** [comment]
1. Looks the sgx_create_rsa_pub1_key() API requires &pub_key as the input.  

> sgx_status_t sgx_create_rsa_pub1_key(int mod_size, int exp_size, const unsigned char *le_n, const unsigned char *le_e, **void \*\*new_pub_key1**)

2.  Can you tell how you get the `size` value, that you are using in the memcpy?

If you just want to copy the public RSA key outside, I think you can directly copy the public part (`p_n,` `p_e`) of the RSA key pair to untrusted domain after the` sgx_create_rsa_key_pair() `API.  Then you can use the N and E to construct the public key in the clients.

**Comment by joon5283** [comment]
@lzha101 Thanks for your answer.

1. Yes. I think I used the correct parameter which is (void**)&pub_key. I followed the example code.
2. Since I am using the parameter as sgx_create_rsa_pub1_key(SGX_RSA3072_KEY_SIZE, SGX_RSA3072_PUB_EXP_SIZE, ...)
I am using the RSA size SGX_RSA3072_KEY_SIZE (i.e., 384). That is the size value I used. Will the size be larger than this one?

Also, thanks for the alternative way.

**Comment by lzha101** [comment]
> Will the size be larger than this one?

I think so. The pub_key is actually pointing to the key context. The type is IppsRSAPublicKeyState by default. The size of the context is not 384.  384 is actually the size of N.

**Comment by joon5283** [comment]
@lzha101  Thanks for the advice. That makes sense.

Your alternative suggestion works perfectly. I appreciate your help!
