### ISSUE TITLE
Ubuntu 22 Based Docker

### ISSUE THREAD

**Issue by rdockterjr** [intel/linux-sgx#946]
I've noticed that the Dockerfiles for aesm and sample running are still based on Ubuntu 18.04. For various reasons I would like to run these images based on an Ubuntu 22.04 image using the latest SDK and libraries. 

Is there a reason that these examples are pegged at ubuntu 18? Have you done any testing with an Ubuntu 22.04 based system?

Any guidance would be appreciated.

**Comment by lzha101** [comment]
> Is there a reason that these examples are pegged at ubuntu 18? 

Current Dockerfiles were created two or three years ago. Seems at that time Ubuntu 18.04 was the mainstream distro. 

> Have you done any testing with an Ubuntu 22.04 based system?

We have tested on Ubuntu 22.04 on bare metal machines. But we don't test Ubuntu 22.04 in docker environment. I think it should be similar as the existing Docker file, except some dependency, toolset difference.

**Comment by rdockterjr** [comment]
Thanks for the reply. I've done some testing of this on my own the only difference I had to make for an ubuntu 22.04 based image was using the asc key apt commands to install the deb package:

`RUN  echo 'deb [signed-by=/etc/apt/keyrings/intel-sgx-keyring.asc arch=amd64] https://download.01.org/intel-sgx/sgx_repo/ubuntu jammy main' >> /etc/apt/sources.list.d/intel-sgx.list && \

wget -qO- https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key | tee -a /etc/apt/keyrings/intel-sgx-keyring.asc`

Then for host systems the important thing was to make sure the newer 'sgx' group was applied to the host user account. Also making sure the newer udev rules were applied to the /dev/sgx_enclave devices. I'll close this issue.
