### ISSUE TITLE
libsgx_tcrypto not allowing calls from host side

### ISSUE THREAD

**Issue by manuelgustavo** [intel/linux-sgx#958]
e.g., a call to IPP version of `sgx_tcrypto`'s  `sgx_sha256_msg(vec.data(), vec.size, &h);` used to work on the host side.
This can easily be tested on e.g. SampleEnclave, by adding the following:

`Makefile`
``` Makefile
...
App_Link_Flags := -L$(SGX_LIBRARY_PATH) -l$(Urts_Library_Name) -lpthread -lsgx_tcrypto
...
```

`App.cpp`
``` c++
...
#include <sgx_tcrypto.h>
...
int SGX_CDECL main(int argc, char *argv[])
{
    (void)(argc);
    (void)(argv);

    uint8_t c;
    sgx_sha256_hash_t h{};
    sgx_status_t err = sgx_sha256_msg(&c, 1, &h);
    sgx_sha_state_handle_t sha_context;
    sgx_sha256_init(&sha_context);
    printf("err = %d\n", err);
...
```
Stepping through linux-sgx's source code, I've found out that the failure happens within `ippcpGetEnabledCpuFeatures()`, which returns `0` in the following call.

``` c++
IPPFUN( const IppsHashMethod*, sgx_disp_ippsHashMethod_SHA256_TT, (void) )
{
    Ipp64u _features;
    _features = ippcpGetEnabledCpuFeatures();

    if( AVX3I_FEATURES  == ( _features & AVX3I_FEATURES  )) {
        return k1_ippsHashMethod_SHA256_TT(  );
    } else 
    if( ippCPUID_AVX2  == ( _features & ippCPUID_AVX2  )) {
        return l9_ippsHashMethod_SHA256_TT(  );
    } else 
    if( ippCPUID_SSE42  == ( _features & ippCPUID_SSE42  )) {
        return y8_ippsHashMethod_SHA256_TT(  );
    } else 
        return NULL;
}
```

As part of `sgx_create_enclave`'s initialization process, a call to `ippcpSetCpuFeatures` is performed, which enables ippcpGetEnabledCpuFeatures().

Calling `ippcpInit()` on the host side, which internally performs a call to `ippcpGetCpuFeatures` and subsequently to `ippcpSetCpuFeatures` with its returned value, seems to fix the issue.

This raised the question if libsgx_tcrypto was ever intended to be used on the host side, though I haven't found a reason why it shouldn't. Also, it's good to be able to call the same function on trusted and untrusted code, as it should highlight that the code behaves in a similar way.

Regardless of that, please let me know if this is working as expected. Also, maybe more information in the specification would be nice.

Thanks,

Manuel Saraiva
manuel.gustavo@gmail.com

**Comment by lzha101** [comment]
Hi, @manuelgustavo. The sgx_tcrypto library is for trusted code by design. But as you described, you can use it in the untrusted code although we don't validate this usage. The failure you meet is caused by the updated IPP crypto lib behavior changes. We have reported this behavior change to the IPP crypto owners. Let's wait for their behavior change back in future. Right now, you can use the walkaround to call ippcpInit() first as what we are doing in [ref_le](https://github.com/intel/linux-sgx/blob/e7bbc158fa242cf5b5534ecb1fb2668edf5cd887/psw/ae/ref_le/ref_wl_gen/ref_wl.cpp#L40).

**Comment by manuelgustavo** [comment]
Hi @lzha101, thank you very much for your quick reply.

I'm using ippcpInit() and it's working, though not for all the IPP calls that we do, which may be something else (pending investigation in the following weeks).
I will let you know if we find a solution for it.

Best, Manuel
