### ISSUE TITLE
Error with make sdk

### ISSUE THREAD

**Issue by ksy980418** [intel/linux-sgx#964]
I got some error while make sdk like below.

I checked that migration tools are successfully copied.

I found similar issues with centOS but I cannot understand how do I fix it.

________________________________________________________________________
~/linux-sgx$ which ar as ld objcopy objdump ranlib
/usr/local/bin/ar
/usr/local/bin/as
/usr/local/bin/ld
/usr/local/bin/objcopy
/usr/local/bin/objdump
/usr/local/bin/ranlib
________________________________________________________________________

/usr/bin/x86_64-linux-gnu-as: unrecognized option '-mlfence-after-load=yes'
make[3]: *** [Makefile:57: sethread_mutex.o] Error 1
make[3]: Leaving directory '/home/ksy980418/linux-sgx/sdk/tlibthread'
make[2]: *** [Makefile.source:99: tlibthread] Error 2
make[2]: Leaving directory '/home/ksy980418/linux-sgx/sdk'
make[1]: *** [Makefile:50: all] Error 2
make[1]: Leaving directory '/home/ksy980418/linux-sgx/sdk'
make: *** [Makefile:72: sdk] Error 2

**Comment by llly** [comment]
Building toolchain on your platform uses `x86_64-linux-gnu-as` instead of `as`. You can copy `as` to `/usr/local/bin/x86_64-linux-gnu-as`, and maybe also the other executables.
Can you provide OS name and version of this platform?

**Comment by ksy980418** [comment]
Sorry I found that it was my mistake.
The gcc version was not satisfied.
But after that I got some new error during make psw like below.

Thank you

Ubuntu 20.04 & gcc 9.4.0

linux-sgx/psw/urts/enclave_creator_hw_com.cpp:169:29: error: ‘SGX_FLAGS_AEX_NOTIFY’ was not declared in this scope
  169 |     if(((secs_attr->flags & SGX_FLAGS_AEX_NOTIFY) != false) && (is_edeccssa_supported() == false))
      |                             ^~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:155: enclave_creator_hw_com.o] Error 1

**Comment by llly** [comment]
You need to install the SDK you just built out and `source` following the README.

**Comment by ksy980418** [comment]
I already done with make sdk.

Do I need to do something more?

**Comment by llly** [comment]
```
$ cd linux/installer/bin
$ ./sgx_linux_x64_sdk_${version}.bin
 ```
and `$ source ${sgx-sdk-install-path}/environment`. Please check `Install the Intel(R) SGX SDK` section in README.

**Comment by ksy980418** [comment]
Sorry but even though I successfully installed SDK, the same error occurs.

**Comment by llly** [comment]
This flag is just added in 2.20 release.
https://github.com/intel/linux-sgx/blob/a1eeccba5a72b3b9b342569d2cc469ece106d3e9/common/inc/sgx_attributes.h#L44
You are compiling PSW using an out-of-date SDK, instead of the latest one.

**Comment by ksy980418** [comment]
I checked that installer version is 2.20.

``` ~/linux-sgx$ ls linux/installer/bin/
build-installpkg.sh       install-sgx-sdk.bin.tmpl
install-sgx-psw.bin.tmpl  sgx_linux_x64_sdk_2.20.100.4.bin

**Comment by llly** [comment]
Well, check putput of this command
```
$ grep SGX_FLAGS_AEX_NOTIFY ${SGX_SDK}/include/sgx_attributes.h
#define SGX_FLAGS_AEX_NOTIFY     0x0000000000000400ULL     /* If set, then the enclave enables AEX Notify */
```

**Comment by ksy980418** [comment]
```
~/linux-sgx$ grep SGX_FLAGS_AEX_NOTIFY ${SGX_SDK}/include/sgx_attributes.h
#define SGX_FLAGS_AEX_NOTIFY     0x0000000000000400ULL     /* If set, then the enclave enables AEX Notify */

**Comment by llly** [comment]
Yes, it's correct. Then, `error: ‘SGX_FLAGS_AEX_NOTIFY’ was not declared` shouldn't exist.

**Comment by ksy980418** [comment]
But it happens to me... 

```
/home/ksy980418/linux-sgx/psw/urts/enclave_creator_hw_com.cpp:169:29: error: ‘SGX_FLAGS_AEX_NOTIFY’ was not declared in this scope
  169 |     if(((secs_attr->flags & SGX_FLAGS_AEX_NOTIFY) != false) && (is_edeccssa_supported() == false))
      |                             ^~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:155: enclave_creator_hw_com.o] Error 1
make[2]: Leaving directory '/home/ksy980418/linux-sgx/psw/urts/linux'
make[1]: *** [Makefile:46: urts] Error 2
make[1]: Leaving directory '/home/ksy980418/linux-sgx/psw'
make: *** [Makefile:63: psw] Error 2
ksy980418@wbs79-System-Product-Name:~/linux-sgx$ grep SGX_FLAGS_AEX_NOTIFY ${SGX_SDK}/include/sgx_attributes.h
#define SGX_FLAGS_AEX_NOTIFY     0x0000000000000400ULL     /* If set, then the enclave enables AEX Notify */

**Comment by llly** [comment]
You can run this command to see which header files you are really using
`pushd psw/urts/linux/; make clean; CXXFLAGS=-MMD make; grep sgx_attributes.h  enclave_thread.d; popd`

**Comment by ksy980418** [comment]
Oh... it results reasonable
Then how do I fix it?

```
~/linux-sgx/psw/urts/linux$ grep sgx_attributes.h  enclave_thread.d
 /opt/intel/sgxsdk/include/sgx_attributes.h \
 /opt/intel/sgxsdk/include/sgx_attributes.h \

**Comment by ksy980418** [comment]
It solved by reinstalling in /opt/intel/ folder.

Thanks for your help.
