### ISSUE TITLE
keeping data inside the enclave till it's destruction

### ISSUE THREAD

**Issue by johnkaramp** [intel/linux-sgx#973]
Hello, is there any way to keep some data inside the enclave starting from it's creation till it's destruction and use them for example each time i invoke an OCALL? Can i use a global array and initialise each element with one ECALL i invoke or after the first ECALL returns, the data i just initialised will be lost? (i tested that and they remain accessible, but i cannot say for sure if they are there because they are not overwritten yet, like a C++ regular runtime).

On a side note, i was trying to learn how the LRU cache of intel protected file system works and how it keeps some blocks of data inside the enclave (i assume there is a way each ECALL searches if a block is already stored in some LRU node, before initiating an OCALL to transfer the corresponding block inside the enclave, because otherwise it will be continues transfers between untrusted and trusted domain - high overhead), but could not find whether there is a global class object that they initialise somewhere at first.

For reference, i read a paper that attempts to create a virtual file system with the help of SGX. Here is the enclave's c++ code: [[sgx-fs](https://github.com/dburihabwa/sgx-fs/blob/master/Enclave/Enclave.cpp)] As you can see there is a global pointer (line:18) that is initialised inside a function (line:158) with an object. How can something like that work and the object still exist after the _init_ function returns?

**Comment by lzha101** [comment]
Yes, you can use a global variable in the enclave. The global variable will be existed until the destruction function is triggered or the enclave is destroyed.  Actually, we have demonstrated this kind of usage in the sample code, for example: https://github.com/intel/linux-sgx/blob/f656e74afd6ecdbdc2d7397db7ebd46d8cf46ca6/SampleCode/PowerTransition/Enclave/Enclave.cpp#L43-L44
You can treat the SGX enclave similar as a normal shared object in this case.  A local variable defined in an ECALL is in the trusted stack so it will be inaccessible after the ECALL return.  While a global variable is not in the trusted stack but in the .data or .bss section and will be accessible globally inside enclave.
