### ISSUE TITLE
Failed to open Intel SGX device

### ISSUE THREAD

**Issue by LiuJohn-1886** [intel/linux-sgx#974]
Anyone can please help to take a look at this issue?

Refer to issue: https://github.com/intel/intel-device-plugins-for-kubernetes/issues/1526

```
$ kubectl logs oe-helloworld-onetwo-sndd9
[get_driver_type /home/sgx/jenkins/ubuntuServer2004-release-build-trunk-218/build_target/PROD/label/Builder-UbuntuSrv20/label_exp/ubuntu64/linux-trunk-opensource/psw/urts/linux/edmm_utility.cpp:111] Failed to open Intel SGX device.
oe_create_helloworld_enclave(): result=21 (OE_PLATFORM_ERROR)
2023-09-18T19:56:18+0000.514554Z [(H)ERROR] tid(0x7fde872e6f40) | enclave_create with ENCLAVE_TYPE_SGX1 type failed (err=0x1) (oe_result_t=OE_PLATFORM_ERROR) [/source/openenclave/host/sgx/sgxload.c:oe_sgx_create_enclave:454]
2023-09-18T19:56:18+0000.514565Z [(H)ERROR] tid(0x7fde872e6f40) | :OE_PLATFORM_ERROR [/source/openenclave/host/sgx/create.c:oe_sgx_build_enclave:1074]
2023-09-18T19:56:18+0000.514635Z [(H)ERROR] tid(0x7fde872e6f40) | :OE_PLATFORM_ERROR [/source/openenclave/host/sgx/create.c:oe_create_enclave:1345]
```

But after I monted  /dev path in oe-helloworld yaml file, the application works.

```
apiVersion: batch/v1
kind: Job
metadata:
  name: oe-helloworld-onetwo-mountdev
spec:
  template:
    metadata:
      labels:
        app: oe-helloworld-onetwo-mountdev
    spec:
      containers:
      - name: oe-helloworld-onetwo-mountdev
        image: mcr.microsoft.com/acc/samples/helloworld-outproc:1.2
        volumeMounts:
        - name: var-run-aesmd
          mountPath: /var/run/aesmd
        - name: sgxdevices
          mountPath: /dev
          readOnly: true
        resources:
          limits:
            kubernetes.azure.com/sgx_epc_mem_in_MiB: 10
          requests:
            kubernetes.azure.com/sgx_epc_mem_in_MiB: 10
      volumes:
      - name: var-run-aesmd
        hostPath:
          path: /var/run/aesmd
      - name: sgxdevices
        hostPath:
          path: /dev
          type: DirectoryOrCreate
      restartPolicy: "Never"
  backoffLimit: 0
```

I'd like to know why the same application works before, but now we have to mount /dev path？

**Comment by mythi** [comment]
> `/home/sgx/jenkins/ubuntuServer2004-release-build-trunk-218`

isn't this 2.18 where the SDK failed to open any upstream device nodes. See #920

**Comment by LiuJohn-1886** [comment]
This issue is not releted to psw 2.18.  I built the sgx_plugin from commit 17bf4c497c6a2621dab5b92cab4494e1c96141cc of repo [intel-device-plugins-for-kubernetes]. This issue should relate to sgx_plugin.  we install PSW inside a container sgx-quote-helper, the Host only exposes the sgx devices to the sgx_plugin.

**Comment by mythi** [comment]
@LiuJohn-1886 but you are using PSW 2.18?

**Comment by LiuJohn-1886** [comment]
I am using PWS 2.21.100.

**Comment by LiuJohn-1886** [comment]
> @LiuJohn-1886 but you are using PSW 2.18?



> @LiuJohn-1886 but you are using PSW 2.18?

I am using PWS 2.21.100.

**Comment by mythi** [comment]
@LiuJohn-1886 OK, in order to help, can you provide the output of

```
$ ls -la /dev/sgx*
```

on your node.

**Comment by LiuJohn-1886** [comment]
I just realized, in my sample testing application, the PSW is 2.18.100.

**Comment by haitaohuang** [comment]
Can this be closed? I suppose it should be fixed by updating PSW?

**Comment by LiuJohn-1886** [comment]
thank you Haitao and Mikko. Closed it.
