### ISSUE TITLE
Pass user input data when enclave init

### ISSUE THREAD

**Issue by doutv** [intel/linux-sgx#977]
## Question
I want to pass some user input data to the enclave during initialization, so that these data are included in the enclave measurement.

`sgx_create_enclave` do not accept custom user data.
```cpp
extern "C" sgx_status_t sgx_create_enclave(const char *file_name, 
                                           const int debug, 
                                           sgx_launch_token_t *launch_token, 
                                           int *launch_token_updated, 
                                           sgx_enclave_id_t *enclave_id, 
                                           sgx_misc_attribute_t *misc_attr)  
```

https://github.com/intel/linux-sgx/blob/f656e74afd6ecdbdc2d7397db7ebd46d8cf46ca6/psw/urts/linux/urts.cpp#L113

## My use case

Use remote attestation to prove the enclave compute ML inference with given input. 

If I use ECall like `ecall_inference(chat* input)`, In the attestation report, I cannot prove that the enclave did call `ecall_inference` with certain `input`. 

If I can store user input data in enclave during initialization, at least I can prove the enclave use certain `input`.

**Can I prove enclave did execute ECall function with certain params?**

**Comment by lzha101** [comment]
You cannot include these runtime input data into measurement.  The enclave signing process only measure the enclave image itself with the configuration.
Do you have any idea on the input? If yes, perhaps you can place the data in your enclave and check the input with the prepared data during the ECALL function. Is that workable?

**Comment by doutv** [comment]
Well. Thanks for your explanation. 

I read the [SGX Developer Guide](https://community.intel.com/legacyfs/online/drupal_files/managed/33/70/intel-sgx-developer-guide.pdf), it said: 
> There is no guarantee that the input parameters of a call into an enclave
(ECall) or the return parameters from a call outside an enclave (OCall) will
be what the enclave expects because the untrusted domain supplies
them.

I want to prove the untrusted domain (outer app program) did call the ECall function `ecall_inference(chat* input)` with certain `input`. 

Seems that SGX attestation cannot prove this stuff. I should consider using other proving method.

**Comment by andyzyb** [comment]
Actually you can approve that.  Record the evidence in the function, and generate a report with that evidence. Then do remote attestation to approve it.

**Comment by doutv** [comment]
https://github.com/intel/linux-sgx/blob/f656e74afd6ecdbdc2d7397db7ebd46d8cf46ca6/common/inc/sgx_report.h#L110

To clarify:
In enclave ECall function `ecall_inference(chat* input)`, record `input` as `sgx_report_body_t.report_data`, and call `sgx_create_report` to generate a report. This report will contain the `input` evidence. 

Is that correct?

**Comment by andyzyb** [comment]
Yes. You can put evidence in the report_data.   report_data has limited size, you may need to convert input to other type of evidence if it is too big.
