### ISSUE TITLE
How to enable EPC pages' swapping ?

### ISSUE THREAD

**Issue by aghia98** [intel/linux-sgx#994]
Hi,
I am using Azure confidential computing VMs to build an SGX-based confidential Key-Value Store.
But, the VMs' enclaves crash after pushing arround 14000 secrets of 20 bytes using YCSB client, which is just around 280KB of data in enclave. It is very tiny, even regarding SGX-v1 limited EPC size (128MB). More precisely I am getting the error `SGX_ERROR_ENCLAVE_CRASHED`

I am confronting two issues:
1.  The Azure VMs I used are said to be compatible with SGX2. Still, my experience seems to show that EDMM (Enclave Dynamic Memory Management) is disabled because if it was enabled, additional pages would dynamically be allocated as I push more data. Searching further, I figured out that EDMM feature is enabled only on 6.0+ Linux kernel and not for 5.3, which is my actual Linux kernel version. Do you agree that this is the cause of the problem ?
2. Swapping of EPC pages seems also disabled since my enclaves just crash when I push "many" data  instead of using swap to bring additional space. 

I didn't find solution on the internet for the second problem, and it seems trivial at same time.

This is my `Enclave.config.xml` file if it can help you:

```
<EnclaveConfiguration>
  <ProdID>0</ProdID>
  <ISVSVN>0</ISVSVN>
  <StackMaxSize>0x40000</StackMaxSize>
  <HeapMaxSize>0x100000</HeapMaxSize>
  <TCSNum>600</TCSNum>
  <TCSPolicy>0</TCSPolicy>
  <!-- Recommend changing 'DisableDebug' to 1 to make the enclave undebuggable for enclave release -->
  <DisableDebug>0</DisableDebug>
  <MiscSelect>0</MiscSelect>
  <MiscMask>0xFFFFFFFF</MiscMask>
</EnclaveConfiguration>

```

Can you point me on potential solutions ?

Thank you

**Comment by lzha101** [comment]
1. Agree. You Linux kernel v5.3 doesn't support EDMM feature. 
2. You Enclave configuration requires much EPC as it sets `TCSNum` as 600. I tried to use your configuration to sign a simple enclave. It shows about 160MB EPC is required. So, looks the machine already supports swapping.  If you don't need so many TCSs, you can decrease the `TCSNum` to reduce the EPC usage.

**Comment by aghia98** [comment]
Thank you for you answer.
Actually I have 16GB of RAM in my VM. So I still find 160MB of EPC too small. 
The application consists of a C++ std::map<string, string> while each key and value doesn't exceed 20 bytes. When I reach around 14000 pushed key-value pairs, the enclave crashes. 
Increasing the HeapMaxSize (as well decreasing TCSNum to 10) doesn't seem to have much effect (I barely increase the storage capacity). U think there must be another bottleneck here.
Still, I need to push the TCSNum to such high value in order to benchmark the performance of my app with a real workload use case.

Do you think my RAM is saturated for my use case ?

**Comment by aghia98** [comment]
I did some tests using sgx_emmt to measure the memory consumption after pushing 7000 secrets, I got these results:

```
[Peak stack used]: 13 KB
[Peak heap used]:  972 KB
[Peak reserved memory used]:  0 KB
```

**Comment by lzha101** [comment]
Setting HeapMaxSize to 0x400000 means the max heap size that can be used is 0x400000, but the prerequisite is your enclave can be executed normally.
Suggest decreasing the TCSNum (for example, to 5) and increasing the HeapMaxSize (for example, to 0x400000) to make things simpler. If your application still crashes before the heap usage is reached to HeapMaxSize, then you can debug into the enclave with sgx-gdb to figure out the root cause.

**Comment by aghia98** [comment]
I tried to limit the TCSNum to 10 instead of 600 and the enclave is still crashing (`Aborted (core dumped)`). Like you told me I used `bt` command in `sgx-gdb` to find the region where it crashes and it gives me this:
```
#0  __pthread_kill_implementation (no_tid=0, signo=6, 
    threadid=140701950515456) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: No such file or directory.
[Current thread is 1 (Thread 0x7ff7b9c79900 (LWP 204777))]
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, 
    threadid=140701950515456) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, 
    threadid=140701950515456) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140701950515456, 
    signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ff7b9642476 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/posix/raise.c:26
#4  0x00007ff7b96287f3 in __GI_abort ()
    at ./stdlib/abort.c:79
#5  0x0000561457587796 in add_lost_keys_in_enclave (
    local_lost_keys_set=std::set with 1 element = {...})
    at App/TrustedLibrary/Types.cpp:139
```

This is the code of the `add_lost_keys_in_enclave()` function where it systematically abort after the some normal executions :
```
void add_lost_keys_in_enclave(const set<string>& local_lost_keys_set){
    string lost_keys_string="";
    for (const auto& key_with_last_share_owner : local_lost_keys_set) {
        lost_keys_string += key_with_last_share_owner+"\n";
    } 


    sgx_status_t ret = SGX_ERROR_UNEXPECTED;
    ret = ecall_add_lost_keys(global_eid, convertCString(lost_keys_string)); 
    if (ret != SGX_SUCCESS)
        abort();
}
```

I am pretty sure that something turned wrong inside the ecall function "ecall_add_lost_keys()". But I cannot debug further in the stack.
But I should say that I am calling this ecall function many times in a second since I am benchmarking my system under heavy load.
