### ISSUE TITLE
Docker example failed to run because of device file privilege

### ISSUE THREAD

**Issue by plzfgme** [intel/linux-sgx#996]
The [Dockerfile](https://github.com/intel/linux-sgx/blob/master/docker/build/Dockerfile) create a user `sgxuser` to run the sample code. 
However on my computer, `/dev/sgx_enclave` belongs to `sgx`(988) group, when I map the device to container, it also belongs to 988 group, and then the SampleEnclave cannot run.

**Comment by llly** [comment]
All users can access `/dev/sgx_enclave` to run an SGX enclave.
```
$ ls /dev/sgx_enclave -l
crw-rw-rw- 1 root sgx 10, 125 Oct 30 22:34 /dev/sgx_enclave
```
It should be not caused be SGX device permission.

**Comment by plzfgme** [comment]
It's different on my computer. I wonder why. 

```
ls -al /dev | grep sgx
crw-rw----   1 root sgx     10, 125 Nov 30 09:06 sgx_enclave
crw-------   1 root root    10, 126 Nov 30 09:06 sgx_provision
crw-rw----   1 root sgx     10, 124 Nov 30 09:06 sgx_vepc
```
